var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(d){var e=function(){};e.prototype=d;return new e};
$jscomp.underscoreProtoCanBeSet=function(){var d={a:!0},e={};try{return e.__proto__=d,e.a}catch(h){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(d,e){d.__proto__=e;if(d.__proto__!==e)throw new TypeError(d+" is not extensible");return d}:null;
$jscomp.inherits=function(d,e){d.prototype=$jscomp.objectCreate(e.prototype);d.prototype.constructor=d;if($jscomp.setPrototypeOf){var h=$jscomp.setPrototypeOf;h(d,e)}else for(h in e)if("prototype"!=h)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(e,h);g&&Object.defineProperty(d,h,g)}else d[h]=e[h];d.superClass_=e.prototype};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,e,h){d!=Array.prototype&&d!=Object.prototype&&(d[e]=h.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var e=0;return $jscomp.iteratorPrototype(function(){return e<d.length?{done:!1,value:d[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.iteratorFromArray=function(d,e){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var h=0,g={next:function(){if(h<d.length){var q=h++;return{value:e(q,d[q]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(d,e,h,g){if(e){h=$jscomp.global;d=d.split(".");for(g=0;g<d.length-1;g++){var q=d[g];q in h||(h[q]={});h=h[q]}d=d[d.length-1];g=h[d];e=e(g);e!=g&&null!=e&&$jscomp.defineProperty(h,d,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");window.dji=window.dji||{};
window.dji.accessibility=function(){function d(a){return(a=a.match(v))&&2<=a.length?a[1]:void 0}function e(){var a=[];CWEChromeUtilities.findValidIframeElements(void 0,a,!0);for(var b=0;b<a.length;b++){var c=a[b];try{c.removeEventListener("load",h)}catch(A){}h.apply(c);c.addEventListener("load",h)}}function h(){CWEChromeUtilities.validateIframe(this,!0)&&g(this.contentWindow)}function g(a){a.addEventListener("keydown",q,!0);a.addEventListener("keyup",w,!0);a.addEventListener("mousedown",x,!0)}function q(a){r&&
(!a.altKey||a.ctrlKey&&32!==a.which||a.shiftKey||a.metaKey?m=k.None:(37===a.which?m=k.Previous:39===a.which?m=k.Next:13===a.which?m=k.Enter:32===a.which&&a.ctrlKey?m=k.Select:27===a.which?m=k.Escape:88===a.which?m=k.ContextMenu:"Alt"!==a.key&&(m=k.None),m!==k.None&&(a.stopPropagation(),a.preventDefault())))}function w(a){if(r&&m!==k.None){var b=m;m=k.None;a.stopPropagation();a.preventDefault();b!==k.Ignore&&(b===k.Previous?n.goPrevious():b===k.Next?n.goNext():b===k.Enter?n.enter():b===k.Select?n.select():
b===k.Escape?n.dismiss():b===k.ContextMenu&&n.contextMenu())}}function x(){n.enable(!1);n.enable(!0)}function y(a){if(0>=a.length)return a;for(var b={},c,d,e=0;e<a.length;e++)c=a[e].accessibilityIndex,(d=b.hasOwnProperty(c)?b[c]:null)||(d=b[c]=[]),d.push(a[e]);d=Object.keys(b).map(function(a){return parseInt(a)}).sort(function(a,b){return isNaN(a)||isNaN(b)?isNaN(a)?isNaN(b)?0:0>b?-1:1:0>=a?1:-1:0>a||0>b?0<a?-1:0<b?1:b-a:a-b});a=[];for(e=0;e<d.length;e++)c=d[e],isNaN(c)&&(c=void 0),a=a.concat(b[c]);
return a}function u(a){var b=(a?a.ownerDocument:document).activeElement;if(b&&a){for(var c=b;c&&c!==a;)c=c.parentElement;return c===a?b:null}return b}function z(a,b){if(!a)return!1;if(a.nodeType===Node.DOCUMENT_NODE)return!0;b=b||document;if(a.parentNode&&"HTML"===a.parentNode.tagName)return"BODY"===a.tagName;a.nodeType===Node.TEXT_NODE&&(a=a.parentElement);var c;for(c=!0;a&&c;){if(a.nodeType===Node.DOCUMENT_NODE||"BODY"===a.tagName||a===a.ownerDocument||a===a.ownerDocument.documentElement)return!0;
var d=b.defaultView.getComputedStyle(a,null);d.getPropertyValue("position");c=d.getPropertyValue("display");d=d.getPropertyValue("visibility");(c="none"!==c&&"hidden"!==d)&&(c=!(!a.offsetParent&&a.parentElement!==a.ownerDocument&&a.parentElement!==a.ownerDocument.documentElement));a=a.parentElement}return c}var k={Ignore:-1,None:0,Previous:200,Next:201,Enter:202,Select:203,ContextMenu:204,Escape:205},n=void 0,r=!1,m=k.None,v=/^{([^}]+)}$/,p=function(a,b){this.m_domElem=a;this.m_parent=b;this.m_focused=
!1;this.m_accessibilityIndex=void 0;if(a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible"):void 0){try{a=parseInt(a)}catch(c){}a&&!isNaN(a)&&(this.m_accessibilityIndex=a)}};p.prototype.focus=function(a){a=void 0===a||!0===a;this.m_focused=!0;$(this.m_domElem).addClass("dji-x-highlighted");a&&$(this.m_domElem).focus();(a||this.requiresScrollIntoView)&&this.m_domElem.scrollIntoView(!1);this.m_domElem.dispatchEvent(new CustomEvent("x-focus"))};p.prototype.blur=function(a){if(a=void 0===a||
!0===a){var b=u(this.m_domElem);b&&$(b).blur()}this.m_focused&&(this.m_focused=!1,a&&$(this.m_domElem).blur(),$(this.m_domElem).removeClass("dji-x-highlighted"),this.m_domElem.dispatchEvent(new CustomEvent("x-blur")))};p.prototype.enter=function(){this.m_domElem.dispatchEvent(new CustomEvent("x-enter"))};p.prototype.select=function(){this.m_domElem.dispatchEvent(new CustomEvent("x-select"))};p.prototype.contextMenu=function(){this.m_domElem.dispatchEvent(new CustomEvent("x-contextmenu"))};p.prototype.dismiss=
function(){this.m_domElem.dispatchEvent(new CustomEvent("x-dismiss"))};p.prototype.reset=function(){this.blur()};$jscomp.global.Object.defineProperties(p.prototype,{domElement:{configurable:!0,enumerable:!0,get:function(){return this.m_domElem}},accessibilityIndex:{configurable:!0,enumerable:!0,get:function(){return this.m_accessibilityIndex}},isUsable:{configurable:!0,enumerable:!0,get:function(){return!z(this.m_domElem)||$(this.m_domElem).hasClass("dji-disable")?!1:!0}},isFocused:{configurable:!0,
enumerable:!0,get:function(){return this.m_focused}},requiresStrongFocus:{configurable:!0,enumerable:!0,get:function(){var a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible-strong-focus"):void 0;return null!==a&&void 0!==a}},requiresNoFocus:{configurable:!0,enumerable:!0,get:function(){var a=this.m_domElem?this.m_domElem.getAttribute("dji-accessible-no-focus"):void 0;return null!==a&&void 0!==a}},requiresScrollIntoView:{configurable:!0,enumerable:!0,get:function(){var a=this.m_domElem?
this.m_domElem.getAttribute("dji-accessible-scroll-into-view"):void 0;return null!==a&&void 0!==a}}});var f=function(a,b,c){b=p.call(this,void 0,b)||this;b.m_name=a;b.m_children=[];b.m_current=void 0;b.m_setup=c||void 0;b.m_setup&&b.setup();return b};$jscomp.inherits(f,p);f.prototype.focus=function(){};f.prototype.blur=function(a,b){for(var c=0;c<this.m_children.length;c++){var d=this.m_children[c];d!==b&&d.blur(a,b)}};f.prototype.findBlock=function(a){for(var b=0;b<this.m_children.length;b++){var c=
this.m_children[b];if(c instanceof f&&c.name===a)return c}return null};f.prototype.findBlockInPath=function(a){if(!(a instanceof Array)||0>=a.length)return null;for(var b=this,c=0;b&&c<a.length;c++)0<a[c].length&&(b=b.findBlock(a[c]));return b};f.prototype.addDomElementsUsingSelector=function(a,b){var c=void 0;try{if("string"===typeof b)(c=d(b))?this.m_children.push(new f(c,this)):this.addDomElements(a.querySelectorAll(b));else for(var e=0;e<b.length;e++)(c=d(b[e]))?this.m_children.push(new f(c,this)):
this.addDomElements(a.querySelectorAll(b[e]))}catch(t){throw dji.logger.error(t),t;}};f.prototype.addDomElements=function(a){for(var b=0;b<a.length;b++)this.m_children.push(new p(a[b]))};f.prototype.setup=function(){if(this.m_setup.blocks)for(var a=0;a<this.m_setup.blocks.length;a++){var b=this.m_setup.blocks[a];b=new f(b.name,this,b);this.m_children.push(b)}this.m_setup.dom&&this.addDomElementsUsingSelector(this.m_setup.dom.element,this.m_setup.dom.selectors);this.m_children=y(this.m_children)};
f.prototype.reload=function(a){var b=a?this.findFocusedElement():void 0;this.clear();this.setup();a&&b&&(a=this.elements,0<=b.index&&b.index<a.length&&a[b.index].focus())};f.prototype.sync=function(){for(var a=this.elements,b=void 0,c=0;c<a.length;c++){var d=a[c];u(d.domElement)&&(b=d)}this.blur(void 0,b);return b?(b.focus(),!0):!1};f.prototype.clear=function(){this.blur();this.m_children.splice(0,this.m_children.length);this.m_current=-1};f.prototype.reset=function(){0>=this.m_children.length||(0<=
this.m_current&&this.m_children[this.m_current].reset(),this.m_current=-1)};f.prototype.findNextElement=function(a){var b=this.elements,c=-1,d=void 0,e=-1,f=void 0,h=0>a?b.length:0;a=0>a?-1:1;for(var g=0;g<b.length;g++){var k=b[g];if(k.isFocused){c=g;d=k;break}}for(g=0;g<b.length;g++){e=(h+Math.max(c,0)+a*g)%b.length;f=b[e];if(f!==d&&f.isUsable)break;f=void 0}f||(e=-1);return{oldIndex:c,oldElement:d,newIndex:e,newElement:f}};f.prototype.findFocusedElement=function(a){a||(a=this.elements);for(var b=
0;b<a.length;b++){var c=a[b];if(c.isFocused)return{index:b,element:c}}return null};f.prototype.go=function(a){a=this.findNextElement(a);if(a.newElement&&a.newElement!==a.oldElement){var b=!a.newElement.requiresNoFocus;a.oldElement&&a.oldElement.blur(b);a.newElement.focus(b)}};f.prototype.goPrevious=function(){return this.go(-1)};f.prototype.goNext=function(){return this.go(1)};f.prototype.enter=function(){var a=this.findFocusedElement();a&&a.element&&a.element.enter()};f.prototype.select=function(){var a=
this.findFocusedElement();a&&a.element&&a.element.select()};f.prototype.contextMenu=function(){var a=this.findFocusedElement();a&&a.element&&a.element.contextMenu()};f.prototype.dismiss=function(){var a=this.findFocusedElement();a&&a.element&&a.element.dismiss()};$jscomp.global.Object.defineProperties(f.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.m_name}},isUsable:{configurable:!0,enumerable:!0,get:function(){for(var a=0;a<this.m_children.length;a++)if(this.m_children[a].isUsable)return!0;
return!1}},elements:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=0;b<this.m_children.length;b++){var c=this.m_children[b];c instanceof f?a=a.concat(c.elements):a.push(c)}return a}},domElements:{configurable:!0,enumerable:!0,get:function(){for(var a=this.elements,b=[],c=0;c<a.length;c++)b.push(a[c].m_domElem);return b}}});var l=function(){this.m_enabled=!1;this.m_blocks=[new f("@default")]};l.prototype.findBlockIndex=function(a){for(var b=[],c=0;c<this.m_blocks.length;c++)this.m_blocks[c].name===
a&&b.push(c);return b};l.prototype.findBlockInPath=function(a){var b=!1;a instanceof Array||(a=(a||"").trim().replace(/[ ]+/g,"/"),b=0===a.indexOf("/"),a=a.split("/"));for(var c=0;c<a.length;c++)if(a[c]&&0<a[c].length){0<c&&a.splice(0,c);break}if(0>=a.length)return null;0===a[0].indexOf("#")&&(b=!0,a[0]=a[0].substr(1));c=void 0;b?(b=this.findBlockIndex(a[0]),0<b.length&&(c=this.m_blocks[b[0]]),a.splice(0,1)):c=this.topBlock;return c?c.findBlockInPath(a):null};l.prototype.addBlockAndSetup=function(a,
b,c){c||(c=this.topBlock)&&c.blur(!1);a=new f(a,void 0,b);this.m_blocks.splice(0,0,a);return a};l.prototype.popBlock=function(a){if(a&&0<this.m_blocks.length&&this.m_blocks[0].name!==a)return null;a=this.m_blocks.splice(0,1);0<a.length&&a[0].blur();return a&&0<a.length?a[0]:null};l.prototype.removeBlock=function(a){a=this.findBlockIndex(a);for(var b=a.length-1;0<=b;b--){var c=this.m_blocks.splice(a[b],1);0<c.length&&c[0].blur()}};l.prototype.clearBlock=function(a){(a=this.findBlockInPath(a))&&a.clear()};
l.prototype.reloadBlock=function(a,b){(a=a?this.findBlockInPath(a):this.topBlock)&&a.reload(b)};l.prototype.reset=function(){for(var a=this.m_blocks.length-1;0<=a;a--)this.m_blocks[a].blur();this.m_blocks=[new f("@default")]};l.prototype.sync=function(){if(!this.m_enabled)return!1;var a=this.topBlock;return a?a.sync():!1};l.prototype.enable=function(a,b){void 0===a&&(a=!this.m_enabled);a=!!a;a!==this.m_enabled&&(this.m_enabled=a,b||!this.topBlock||this.m_enabled||this.topBlock.blur(!1))};l.prototype.goPrevious=
function(){if(this.m_enabled){var a=this.topBlock;a&&a.goPrevious()}};l.prototype.goNext=function(){if(this.m_enabled){var a=this.topBlock;a&&a.goNext()}};l.prototype.enter=function(){if(this.m_enabled){var a=this.topBlock;a&&a.enter()}};l.prototype.select=function(){if(this.m_enabled){var a=this.topBlock;a&&a.select()}};l.prototype.contextMenu=function(){if(this.m_enabled){var a=this.topBlock;a&&a.contextMenu()}};l.prototype.dismiss=function(){if(this.m_enabled){var a=this.topBlock;a&&a.dismiss()}};
l.prototype.dump=function(a){a={};for(var b=0;b<this.m_blocks.length;b++)a[b]=this.m_blocks[b].name;return JSON.stringify(a,null,4)};$jscomp.global.Object.defineProperties(l.prototype,{isEnabled:{configurable:!0,enumerable:!0,get:function(){return this.m_enabled}},topBlock:{configurable:!0,enumerable:!0,get:function(){return 0>=this.m_blocks.length?null:this.m_blocks[0]}}});n=new l;r=!1;document.documentElement.addEventListener("com.donjohnston.query.vpat",function(a){r&&"cwu"!==a.detail.app&&(a=
new CustomEvent(a.detail.answer.event,{detail:{app:"cwu",session:a.detail.answer.session,priority:1E6,active:!0}}),document.documentElement.dispatchEvent(a))},!0);g(window);CWEChromeUtilities.isIframeFree()||((new MutationObserver(e)).observe(document.documentElement,{childList:!0}),e());return{enable:function(a){a=!!a;r!==a&&(r=a,n.enable(a))},manager:n}}();
