var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var g=a[d];g in c||(c[g]={});c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof g?a:new g(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};g.prototype.createResolveAndReject_=
function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var h=new b;g.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};g.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};g.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(t){f(t)}}:b}var d,f,e=new g(function(a,
b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return e};g.prototype.catch=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(function(){h.asyncExecute(c)})};g.resolve=c;g.reject=function(a){return new g(function(b,c){c(a)})};g.race=function(a){return new g(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};g.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new g(function(a,f){function e(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(e(g.length-1),f),d=b.next();while(!d.done)})};return g},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,g){function h(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(h,g)}h(a.next())})};
function CWEChromeHookGoogleDocs(a){this.m_ime=a;this.m_windowProxy=this.m_windowCaret=this.m_windowSpan=this.m_window=this.m_hookOnContextMenu=this.m_hookOnScroll=this.m_hookOnKeyUp=this.m_hookOnKeyPress=this.m_hookOnKeyDown=this.m_hookOnMouseUp=this.m_hookOnMouseDown=this.m_hookOnSelect=this.m_hookOnBlur=this.m_hookOnFocus=this.m_contextMenuRemovePersonalWords=this.m_contextMenuAddPersonalWords=this.m_contextMenuStopSpeak=this.m_contextMenuStartSpeak=this.m_contextMenuCoWriterSubmenu=this.m_contextMenuCoWriter=
this.m_contextMenuSeparator=this.m_contextMenu=this.m_selectionOverlays=this.m_appViewEditor=this.m_appView=this.m_textEventTargetDoc=this.m_textEventTargetIframe=this.m_caret=this.m_cursor=null;this.__initialize();return this}
CWEChromeHookGoogleDocs.prototype.__initialize=function(){this.__findEditorElements();var a=this;this.m_windowProxy=document.getElementById("__DJI_CWE_CHROME_GOOGLE_DOCS_PROXY");this.m_windowProxy||(this.m_windowProxy=document.createElement("div"),this.m_windowProxy.id="__DJI_CWE_CHROME_GOOGLE_DOCS_PROXY",document.documentElement.appendChild(this.m_windowProxy));var b=document.getElementById("__DJI_CWE_CHROME_GOOGLE_DOCS_SERVERSIDE");b?(b=new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(b)):
(b=document.createElement("script"),b.id="__DJI_CWE_CHROME_GOOGLE_DOCS_SERVERSIDE",b.type="text/javascript",b.async=!0,b.src=chrome.extension.getURL("ContentScripts/cweChromeHookGoogleDocsServerSide.js"),b.onload=function(){Logger.instance.log("Co:Writer Javascript for Google Docs downloaded!")},document.body.appendChild(b));null===this.m_window&&(this.m_window=document.createElement("div"),this.m_window.id="__DJI_CWE_MEASUREMENT_WINDOW",this.m_windowSpan=document.createElement("span"),this.m_windowSpan.id=
"__DJI_CWE_MEASUREMENT_WINDOW_SPAN",this.m_windowCaret=document.createElement("div"),this.m_windowCaret.id="__DJI_CWE_MEASUREMENT_WINDOW_CARET",this.m_window.appendChild(this.m_windowSpan),this.m_window.appendChild(this.m_windowCaret),document.documentElement.appendChild(this.m_window));b=document.createElement("style");b.setAttribute("type","text/css");b.setAttribute("id","__DJI_CWE_CSS_DYN");b.innerHTML=".__dji_cwe_icon {width: 21px; height: 19px; margin-top: 2px;background: url('"+chrome.extension.getURL("Graphics/CoWriterIcon-16x16.png")+
"') no-repeat !important;}";document.head.appendChild(b);this.m_hookOnContextMenu=function(b){a.onContextMenu(a.m_appViewEditor,b)};document.addEventListener("contextmenu",this.m_hookOnContextMenu)};
CWEChromeHookGoogleDocs.prototype.__findEditorElements=function(){this.m_textEventTargetIframe=document.getElementsByClassName("docs-texteventtarget-iframe")[0];this.m_textEventTargetDoc=this.m_textEventTargetIframe.contentDocument;this.m_appView=document.getElementById("kix-appview");this.m_appViewEditor=this.m_appView.getElementsByClassName("kix-appview-editor")[0];this.m_selectionOverlays=this.m_appView.getElementsByClassName("kix-selection-overlay");this.m_cursor=this.m_appView.getElementsByClassName("kix-cursor")[0];
this.m_caret=this.m_appView.getElementsByClassName("kix-cursor-caret")[0];Logger.instance.log(this.m_textEventTargetIframe);Logger.instance.log(this.m_textEventTargetDoc);Logger.instance.log(this.m_appView);Logger.instance.log(this.m_appViewEditor);Logger.instance.log(this.m_selectionOverlays);Logger.instance.log(this.m_cursor);Logger.instance.log(this.m_caret)};
CWEChromeHookGoogleDocs.prototype.install=function(a){this.__findEditorElements();if(null===this.m_hookOnFocus){var b=this;this.m_hookOnFocus=function(a){b.onFocus(b.m_appViewEditor,a)};this.m_hookOnBlur=function(a){b.onBlur(b.m_appViewEditor,a)};this.m_hookOnSelect=function(a){b.onSelect(b.m_appViewEditor,a)};this.m_hookOnMouseDown=function(a){b.onMouseDown(b.m_appViewEditor,a)};this.m_hookOnMouseUp=function(a){b.onMouseUp(b.m_appViewEditor,a)};this.m_hookOnKeyDown=function(a){b.onKeyDown(b.m_appViewEditor,
a)};this.m_hookOnKeyPress=function(a){b.onKeyPress(b.m_appViewEditor,a)};this.m_hookOnKeyUp=function(a){b.onKeyUp(b.m_appViewEditor,a)};this.m_hookOnScroll=function(a){b.onScroll(b.m_appViewEditor,a)}}if(this.__appViewIsVisible())a=new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(a),this.__installHooks(),this.m_ime.onEditorChanged(this,this.m_appViewEditor);else this.m_ime.onEditorChanged(null,null)};CWEChromeHookGoogleDocs.prototype.uninstall=function(){this.__uninstallHooks()};
CWEChromeHookGoogleDocs.prototype.reload=function(a){this.__uninstallHooks();this.__findEditorElements();if(this.__appViewIsVisible())a=new CustomEvent("__DJI_CWE_IME_RELOAD"),this.m_windowProxy.dispatchEvent(a),Logger.instance.log(this.m_appView),Logger.instance.log(this.m_appView.style.display),this.__installHooks(),this.m_ime.onEditorChanged(this,this.m_appViewEditor);else this.m_ime.onEditorChanged(null,null)};CWEChromeHookGoogleDocs.prototype.setTrueKeyMode=function(){};
CWEChromeHookGoogleDocs.prototype.getState=function(){var a=this.__appViewIsVisible();return{active:a,hook:a?this:null,editor:a?this.m_appViewEditor:null}};CWEChromeHookGoogleDocs.prototype.__appViewIsVisible=function(){var a=document.defaultView.getComputedStyle(this.m_appView),b=a.getPropertyValue("display");a=a.getPropertyValue("visibility");return"none"!==b&&"hidden"!==a};CWEChromeHookGoogleDocs.prototype.__findEditableElements=function(a,b){};
CWEChromeHookGoogleDocs.prototype.__validateEditor=function(a){};CWEChromeHookGoogleDocs.prototype.__validateIframe=function(a){};
CWEChromeHookGoogleDocs.prototype.__installHooks=function(){this.m_textEventTargetDoc.addEventListener("keydown",this.m_hookOnKeyDown,!0);this.m_textEventTargetDoc.addEventListener("keypress",this.m_hookOnKeyPress,!0);this.m_textEventTargetDoc.addEventListener("keyup",this.m_hookOnKeyUp,!0);this.m_appViewEditor.addEventListener("mousedown",this.m_hookOnMouseDown,!0);this.m_appViewEditor.addEventListener("mouseup",this.m_hookOnMouseUp,!0)};
CWEChromeHookGoogleDocs.prototype.__uninstallHooks=function(){this.m_textEventTargetDoc&&(this.m_textEventTargetDoc.removeEventListener("keydown",this.m_hookOnKeyDown,!0),this.m_textEventTargetDoc.removeEventListener("keypress",this.m_hookOnKeyPress,!0),this.m_textEventTargetDoc.removeEventListener("keyup",this.m_hookOnKeyUp,!0),this.m_textEventTargetDoc=null);this.m_appViewEditor&&(this.m_appViewEditor.removeEventListener("mousedown",this.m_hookOnMouseDown,!0),this.m_appViewEditor.removeEventListener("mouseup",
this.m_hookOnMouseUp,!0))};CWEChromeHookGoogleDocs.prototype.onFocus=function(a,b){Logger.instance.log("CWEChromeHookGoogleDocs.onFocus: "+b);this.m_ime.onEditorChanged(this,a)};CWEChromeHookGoogleDocs.prototype.onBlur=function(a,b){this.m_ime.onEditorChanged(null,null);Logger.instance.log("CWEChromeHookGoogleDocs.onBlur: "+b)};CWEChromeHookGoogleDocs.prototype.onSelect=function(a,b){Logger.instance.log("CWEChromeHookGoogleDocs.onSelect: "+b);this.m_ime.onContextChanged(this)};
CWEChromeHookGoogleDocs.prototype.onMouseDown=function(a,b){Logger.instance.log("CWEChromeHookGoogleDocs.onMouseDown: "+b)};CWEChromeHookGoogleDocs.prototype.onMouseUp=function(a,b){Logger.instance.log("CWEChromeHookGoogleDocs.onMouseUp: "+b);this.m_ime.onContextChanged(this)};CWEChromeHookGoogleDocs.prototype.onKeyDown=function(a,b){this.m_ime.onKeyDown(this,b)&&(b.stopPropagation(),b.preventDefault())};
CWEChromeHookGoogleDocs.prototype.onKeyPress=function(a,b){this.m_ime.onKeyPress(this,b)&&(b.stopPropagation(),b.preventDefault())};CWEChromeHookGoogleDocs.prototype.onKeyUp=function(a,b){this.m_ime.onKeyUp(this,b)&&(b.stopPropagation(),b.preventDefault())};CWEChromeHookGoogleDocs.prototype.onScroll=function(a,b){Logger.instance.log("onScroll: "+b);this.m_ime.onContextChanged(this)};
CWEChromeHookGoogleDocs.prototype.onContextMenu=function(a,b){for(a=b.toElement;a&&a!==this.m_appViewEditor;a=a.parentElement);a&&(a=this.__getContextMenu(),Logger.instance.log("--------------------------------------------------- CWEChromeHookGoogleDocs.onContextMenu"),Logger.instance.log(b),Logger.instance.log(a))};
CWEChromeHookGoogleDocs.prototype.__getContextMenu=function(){if(null===this.m_contextMenu)for(var a=document.getElementsByClassName("goog-menu"),b=0;b<a.length;b++){var c=a[b].getAttribute("role"),d=parseInt(a[b].getAttribute("tabindex"));if("menu"===c&&0===d){this.m_contextMenu=a[b];this.__buildContextMenu();break}}return this.m_contextMenu};
CWEChromeHookGoogleDocs.prototype.__buildContextMenu=function(){var a=this;if(null===this.m_contextMenuCoWriter){this.m_contextMenuSeparator=this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP");this.m_contextMenuCoWriter=this.__createCoWriterMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_SM");this.m_contextMenuCoWriterSubmenu=this.__createSubmenu();this.m_contextMenuStartSpeak=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_STARTSPEAK","Speak");this.m_contextMenuStopSpeak=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_STOPSPEAK",
"Stop Speak");var b=this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP_SPEAK");this.m_contextMenuAddPersonalWords=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_APW","Add Personal Words");this.m_contextMenuRemovePersonalWords=this.__createSimpleMenuItem("__DJI_CWE_GOOGLE_DOCS_CM_RPW","Remove Personal Words");this.__createSeparatorMenuItem("__DJI_CWE_GOOGLE_DOC_CM_SEP_PW");this.m_contextMenu.addEventListener("mouseover",function(b){a.m_contextMenuCoWriter.__mouseOver||(a.m_contextMenuCoWriterSubmenu.style.display=
"none",CWEChromeUtilities.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight"))});this.m_contextMenu.addEventListener("blur",function(b){a.m_contextMenuCoWriterSubmenu.style.display="none";CWEChromeUtilities.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight")});this.m_contextMenu.addEventListener("keydown",function(b){a.m_contextMenuCoWriterSubmenu.style.display="none";CWEChromeUtilities.removeClassFromElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight")});
this.m_contextMenuCoWriterSubmenu.addEventListener("mouseover",function(b){a.m_contextMenuCoWriterSubmenu.__mouseOver=!0});this.m_contextMenuCoWriterSubmenu.addEventListener("mouseout",function(b){a.m_contextMenuCoWriterSubmenu.__mouseOver=!1});this.m_contextMenuCoWriter.addEventListener("mouseover",function(b){a.m_contextMenuCoWriter.__mouseOver=!0;a.m_contextMenuCoWriter.__mouseOutHandler&&null!==a.m_contextMenuCoWriter.__mouseOutHandler&&(clearTimeout(a.m_contextMenuCoWriter.__mouseOutHandler),
a.m_contextMenuCoWriter.__mouseOutHandler=null);b=a.m_contextMenu.querySelectorAll("div.goog-menuitem-highlight");for(var c=0;c<b.length;c++)b[c]!==a.m_contextMenuCoWriter&&CWEChromeUtilities.removeClassFromElement(b[c],"goog-menuitem-highlight");a.m_contextMenu.setAttribute("aria-activedescendant",a.m_contextMenuCoWriter.id);CWEChromeUtilities.addClassToElement(a.m_contextMenuCoWriter,"goog-menuitem-highlight");b=a.m_contextMenuCoWriter.getBoundingClientRect();a.m_contextMenuCoWriterSubmenu.style.left=
b.right+"px";a.m_contextMenuCoWriterSubmenu.style.top=b.top-7+"px";a.m_contextMenuCoWriterSubmenu.style.display=""},!0);this.m_contextMenuCoWriter.addEventListener("mouseout",function(b){a.m_contextMenuCoWriter.__mouseOutHandler=setTimeout(function(){a.m_contextMenuCoWriter.__mouseOver=!1;!1===a.m_contextMenuCoWriterSubmenu.__mouseOver&&(a.m_contextMenuCoWriterSubmenu.style.display="none",a.m_contextMenu.removeAttribute("aria-activedescendant"),CWEChromeUtilities.removeClassFromElement(a.m_contextMenuCoWriter,
"goog-menuitem-highlight"))},10)},!0);this.m_contextMenuCoWriter.addEventListener("mousedown",function(a){a.stopPropagation();a.preventDefault()},!0);this.m_contextMenuStartSpeak.addEventListener("mouseover",function(b){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",a.m_contextMenuStartSpeak.id);CWEChromeUtilities.addClassToElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight")});this.m_contextMenuStartSpeak.addEventListener("mouseout",function(b){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");
CWEChromeUtilities.removeClassFromElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight")});this.m_contextMenuStartSpeak.addEventListener("mousedown",function(b){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");CWEChromeUtilities.removeClassFromElement(a.m_contextMenuStartSpeak,"goog-menuitem-highlight");a.__contextMenuStartSpeak()});this.m_contextMenuStopSpeak.addEventListener("mouseover",function(b){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",
a.m_contextMenuStopSpeak.id);CWEChromeUtilities.addClassToElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight")});this.m_contextMenuStopSpeak.addEventListener("mouseout",function(b){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");CWEChromeUtilities.removeClassFromElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight")});this.m_contextMenuStopSpeak.addEventListener("mousedown",function(b){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");
CWEChromeUtilities.removeClassFromElement(a.m_contextMenuStopSpeak,"goog-menuitem-highlight");a.__contextMenuStopSpeak()});this.m_contextMenuAddPersonalWords.addEventListener("mouseover",function(b){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",a.m_contextMenuAddPersonalWords.id);CWEChromeUtilities.addClassToElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight")});this.m_contextMenuAddPersonalWords.addEventListener("mouseout",function(b){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");
CWEChromeUtilities.removeClassFromElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight")});this.m_contextMenuAddPersonalWords.addEventListener("mousedown",function(b){a.m_contextMenu.style.display="none";a.m_contextMenu.removeAttribute("aria-activedescendant");CWEChromeUtilities.removeClassFromElement(a.m_contextMenuAddPersonalWords,"goog-menuitem-highlight");a.__contextMenuAddPersonalWords()});this.m_contextMenuRemovePersonalWords.addEventListener("mouseover",function(b){a.m_contextMenuCoWriterSubmenu.setAttribute("aria-activedescendant",
a.m_contextMenuRemovePersonalWords.id);CWEChromeUtilities.addClassToElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight")});this.m_contextMenuRemovePersonalWords.addEventListener("mouseout",function(b){a.m_contextMenuCoWriterSubmenu.removeAttribute("aria-activedescendant");CWEChromeUtilities.removeClassFromElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight")});this.m_contextMenuRemovePersonalWords.addEventListener("mousedown",function(b){a.m_contextMenu.style.display=
"none";a.m_contextMenu.removeAttribute("aria-activedescendant");CWEChromeUtilities.removeClassFromElement(a.m_contextMenuRemovePersonalWords,"goog-menuitem-highlight");a.__contextMenuRemovePersonalWords()});this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuStartSpeak);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuStopSpeak);this.m_contextMenuCoWriterSubmenu.appendChild(b);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuAddPersonalWords);this.m_contextMenuCoWriterSubmenu.appendChild(this.m_contextMenuRemovePersonalWords);
document.body.appendChild(this.m_contextMenuCoWriterSubmenu);a.m_contextMenu.insertBefore(this.m_contextMenuSeparator,a.m_contextMenu.children[0]);a.m_contextMenu.insertBefore(this.m_contextMenuCoWriter,a.m_contextMenu.children[0])}};
CWEChromeHookGoogleDocs.prototype.__createCoWriterMenuItem=function(a){var b=document.createElement("div");b.id=a;b.className="goog-menuitem goog-submenu";b.setAttribute("aria-haspopup","true");b.setAttribute("role","menuitem");b.setAttribute("style","-webkit-user-select: none;");b.innerHTML='<div class="docs-icon goog-inline-block goog-menuitem-icon" style="-webkit-user-select: none;"><div class="__dji_cwe_icon" style="-webkit-user-select: none;"></div></div><div class="goog-menuitem-content"><span aria-label="CoWriter;" style="-webkit-user-select: none;">Co:Writer</span><span class="goog-submenu-arrow" style="-webkit-user-select: none;">&#9658;</span></div>';
return b};CWEChromeHookGoogleDocs.prototype.__createSimpleMenuItem=function(a,b){var c=document.createElement("div");c.id=a;c.className="goog-menuitem";c.setAttribute("role","menuitem");c.setAttribute("style","-webkit-user-select: none;");c.innerHTML='<div class="goog-menuitem-content">'+b+"</div>";return c};
CWEChromeHookGoogleDocs.prototype.__createSeparatorMenuItem=function(a){var b=document.createElement("div");b.id=a;b.className="goog-menuseparator";b.setAttribute("role","separator");b.setAttribute("aria-hidden","true");b.setAttribute("style","-webkit-user-select: none;");return b};
CWEChromeHookGoogleDocs.prototype.__createSubmenu=function(){var a=document.createElement("div");a.className="goog-menu goog-menu-vertical goog-menu-noaccel docs-menu-hide-mnemonics";a.setAttribute("aria-haspopup","true");a.setAttribute("role","menu");a.setAttribute("style","-webkit-user-select: none; left: 0px; top: 0px; display: none;");return a};CWEChromeHookGoogleDocs.prototype.__contextMenuStartSpeak=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onSpeak(a)};
CWEChromeHookGoogleDocs.prototype.__contextMenuStopSpeak=function(){this.m_ime.onStopSpeak()};CWEChromeHookGoogleDocs.prototype.__contextMenuAddPersonalWords=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onAddPersonalWords(a)};CWEChromeHookGoogleDocs.prototype.__contextMenuRemovePersonalWords=function(){var a=this.__getSelectedText();if(0<a.length)this.m_ime.onRemovePersonalWords(a)};
CWEChromeHookGoogleDocs.prototype.__contextMenuQuickTopic=function(){var a=this.__getSelectedText();this.m_ime.onQuickTopic(a)};CWEChromeHookGoogleDocs.prototype.__getSelectedText=function(){var a=this.getContext(this.m_appViewEditor);Logger.instance.log(a);return 0<a.text.length&&0<a.selection.length?a.text.substring(a.selection.start,a.selection.start+a.selection.length):""};
CWEChromeHookGoogleDocs.prototype.getCaret=function(a){a=this.m_cursor?this.m_cursor.getBoundingClientRect():this.m_appView.getElementsByClassName("kix-cursor")[0].getBoundingClientRect();var b=this.m_caret?this.m_caret.getBoundingClientRect():this.m_appView.getElementsByClassName("kix-cursor-caret")[0].getBoundingClientRect();return{left:a.left,top:b.top,right:a.right,bottom:b.bottom}};
CWEChromeHookGoogleDocs.prototype.getContext=function(a){var b=this.__getSelectionOverlayInfo(),c=b.first;a=b.last;var d=c.left,g=a.right,h=this.__getSourandingLines(b,1,1),e={selection:{start:0,length:0},text:"",custom:{embededLocations:{}},extended:{text:"",selection:{start:0,length:0}}};if(0>=h.lines.length)return e;for(var m=this.__getChunksFromLine(h.lines[h.firstLineIndex]),l,k=-1,f=0;f<m.length;f++)if(l=m[f].chunk.getBoundingClientRect(),l.left<=d&&d<=l.right){k=f;break}-1===k&&0<m.length&&
(k=m.length);for(f=0;f<=h.firstLineIndex;f++)if(0<f&&(e.selection.start+=1,e.selection.length+=1),f<h.firstLineIndex)d=this.__computeTextLengthOfLine(h.lines[f]),e.selection.start+=d,e.selection.length+=d;else for(d=0;d<k;d++)1===m[d].type&&(0<m[d].paddingLeft&&(e.selection.start+=1),e.selection.start+=this.__computeTextLengthOfChunk(m[d]));h.extras&&(f=h.extras.firstLineIndex-h.firstLineIndex,0<f&&(f=h.extras.lines.slice(Math.max(0,f-5),f),e.extended.text=this.__computeText(f,null)));e.text=this.__computeText(h.lines,
e.custom.embededLocations);0<=k&&k<m.length?(0<m[k].paddingLeft&&(e.selection.start+=1),e.selection.start+=this.__measureTextBlock(m[k],c.left,c.top)):m.length<=k&&(e.selection.start+=1,e.text+=" ");if(b.isSelection){b=this.__getChunksFromLine(h.lines[h.lastLineIndex]);c=-1;for(f=0;f<b.length;f++)if(m=b[f].chunk.getBoundingClientRect(),m.left<=g&&g<=m.right){c=f;break}-1===c&&0<b.length&&(c=b.length);if(h.firstLineIndex==h.lastLineIndex)for(d=0;d<c;d++)e.selection.length+=this.__computeTextLengthOfChunk(b[d]);
else for(f=h.firstLineIndex;f<=h.lastLineIndex;f++)if(f>h.firstLineIndex&&(e.selection.length+=1),f<h.lastLineIndex)e.selection.length+=this.__computeTextLengthOfLine(h.lines[f]);else for(d=0;d<c;d++)1===b[d].type&&(0<b[d].paddingLeft&&(e.selection.length+=1),e.selection.length+=this.__computeTextLengthOfChunk(b[d]));0<=c&&c<b.length?(0<b[c].paddingLeft&&(e.selection.start+=1),e.selection.length+=this.__measureTextBlock(b[c],a.right,a.top)):b.length<=c&&(e.selection.length+=1);e.selection.length-=
e.selection.start}else e.selection.length=0;h.extras&&(e.extended.selection.start=e.extended.text.length+e.selection.start,e.extended.text+=e.text);return e};
CWEChromeHookGoogleDocs.prototype.__getChunksFromLine=function(a){for(var b=a.querySelectorAll("span.kix-lineview-text-block"),c=[],d=0;d<b.length;d++){var g=b[d],h=g.childNodes,e=g.style,m=e.paddingLeft?parseFloat(e.paddingLeft):0;e=e.paddingRight?parseFloat(e.paddingRight):0;for(var l=0;l<h.length;l++){var k=h[l];if(k.nodeType===Node.ELEMENT_NODE)if("SPAN"!==k.tagName)Logger.instance.log("Invalid chunk type!");else{var f={type:1,block:g,chunk:k,paddingLeft:m,paddingRight:e,parts:[]};k=k.childNodes;
var n=k.length;a.__isLastLine&&l===h.length-1&&0<n&&k[n-1].nodeType===Node.ELEMENT_NODE&&"SPAN"===k[n-1].tagName&&160===k[n-1].innerText.charCodeAt(0)&&n--;for(var p=0;p<n;p++){var q=k[p];if(q.nodeType===Node.ELEMENT_NODE){var r=q.childNodes;1===r.length&&r[0].nodeType===Node.TEXT_NODE?f.parts.push({type:1,element:q,textElement:r[0],text:this.__cleanupText(r[0].textContent)}):f.parts.push({type:1,element:q,text:" "})}else q.nodeType===Node.TEXT_NODE&&f.parts.push({type:3,element:q,text:this.__cleanupText(q.textContent)})}c.push(f)}else k.nodeType===
Node.TEXT_NODE&&(f={type:3,block:g,chunk:g,paddingLeft:m,paddingRight:e,parts:[{type:3,element:k,text:this.__cleanupText(k.textContent)}]},c.push(f))}}return c};CWEChromeHookGoogleDocs.prototype.__cleanupText=function(a){if(!a||0>=a.length)return a;a=a.split("");for(var b=0;b<a.length;b++)switch(a[b].charCodeAt(0)){case 8203:a[b]="";break;case 160:a[b]=" "}return a.join("")};
CWEChromeHookGoogleDocs.prototype.__computeText=function(a,b){if(null===a||0===a.length)return"";for(var c="",d=0;d<a.length;d++)0<d&&(c+=" "),c+=this.__computeTextOfLine(a[d],c.length,b);return c};CWEChromeHookGoogleDocs.prototype.__computeTextOfLine=function(a,b,c){if(null===a)return"";var d="";a=this.__getChunksFromLine(a);for(var g=0;g<a.length;g++){var h=a[g];1===h.type&&(d+=this.__computeTextOfChunk(h,d.length+b,c))}return d};
CWEChromeHookGoogleDocs.prototype.__computeTextLengthOfLine=function(a){if(null===a)return 0;var b=0;a=this.__getChunksFromLine(a);for(var c=0;c<a.length;c++)b+=this.__computeTextLengthOfChunk(a[c]);return b};
CWEChromeHookGoogleDocs.prototype.__computeTextOfChunk=function(a,b,c){if(null===a)return 0;var d="";if(1===a.type){0<a.paddingLeft&&(d+=" ");for(var g=0;g<a.parts.length;g++){var h=a.parts[g];switch(h.type){case Node.ELEMENT_NODE:d=h.textElement?d+h.text:d+" ";c&&(c[d.length+b]=h);break;case Node.TEXT_NODE:d+=h.text}}}return d};
CWEChromeHookGoogleDocs.prototype.__computeTextLengthOfChunk=function(a){if(null===a)return 0;var b=0;if(1===a.type){0<a.paddingLeft&&(b+=1);for(var c=0;c<a.parts.length;c++)switch(a.parts[c].type){case 1:b+=1;break;case 3:b+=a.parts[c].text.length}}return b};
CWEChromeHookGoogleDocs.prototype.__getSelectionOverlayInfo=function(){var a=this.getCaret(),b=this.m_appView.querySelectorAll("div.kix-page-content-wrapper");this.m_selectionOverlays=[];for(var c=0,d=-1;c<b.length;c++){var g=Array.prototype.slice.call(b[c].querySelectorAll("div.kix-selection-overlay"));if(0<g.length){if(d<c-1)return this.m_selectionOverlays=[],{first:a,last:a,caret:a,isSelection:!1};this.m_selectionOverlays=this.m_selectionOverlays.concat(g);d=c}}if(0>=this.m_selectionOverlays.length)return{first:a,
last:a,caret:a,isSelection:!1};c=b=null;for(d=0;d<this.m_selectionOverlays.length;d++)null===b?b=c=this.m_selectionOverlays[d].getBoundingClientRect():c=this.m_selectionOverlays[d].getBoundingClientRect();return b&&c&&(d=(a.top+a.bottom)/2,d<b.top||c.bottom<d)?(this.m_selectionOverlays=[],{first:a,last:a,caret:a,isSelection:!1}):{first:b,last:c,caret:a,isSelection:!0}};
CWEChromeHookGoogleDocs.prototype.__getSourandingLines=function(a,b,c){var d={currentLineIndex:0,firstLineIndex:0,lastLineIndex:0,lines:[]},g=(a.first.top+a.first.bottom)/2,h=(a.last.top+a.last.bottom)/2,e=(a.caret.top+a.caret.bottom)/2;a=this.__getCurrentParagraphs(a);for(var m=[],l=0;l<a.length;l++)for(var k=a[l].querySelectorAll("div.kix-lineview div.kix-lineview-content"),f=0;f<k.length;f++)k[f].__isLastLine=f===k.length-1,m.push(k[f]);f=-1;for(l=1;l<m.length;l++)if(k=m[l].getBoundingClientRect(),
g<k.top){f=l-1;break}-1===f&&(f=m.length-1);for(l=f+1;l<m.length;l++)if(k=m[l].getBoundingClientRect(),h<k.top){l--;break}l>=m.length&&(l=m.length-1);d.currentLineIndex=Math.abs(g-e)<Math.abs(h-e)?f:l;d.firstLineIndex=f;d.lastLineIndex=l;void 0!==b&&(f=Math.max(0,f-b));void 0!==c&&(l=Math.min(m.length-1,l+c));d.currentLineIndex-=f;d.firstLineIndex-=f;d.lastLineIndex-=f;d.lines=m.slice(f,l+1);1===a.length&&(d.extras={lines:m,currentLineIndex:d.currentLineIndex+f,firstLineIndex:d.firstLineIndex+f,lastLineIndex:d.lastLineIndex+
f});return d};
CWEChromeHookGoogleDocs.prototype.__getCurrentParagraphs=function(a){var b=(a.first.top+a.first.bottom)/2,c=a.first.left,d=a.first.right,g=a.isSelection?0:a.first.right-a.first.left+1,h=(a.last.top+a.last.bottom)/2,e=a.last.right,m=this.m_appViewEditor.querySelectorAll("div.kix-page div.kix-paragraphrenderer"),l=[],k;for(k=0;k<m.length;k++){var f=m[k].getBoundingClientRect();if(f.top<=b&&b<=f.bottom&&f.left<=d&&c<=f.right+g)break}if(a.isSelection)for(a=k;a<m.length;a++)if(f=m[a].getBoundingClientRect(),f.top<
h&&(f.right<=e||f.left<=e&&e<=f.right))l.push(m[a]);else break;else for(a=k;a<m.length;a++)if(f=m[a].getBoundingClientRect(),f.top<h&&f.left<=e&&c<=f.right+g)l.push(m[a]);else break;return l};
CWEChromeHookGoogleDocs.prototype.__measureTextBlock=function(a,b,c){if(null===a)return this.m_windowSpan.innerHTML="",0;var d=a.chunk.getBoundingClientRect().left,g=1E10,h=0;this.m_windowCaret.style.left=b+"px";this.m_windowCaret.style.top=c+"px";this.m_windowCaret.style.width=this.m_caret.style.width;this.m_windowCaret.style.height=this.m_caret.style.height;this.m_windowSpan.innerHTML="";this.m_windowSpan.className=a.chunk.className;this.m_windowSpan.style.cssText=a.chunk.style.cssText;this.m_windowSpan.style.whiteSpace=
"pre";for(var e=c=0;e<a.parts.length;e++){var m=d+this.m_windowSpan.offsetWidth;var l=Math.abs(m-b);if(l<g)g=l,h=c;else if(g<l)break;var k=a.parts[e];if(k.type===Node.ELEMENT_NODE){l=k.element.getBoundingClientRect();var f=document.createElement(k.element.tagName);k.textElement?(f.innerText=k.textElement.textContent,f.style.cssText=k.element.style.cssText):(f.innerHTML="",f.style.cssText="position: relative; display: inline-block; height: 2px; width: "+l.width+"px; background-color: #FF0000;");this.m_windowSpan.appendChild(f);
c++}else if(k.type===Node.TEXT_NODE){l=this.m_windowSpan.innerHTML;k=k.text;f=0;for(var n=k.length,p;f<n;)if(p=parseInt((f+n)/2),m=k.slice(0,p),this.m_windowSpan.innerHTML=l+m,m=d+this.m_windowSpan.offsetWidth,m-.75<=b&&b<=m+.75){f=p;break}else m<b?f=p+1:n=p;this.m_windowSpan.innerHTML=l+k.slice(0,f);c+=f}}0<a.parts.length&&(m=d+this.m_windowSpan.offsetWidth,l=Math.abs(m-b),l<g&&(h=c));return h};
CWEChromeHookGoogleDocs.prototype.replaceText=function(a,b,c){if(0===c.selection.length&&c.selection.start<b.selection.end)for(a=b.selection.end;a>b.selection.start;a--)a in c.custom.embededLocations&&(b.selection.end=a-1);b.extended={rightKey:Math.max(0,0===c.selection.length?b.selection.end-c.selection.start:0),backspaceKey:Math.max(0,0===c.selection.length?b.selection.end-b.selection.start:0)};b=new CustomEvent("__DJI_CWE_IME_REPLACETEXT",{detail:b});this.m_windowProxy.dispatchEvent(b)};
CWEChromeHookGoogleDocs.prototype.getContextForMomentaryTopic=function(a,b){a="";for(var c=this.m_appViewEditor.querySelectorAll("div.kix-page div.kix-paragraphrenderer"),d=0;d<c.length;d++){0<d&&(a+="\n");for(var g=c[d].querySelectorAll("div.kix-lineview div.kix-lineview-content"),h=0;h<g.length;h++)0<h&&(a+=" "),a+=g[h].textContent}b(a)};
CWEChromeHookGoogleDocs.prototype.acquireTextForTopicAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,h,l){for(;;)switch(d){case 0:return g=b,d=-1,{value:new Promise(function(b){g.m_appViewEditor||g.__findEditorElements();if(!g.m_appViewEditor)return b(null);var c=document.activeElement;c&&c.tagName&&c.tagName.toUpperCase();c=null;if("selection"===a){var d=g.getContext();if(d||0<d.selection.length)c=d.text.substr(d.selection.start,d.selection.length)}else if("page"===
a){c="";d=g.m_appViewEditor.querySelectorAll("div.kix-page div.kix-paragraphrenderer");for(var e=0;e<d.length;e++){0<e&&(c+="\n");for(var h=d[e].querySelectorAll("div.kix-lineview div.kix-lineview-content"),k=0;k<h.length;k++)0<k&&(c+=" "),c+=h[k].textContent}}b(c)}),done:!0};default:return{value:void 0,done:!0}}}var d=0,g,h={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=
function(){return this};return h}())};
CWEChromeHookGoogleDocs.prototype.shouldIgnoreMutations=function(a){for(var b=!0,c=0;c<a.length;c++){var d=a[c],g=d.target.ownerDocument;if(g.querySelector("#__dji_sru_main_container_content")){b=!1;break}for(var h=!1,e=0;e<d.addedNodes.length&&!h;e++)0<g.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",d.addedNodes[e],null,XPathResult.NUMBER_TYPE).numberValue&&(h=!0);for(e=0;e<d.removedNodes.length&&!h;e++)0<g.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",d.removedNodes[e],
null,XPathResult.NUMBER_TYPE).numberValue&&(h=!0);if(h){b=!1;break}}return b};
