var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof d?a:new d(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(q){f(q)}}:b}var e,f,g=new d(function(a,
b){e=a;f=b});this.callWhenSettled_(c(a,e),c(b,f));return g};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(function(){g.asyncExecute(c)})};d.resolve=c;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};d.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?c([]):new d(function(a,d){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(e.value).callWhenSettled_(f(g.length-1),d),e=b.next();while(!e.done)})};return d},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(e,d){function g(a){a.done?e(a.value):Promise.resolve(a.value).then(b,c).then(g,d)}g(a.next())})};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
function CWEChromeEditorInfo(a,b,c){this.m_iframes=a;this.m_document=b;this.m_editor=c;return this}
function CWEChromeHookGeneric(a){this.m_ime=a;this.m_editors=[];this.m_windowCaret=this.m_windowDiv=this.m_window=null;this.m_isGoogleDocs=CWEChromeUtilities.isGoogleDocs();this.m_isGooglePresentation=CWEChromeUtilities.isGooglePresentation();this.m_isGoogleSearch=CWEChromeUtilities.isGoogleSearch();this.m_isGoogleMail=CWEChromeUtilities.isGoogleMail();this.m_isYahooMail=CWEChromeUtilities.isYahooMail();this.m_isMicrosoftMail=CWEChromeUtilities.isMicrosoftMail();this.m_isEvernote=CWEChromeUtilities.isEvernote();
this.m_isFacebook=CWEChromeUtilities.isFacebook();this.m_isTwitter=CWEChromeUtilities.isTwitter();return this}
CWEChromeHookGeneric.prototype.install=function(a){a=a||!1;this.__uninstallHooks();this.m_editors=[];this.__findEditableElements(document,a,[],this.m_editors);Logger.instance.log(this.m_editors);null===this.m_window&&(this.m_window=document.createElement("div"),this.m_window.id="__DJI_CWE_MEASUREMENT_WINDOW_GENERIC",this.m_windowDiv=document.createElement("div"),this.m_windowDiv.id="__DJI_CWE_MEASUREMENT_WINDOW_GENERIC_DIV",this.m_window.appendChild(this.m_windowDiv),document.documentElement.appendChild(this.m_window));
this.__installHooks();this.__detectActiveEditor(!0)};CWEChromeHookGeneric.prototype.uninstall=function(){this.__uninstallHooks();this.m_editors=[]};CWEChromeHookGeneric.prototype.reload=function(a){a=a||!1;this.__uninstallHooks();this.m_editors=[];this.__findEditableElements(document,a,[],this.m_editors);Logger.instance.log(this.m_editors);this.__installHooks();this.__detectActiveEditor(!1)};
CWEChromeHookGeneric.prototype.__findEditableElements=function(a,b,c,e,d){for(var g=a.evaluate("//*[@contenteditable]|//input|//textarea|//body",a),f;f=g.iterateNext();)this.__validateEditor(f)&&e.push(new CWEChromeEditorInfo(c,a,f));if(b)for(a=a.getElementsByTagName("iframe"),d||window.top!==window||(d=document.getElementById("__dji_sru_main_container"))&&d.shadowRoot&&(d=d.shadowRoot.getElementById("__dji_sru_main_container_iframe"))&&(a=[].concat($jscomp.arrayFromIterable(a),[d])),d=0;d<a.length;d++)g=
a[d],this.__validateIframe(g)&&null!==g.contentDocument&&(f=[g].concat(c),this.__findEditableElements(g.contentDocument,b,f,e,!0))};
CWEChromeHookGeneric.prototype.__validateEditor=function(a){if(a.hasAttribute("dji-cwu-no-prediction"))return!1;if("input"===a.tagName.toLowerCase()){if(this.m_isGoogleDocs&&a.classList.contains("goog-toolbar-combo-button-input"))return!1;a=a.getAttribute("type");return!a||"text"===a.toLowerCase()}var b=a.getAttribute("id");if(b&&"__DJI_CWE_QUICKTOPIC_WINDOW_SEARCH_INPUT"===b)return!1;if("BODY"===a.tagName){if(!this.m_isGoogleDocs)if(this.m_isYahooMail){if((a=a.getAttribute("aria-label"))&&"Message Body"===
a)return!0}else{if("true"===a.getAttribute("contenteditable"))return!0;if(this.m_isEvernote){var c=a.getAttribute("class");if(c&&-1!=c.indexOf("ennote"))return!0}}return!1}var e=a.getAttribute("name");c=a.getAttribute("class");if("username"===b||"username"===e||"login"===e||"email"===b||"email"===e||"reg_email_confirmation__"===e||"signin-email"===b||c&&-1!=c.indexOf("email-input"))return!1;if(this.m_isGoogleDocs){if((c=a.getAttribute("class"))&&-1!=c.indexOf("goog-sa-searchbox-input"))return!1}else if(this.m_isGoogleMail){if("true"===
a.getAttribute("aria-haspopup"))return!1}else if(this.m_isYahooMail){if(b=a.getAttribute("aria-autocomplete"),"list"===b)return!1}else if(this.m_isFacebook){if("TEXTAREA"!==a.tagName&&(b=a.getAttribute("aria-autocomplete"),a=a.getAttribute("aria-expanded"),"list"===b&&"true"===a))return!1}else if(this.m_isTwitter&&"search-query"===b)return!1;return!0};
CWEChromeHookGeneric.prototype.__validateIframe=function(a){return a.classList.contains("docs-texteventtarget-iframe")||!CWEChromeUtilities.validateIframe(a)?!1:!0};CWEChromeHookGeneric.prototype.__installHooks=function(){for(var a=0;a<this.m_editors.length;a++)this.__installHooksInEditor(this.m_editors[a])};
CWEChromeHookGeneric.prototype.__installHooksInEditor=function(a){if(void 0===a.__djiHook||null===a.__djiHook){var b=this;a=a.m_editor;a.__djiHook=this;a.__djiHookOnFocus=function(c){b.onFocus(a,c)};a.__djiHookOnBlur=function(c){b.onBlur(a,c)};a.__djiHookOnSelect=function(c){b.onSelect(a,c)};a.__djiHookOnMouseDown=function(c){b.onMouseDown(a,c)};a.__djiHookOnMouseUp=function(c){b.onMouseUp(a,c)};a.__djiHookOnKeyDown=function(c){b.onKeyDown(a,c)};a.__djiHookOnKeyPress=function(c){b.onKeyPress(a,c)};
a.__djiHookOnKeyUp=function(c){b.onKeyUp(a,c)};a.addEventListener("focus",a.__djiHookOnFocus,!0);a.addEventListener("blur",a.__djiHookOnBlur,!0);a.addEventListener("select",a.__djiHookOnSelect,!0);a.addEventListener("dji-select",a.__djiHookOnSelect,!0);a.addEventListener("mousedown",a.__djiHookOnMouseDown,!0);a.addEventListener("mouseup",a.__djiHookOnMouseUp,!0);a.addEventListener("keydown",a.__djiHookOnKeyDown,!0);a.addEventListener("keypress",a.__djiHookOnKeyPress,!0);a.addEventListener("keyup",
a.__djiHookOnKeyUp,!0)}};
CWEChromeHookGeneric.prototype.__uninstallHooks=function(){for(var a=0;a<this.m_editors.length;a++){var b=this.m_editors[a].m_editor;void 0!==b.__djiHook&&null!==b.__djiHook&&(b.removeEventListener("focus",b.__djiHookOnFocus,!0),b.removeEventListener("blur",b.__djiHookOnBlur,!0),b.removeEventListener("select",b.__djiHookOnSelect,!0),b.removeEventListener("mousedown",b.__djiHookOnMouseDown,!0),b.removeEventListener("mouseup",b.__djiHookOnMouseUp,!0),b.removeEventListener("keydown",b.__djiHookOnKeyDown,
!0),b.removeEventListener("keypress",b.__djiHookOnKeyPress,!0),b.removeEventListener("keyup",b.__djiHookOnKeyUp,!0),b.__djiHookOnFocus=null,b.__djiHookOnBlur=null,b.__djiHookOnSelect=null,b.__djiHookOnMouseDown=null,b.__djiHookOnMouseUp=null,b.__djiHookOnKeyDown=null,b.__djiHookOnKeyPress=null,b.__djiHookOnKeyUp=null,b.__djiHook=null)}this.m_editors=[]};
CWEChromeHookGeneric.prototype.__findActiveEditorInfo=function(){for(var a=0;a<this.m_editors.length;a++){var b=this.m_editors[a];if(b.m_editor===b.m_document.activeElement){for(var c=document,e=!0,d=0;e&&d<b.m_iframes.length;d++){var g=b.m_iframes[d];e=c.activeElement===g;if(!e){var f=g.getRootNode({composed:!1});f&&f.host&&f.activeElement===g&&f.host===c.activeElement&&(e=!0)}c=g.contentDocument}if(e)return b}}return null};
CWEChromeHookGeneric.prototype.__getEditorInfo=function(a){for(var b=0;b<this.m_editors.length;b++)if(this.m_editors[b].m_editor===a)return this.m_editors[b];return null};CWEChromeHookGeneric.prototype.__detectActiveEditor=function(a){var b=this.__findActiveEditorInfo();b=b?b.m_editor:null;if(this.m_isMicrosoftMail&&b&&"BODY"===b.tagName){var c=b.getBoundingClientRect();if(0>=c.width||0>=c.height)b=null}if(a){if(b)this.m_ime.onEditorChanged(this,b)}else this.m_ime.onEditorChanged(this,b)};
CWEChromeHookGeneric.prototype.setTrueKeyMode=function(){};CWEChromeHookGeneric.prototype.onFocus=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onFocus: "+b);this.m_ime.onEditorChanged(this,a)};CWEChromeHookGeneric.prototype.onBlur=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onBlur: "+b);this.m_ime.onEditorChanged(null,null)};CWEChromeHookGeneric.prototype.onSelect=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onSelect: "+b);this.m_ime.onContextChanged(this)};
CWEChromeHookGeneric.prototype.onMouseDown=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onMouseDown: "+b)};CWEChromeHookGeneric.prototype.onMouseUp=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onMouseUp: "+b);this.m_ime.onContextChanged(this)};CWEChromeHookGeneric.prototype.onKeyDown=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onKeyDown: "+b);this.m_ime.onKeyDown(this,b)&&(b.stopPropagation(),b.preventDefault())};
CWEChromeHookGeneric.prototype.onKeyPress=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onKeyPress: "+b);this.m_ime.onKeyPress(this,b)&&(b.stopPropagation(),b.preventDefault())};CWEChromeHookGeneric.prototype.onKeyUp=function(a,b){Logger.instance.log("CWEChromeHookGeneric.onKeyUp: "+b);this.m_ime.onKeyUp(this,b)&&(b.stopPropagation(),b.preventDefault())};
CWEChromeHookGeneric.prototype.getCaret=function(a){var b={left:0,top:0,right:0,bottom:0},c=this.__getEditorInfo(a);if(null===c)return b;if(void 0!==a.selectionStart){var e=a.selectionStart,d=a.selectionEnd-a.selectionStart,g=a.value,f=CWEChromeUtilities.escapeHtml(g.slice(0,e+d));e=CWEChromeUtilities.escapeHtml(g.slice(e+d,g.length));d=document.defaultView.getComputedStyle(a,null);"INPUT"===a.tagName&&0<f.length&&(f=f.replace(/ /g,"."));this.m_windowDiv.innerHTML="";this.m_windowDiv.style.cssText=
d.cssText;this.m_windowDiv.innerHTML=f+"<span id='__DJI_CWE_MEASUREMENT_WINDOW_GENERIC_CARET'></span>"+e;this.m_windowCaret=document.getElementById("__DJI_CWE_MEASUREMENT_WINDOW_GENERIC_CARET");f=a.getBoundingClientRect();e=this.m_windowDiv.getBoundingClientRect();d=this.m_windowCaret.getBoundingClientRect();b.left=-a.scrollLeft+f.left+d.left-e.left;b.top=-a.scrollTop+f.top+d.top-e.top;b.right=d.right-d.left;b.bottom=d.bottom-d.top}else{a=c.m_document.getSelection();var h=a.focusNode,k=a.focusOffset;
try{if(f=0<a.rangeCount?a.getRangeAt(0).cloneRange():null,!f&&h&&(f=document.createRange(),f.setStart(h,k),f.setEnd(h,k)),e=f.getClientRects(),0>=e.length&&0<k&&k<=h.childNodes.length&&(f.detach(),f.selectNode(h.childNodes[k-1]),e=f.getClientRects()),f.detach(),0<e.length)d=e[e.length-1],b.left=d.right,b.top=d.top,b.right=0,b.bottom=d.bottom-d.top;else if(h){g=document.defaultView.getComputedStyle(h,null);var l=h.getBoundingClientRect(),m=parseFloat(g.getPropertyValue("padding-left")),r=parseFloat(g.getPropertyValue("padding-top")),
n=parseFloat(g.getPropertyValue("font-size"));b.left=m+l.left;b.top=r+l.top;b.right=0;b.bottom=n+2}}catch(p){Logger.instance.error(p,h,k,a)}}b.left+=window.pageXOffset;b.top+=window.pageYOffset;if(0<c.m_iframes.length)for(a=0;a<c.m_iframes.length;a++)f=c.m_iframes[a].getBoundingClientRect(),b.left+=f.left,b.top+=f.top;b.right=b.left+b.right;b.bottom=b.top+b.bottom;return b};
CWEChromeHookGeneric.prototype.getContext=function(a){Logger.instance.log("----------------------- CWEChromeHookGeneric.prototype.getContext BEGIN -------------------");var b={selection:{start:0,length:0},text:null,custom:null};a=void 0!==a.selectionStart?this.__getContextFromInput(a,null):this.__getContextFromContentEditable(a,null);b.text=a.text;b.selection.start=a.selection.start;b.selection.length=a.selection.length;b.custom=a.custom;b.extended=a.extended;Logger.instance.log("----------------------- CWEChromeHookGeneric.prototype.getContext END -------------------");
return b};
CWEChromeHookGeneric.prototype.__getContextFromInput=function(a,b){b=CWEChromeUtilities.htmlToUnicode(a.value);a={selection:{start:a.selectionStart,length:a.selectionEnd-a.selectionStart},text:b,custom:{selectionOffset:0},extended:{text:b,selection:{start:a.selectionStart,length:a.selectionEnd-a.selectionStart}}};if(0<a.text.length){b=a.text.lastIndexOf("\n",a.selection.start-1);var c=a.text.indexOf("\n",a.selection.start+a.selection.length),e=Math.max(0,a.selection.start-160),d=Math.min(a.text.length,a.selection.start+
a.selection.length+32);for(b=Math.max(b,a.selection.start-128);b>=e&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(a.text.charAt(b));b--);b++;for(c=Math.min(a.text.length,Math.max(c,a.selection.start+a.selection.length+10));c<d&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(a.text.charAt(c));c++);a.text=b<c?a.text.slice(b,c):"";a.selection.start-=b;a.custom.selectionOffset=b;b=Math.max(0,a.text.lastIndexOf("\n",b-1));c-b<a.text.length&&(a.extended.selection.start-=b,a.extended.custom.selectionOffset=
b,a.extended.text=a.extended.text.slice(b,c))}return a};
CWEChromeHookGeneric.prototype.__getContextFromContentEditable=function(a,b){a=this.__mapContentFromContentEditable(a,b);a={selection:a.selection,text:a.text,custom:{map:a.map,selectionOffset:0},extended:{text:a.text,selection:{start:a.selection.start,length:a.selection.length}}};if(0<a.text.length){b=a.text.lastIndexOf("\n",a.selection.start-1);var c=a.text.indexOf("\n",a.selection.start+a.selection.length),e=Math.max(0,a.selection.start-160),d=Math.min(a.text.length,a.selection.start+a.selection.length+
32);for(b=Math.max(b,a.selection.start-128);b>=e&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(a.text.charAt(b));b--);b++;for(c=Math.min(a.text.length,Math.max(c,a.selection.start+a.selection.length+10));c<d&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(a.text.charAt(c));c++);a.text=b<c?a.text.slice(b,c):"";a.selection.start-=b;a.custom.selectionOffset=b;b=Math.max(0,a.text.lastIndexOf("\n",b-1));c-b<a.text.length&&(a.extended.selection.start-=b,a.extended.custom.selectionOffset=
b,a.extended.text=a.extended.text.slice(b,c))}return a};
CWEChromeHookGeneric.prototype.__mapContentFromContentEditable=function(a,b){var c=this.__getEditorInfo(a);if(null===c)return{selection:{start:0,length:0},text:"",map:[]};c=c.m_document.getSelection();if(0>=c.rangeCount)return{selection:{start:0,length:0},text:"",map:[]};var e=c.getRangeAt(0);Logger.instance.log(e);c={selection:{start:0,length:0},text:"",map:[],params:{startContainer:e.startContainer,startOffset:e.startOffset,endContainer:e.endContainer,endOffset:e.endOffset,selection:c,range:e,prevNode:null,
stop:!1}};1===c.params.startContainer.nodeType&&0<c.params.startOffset&&(c.params.startContainer=c.params.startContainer.childNodes[c.params.startOffset-1]);1===c.params.endContainer.nodeType&&0<c.params.endOffset&&(c.params.endContainer=c.params.endContainer.childNodes[c.params.endOffset-1]);this.__mapContentFromContentEditableUsingParams(a,c,b);a={selection:c.selection,text:CWEChromeUtilities.htmlToUnicode(c.text),map:c.map};a.selection.length-=a.selection.start;return a};
CWEChromeHookGeneric.prototype.__mapContentFromContentEditableUsingParams=function(a,b,c){for(var e=a.childNodes,d=0;!b.params.stop&&d<e.length;d++){var g=e[d],f=g.tagName,h=g.nodeType;if("STYLE"!==f&&"SCRIPT"!==f){null!==c&&(Logger.instance.log(c+d+": tag = "+g.tagName+", id = "+g.id+", type = "+g.nodeType+", text = #"+g.textContent+"#"),Logger.instance.log(g));null!==b.params.prevNode&&(this.__tagNameRequiresNewLine(f)||3==h&&this.__tagNameRequiresNewLine(b.params.prevNode.tagName))&&(b.text+="\n",
b.map.push({element:b.params.prevNode,offset:b.params.prevNode.childNodes.length,text:"\n",embeded:!0}),null!=b.params.startContainer&&(b.selection.start+=1),null!=b.params.endContainer&&(b.selection.length+=1));if(b.params.startContainer&&b.params.startContainer===g||b.params.endContainer&&b.params.endContainer===g){f=3==h?g.textContent:" ";var k=3==h?b.params.startOffset:1,l=3==h?b.params.endOffset:1;if(3==h)for(h=0;h<f.length;h++)b.map.push({element:g,offset:h,text:f.charAt(h),embeded:!1});else b.map.push({element:a,
offset:d+1,text:" ",embeded:!0});b.text+=f;b.params.startContainer===g&&(b.selection.start+=k,b.params.startContainer=null,null!==c&&(Logger.instance.log(c+d+": start found = "+g.tagName+", text = #"+g.textContent+"#"),Logger.instance.log(c+d+": all text = #"+b.text+"#")));b.params.endContainer===g?(b.selection.length+=l,b.params.endContainer=null,null!==c&&(Logger.instance.log(c+d+": end found = "+g.tagName+", text = #"+g.textContent+"#"),Logger.instance.log(c+d+": all text = #"+b.text+"#"))):b.params.endContainer&&
(b.selection.length+=f.length)}else if(3==h){f=g.textContent;b.text+=f;for(h=0;h<f.length;h++)b.map.push({element:g,offset:h,text:f.charAt(h),embeded:!1});null!=b.params.startContainer&&(b.selection.start+=f.length);null!=b.params.endContainer&&(b.selection.length+=f.length)}else 1==h&&("IMG"===f?(b.text+=" ",b.map.push({element:a,offset:d+1,text:" ",embeded:!0}),null!=b.params.startContainer&&(b.selection.start+=1),null!=b.params.endContainer&&(b.selection.length+=1)):this.__mapContentFromContentEditableUsingParams(g,
b,null===c?null:"  "+c));b.params.prevNode=g}}};CWEChromeHookGeneric.prototype.__tagNameRequiresNewLine=function(a){return"P"===a||"DIV"===a||"LI"===a||"TD"===a};CWEChromeHookGeneric.prototype.replaceText=function(a,b,c){var e=this.__getEditorInfo(a);null!==e&&(void 0!==a.selectionStart?this.__replaceTextInInput(e,b,c):this.__replaceTextInContentEditable(e,b,c))};
CWEChromeHookGeneric.prototype.__replaceTextInInput=function(a,b,c){var e=c.custom.selectionOffset+b.selection.start;c=c.custom.selectionOffset;b.selection.hasOwnProperty("end")&&!isNaN(b.selection.end)?c+=b.selection.end:b.selection.hasOwnProperty("length")&&!isNaN(b.selection.length)&&(c+=b.selection.start+b.selection.length);a.m_editor.setSelectionRange(e,c);a.m_document.execCommand("insertHTML",!1,b.text)};
CWEChromeHookGeneric.prototype.__replaceTextInContentEditable=function(a,b,c){if(b.selection.start<b.selection.end){var e=a.m_document.getSelection();try{var d=c.custom.selectionOffset+b.selection.start,g=c.custom.selectionOffset+b.selection.end-1,f=0;c.custom.map[g].embeded&&(d==g&&(f=1,d--),g--);var h=c.custom.map[d];e.extend(a.m_editor,0);e.collapseToStart();e.extend(h.element,h.offset+f);e.collapseToEnd();if(d<=g){var k=c.custom.map[g];e.extend(k.element,k.offset+f+1)}}catch(l){Logger.instance.log(e),
Logger.instance.log(l)}}a.m_document.execCommand("insertText",!1,b.text)};CWEChromeHookGeneric.prototype.getContextForMomentaryTopic=function(a,b){Logger.instance.log("---------------------------- CWEChromeHookGeneric.getContextForMomentaryTopic");Logger.instance.log(a);b(CWEChromeUtilities.extractVisibleTextFromElement(document.body))};
CWEChromeHookGeneric.prototype.acquireTextForTopicAsync=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,e,f){for(;;)switch(c){case 0:return c=-1,{value:new Promise(function(b){var c="selection"===a?document.getSelection().toString():CWEChromeUtilities.extractVisibleTextFromElement(document.body);b(c)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEChromeHookGeneric.prototype.shouldIgnoreMutations=function(a){for(var b=!0,c=0;c<a.length;c++){var e=a[c],d=e.target.ownerDocument;if(d.querySelector("#__dji_sru_main_container_content")){b=!1;break}for(var g=!1,f=0;f<e.addedNodes.length&&!g;f++)0<d.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",e.addedNodes[f],null,XPathResult.NUMBER_TYPE).numberValue&&(g=!0);for(f=0;f<e.removedNodes.length&&!g;f++)0<d.evaluate("count(.//*[@contenteditable]|.//input|.//textarea)",e.removedNodes[f],
null,XPathResult.NUMBER_TYPE).numberValue&&(g=!0);if(g){b=!1;break}}return b};
