var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,d){b!=Array.prototype&&b!=Object.prototype&&(b[a]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var a=0;return $jscomp.iteratorPrototype(function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var a=b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill=function(b,a,d,c){if(a){d=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var e=b[c];e in d||(d[e]={});d=d[e]}b=b[b.length-1];c=d[b];a=a(c);a!=c&&null!=a&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:a})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function a(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(b,f){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;a.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};a.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var c=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){c(a,
0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];delete a[b];try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(f){d||(d=!0,a.call(b,f))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new a;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(l){d.reject(l)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(m){f(m)}}:b}var c,f,h=new e(function(a,
b){c=a;f=b});this.callWhenSettled_(d(a,c),d(b,f));return h};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?g.asyncExecute(d):this.onSettledCallbacks_.push(function(){g.asyncExecute(d)})};e.resolve=d;e.reject=function(a){return new e(function(b,d){d(a)})};e.race=function(a){return new e(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new e(function(a,e){function f(b){return function(d){g[b]=d;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(c.value).callWhenSettled_(f(g.length-1),e),c=b.next();while(!c.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(b){function a(a){return b.next(a)}function d(a){return b.throw(a)}return new Promise(function(c,e){function g(b){b.done?c(b.value):Promise.resolve(b.value).then(a,d).then(g,e)}g(b.next())})};
window.CWEChromeHookOffice365=function(){var b=function(a,b){this.m_installed=!1;this.m_ime=a;this.m_messageProxy=b;this.m_editor=b.window;this.m_hasFocus=!1;this.m_cache={cursor:void 0,context:void 0};this.__initialize()};b.prototype.__initialize=function(){var a=this;this.m_messageProxy.on("com.donjohnston.cwu.service.disconnect",function(){a.m_installed&&(a.m_hasFocus=!1,a.m_ime.serviceUnavailable(a.m_messageProxy.service,a))});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.ready",
function(){if(a.m_installed)a.m_ime.onCapabilitiesUpdate(this,"office365-word-document")});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.focus",function(){if(a.m_installed)a.onFocus(a.m_editor)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.blur",function(){if(a.m_installed)a.onBlur(a.m_editor)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.cursor",function(b,c){if(a.m_installed)a.onCursorAvailable(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.context",
function(b,c){if(a.m_installed)a.onContextAvailable(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.trueKeyMode",function(){if(a.m_installed)a.onToggleTrueKeyMode()});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.digitKey",function(b,c){if(a.m_installed)a.onDigitKey(c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keydown",function(b,c){if(a.m_installed)a.onKeyDown(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keypress",
function(b,c){if(a.m_installed)a.onKeyPress(a.m_editor,c)});this.m_messageProxy.on("com.donjohnston.cwu.office365.word.keyup",function(b,c){if(a.m_installed)a.onKeyUp(a.m_editor,c)});this.m_messageProxy.enable(!0)};b.prototype.install=function(){this.m_installed||(this.m_installed=!0,this.m_messageProxy.send("com.donjohnston.cwu.office365.word.activate",void 0,!0),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.cursor"),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.context"),
DexController.instance.setCursorInfoDelegate(this.getCaret.bind(this)))};b.prototype.uninstall=function(){this.m_installed&&(DexController.instance.setCursorInfoDelegate(null),this.m_messageProxy.send("com.donjohnston.cwu.office365.word.activate",void 0,!1),this.m_installed=!1)};b.prototype.reload=function(){if(this.m_hasFocus)this.m_ime.onEditorChanged(this,this.m_editor)};b.prototype.setTrueKeyMode=function(a){this.m_installed&&this.m_messageProxy.send("com.donjohnston.cwu.office365.word.trueKeyMode",
void 0,a)};b.prototype.onFocus=function(a,b){this.m_hasFocus=!0;this.m_ime.onEditorChanged(this,this.m_editor)};b.prototype.onBlur=function(a,b){this.m_hasFocus=!1;this.m_ime.onEditorChanged(null,null)};b.prototype.onCursorAvailable=function(a,b){this.m_cache.cursor=b;if(this.m_hasFocus)this.m_ime.onContextChanged(this)};b.prototype.onContextAvailable=function(a,b){this.m_cache.context=b;if(this.m_hasFocus)this.m_ime.onContextChanged(this)};b.prototype.onMouseDown=function(a,b){};b.prototype.onMouseUp=
function(a,b){};b.prototype.onKeyDown=function(a,b){b.skipHandleInput=!0;this.m_ime.onKeyDown(this,b)};b.prototype.onKeyPress=function(a,b){b.skipHandleInput=!0;this.m_ime.onKeyPress(this,b)};b.prototype.onKeyUp=function(a,b){b.skipHandleInput=!0;this.m_ime.onKeyUp(this,b)};b.prototype.onToggleTrueKeyMode=function(){this.m_ime.__toggleTruKeyMode(this)};b.prototype.onDigitKey=function(a){this.m_ime.onDigitKey(this,a)};b.prototype.getCaret=function(a){return this.m_cache.cursor||{left:0,top:0,right:0,
bottom:10}};b.prototype.getContext=function(a){a={session:-1,selection:{start:0,length:0},text:"",extended:{text:"",selection:{start:0,length:0}}};this.m_cache.context&&(a.session=this.m_cache.context.session,a.text=this.m_cache.context.text,a.selection.start=this.m_cache.context.selection.start,a.selection.end=this.m_cache.context.selection.start+this.m_cache.context.selection.length,a.selection.length=this.m_cache.context.selection.length,a.extended.text=this.m_cache.context.text,a.extended.selection.start=
this.m_cache.context.selection.start,a.extended.selection.length=this.m_cache.context.selection.length);return a};b.prototype.replaceText=function(a,b,c){this.m_installed&&this.m_cache.context&&this.m_cache.context.session===c.session&&(b.session=this.m_cache.context.session,this.m_messageProxy.send("com.donjohnston.cwu.office365.word.replaceText",void 0,b))};b.prototype.getContextForMomentaryTopic=function(a,b){this.m_installed?this.m_messageProxy.send("com.donjohnston.cwu.office365.word.text",function(a){b(a||
"")}):b("")};b.prototype.acquireTextForTopicAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,g){for(;;)switch(e){case 0:return d=b,e=-1,{value:new Promise(function(b){d.m_messageProxy.send("com.donjohnston.cwu.office365.word.text",b,a)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,d,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
f[Symbol.iterator]=function(){return this};return f}())};b.prototype.shouldIgnoreMutations=function(a){return!0};return b}();
