var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(g){b.reject(g)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(g){this.reject_(g);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(v){f(v)}}:b}var d,f,h=new e(function(a,
b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return h};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())c(e.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,f){function e(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(e(g.length-1),f),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var e=a.length;0<e&&0<c;)if(b[--c]!=a[--e])return!1;return 0>=e}},"es6","es3");
function CWEChromeIME(a,b){this.State={Idle:0,UpdateTopic:1,UpdateTopicFromPage:2};this.m_isChromeOS=-1!=window.navigator.userAgent.indexOf("CrOS");this.m_isMacOS=-1!=window.navigator.userAgent.indexOf("Macintosh");this.m_isWindowsOS=-1!=window.navigator.userAgent.indexOf("Windows");this.m_isGoogleDocs=this.m_isOffice365=!1;this.m_hookOffice365=this.m_hookGoogleDocs=this.m_hookGeneric=null;this.m_hooks=[];this.m_currentEditor=this.m_currentHook=null;this.m_currentContext={};this.m_currentBkgndRequest=
{id:0,responseCount:0};this.m_shortcut={Shortcuts:{None:0,TrueKeyMode:1,SelectGuess:2},active:0};this.m_digitKeyRegExp=/^(Digit|Numpad)([\d]{1})$/;this.m_arrowKeyRegExp=/^Arrow.*$/;this.m_trueKeyMode=!1;this.m_port=a;this.m_state=this.State.Idle;this.m_pause=this.m_on=!1;this.m_speechRecognition={session:null,on:!1,scope:null};this.m_mutationTimer=this.m_contextTimer=this.m_mutationObserver=null;this.m_settings={};this.m_developerMode=!1;this.__intialize(b);return this}
CWEChromeIME.prototype.__intialize=function(a){var b=this;if(this.m_isGoogleDocs=CWEChromeUtilities.isGoogleDocs())this.m_hookGoogleDocs=new CWEChromeHookGoogleDocs(this),this.m_hooks.push(this.m_hookGoogleDocs);this.m_isOffice365&&(this.m_hookOffice365=new CWEChromeHookOffice365(this),this.m_hooks.push(this.m_hookOffice365));this.m_hookGeneric=new CWEChromeHookGeneric(this);this.m_hooks.push(this.m_hookGeneric);DexController.instance.setLocationInfoDelegate(this.getImeLocation.bind(this));DexController.instance.addExtensionControls(cweMainView.view,
500);this.m_port.onDisconnect.addListener(function(a){b.__onPortDisconnect(a)});this.m_port.onMessage.addListener(function(a){b.__onPortMessage(a)});this.m_mutationObserver=new MutationObserver(function(a){b.onDOMMutations(a)});cweMainView.viewDidChangeDelegate=this.__onViewDidChange.bind(this);cweMainView.trueKeyModeDidChangeDelegate=this.__onTrueKeyModeDidChangeDelegate.bind(this);cweMainView.speakClickDelegate=this.__onSpeakText.bind(this);cweMainView.suggestionClickDelegate=this.__onSuggestionSelected.bind(this);
cweMainView.keyboardClickDelegate=this.__onVirtualKeyboardInput.bind(this);cweMainView.speechRecognitionDelegate=this.__onSpeechRecognition.bind(this);dji.topicHelper.setActivateTopicDelegate(this.__onActivateTopic.bind(this));dji.topicHelper.setUpdateTopicDelegate(this.__onUpdateTopic.bind(this));Logger.instance.log("[Co:Writer IME] Document state is: "+document.readyState);"complete"===document.readyState?(Logger.instance.log("[Co:Writer IME] Document is already loaded: "+window.location),this.__postNeedSetup(),
this.__postDocumentReady()):(Logger.instance.log("[Co:Writer IME] Waiting for document to finish loading: "+window.location),document.onreadystatechange=function(){Logger.instance.log("[Co:Writer IME] document state: "+document.readyState);"complete"===document.readyState&&(Logger.instance.log("[Co:Writer IME] Document fully loaded: "+window.location),b.__postNeedSetup(),b.__postDocumentReady())});a&&a()};CWEChromeIME.prototype.serviceIsSupported=function(a){return"ms-office-word-editor"===a};
CWEChromeIME.prototype.serviceAvailable=function(a,b){if("ms-office-word-editor"!==a||this.m_isOffice365)return b.disconnect();this.m_isOffice365=!0;this.m_hookOffice365=new CWEChromeHookOffice365(this,b,!(!this.m_on||this.m_pause));this.m_hooks.push(this.m_hookOffice365);this.m_on&&!this.m_pause&&this.m_hookOffice365.install()};
CWEChromeIME.prototype.serviceUnavailable=function(a,b){if("ms-office-word-editor"===a&&b&&(a=this.m_hooks.indexOf(b),0<=a&&this.m_hooks.splice(a,1),this.m_isOffice365=!1,this.m_currentHook===b))this.onEditorChanged(null,null)};CWEChromeIME.prototype.setup=function(a){cweMainView.setWikiReaderOptions(a)};CWEChromeIME.prototype.getTrueKeyMode=function(){return this.m_trueKeyMode};
CWEChromeIME.prototype.restart=function(a){Logger.instance.log("------------- CWEChromeIME.restart begin");var b=this;this.m_port=a;this.m_port.onMessage.addListener(function(a){b.__onPortMessage(a)});this.__postNeedSetup();this.__cancelContextTimer();this.stopObservingDOMMutations();this.__showWindow(!1);for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall();this.__accumulateData(null);if(this.m_on&&!this.m_pause){for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.observeDOMMutations();
this.__accumulateData(null)}Logger.instance.log("------------- CWEChromeIME.restart finished")};CWEChromeIME.prototype.activate=function(a){Logger.instance.log("------------- CWEChromeIME.activate begin");if(!this.m_on&&!this.m_pause)if(a&&"create_topic"===a.action)this.m_pause=!0;else{for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.observeDOMMutations()}this.m_on=!0;Logger.instance.log("------------- CWEChromeIME.activate finished");return this.m_on};
CWEChromeIME.prototype.deactivate=function(){Logger.instance.log("------------- CWEChromeIME.deactivate");if(this.m_on)if(this.m_on=!1,this.m_pause)this.m_pause=!1,this.__showWindow(!1,!0,!0);else{this.__cancelContextTimer();this.stopObservingDOMMutations();this.__showWindow(!1,!0,!0);for(var a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall()}Logger.instance.log("------------- CWEChromeIME.deactivate finished");return this.m_on};
CWEChromeIME.prototype.resume=function(){Logger.instance.log("------------- CWEChromeIME.resume begin");if(this.m_on&&this.m_pause){for(var a=0;a<this.m_hooks.length;a++)this.m_hooks[a].install(!0);this.observeDOMMutations()}this.m_pause=!1;Logger.instance.log("------------- CWEChromeIME.resume finished")};
CWEChromeIME.prototype.pause=function(a){Logger.instance.log("------------- CWEChromeIME.suspend");if(!this.m_pause&&(this.m_pause=!0,this.m_on)){this.__cancelContextTimer();this.stopObservingDOMMutations();a||this.__showWindow(!1);for(a=0;a<this.m_hooks.length;a++)this.m_hooks[a].uninstall();this.__accumulateData(null)}Logger.instance.log("------------- CWEChromeIME.suspend finished")};
CWEChromeIME.prototype.findSruInfo=function(){var a={div:document.getElementById("__dji_sru_main_container"),iframe:document.getElementById("__dji_sru_main_container_iframe"),contentDocument:null};a.div&&!a.iframe&&a.div.shadowRoot&&(a.iframe=a.div.shadowRoot.getElementById("__dji_sru_main_container_iframe"));try{a.iframe&&(a.contentDocument=a.iframe.contentDocument)}catch(b){Logger.instance.error(b)}return a};CWEChromeIME.prototype.onCapabilitiesUpdate=function(a,b){this.__postDocumentCapabilitiesUpdate({service:b})};
CWEChromeIME.prototype.observeDOMMutations=function(a){var b=this.findSruInfo();if(!a||b.contentDocument&&!b.contentDocument.watchedByCoWriter){var c={subtree:!0,childList:!0},d={subtree:!0,childList:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["contenteditable"]};a||(this.m_mutationObserver.observe(document.body,c),this.m_mutationObserver.observe(document.body,d));b.contentDocument&&!b.contentDocument.watchedByCoWriter&&(b.contentDocument.watchedByCoWriter=!0,this.m_mutationObserver.observe(b.contentDocument.body,
c),this.m_mutationObserver.observe(b.contentDocument.body,d))}};CWEChromeIME.prototype.stopObservingDOMMutations=function(){this.m_mutationObserver.disconnect();var a=this.findSruInfo();a.contentDocument&&a.contentDocument.watchedByCoWriter&&(a.contentDocument.watchedByCoWriter=!1)};
CWEChromeIME.prototype.onDOMMutations=function(a){this.observeDOMMutations(!0);if(!this.m_currentHook||!this.m_currentHook.shouldIgnoreMutations(a)){for(var b=!1,c=0;!b&&c<a.length;c++){var d=a[c];"attributes"===d.type&&d.target.getAttribute("contenteditable")!==d.oldValue&&(b=!0)}var e=this;this.__cancelDOMMutationTimer();this.m_mutationTimer=setTimeout(function(){e.__cancelDOMMutationTimer();for(var a=0;a<e.m_hooks.length;a++)e.m_hooks[a].reload(!0)},b?200:800)}};
CWEChromeIME.prototype.toggleOnOff=function(){this.m_port.postMessage({message:"com.donjohnston.cowriter.chrome.message.toggleOnOff"})};
CWEChromeIME.prototype.onEditorChanged=function(a,b){Logger.instance.log("CWEChromeIME.onEditorChanged:",a,b);Logger.instance.log(a);Logger.instance.log(b);this.__accumulateData(null);this.m_shortcut.active=this.m_shortcut.Shortcuts.None;if(this.m_isGoogleDocs&&a!==this.m_hookGoogleDocs&&null===b&&this.m_hookGoogleDocs&&this.m_on&&!this.m_pause){var c=this.m_hookGoogleDocs.getState();c.active&&(a=c.hook,b=c.editor,Logger.instance.log("-------------------------------- editor fallback to Google Docs:",
a,b),Logger.instance.log(a),Logger.instance.log(b))}this.m_currentHook=a;this.m_currentEditor=b;this.__postIMEActivationChanged(!(null==b||void 0===b));this.__getContext(!0,!0)};CWEChromeIME.prototype.onContextChanged=function(a){Logger.instance.log("CWEChromeIME.onContextChanged:",a);this.__postScheduleSpeechRecognition(!1);this.__getContext(!1,!0)};CWEChromeIME.prototype.onCaretChanged=function(a){Logger.instance.log("CWEChromeIME.onCaretChanged:",a);this.__onCaretChanged()};
CWEChromeIME.prototype.onMouseDown=function(a,b){Logger.instance.log("CWEChromeIME.onMouseDown:",a);this.__accumulateData(null)};CWEChromeIME.prototype.onMouseUp=function(a,b){Logger.instance.log("CWEChromeIME.onMouseUp:",a);this.__getContext(!1,!0)};
CWEChromeIME.prototype.onKeyDown=function(a,b){if("Alt"===b.key||"Control"===b.key||"Shift"===b.key||"CapsLock"===b.key||"Meta"===b.key)return!1;this.__cancelContextTimer();if("Backspace"===b.code)this.__accumulateData("\b");else if(this.m_arrowKeyRegExp.test(b.code))this.__accumulateData(null);else if("Enter"===b.code&&this.m_hookGoogleDocs===this.m_currentHook&&this.m_hookGoogleDocs===a)this.__onTryToSpeak("\n");else if("KeyN"===b.code){if(b.altKey&&!(b.ctrlKey||b.shiftKey||b.metaKey))return this.m_shortcut.active===
this.m_shortcut.Shortcuts.None&&(this.m_shortcut.active=this.m_shortcut.Shortcuts.TrueKeyMode,this.__toggleTruKeyMode(),this.__getContext(!1,!1)),!0}else if(!(this.m_trueKeyMode||b.altKey||b.ctrlKey||b.shiftKey||b.metaKey)&&(a=b.code.match(this.m_digitKeyRegExp))&&3===a.length&&(a=parseInt(a[2]),(a=cweMainView.suggestionFromNumber(a))&&a.item))return this.m_settings.speech.words&&this.__postScheduleSpeak(a.item),this.__postGuessSelected(a.item),!0;this.m_shortcut.active=this.m_shortcut.Shortcuts.None;
this.__getContext(!1,!0);return!1};CWEChromeIME.prototype.onKeyPress=function(a,b){Logger.instance.log("CWEChromeIME.onKeyPress:",a);Logger.instance.log(b);a=String.fromCharCode(b.charCode);this.__cancelContextTimer(a);this.__onTryToSpeak(a);if(!b.skipHandleInput&&this.__handleInput(a))return!0;this.__getContext(!1,!1);return!1};CWEChromeIME.prototype.onKeyUp=function(a,b){this.m_shortcut.active=this.m_shortcut.Shortcuts.None;return!1};CWEChromeIME.prototype.onToggleTrueKeyMode=function(){this.__toggleTruKeyMode()};
CWEChromeIME.prototype.onDigitKey=function(a,b){if((a=cweMainView.suggestionFromNumber(b))&&a.item)return this.m_settings.speech.words&&this.__postScheduleSpeak(a.item),this.__postGuessSelected(a.item),!0};
CWEChromeIME.prototype.__onTryToSpeak=function(a){if(this.m_settings.speech.sentences&&CWECharacterSet.sentenceSeparatorCharacterSet.characterIsMember(a)){this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor);var b=CWEChromeUtilities.findSentence(this.m_currentContext.extended.text,this.m_currentContext.extended.selection.start-1);b&&0<b.length&&this.__postScheduleSpeak(b+a)}else this.m_settings.speech.words&&CWECharacterSet.wordSeparatorCharacterSet.characterIsMember(a)?(this.m_currentContext=
this.m_currentHook.getContext(this.m_currentEditor),(b=CWEChromeUtilities.findWord(this.m_currentContext.extended.text,this.m_currentContext.extended.selection.start-1))&&0<b.length&&this.__postScheduleSpeak(b)):this.m_settings.speech.letters&&this.__postScheduleSpeak(a)};CWEChromeIME.prototype.onSpeak=function(a){this.__postSpeak(a,!0)};CWEChromeIME.prototype.onStopSpeak=function(){this.__postStopSpeak()};CWEChromeIME.prototype.onAddPersonalWords=function(a){this.__postAddPersonalWords(a)};
CWEChromeIME.prototype.onRemovePersonalWords=function(a){this.__postRemovePersonalWords(a)};CWEChromeIME.prototype.onQuickTopic=function(a){this.__postQuickTopic(a)};CWEChromeIME.prototype.__cancelDOMMutationTimer=function(){null!=this.m_mutationTimer&&(clearTimeout(this.m_mutationTimer),this.m_mutationTimer=null)};CWEChromeIME.prototype.__cancelContextTimer=function(){null!=this.m_contextTimer&&(clearTimeout(this.m_contextTimer),this.m_contextTimer=null)};
CWEChromeIME.prototype.__getContext=function(a,b){var c=this;this.__cancelContextTimer();a?setTimeout(function(){c.__onEditorChanged()},0):(setTimeout(function(){c.__onCaretChanged()},0),this.m_contextTimer=setTimeout(function(){c.__onContextChanged(b)},100))};CWEChromeIME.prototype.__onCaretChanged=function(){var a=this.getImeLocation();a&&this.__moveWindow(a.left,a.top)};
CWEChromeIME.prototype.getImeLocation=function(){var a=this.m_currentEditor?this.m_currentHook.getCaret(this.m_currentEditor):null,b=null;if(a){var c=cweMainView.size;b=CWEChromeUtilities.getScrollbarSize();var d=c.width;c=c.height;var e=window.innerHeight,f=a.left,h=a.bottom+2;window.innerWidth<f+d+b.width+2&&(0<=a.left-d&&(f=a.left-d),f<window.pageXOffset&&(f=window.pageXOffset));e<h+c+b.height+2&&0<=a.top-c-2&&(h=a.top-c-2);b={left:f,top:h,caret:a}}return b};
CWEChromeIME.prototype.__onEditorChanged=function(){Logger.instance.log("CWEChromeIME.__onEditorChanged: ");this.m_currentContext=this.m_currentEditor?this.m_currentHook.getContext(this.m_currentEditor):null;Logger.instance.log(this.m_currentContext);this.m_currentEditor&&null!==this.m_currentContext&&this.__postContextAvailable(!0);this.__onCaretChanged();this.__showWindow(null!==this.m_currentEditor)};
CWEChromeIME.prototype.__onContextChanged=function(a){this.__cancelContextTimer();null!==this.m_currentHook&&(this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor),Logger.instance.log("contextChanged:",this.m_currentContext),this.__postContextAvailable(a))};CWEChromeIME.prototype.__toggleTruKeyMode=function(){cweMainView.toggleTrueKeyMode()&&this.__updateTruKeyMode()};
CWEChromeIME.prototype.__updateTruKeyMode=function(){this.m_trueKeyMode=cweMainView.trueKeyMode;for(var a=0;a<this.m_hooks.length;a++)this.m_hooks[a].setTrueKeyMode(this.m_trueKeyMode)};CWEChromeIME.prototype.__showWindow=function(a,b,c){a=!!a||!(b||!cweMainView.hasFocus());c&&a&&cweMainView.reset();cweMainView.show(a);c&&!a&&cweMainView.reset()};CWEChromeIME.prototype.__moveWindow=function(a,b){DexController.instance.move(cweMainView.view,a,b)};CWEChromeIME.prototype.__postDocumentReady=function(){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.documentReady"})};
CWEChromeIME.prototype.__postDocumentCapabilitiesUpdate=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.documentCapabilitiesUpdate",details:a})};CWEChromeIME.prototype.__postNeedSetup=function(){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.needSetup"})};
CWEChromeIME.prototype.__postContextAvailable=function(a){var b=this.m_currentContext.selection,c=this.m_currentContext.text;this.m_currentBkgndRequest.id=Math.max(1,(this.m_currentBkgndRequest.id+1)%1E6);this.m_currentBkgndRequest.responseCount=0;this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.contextAvailable",context:{selection:b,text:c,changed:a},requestId:this.m_currentBkgndRequest.id})};
CWEChromeIME.prototype.__postContextForMomentaryTopicAvailable=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.contextForMomentaryTopicAvailable",context:{text:a}})};CWEChromeIME.prototype.__postGuessSelected=function(a){Logger.instance.log("CWEChromeIME.__postGuessSelected: #"+a+"#");this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.guessSelected",guess:a})};CWEChromeIME.prototype.__postRestartGuesses=function(){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.restartGuesses"})};
CWEChromeIME.prototype.__postScheduleSpeak=function(a){this.m_speechRecognition.on||this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.scheduleSpeak",text:a,stopCurrentSpeech:!0})};CWEChromeIME.prototype.__postAddPersonalWords=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.onAddPersonalWords",text:a})};
CWEChromeIME.prototype.__postRemovePersonalWords=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.onRemovePersonalWords",text:a})};CWEChromeIME.prototype.__postQuickTopic=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.onQuickTopic",text:a})};
CWEChromeIME.prototype.__execUpdateTopic=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,e,k){for(;;)switch(d){case 0:return d=-1,{value:b.__executeCommandAsync("com.donjohnston.cowriter.chrome.message.topics.update",a),done:!0};default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};
return e}())};
CWEChromeIME.prototype.__execActivateTopic=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,e,k){for(;;)switch(d){case 0:return d=-1,{value:b.__executeCommandAsync("com.donjohnston.cowriter.chrome.message.topics.activate",a),done:!0};default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};
return e}())};CWEChromeIME.prototype.__postSpeak=function(a,b){this.m_speechRecognition.on||this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.speak",text:a,force:b})};CWEChromeIME.prototype.__postStopSpeak=function(){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.stopspeak"})};CWEChromeIME.prototype.__postIMEActivationChanged=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.imeActivationChanged",active:a})};
CWEChromeIME.prototype.__postAccumulateData=function(a){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.accumulateData",text:a})};CWEChromeIME.prototype.__postScheduleSpeechRecognition=function(a,b,c,d){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.speechRecognition",on:a,langCode:b,scope:c,session:d})};
CWEChromeIME.prototype.__postSearchTopics=function(a,b){this.__postPortMessage({message:"com.donjohnston.cowriter.chrome.message.topics.search",pattern:a,session:b})};CWEChromeIME.prototype.__postPortMessage=function(a){if(this.m_port)try{this.m_port.postMessage(a)}catch(b){Logger.instance.error(b)}};
CWEChromeIME.prototype.__executeCommandAsync=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,k,n){for(;;)switch(f){case 0:if(!d.m_port){f=1;break}h=d;f=-1;return{value:new Promise(function(d,e){h.__executeCommand(a,b,c,d,e)}),done:!0};case 1:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,k={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
k[Symbol.iterator]=function(){return this};return k}())};
CWEChromeIME.prototype.__executeCommand=function(a,b,c,d,e){if(d&&!(d instanceof Function))throw Error("Invalid arguments: successCallback is not a function!");var f=this.m_port;c=this.__executeCommand.session=(this.__executeCommand.session||0)+1;var h=d?"com.donjohnston.cwu.cs.session."+c:void 0;a={message:a,params:b,options:{callbackMessage:h}};var k=void 0,g=void 0;try{d&&(k=function(a){if(a&&a.message===h){g&&f.onDisconnect.removeListener(g);f.onMessage.removeListener(k);try{d(a.params)}catch(n){Logger.instance.error(n)}}},
f.onMessage.addListener(k)),e&&(g=function(){f.onDisconnect.removeListener(g);d&&f.onMessage.removeListener(k);try{e()}catch(l){Logger.instance.error(l)}},f.onDisconnect.addListener(g)),f.postMessage(a)}catch(l){Logger.instance.error(l),g&&f.onDisconnect.removeListener(g),k&&f.onMessage.removeListener(k),e&&e(l)}};CWEChromeIME.prototype.__onPortDisconnect=function(a){Logger.instance.log("CWEChromeIME.__onPortDisconnect");Logger.instance.log(a)};
CWEChromeIME.prototype.__onPortMessage=function(a){if("com.donjohnston.cowriter.chrome.message.guessesAvailable"===a.message)a.requestId===this.m_currentBkgndRequest.id&&(this.m_currentBkgndRequest.responseCount++,this.__showGuesses(1===this.m_currentBkgndRequest.responseCount,a.guesses,a.replacements,void 0));else if("com.donjohnston.cowriter.chrome.message.translationsAvailable"===a.message)a.requestId===this.m_currentBkgndRequest.id&&(this.m_currentBkgndRequest.responseCount++,this.__showGuesses(1===
this.m_currentBkgndRequest.responseCount,void 0,void 0,a.translations));else if("com.donjohnston.cowriter.chrome.message.replaceText"===a.message)this.__replaceText(a.info,!0);else if("com.donjohnston.cowriter.chrome.message.settings"===a.message)(this.m_settings=a.settings)&&this.m_settings.text&&this.m_settings.text.textColor&&dji.cwe.resourceProxy.cacheSvgData(this.m_settings.text.textColor),cweMainView.setOptions({locale:this.m_settings.locale,window:{scale:this.m_settings.window.scale,fontFamily:this.m_settings.text.fontFamily,
textColor:this.m_settings.text.textColor,backgroundColor:this.m_settings.text.backgroundColor},suggestions:this.m_settings.window.suggestions,translation:this.m_settings.translation});else if("com.donjohnston.cowriter.chrome.message.topics.data"===a.message)this.topicsDataAvailable(a.data);else if("com.donjohnston.cowriter.chrome.message.topics.update"===a.message)cweMainView.cancelResetToCreateTopic();else if("com.donjohnston.cowriter.chrome.message.getContextForMomentaryTopic"===a.message&&this.m_on&&
!this.m_pause)if(this.m_currentHook){var b=this;this.m_currentHook.getContextForMomentaryTopic(this.m_currentEditor,function(a){b.m_settings.isEnglish&&(a=CWEChromeUtilities.wikiHtmlToAscii(a));b.__postContextForMomentaryTopicAvailable(a)})}else a=CWEChromeUtilities.extractVisibleTextFromElement(document.body),this.m_settings.isEnglish&&(a=CWEChromeUtilities.wikiHtmlToAscii(a)),this.__postContextForMomentaryTopicAvailable(a)};
CWEChromeIME.prototype.__showGuesses=function(a,b,c,d){b&&cweMainView.setSuggestions(b,c,a);d&&cweMainView.setTranslations(d,null,a);(b||d)&&this.__onCaretChanged()};CWEChromeIME.prototype.__replaceText=function(a,b){this.m_currentEditor&&(this.m_currentHook.replaceText(this.m_currentEditor,a,this.m_currentContext),a.skipGetContext||this.__getContext(!1),b&&(b="",a.selection.start<a.selection.end&&(b+=Array(a.selection.end-a.selection.start+1).join("\b")),b+=a.text,this.__accumulateData(b)))};
CWEChromeIME.prototype.__handleInput=function(a,b){Logger.instance.log("CWEChromeIME.__handleInput: "+a);if(void 0===a||null===a||0>=a.length)return!1;this.m_currentContext=this.m_currentHook.getContext(this.m_currentEditor);Logger.instance.log(this.m_currentContext);var c=this.m_currentContext.selection.start,d=this.m_currentContext.selection.length,e=c+d,f=this.m_currentContext.text,h=null,k;var g=a.charAt(0);for(k=c-1;0<=k;k--){var l=f.charAt(k);if(" "!=l){h=l;break}}if("\n"!=g&&"\r"!=g&&(null===
h||"."==h||"?"==h||"!"==h||";"==h||"\n"==h||"\r"==h))return f=g.toUpperCase(),b?(b.selection={start:c,end:c+d},b.text=f+a.substring(1)):(this.__replaceText({selection:{start:c,end:c+d},text:f}),this.__accumulateData(f)),!0;if("."==g||"?"==g||"!"==g||";"==h||","==g)return f=g+" ",c=k+1,d=e-c,b?(b.selection={start:c,end:c+d},b.text=f):(this.__replaceText({selection:{start:c,end:c+d},text:f}),this.__accumulateData(f)),!0;b||(this.__accumulateData(a),this.__postRestartGuesses());return!1};
CWEChromeIME.prototype.__accumulateData=function(a){a&&13==a.charCodeAt(0)&&(a=null);this.__postAccumulateData(a)};CWEChromeIME.prototype.__onViewDidChange=function(a,b){"topics"===a?this.pause(!0):"topics"===b&&this.resume()};CWEChromeIME.prototype.__onTrueKeyModeDidChangeDelegate=function(a,b){this.__updateTruKeyMode()};CWEChromeIME.prototype.__onSpeakText=function(a){this.__postSpeak(a,!0)};
CWEChromeIME.prototype.__onSuggestionSelected=function(a){this.m_settings.speech.words&&this.__postScheduleSpeak(a.audio);this.__postGuessSelected(a.item)};CWEChromeIME.prototype.__onVirtualKeyboardInput=function(a){!this.m_currentContext||!a.key||1>a.key.length||this.__replaceText({selection:this.m_currentContext.selection,text:a.key},!0)};
CWEChromeIME.prototype.__onSpeechRecognition=function(a){if(a.activate)this.m_speechRecognition.session=Date.now()+"-"+parseInt(1E3*Math.random()),this.m_speechRecognition.scope=a.scope,this.m_speechRecognition.on=!0,this.__postScheduleSpeechRecognition(a.activate,a.langCode,a.scope,this.m_speechRecognition.session);else{var b=this.resetSpeechRecognitionInfo();this.__postScheduleSpeechRecognition(a.activate);cweMainView.stopSpeechRecognition(b)}};
CWEChromeIME.prototype.__onUpdateTopic=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,e,k){for(;;)switch(d){case 0:return d=-1,{value:b.__execUpdateTopic(a),done:!0};default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEChromeIME.prototype.__onActivateTopic=function(a){return this.__execActivateTopic(a)};CWEChromeIME.prototype.onSpeechRecognitionNotification=function(a,b){a===this.m_speechRecognition.session&&("soundstart"===b.type?cweMainView.pulseSpeechRecognition(!0,this.m_speechRecognition.scope):"soundend"===b.type&&cweMainView.pulseSpeechRecognition(!1,this.m_speechRecognition.scope))};
CWEChromeIME.prototype.onSpeechRecognitionProgress=function(a,b,c){a===this.m_speechRecognition.session&&("search_topics"===this.m_speechRecognition.scope?cweMainView.searchTopicsPattern=c:"dictation"!==this.m_speechRecognition.scope||!this.m_currentContext||!c||1>c.length||(a=this.m_currentContext.selection,b={},this.__handleInput(c,b)&&b.selection&&(a=b.selection,c=b.text),c.endsWith(" ")||c.endsWith("\n")||(c+=" "),this.__replaceText({selection:a,text:c},!0)))};
CWEChromeIME.prototype.onSpeechRecognitionEnd=function(a,b){a===this.m_speechRecognition.session&&(a=this.resetSpeechRecognitionInfo(),b&&401!==b&&cweMainView.showSpeechRecognitionError(!0,a),cweMainView.stopSpeechRecognition(a),401===b&&((b=document.getElementById("__DJI_CWE_SPEECHRECOGNITION_PERMISSION"))?b.src=b.src:(b=document.createElement("iframe"),b.id="__DJI_CWE_SPEECHRECOGNITION_PERMISSION",b.src=chrome.extension.getURL("Background/helpers/speechRecognitionPermission.html"),b.allow="microphone",
document.body.appendChild(b))))};CWEChromeIME.prototype.resetSpeechRecognitionInfo=function(){var a=this.m_speechRecognition.scope;this.m_speechRecognition.on=!1;this.m_speechRecognition.scope=null;this.m_speechRecognition.session=null;return a};
CWEChromeIME.prototype.topicsDataAvailable=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,d,h){for(;;)switch(c){case 0:dji.topicHelper.setTopics(a.topics,a.activeTopics,a.displayTopics),cweMainView.topics=a.topics,cweMainView.displayTopics=a.displayTopics,c=-1;default:return{value:void 0,done:!0}}}var c=0,d={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
d[Symbol.iterator]=function(){return this};return d}())};
CWEChromeIME.prototype.createTopic=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,q,t){for(;;)switch(d){case 0:return d=1,{value:b.acquireTextForTopicAsync(a.from),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw t;case 2:(p=u=q)&&(p=p.trim());if(p&&!(0>=p.length)){d=3;break}d=-1;return{value:void 0,done:!0};case 3:p=a.isEnglish?CWEChromeUtilities.wikiHtmlToAscii(p):CWEChromeUtilities.htmlToUnicode(p);n=CWEChromeUtilities.titleForTopic({text:p,maxLength:34,useAscii:!0,
usePageTitle:"selection"!==a.from,combine:!1});a.topics&&b.topicsDataAvailable(a);l=b;g=!1;b.m_state=b.State.UpdateTopicFromPage;b.pause();try{return d=6,{value:dji.topicHelper.updateTopicAsync({name:n,data:p,local:!1,extras:{source:a.from}},function(b){g="update"===b.userData.action;l.showToastForUpdateTopic(g,a.from)}),done:!1}}catch(r){k=r;d=4;break}case 6:try{if(1!=c){d=7;break}d=-1;throw t;}catch(r){k=r;d=4;break}case 7:try{(f=h=q)&&f.success?b.showToastForUpdateTopicDidFinish(g,f.active):b.showToastForUpdateTopicDidFail(g);
d=5;break}catch(r){k=r;d=4;break}case 4:e=k,Logger.instance.error(e),b.showToastForUpdateTopicDidFail(g);case 5:b.m_state=b.State.Idle,b.resume(),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,h,k,g,l,n,p,u,q={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q}())};
CWEChromeIME.prototype.acquireTextForTopicAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,n,q){for(;;)switch(d){case 0:l=void 0;try{if(null!==l&&void 0!==l||!b.m_hookOffice365){d=3;break}d=4;return{value:b.m_hookOffice365.acquireTextForTopicAsync(a),done:!1}}catch(m){g=m;d=1;break}case 4:try{if(1!=c){d=5;break}d=-1;throw q;}catch(m){g=m;d=1;break}case 5:try{l=k=n}catch(m){g=m;d=1;break}case 3:try{if(null!==l&&void 0!==l||!b.m_hookGoogleDocs){d=6;break}d=7;
return{value:b.m_hookGoogleDocs.acquireTextForTopicAsync(a),done:!1}}catch(m){g=m;d=1;break}case 7:try{if(1!=c){d=8;break}d=-1;throw q;}catch(m){g=m;d=1;break}case 8:try{l=h=n}catch(m){g=m;d=1;break}case 6:try{if(null!==l&&void 0!==l||!b.m_hookGeneric){d=9;break}d=10;return{value:b.m_hookGeneric.acquireTextForTopicAsync(a),done:!1}}catch(m){g=m;d=1;break}case 10:try{if(1!=c){d=11;break}d=-1;throw q;}catch(m){g=m;d=1;break}case 11:try{l=f=n}catch(m){g=m;d=1;break}case 9:try{d=2;break}catch(m){g=m;
d=1;break}case 1:e=g,Logger.instance.error(e);case 2:return d=-1,{value:l,done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,h,k,g,l,n={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};
CWEChromeIME.prototype.showToastForUpdateTopic=function(a,b){return $jscomp.executeAsyncGenerator(function(){function c(c,g,h){for(;;)switch(d){case 0:f=b?" from "+b:" from web",e=a?"Updating topic"+f+".":"Creating topic"+f+".",DjiCwuToast.show(e),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,h={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};
return h}())};
CWEChromeIME.prototype.showToastForUpdateTopicDidFail=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,e,k){for(;;)switch(c){case 0:d=a?"An error has been encountered while updating the topic.":"An error has been encountered while creating the topic.",DjiCwuToast.show(d,{closeOnClick:!0},1E4),c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};
$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEChromeIME.prototype.showToastForUpdateTopicDidFinish=function(a,b){return $jscomp.executeAsyncGenerator(function(){function c(c,g,h){for(;;)switch(d){case 0:f=b?" and is now active":"",e=a?"Your topic has been updated"+f+".":"Your topic has been created"+f+".",DjiCwuToast.show(e,{action:{name:"TOPICS",message:"com.donjohnston.cowriter.chrome.message.options",close:!0},closeOnClick:!0},1E4),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,h={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
CWEChromeIME.prototype.notificationAvailable=function(a,b){"update_topic_started"===a?b&&b.userData&&this.showToastForUpdateTopic("update"===b.userData.action,b.userData.extras?b.userData.extras.source:void 0):"update_topic_failed"===a?(b&&b.userData&&this.showToastForUpdateTopicDidFail("update"===b.userData.action),this.resume()):"update_topic_finished"===a?(b&&b.userData&&this.showToastForUpdateTopicDidFinish("update"===b.userData.action),this.resume()):"deactivate"===a&&DjiCwuToast.hide()};
