var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,h){c!=Array.prototype&&c!=Object.prototype&&(c[e]=h.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var e=0;return $jscomp.iteratorPrototype(function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,e){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var h=0,k={next:function(){if(h<c.length){var n=h++;return{value:e(n,c[n]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill=function(c,e,h,k){if(e){h=$jscomp.global;c=c.split(".");for(k=0;k<c.length-1;k++){var n=c[k];n in h||(h[n]={});h=h[n]}c=c[c.length-1];k=h[c];e=e(k);e!=k&&null!=e&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
(function(){function c(a,d,l,f){if(!a||a instanceof Array&&0>=a.length)return l();f=f||0;if(a instanceof Array)e(a,0,d,l,f);else{var c=Object.keys(a);h(a,c,0,d,l,f)}}function e(a,d,c,f,g){if(a.length<=d)return f();2===c.length?c(a[d],function(l){l?setTimeout(f,g,l):setTimeout(e,g,a,d+1,c,f,g)}):c(d,a[d],function(l){l?setTimeout(f,g,l):setTimeout(e,g,a,d+1,c,f,g)})}function h(a,d,c,f,g,m){if(d.length<=c)return g();2===f.length?f(a[d[c]],function(b){b?setTimeout(g,m,b):setTimeout(h,m,a,d,c+1,f,g,m)}):
f(d[c],a[d[c]],function(b){b?setTimeout(g,m,b):setTimeout(h,m,a,d,c+1,f,g,m)})}function k(a,d){if(!a||0>=a.length||!document.activeElement)return d();a=r(a);p(a,!0,5,function(a,d,c){!c&&d.__char&&document.execCommand("insertText",!1,d.__char)},function(){setTimeout(function(){var a=new Event("textInput",{bubbles:!0,cancelable:!0});a.__isDjiSyntheticEvent=!0;a.data="";a.which=0;a.detail=0;a.repeat=!1;a.isComposing=!1;document.activeElement.dispatchEvent(a);setTimeout(d,10)},10)})}function n(a,d){a=
a&&void 0!==a.repeats?a.repeats:1;if(0>=a)return d();a=t([{id:1,type:"keydown",key:"Delete",keyCode:46,repeats:a},{type:"keyup",key:"Delete",keyCode:46}]);p(a,!0,0,function(a,d,c){c||1!==d.__id||document.execCommand("forwardDelete",!1,null)},function(){setTimeout(d,10)})}function u(a,d){c(a,function(a,d,c){a=v(d);p(a,!1,0,function(a,b,c){d.callbackMessage&&(a=new CustomEvent(d.callbackMessage,{detail:{index:a,cancelled:c,params:d}}),document.documentElement.dispatchEvent(a))},c)},function(){setTimeout(d,
10)})}function p(a,d,l,f,g){var m=document.activeElement;if(d)c(a,function(a,b,d){var c=!m.dispatchEvent(b);f&&f(a,b,c)?d(!0):d(!1)},g,l);else{d=!1;l=function(a){};var b=function(a){};m.addEventListener("blur",l,!0);m.addEventListener("focus",b,!0);for(var e=0;!d&&e<a.length;e++){var h=a[e],k=!m.dispatchEvent(h);if(f&&f(e,h,k)){d=!0;break}}m.removeEventListener("blur",l,!0);m.removeEventListener("focus",b,!0);g(d)}}function r(a){for(var d=[],c=0;c<a.length;c++){var f=a.charCodeAt(c),g=a.charAt(c),
e=g.toUpperCase()===g;if(e){var b=new Event("keydown",{bubbles:!0,cancelable:!0});b.__isDjiSyntheticEvent=!0;b.altKey=!1;b.ctrlKey=!1;b.metaKey=!1;b.shiftKey=e;b.code="Shift";b.key="Shift";b.keyCode=16;b.which=16;b.location=0;b.repeat=!1;b.isComposing=!1}b=new Event("keydown",{bubbles:!0,cancelable:!0});b.__isDjiSyntheticEvent=!0;b.altKey=!1;b.ctrlKey=!1;b.metaKey=!1;b.shiftKey=e;b.code="KeySynthetic";b.key=g;b.keyCode=f;b.which=f;b.location=0;b.repeat=!1;b.isComposing=!1;b=new Event("keypress",{bubbles:!0,
cancelable:!0});b.__isDjiSyntheticEvent=!0;b.__char=g;b.altKey=!1;b.ctrlKey=!1;b.metaKey=!1;b.shiftKey=e;b.key=g;b.keyCode=f;b.charCode=f;b.which=f;b.location=0;b.repeat=!1;b.isComposing=!1;d.push(b);b=new Event("textInput",{bubbles:!0,cancelable:!0});b.__isDjiSyntheticEvent=!0;b.data=g;b.which=0;b.detail=0;b.repeat=!1;b.isComposing=!1;d.push(b);b=new Event("keyup",{bubbles:!0,cancelable:!0});b.__isDjiSyntheticEvent=!0;b.altKey=!1;b.ctrlKey=!1;b.metaKey=!1;b.shiftKey=e;b.code="KeySynthetic";b.key=
g;b.keyCode=f;b.which=f;b.location=0;b.repeat=!1;b.isComposing=!1;e&&(b=new Event("keyup",{bubbles:!0,cancelable:!0}),b.__isDjiSyntheticEvent=!0,b.altKey=!1,b.ctrlKey=!1,b.metaKey=!1,b.shiftKey=!1,b.code="Shift",b.key="Shift",b.keyCode=16,b.which=16,b.location=0,b.repeat=!1,b.isComposing=!1)}return d}function q(a){var d=new Event(a.type,{bubbles:!0,cancelable:!0}),c="keypress"===a.type;d.__isDjiSyntheticEvent=!0;a.hasOwnProperty("id")&&(d.__id=a.id);d.altKey=!!a.altKey;d.ctrlKey=!!a.ctrlKey;d.metaKey=
!!a.metaKey;d.shiftKey=!!a.shiftKey;d.key=a.key;d.keyCode=a.keyCode;d.code=a.key;d.charCode=c?a.keyCode:0;d.which=a.keyCode;d.location=0;d.repeat=!!a.repeat;d.isComposing=!1;return d}function v(a){for(var c=[],e=a.repeats||1,f=!a.hasOwnProperty("repeat"),g=0;g<e;g++)f&&(a.repeat=0<g),c.push(q(a));return c}function t(a){for(var c=[],e=0;e<a.length;e++)for(var f=a[e],g=f.repeats||1,h=!f.hasOwnProperty("repeat"),b=0;b<g;b++)h&&(f.repeat=0<b),c.push(q(f));return c}document.documentElement.addEventListener("com.donjohnston.cwu.dispatch",
function(a){a.preventDefault();a.stopPropagation();if(a.detail)try{"keyboardEvents"===a.detail.command?u(a.detail.params,function(){if(a.detail.callbackMessage){var c=new CustomEvent(a.detail.callbackMessage,{detail:{userData:a.detail.userData}});document.documentElement.dispatchEvent(c)}}):"text"===a.detail.command?k(a.detail.params,function(){if(a.detail.callbackMessage){var c=new CustomEvent(a.detail.callbackMessage,{detail:{userData:a.detail.userData}});document.documentElement.dispatchEvent(c)}}):
"deleteForward"===a.detail.command&&n(a.detail.params,function(){if(a.detail.callbackMessage){var c=new CustomEvent(a.detail.callbackMessage,{detail:{userData:a.detail.userData}});document.documentElement.dispatchEvent(c)}})}catch(d){}},!0)})();
