var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,f,g){d!=Array.prototype&&d!=Object.prototype&&(d[f]=g.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var f=0;return $jscomp.iteratorPrototype(function(){return f<d.length?{done:!1,value:d[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var f=d[Symbol.iterator];return f?f.call(d):$jscomp.arrayIterator(d)};
$jscomp.polyfill=function(d,f,g,l){if(f){g=$jscomp.global;d=d.split(".");for(l=0;l<d.length-1;l++){var e=d[l];e in g||(g[e]={});g=g[e]}d=d[d.length-1];l=g[d];f=f(l);f!=l&&null!=f&&$jscomp.defineProperty(g,d,{configurable:!0,writable:!0,value:f})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(d){function f(){this.batch_=null}function g(a){return a instanceof e?a:new e(function(b,d){b(a)})}if(d&&!$jscomp.FORCE_POLYFILL_PROMISE)return d;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var l=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(a){l(a,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];delete a[b];try{d()}catch(c){this.asyncThrow_(c)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=
function(){function a(c){return function(a){d||(d=!0,c.call(b,a))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var m=new f;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(c){d.reject(c)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(n){k(n)}}:b}var c,k,f=new e(function(a,
b){c=a;k=b});this.callWhenSettled_(d(a,c),d(b,k));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?m.asyncExecute(d):this.onSettledCallbacks_.push(function(){m.asyncExecute(d)})};e.resolve=g;e.reject=function(a){return new e(function(b,d){d(a)})};e.race=function(a){return new e(function(b,
d){for(var c=$jscomp.makeIterator(a),k=c.next();!k.done;k=c.next())g(k.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?g([]):new e(function(c,a){function k(a){return function(b){e[a]=b;f--;0==f&&c(e)}}var e=[],f=0;do e.push(void 0),f++,g(d.value).callWhenSettled_(k(e.length-1),a),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(d){function f(f){return d.next(f)}function g(f){return d.throw(f)}return new Promise(function(l,e){function m(a){a.done?l(a.value):Promise.resolve(a.value).then(f,g).then(m,e)}m(d.next())})};
(function(){function d(){null!==a&&a.disconnect();a=chrome.runtime.connect({name:"__dji__cowriter_port"})}function f(c,k,e){if("com.donjohnston.cowriter.chrome.notification"===c.message)b&&b.notificationAvailable(c.reason,c.details);else if("com.donjohnston.cowriter.chrome.message.engineReady"===c.message)Logger.instance.log("engineReady message received into: "+window.location),Logger.instance.log("       |-> message ="+c.message),Logger.instance.log("       |-> hostname="+window.location.hostname),
d(),null!==b&&b.restart(a);else if("com.donjohnston.cowriter.chrome.message.setup"===c.message)b&&b.setup(c.data);else if("com.donjohnston.cowriter.chrome.message.activate"===c.message)Logger.instance.log("activate message received into: "+window.location),Logger.instance.log("       |-> message ="+c.message),Logger.instance.log("       |-> hostname="+window.location.hostname),k=b?b.activate(c.state):!1,e({token:c.token,active:k});else if("com.donjohnston.cowriter.chrome.message.deactivate"===c.message)Logger.instance.log("deactivate message received into: "+
window.location),Logger.instance.log("       |-> message ="+c.message),Logger.instance.log("       |-> hostname="+window.location.hostname),k=b?b.deactivate():!1,e({token:c.token,active:k});else if("com.donjohnston.cowriter.chrome.message.topics.create"===c.message)b&&b.createTopic(c.params);else if("com.donjohnston.cowriter.chrome.message.topics.data"===c.message)b&&b.topicsDataAvailable(c.data);else if("com.donjohnston.cowriter.chrome.message.speechRecognitionNotification"===c.message){if(null!==
b)b.onSpeechRecognitionNotification(c.session,c.details)}else if("com.donjohnston.cowriter.chrome.message.speechRecognitionProgress"===c.message){if(null!==b)b.onSpeechRecognitionProgress(c.session,c.error,c.text)}else if("com.donjohnston.cowriter.chrome.message.speechRecognitionEnd"===c.message&&null!==b)b.onSpeechRecognitionEnd(c.session,c.error);return!1}function g(c){if(c.data&&c.data.hasOwnProperty("message")&&"com.donjohnston.cwu.service.available"===c.data.message&&c.data.service&&b.serviceIsSupported(c.data.service)){var a=
new MessageChannel,d=new MessageProxy("hookLoader::"+c.data.service,{wnd:c.source,port:a.port1,service:c.data.service});c.source.postMessage({message:"com.donjohnston.cwu.service.available.ack",timestamp:Date.now(),service:c.data.service,checksum:c.data.checksum},"*",[a.port2]);b.serviceAvailable(c.data.service,d)}}function l(){var c=[document];CWEChromeUtilities.findValidDocumentElements(document,c);for(var a=0;a<c.length;a++){if("true"!==(c[a].body?c[a].body.getAttribute("contenteditable"):null)){var b=
c[a].getElementById("__DJI_CWE_SHORTCUTS");null===b&&c[a].body&&(b=c[a].createElement("div"),b.id="__DJI_CWE_SHORTCUTS",b.innerHTML='<button accesskey="m" disabled>Alt+M</button><button accesskey="n" disabled>Alt+N</button>',b.style.display="block",b.style.position="fixed",b.style.top="-5000px",b.style.left="-5000px",c[a].documentElement.appendChild(b))}c[a].removeEventListener("keydown",e);c[a].removeEventListener("keyup",m);c[a].addEventListener("keydown",e);c[a].addEventListener("keyup",m)}}function e(a){77!=
a.keyCode&&109!=a.keyCode||!a.altKey||a.ctrlKey||a.shiftKey||a.metaKey?h=!1:(a.stopPropagation(),a.preventDefault(),h||(h=!0,b.toggleOnOff()))}function m(a){h&&(h=!1)}if(!CWEChromeUtilities.isLoginApp()){Logger.initialize();var a=null,b=null;window.cweMainView=new DjiCwuMainView;var h=!1;Logger.instance.log("Co:Writer injected into: "+window.location);(function(){return $jscomp.executeAsyncGenerator(function(){function c(c,k,h){for(;;)switch(e){case 0:return e=1,{value:dji.ui.templatesRegistry.cache("/ContentScripts/ui/cweMainViewTemplates.html",
"default"),done:!1};case 1:if(1!=c){e=2;break}e=-1;throw h;case 2:return e=3,{value:cweMainView.initialize(),done:!1};case 3:if(1!=c){e=4;break}e=-1;throw h;case 4:chrome.runtime.onMessage.addListener(f),DexController.initialize(function(){d();b=new CWEChromeIME(a,function(){setTimeout(function(){Logger.instance.log("CWEChromeIME is ready in: "+window.location);window.addEventListener("message",g,!0)},0)});(new MutationObserver(function(a){l()})).observe(document.body,{childList:!0});l()}),e=-1;default:return{value:void 0,
done:!0}}}var e=0,h={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())})()}})();
