var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,t,p){if(null==c)throw new TypeError("The 'this' value for String.prototype."+p+" must not be null or undefined");if(t instanceof RegExp)throw new TypeError("First argument to String.prototype."+p+" must not be a regular expression");return c+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,t,p){c!=Array.prototype&&c!=Object.prototype&&(c[t]=p.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,t,p,r){if(t){p=$jscomp.global;c=c.split(".");for(r=0;r<c.length-1;r++){var w=c[r];w in p||(p[w]={});p=p[w]}c=c[c.length-1];r=p[c];t=t(r);t!=r&&null!=t&&$jscomp.defineProperty(p,c,{configurable:!0,writable:!0,value:t})}};
$jscomp.polyfill("String.prototype.repeat",function(c){return c?c:function(c){var p=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var r="";c;)if(c&1&&(r+=p),c>>>=1)p+=p;return r}},"es6","es3");
(function(){function c(a){E();y=setTimeout(t,a||100)}function t(){p();r()}function p(){var a=w();n.send("com.donjohnston.cwu.office365.word.cursor",void 0,a)}function r(){F()&&n.send("com.donjohnston.cwu.office365.word.context",void 0,{session:z,selection:l.selection,text:l.text,extended:l.extended})}function w(){var a={left:0,top:0,right:0,bottom:0},b=document.getSelection(),f=b.focusNode,u=!1;if(0<b.rangeCount){var c=b.getRangeAt(0).getClientRects();0<c.length&&(a.left=c[0].left,a.top=c[0].top,
a.right=0,a.bottom=c[0].bottom-c[0].top,u=!0)}u||(0<b.focusOffset&&f.nodeType!==Node.TEXT_NODE?(f=f.childNodes[b.focusOffset-1].getBoundingClientRect(),a.left=f.right,a.top=f.top,a.right=0,a.bottom=f.bottom-f.top):f?(f.nodeType===Node.TEXT_NODE&&(f=f.parentElement),b=document.defaultView.getComputedStyle(f,null),f=f.getBoundingClientRect(),u=parseFloat(b.getPropertyValue("padding-left")),c=parseFloat(b.getPropertyValue("padding-top")),b=parseFloat(b.getPropertyValue("font-size")),a.left=u+f.left,
a.top=c+f.top,a.right=0,a.bottom=b+2):a.left=a.top=a.right=a.bottom=0);a.left+=window.pageXOffset;a.top+=window.pageYOffset;a.right=a.left+a.right;a.bottom=a.top+a.bottom;return a}function F(){var a=void 0;try{var b=m,f=document.getSelection();if(0>=f.rangeCount)var u={selection:{start:0,length:0},text:"",map:[]};else{var c=f.getRangeAt(0),g={selection:{start:0,length:0},text:"",map:[],params:{startContainer:c.startContainer,startOffset:c.startOffset,endContainer:c.endContainer,endOffset:c.endOffset,
selection:f,range:c,prevNode:null,stop:!1}};1===g.params.startContainer.nodeType&&0<g.params.startOffset&&(g.params.startContainer=g.params.startContainer.childNodes[g.params.startOffset-1]);1===g.params.endContainer.nodeType&&0<g.params.endOffset&&(g.params.endContainer=g.params.endContainer.childNodes[g.params.endOffset-1]);G(b,g,void 0);var h={selection:g.selection,text:CWEChromeUtilities.htmlToUnicode(g.text),map:g.map};h.selection.length-=h.selection.start;u=h}var e={selection:u.selection,text:u.text,
custom:{map:u.map,selectionOffset:0},extended:{text:u.text,selection:{start:u.selection.start,length:u.selection.length}}};if(0<e.text.length){var k=e.text.lastIndexOf("\n",e.selection.start-1),d=e.text.indexOf("\n",e.selection.start+e.selection.length),n=Math.max(0,e.selection.start-160),p=Math.min(e.text.length,e.selection.start+e.selection.length+32);for(k=Math.max(k,e.selection.start-128);k>=n&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(e.text.charAt(k));k--);k++;for(d=Math.min(e.text.length,
Math.max(d,e.selection.start+e.selection.length+10));d<p&&!CWECharacterSet.whiteSpaceCharacterSet.characterIsMember(e.text.charAt(d));d++);e.text=k<d?e.text.slice(k,d):"";e.selection.start-=k;e.custom.selectionOffset=k;k=Math.max(0,e.text.lastIndexOf("\n",k-1));d-k<e.text.length&&(e.extended.selection.start-=k,e.extended.custom.selectionOffset=k,e.extended.text=e.extended.text.slice(k,d))}a=e}catch(ba){a=H()}a.timestamp=Date.now();if(l&&l.text===a.text&&l.selection.start===a.selection.start&&l.selection.length===
a.selection.length)return!1;z++;l=a;return!0}function I(a){l&&(a?(z++,l=H(),l.timestamp=Date.now()):(E(),A=setTimeout(I,2E3,!0)))}function H(){return{selection:{start:0,length:0},text:"",extended:{text:"",selection:{start:0,length:0}}}}function E(){y&&(clearTimeout(y),y=void 0);A&&(clearTimeout(A),A=void 0)}function J(a){d.active&&d.state===q.Idle&&(v&&(clearTimeout(v),v=void 0),v=setTimeout(K,100,!0))}function L(a){d.active&&d.state===q.Idle&&(v&&(clearTimeout(v),v=void 0),v=setTimeout(K,50,!1))}
function K(a){var b=document.activeElement===m;v=void 0;a===b&&d.active&&(b?(n.send("com.donjohnston.cwu.office365.word.focus"),c(200)):(n.send("com.donjohnston.cwu.office365.word.blur"),I()))}function M(a){if(d.active){var b=a instanceof KeyboardEvent;if(d.state!==q.Idle)b&&(a.preventDefault(),a.stopPropagation());else if(!a.__isDjiSyntheticEvent&&b&&"Alt"!==a.key&&"Control"!==a.key&&"Shift"!==a.key&&"CapsLock"!==a.key&&"Meta"!==a.key){b=!1;if("KeyN"===a.code)!a.altKey||a.ctrlKey||a.shiftKey||a.metaKey||
(b=!0,n.send("com.donjohnston.cwu.office365.word.trueKeyMode",void 0));else if(!d.trueKeyMode&&N.test(a.code)){if(!(a.altKey||a.ctrlKey||a.shiftKey||a.metaKey)){b=!0;var f=a.key;f=parseInt(f);isNaN(f)||n.send("com.donjohnston.cwu.office365.word.digitKey",void 0,f)}}else O(a),p();b&&(a.preventDefault(),a.stopPropagation())}}}function P(a){if(d.active){var b=a instanceof KeyboardEvent;if(d.state!==q.Idle)b&&(a.preventDefault(),a.stopPropagation());else if(!a.__isDjiSyntheticEvent&&b){O(a);var f=String.fromCharCode(a.charCode);
b={};(f=W(f,b))&&Q(b);f&&(a.stopPropagation(),a.preventDefault())}}}function R(a){}function S(a){if(d.state===q.Idle&&d.active){var b=a instanceof KeyboardEvent;d.state!==q.Idle?b&&(a.preventDefault(),a.stopPropagation()):!a.__isDjiSyntheticEvent&&b&&"Alt"!==a.key&&"Control"!==a.key&&"Shift"!==a.key&&"CapsLock"!==a.key&&"Meta"!==a.key&&(b=!1,"KeyN"===a.code?!a.altKey||a.ctrlKey||a.shiftKey||a.metaKey||(b=!0):!d.trueKeyMode&&N.test(a.code)&&(a.altKey||a.ctrlKey||a.shiftKey||a.metaKey||(b=!0)),b?(a.preventDefault(),
a.stopPropagation()):c())}}function B(a){d.active&&(d.state===q.Idle?c(200):(a.preventDefault(),a.stopPropagation()))}function C(a){d.active&&(d.state===q.Idle?c(200):(a.preventDefault(),a.stopPropagation()))}function T(a){d.active&&(d.state===q.Idle?c(200):(a.preventDefault(),a.stopPropagation()))}function O(a){n.send("com.donjohnston.cwu.office365.word."+a.type,void 0,{type:a.type,code:a.code,key:a.key,keyCode:a.keyCode,charCode:a.charCode,which:a.which,altKey:a.altKey,ctrlKey:a.ctrlKey,shiftKey:a.shiftKey,
metaKey:a.metaKey,isComposing:a.isComposing,isTrusted:a.isTrusted,location:a.location,composed:a.composed,repeat:a.repeat,timeStamp:a.timeStamp})}function W(a,b){Logger.instance.log("handleKeyPressInput:",a);if(void 0===a||null===a||0>=a.length||!l)return!1;F();Logger.instance.log(l);var f=l.selection.start,c=l.selection.length,d=f+c,g=l.text,h=null,e;var k=a.charAt(0);for(e=f-1;0<=e;e--){var m=g.charAt(e);if(" "!==m){h=m;break}}return"\n"===k||"\r"===k||null!==h&&"."!==h&&"?"!==h&&"!"!==h&&";"!==
h&&"\n"!==h&&"\r"!==h?"."===k||"?"===k||"!"===k||";"===h||","===k?(f=e+1,b.text=k+" ",b.selection={start:f,end:f+(d-f)},!0):!1:(d=k.toUpperCase(),b.text=d+a.substring(1),b.selection={start:f,end:f+c},!0)}function Q(a){d.state===q.Idle&&(d.state=q.ReplaceText,X(a,function(b){if(!b.success)return d.state=q.Idle,c();Y(b.deleteForward,function(){setTimeout(function(){Z(a.text,function(){c();d.state=q.Idle})},10)})}))}function X(a,b){if(m!==document.activeElement||!l)return b({success:!1});var f=document.getSelection();
if("Caret"!==f.type){var c=Math.max(0,l.custom.selectionOffset+a.selection.start);return b({success:!0,deleteForward:"Range"===f.type&&0<c})}if(a.selection.start<a.selection.end)try{c=Math.max(0,l.custom.selectionOffset+a.selection.start);var d=Math.min(l.custom.selectionOffset+a.selection.end,l.custom.map.length-1);for(a=d;a>=c;a--){var g=l.custom.map[a];if(g.embeded)if(g.image||g.emoji)d=a;else if(g.eop){var h=a>c?l.custom.map[a-1].text:void 0;d=h&&160===h.charCodeAt(0)?a-1:a}}if(c<d||c!==l.extended.selection.start){var e=
Math.max(0,d-c);U(0===l.selection.length?c-l.extended.selection.start:0,e,function(a){a=document.getSelection().extentNode;for(var c=!1,f=0;!c&&a&&3>f;f++){if(a.nodeType===Node.ELEMENT_NODE&&a.classList.contains("EOP")){c=!0;break}a=a.parentElement}if(!c)return b({success:!0,deleteForward:0<e});U(0,-1,function(a){b({success:!0,deleteForward:0<e})})})}else b({success:!0,deleteForward:!1})}catch(k){return Logger.instance.error(f,k),b({success:!1})}else b({success:!0,deleteForward:!1})}function Y(a,
b){a?setTimeout(aa,10,b):b()}function Z(a,b){a&&0<a.length&&d.active&&m===document.activeElement?x("text",a,b):b()}function aa(a){x("deleteForward",{repeats:1},a)}function U(a,b,c){var f=[];0>a?f.push({type:"keydown",key:"ArrowLeft",keyCode:37,repeats:Math.abs(a)},{type:"keyup",key:"ArrowLeft",keyCode:37}):0<a&&f.push({type:"keydown",key:"ArrowRight",keyCode:39,repeats:Math.abs(a)},{type:"keyup",key:"ArrowRight",keyCode:39});0>b?f.push({type:"keydown",key:"Shift",keyCode:16,shiftKey:!0},{type:"keydown",
key:"ArrowLeft",keyCode:37,shiftKey:!0,repeats:Math.abs(b)},{type:"keyup",key:"ArrowLeft",keyCode:37},{type:"keyup",key:"Shift",keyCode:16,shiftKey:!1}):0<b&&f.push({type:"keydown",key:"Shift",keyCode:16,shiftKey:!0},{type:"keydown",key:"ArrowRight",keyCode:39,shiftKey:!0,repeats:Math.abs(b)},{type:"keyup",key:"ArrowRight",keyCode:39},{type:"keyup",key:"Shift",keyCode:16,shiftKey:!1});x("keyboardEvents",f,c)}function x(a,b,c){if(c&&"function"!==typeof c)throw Error("Callback is not a function!");
var f=x.session=(x.session||0)+1,d=c?"com.donjohnston.cwu.dispatch.session."+f:void 0,g=document.documentElement;a=new CustomEvent("com.donjohnston.cwu.dispatch",{detail:{command:a,params:b,callbackMessage:d,userData:f}});var h=void 0;c&&(h=function(a){a.preventDefault();a.stopPropagation();try{g.removeEventListener(d,h,!0)}catch(k){Logger.instance.error(k)}try{c(a.detail.params)}catch(k){Logger.instance.error(k)}},g.addEventListener(d,h,!0));try{g.dispatchEvent(a)}catch(e){Logger.instance.error(e),
c&&g.removeEventListener(d,h,!0)}}function G(a,b,c){for(var f=a.childNodes,d=0;!b.params.stop&&d<f.length;d++){var g=f[d],h=g.tagName,e=g.nodeType;if("STYLE"!==h&&"SCRIPT"!==h)if("SPAN"===h&&g.classList.contains("EOP"))b.map.push({element:g,offset:0,text:" ",embeded:!0,eop:!0});else{null!==b.params.prevNode&&(V(h)||e===Node.TEXT_NODE&&V(b.params.prevNode.tagName))&&(b.text+="\n",b.map.push({element:b.params.prevNode,offset:b.params.prevNode.childNodes.length,text:"\n",embeded:!0}),null!=b.params.startContainer&&
(b.selection.start+=1),null!=b.params.endContainer&&(b.selection.length+=1));if(b.params.startContainer&&b.params.startContainer===g||b.params.endContainer&&b.params.endContainer===g){h=e===Node.TEXT_NODE?g.textContent:" ";var k=e===Node.TEXT_NODE?b.params.startOffset:1,l=e===Node.TEXT_NODE?b.params.endOffset:1;if(e===Node.TEXT_NODE)for(e=0;e<h.length;e++){var m=32767<h.charCodeAt(e),n={element:g,offset:e,text:h.charAt(e),embeded:m};m&&(n.emoji=!0);b.map.push(n)}else b.map.push({element:a,offset:d+
1,text:" ",embeded:!0});b.text+=h;b.params.startContainer===g&&(b.selection.start+=k,b.params.startContainer=null);b.params.endContainer===g?(b.selection.length+=l,b.params.endContainer=null):b.params.endContainer&&(b.selection.length+=h.length)}else if(e===Node.TEXT_NODE){h=g.textContent;b.text+=h;for(k=0;k<h.length;k++)l=32767<h.charCodeAt(k),e={element:g,offset:k,text:h.charAt(k),embeded:l},l&&(e.emoji=!0),b.map.push(e);null!=b.params.startContainer&&(b.selection.start+=h.length);null!=b.params.endContainer&&
(b.selection.length+=h.length)}else e===Node.ELEMENT_NODE&&("IMG"===h?(b.text+=" ",b.map.push({element:a,offset:d+1,text:" ",embeded:!0,image:!0}),null!=b.params.startContainer&&(b.selection.start+=1),null!=b.params.endContainer&&(b.selection.length+=1)):G(g,b,null===c?null:"  "+c));b.params.prevNode=g}}}function V(a){return"P"===a||"DIV"===a||"LI"===a||"TD"===a}Logger.instance.warn("CWE Office365 Word Proxy loaded into: "+window.location);var q={None:0,Idle:1,Busy:2,ReplaceText:3},n=void 0,d={active:!1,
trueKeyMode:!1,state:q.None},D=document.querySelector("#application #WACViewPanel"),m=document.querySelector("#WACViewPanel_EditingElement_WrappingDiv #WACViewPanel_EditingElement[contenteditable]"),v=void 0,y=void 0,A=void 0,N=/^(Digit|Numpad)([\d]{1})$/,l=void 0,z=0;CWEChromeUtilities.registerService("ms-office-word-editor",!0,function(a){if(a.success){var b=document.getElementById("dji-office365-word-dispatcher");b||(b=document.createElement("script"),b.setAttribute("id","dji-office365-word-dispatcher"),
b.async=!0,b.src=chrome.extension.getURL("ContentScripts/cweEventDispatcher.js"),document.documentElement.insertBefore(b,document.documentElement.firstElementChild));n=a.messageProxy;n.on("com.donjohnston.cwu.office365.word.activate",function(a,b){d.active=b;d.active?(m.addEventListener("focus",J,!0),m.addEventListener("blur",L,!0),m.addEventListener("keydown",M,!0),m.addEventListener("keypress",P,!0),m.addEventListener("textInput",R,!0),m.addEventListener("keyup",S,!0),m.addEventListener("mousedown",
B,!0),m.addEventListener("mouseup",C,!0),m.addEventListener("paste",T,!0),D.addEventListener("mousedown",B,!0),D.addEventListener("mouseup",C,!0)):(m.removeEventListener("focus",J,!0),m.removeEventListener("blur",L,!0),m.removeEventListener("keydown",M,!0),m.removeEventListener("keypress",P,!0),m.removeEventListener("textInput",R,!0),m.removeEventListener("keyup",S,!0),m.removeEventListener("mousedown",B,!0),m.removeEventListener("mouseup",C,!0),m.removeEventListener("paste",T,!0),D.removeEventListener("mousedown",
B,!0),D.removeEventListener("mouseup",C,!0));d.active?(a=w(),n.send("com.donjohnston.cwu.office365.word.cursor",void 0,a),n.send("com.donjohnston.cwu.office365.word.ready"),r(),m===document.activeElement&&n.send("com.donjohnston.cwu.office365.word.focus")):n.send("com.donjohnston.cwu.office365.word.blur")});n.on("com.donjohnston.cwu.office365.word.trueKeyMode",function(a,b){d.trueKeyMode=b});n.on("com.donjohnston.cwu.office365.word.text",function(a,b){if("selection"===b)b=m===document.activeElement?
document.getSelection().toString():null;else{b="";for(var c=document.querySelectorAll("#application .WACDocumentPanel #WACDocumentPanelContent #WACViewPanelContainer #WACViewPanel #PageContentContainer .OutlineContent .OutlineGroup .ParaWrappingDiv"),d=0;d<c.length;d++){for(var f=c[d].querySelectorAll(".TextRun:not(.EmptyTextRun)"),e=0;e<f.length;e++)b+=f[e].textContent;b+="\n"}}n.respond("com.donjohnston.cwu.office365.word.text",a,b)});n.on("com.donjohnston.cwu.office365.word.cursor",p);n.on("com.donjohnston.cwu.office365.word.context",
function(){r()});n.on("com.donjohnston.cwu.office365.word.replaceText",function(a,b){b.session===z&&l&&Q(b)});n.enable(!0);n.ping();d.state=q.Idle}})})();
