var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,g){a!=Array.prototype&&a!=Object.prototype&&(a[d]=g.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,d,g,k){if(d){g=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var e=a[k];e in g||(g[e]={});g=g[e]}a=a[a.length-1];k=g[a];d=d(k);d!=k&&null!=d&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:d})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function g(b){return b instanceof e?b:new e(function(h,c){h(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};d.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var k=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){k(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var h=0;h<b.length;++h){var c=b[h];delete b[h];try{c()}catch(u){this.asyncThrow_(u)}}}this.batch_=null};d.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var e=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var h=this.createResolveAndReject_();try{b(h.resolve,h.reject)}catch(c){h.reject(c)}};e.prototype.createResolveAndReject_=
function(){function b(b){return function(a){c||(c=!0,b.call(h,a))}}var h=this,c=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};e.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};e.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(c){this.reject_(c);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};e.prototype.reject_=function(b){this.settle_(2,b)};e.prototype.fulfill_=function(b){this.settle_(1,b)};e.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var r=new d;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,h){var c=this.createResolveAndReject_();try{a.call(h,c.resolve,c.reject)}catch(u){c.reject(u)}};e.prototype.then=function(a,h){function c(a,c){return"function"==typeof a?function(c){try{b(a(c))}catch(B){l(B)}}:c}var b,l,d=new e(function(a,
c){b=a;l=c});this.callWhenSettled_(c(a,b),c(h,l));return d};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,d){function c(){switch(b.state_){case 1:a(b.result_);break;case 2:d(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?r.asyncExecute(c):this.onSettledCallbacks_.push(function(){r.asyncExecute(c)})};e.resolve=g;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
c){for(var d=$jscomp.makeIterator(a),l=d.next();!l.done;l=d.next())g(l.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?g([]):new e(function(a,d){function e(c){return function(b){l[c]=b;f--;0==f&&a(l)}}var l=[],f=0;do l.push(void 0),f++,g(c.value).callWhenSettled_(e(l.length-1),d),c=b.next();while(!c.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function d(d){return a.next(d)}function g(d){return a.throw(d)}return new Promise(function(k,e){function r(a){a.done?k(a.value):Promise.resolve(a.value).then(d,g).then(r,e)}r(a.next())})};$jscomp.arrayFromIterator=function(a){for(var d,g=[];!(d=a.next()).done;)g.push(d.value);return g};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.checkStringArgs=function(a,d,g){if(null==a)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,g){var d=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===g&&(g=d.length);g=Math.max(0,Math.min(g|0,d.length));for(var e=a.length;0<e&&0<g;)if(d[--g]!=a[--e])return!1;return 0>=e}},"es6","es3");window.dji=window.dji||{};
window.dji.topicHelper=function(){function a(a,d,l,e){return $jscomp.executeAsyncGenerator(function(){function c(c,A,p){for(;;)switch(f){case 0:if(b.activateTopicDelegate&&b.updateTopicDelegate){f=1;break}f=-1;return{value:e(r("missing_delegate")),done:!0};case 1:w={name:a.name,activate:!!a.activate};if(!a.activate){f=2;break}if(6>h.activeTopics.length||k(w.name)){f=3;break}f=-1;return{value:e(r("too_many_active_topics")),done:!0};case 3:case 2:if(d)try{d(w)}catch(t){Logger.instance.error(t)}x=!1;
q=void 0;try{return f=6,{value:b.activateTopicDelegate(w),done:!1}}catch(t){n=t;f=4;break}case 6:try{if(1!=c){f=7;break}f=-1;throw p;}catch(t){n=t;f=4;break}case 7:try{(v=F=A)&&"ok"===v.status&&(x=!0,q=v.active,g(v.name,v.active));f=5;break}catch(t){n=t;f=4;break}case 4:u=n,Logger.instance.error(u);case 5:l({success:x,active:q}),f=-1;default:return{value:void 0,done:!0}}}var f=0,u,v,F,n,q,x,w,p={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();p[Symbol.iterator]=function(){return this};return p}())}function d(a,d,l,v){return $jscomp.executeAsyncGenerator(function(){function c(c,A,H){for(;;)switch(f){case 0:if(b.activateTopicDelegate&&b.updateTopicDelegate){f=1;break}f=-1;return{value:v(r("missing_delegate")),done:!0};case 1:y=a.name;I=a.url;J=a.data;z=a.local;K=a.extras;var G=y;G=e(G);E=(t=-1!==h.topics.indexOf(G))&&k(y);D=!!(6>h.activeTopics.length||k(y));C=!(!z||E);if(!z||!E){f=2;break}f=-1;return{value:l({success:!0,
activate:!0}),done:!0};case 2:if(!z||D){f=3;break}f=-1;return{value:v(r("too_many_active_topics")),done:!0};case 3:p={name:y,url:I,data:J,local:z,userData:{action:null,activate:D,extras:K}};C?(p.activate=!0,p.provideTopicsData=!0,p.userData.action="activate"):p.userData.action=t?"update":"create";if(d)try{d(p)}catch(m){Logger.instance.error(m)}w=!1;x=void 0;try{n=void 0;if(!C){f=6;break}f=8;return{value:b.activateTopicDelegate(p),done:!1}}catch(m){q=m;f=4;break}case 8:try{if(1!=c){f=9;break}f=-1;
throw H;}catch(m){q=m;f=4;break}case 9:try{n=F=A;f=7;break}catch(m){q=m;f=4;break}case 6:try{return f=10,{value:b.updateTopicDelegate(p),done:!1}}catch(m){q=m;f=4;break}case 10:try{if(1!=c){f=11;break}f=-1;throw H;}catch(m){q=m;f=4;break}case 11:try{n=B=A}catch(m){q=m;f=4;break}case 7:try{n&&"ok"===n.status&&(w=!0,x=n.active,g(n.name,n.active));f=5;break}catch(m){q=m;f=4;break}case 4:u=q,Logger.instance.error(u);case 5:l({success:w,active:x}),f=-1;default:return{value:void 0,done:!0}}}var f=0,u,B,
F,n,q,x,w,p,C,D,E,t,K,z,J,I,y,L={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();L[Symbol.iterator]=function(){return this};return L}())}function g(a,b){a:{var c=h.displayTopics;for(var d=0;d<c.length;d++)if(c[d].name===a){c=c[d];break a}c=null}d=h.activeTopics.indexOf(a);(b=!!b)&&-1===d?h.activeTopics.push(a):b||-1===d||h.activeTopics.splice(d,1);c&&(c.active=b)}function k(a){a=e(a);
return-1!==h.activeTopics.indexOf(a)}function e(a){if(null===a||void 0===a)return null;a=a.replace("_"," ");a.endsWith(" TD")&&(a=a.slice(0,a.length-3));for(var b="",c=0;c<a.length;c++){var d=a.charAt(c),e=d.toLowerCase(),f=d.toUpperCase();b+=a.charAt(c);if(c<a.length-1){var g=a.charAt(c+1),h=g.toLowerCase(),k=g.toUpperCase();e!==f&&h!==k&&d===e&&g===k&&(b+=" ")}}return b}function r(a,b){b=Error(b);b.code=a;return b}var b={activateTopicDelegate:void 0,updateTopicDelegate:void 0},h={topics:[],topicsUpperCase:[],
activeTopics:[],displayTopics:[]};return{setActivateTopicDelegate:function(a){a instanceof Function&&(b.activateTopicDelegate=a)},setUpdateTopicDelegate:function(a){a instanceof Function&&(b.updateTopicDelegate=a)},setTopics:function(a,b,d){h.topics=a?[].concat($jscomp.arrayFromIterable(a)):[];h.topicsUpperCase=h.topics.map(function(a){return a.toUpperCase()});h.displayTopics=d?[].concat($jscomp.arrayFromIterable(d)):[];h.activeTopics=b?[].concat($jscomp.arrayFromIterable(b)):h.displayTopics.reduce(function(a,
b){a.push(b.name)},[])},activateTopicAsync:function(b,d){return $jscomp.executeAsyncGenerator(function(){function c(c,g,h){for(;;)switch(e){case 0:return e=-1,{value:new Promise(function(c,f){a(b,d,c,f)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())},updateTopicAsync:function(a,
b){return $jscomp.executeAsyncGenerator(function(){function c(c,g,h){for(;;)switch(e){case 0:return e=-1,{value:new Promise(function(c,f){d(a,b,c,f)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())}}}();
