var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(q){g(q)}}:b}var d,g,f=new e(function(a,
b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");
var DjiCwuMainView=function(){this.m_demoMode=!1;this.m_templates={suggestion:null,suggestionTranslationPlaceholder:null,topic:null,lookupTopic:null};this.m_ui={mainView:null,tabView:null,tabViewPages:null,tabViewToolbarButtons:null};this.m_eventHandlers={};this.m_data={locale:"",suggestions:[],translations:[],topics:[],topicsUpperCase:[],displayTopics:[],translation:{target:null,source:null}};this.m_messages={translateWriting:{US:"Translate writing from ${source} into ${target}.",UK:"Translate writing from ${source} into ${target}.",
BE:"Translate writing from ${source} into ${target}.",CAN:"Translate writing from ${source} into ${target}.",FR:"Traduire l'\u00e9criture de $ {source} en $ {target}.",GER:"Ubersetze Schreiben von ${source} in ${target}.",SPA:"Traduzca la escritura desde ${source} a ${target}."},translateSpeech:{US:"Speak ${source}, write ${target}",UK:"Speak ${source}, write ${target}",BE:"Speak ${source}, write ${target}",CAN:"Speak ${source}, write ${target}",FR:"Parlez ${source}, \u00e9crivez ${target}",GER:"Sprechen Sie ${source}, schreiben Sie ${target}",
SPA:"Habla ${source}, escribe ${target}"}};this.m_delegates={viewDidChangeDelegate:void 0,trueKeyModeDidChangeDelegate:void 0,suggestionClickDelegate:void 0,keyboardClickDelegate:void 0,speechRecognitionDelegate:void 0,speakDelegate:void 0,updateTopicDelegate:void 0,activateTopicDelegate:void 0};this.m_timers={speak:new DjiTimer(this,this.__onSpeakText),speechRecognition:new DjiTimer(this,this.__onStopPulseSpeechRecognition),searchTopics:new DjiTimer(this,this.__onSearchTopics)};this.m_wikiReader=
window.CWEWikiReader instanceof Function?new CWEWikiReader:null;this.__createEventHandlers()};DjiCwuMainView.prototype.hasFocus=function(){return!!(this.m_ui.mainView&&this.m_ui.mainView.hasFocusWithin()||"topics"===this.mode)};
DjiCwuMainView.prototype.initialize=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,f,h){for(;;)switch(e){case 0:if(!c.m_ui.mainView){e=1;break}e=-1;throw Error("Already initialize!");case 1:c.m_ui.mainView=document.querySelector("dji-cwu-main-view");if(!c.m_ui.mainView)try{var g=dji.ui.templatesRegistry.load(null,"dji-cwu-main-view").content;c.m_ui.mainView=g.querySelector("dji-cwu-main-view")}catch(u){Logger.instance.error("Template for main view couldn't be loaded!")}try{var k=
dji.ui.templatesRegistry.load(null,"dji-cwu-suggestion").content;c.m_templates.suggestion=k.querySelector("dji-cwu-suggestion")}catch(u){Logger.instance.error("Template for suggestion couldn't be loaded!")}try{var m=dji.ui.templatesRegistry.load(null,"dji-cwu-suggestion-translation-placeholder").content;c.m_templates.suggestionTranslationPlaceholder=m.querySelector("dji-cwu-suggestion")}catch(u){Logger.instance.error("Template for suggestion couldn't be loaded!")}try{var n=dji.ui.templatesRegistry.load(null,
"dji-cwu-topic").content;c.m_templates.topic=n.querySelector("dji-cwu-topic")}catch(u){Logger.instance.error("Template for topic couldn't be loaded!")}try{var t=dji.ui.templatesRegistry.load(null,"dji-cwu-topic-lookup").content;c.m_templates.lookupTopic=t.querySelector("dji-cwu-topic")}catch(u){Logger.instance.error("Template for lookup topic couldn't be loaded!")}c.m_ui.mainView&&(a=a||document.documentElement,c.m_demoMode=!!b,c.m_ui.mainView.setAttribute("id",c.m_ui.mainView.tagName+"-"+Date.now()),
c.m_ui.mainView.setAttribute("dji-cwu-hidden",""),c.m_demoMode&&c.m_ui.mainView.setAttribute("dji-cwu-demo",""),a.appendChild(c.m_ui.mainView),c.__detectElements(),c.__addEventListeners(),c.reset(),c.m_ui.mainView.addEventListener("mousedown",DjiCwuMainView.__onBlockDefaultBehaviour,!0));e=-1;default:return{value:void 0,done:!0}}}var e=0,f={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
f[Symbol.iterator]=function(){return this};return f}())};DjiCwuMainView.prototype.show=function(a){this.m_ui.mainView&&(this.__notifyStopSpeechRecognition(),a?this.m_ui.mainView.removeAttribute("dji-cwu-hidden"):this.m_ui.mainView.setAttribute("dji-cwu-hidden",""),window.dji&&window.dji.accessibility&&window.dji.accessibility.enable(a))};
DjiCwuMainView.prototype.setOptions=function(a){this.__notifyStopSpeechRecognition();this.m_data.locale=a.locale||"";var b=this.__prepareTranslationLanguages(a.translation);this.__updateSpeechRecognitionView();this.suggestionsCount=a.suggestions;this.translationsEnabled=b;this.windowOptions=a.window};DjiCwuMainView.prototype.setWikiReaderOptions=function(a){this.m_wikiReader&&this.m_wikiReader.setOptions(a)};
DjiCwuMainView.prototype.suggestionFromNumber=function(a){if(isNaN(a)||!this.m_ui.mainView||this.m_ui.mainView.isHidden()||!this.m_ui.tabViewPageType.isActive()||!this.m_ui.typePagePaneType.isActive())return null;var b=this.m_data.suggestions.length,c=b+this.m_data.translations.length;a--;if(0<=a&&a<b)return this.m_data.suggestions[a];-1===a&&10===c&&(a=b);return b<=a&&a<c?this.m_data.translations[a-b]:null};
DjiCwuMainView.prototype.toggleTrueKeyMode=function(){var a=this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="type"][dji-cwu-active]');return a&&this.m_ui.typePagePaneType.isActive()?(this.__onTypePageToolbarButtonClick(this.m_ui.typePageToolbarButton123),!0):a&&this.m_ui.typePagePane123Keyboard.isActive()?(this.__onTypePageToolbarButtonClick(this.m_ui.typePageToolbarButtonABC),!0):!1};
DjiCwuMainView.prototype.reset=function(){this.resetTypePage();this.resetSpeechRecognitionPage();this.resetTopicsPage();this.__resetAccessibilityManager();this.__onTabViewToolbarButtonClick(this.m_ui.tabView.querySelector('dji-cwu-tab-view-toolbar-button[dji-cwu-link-to="type"]'),!0)};
DjiCwuMainView.prototype.resetTypePage=function(){this.m_ui.typePagePaneTranslations.removeAllChildren("dji-cwu-suggestion");this.m_ui.typePagePaneSuggestions.removeAllChildren();this.m_ui.typePagePaneTranslations.setAttribute("dji-cwu-hidden","");this.m_ui.typePagePaneSuggestions.setAttribute("dji-cwu-hidden","");this.suggestionsCount=5;this.translationsEnabled=!1};
DjiCwuMainView.prototype.resetSpeechRecognitionPage=function(){this.m_ui.speakPageMicrophone.__isActive&&(this.m_ui.tabViewPageSpeak.removeAttribute("dji-cwu-error"),this.m_ui.speakPageMicrophone.setAttribute("dji-cwu-state","idle"),this.m_ui.speakPageInfo.innerText="Click for speech to text",this.m_ui.speakPageMicrophone.__isActive=!1);this.__updateSpeechRecognitionView()};
DjiCwuMainView.prototype.resetTopicsPage=function(){this.m_ui.topicsSearchBox.__speechRecognitionActive&&(this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-speech-recognition"),this.m_ui.topicsSearchBarInput.value="",this.m_ui.topicsSearchBarInput.enableInputEvents(),delete this.m_ui.topicsSearchBarInput.__search,this.m_ui.topicsSearchResultsLocal.removeAllChildren(),this.m_ui.topicsSearchResultsWeb.removeAllChildren(),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-input"),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-no-results"),
this.m_ui.topicsSearchInfoPattern.innerText="",this.m_ui.topicsSearchBox.__speechRecognitionActive=!1)};
DjiCwuMainView.prototype.resetToCreateTopic=function(a){var b=Date.now()+"-"+parseInt(1E3*Math.random()),c=this.mode;this.__onTabViewToolbarButtonClick(this.m_ui.tabView.querySelector('dji-cwu-tab-view-toolbar-button[dji-cwu-link-to="topics"]'),!0);this.m_ui.mainView.__updateTopic=!0;this.m_ui.topicsSearchBox.activate(!0);this.m_ui.topicsSearchBarInput.enableInputEvents(!1);this.m_ui.topicsSearchBarInput.__search={session:b,pattern:a.details.name,extras:!0};this.m_ui.topicsSearchBarInput.value=a.details.name;
this.m_ui.topicsSearchBox.setAttribute("dji-cwu-input","");a.userData&&"activate"===a.userData.action?this.m_ui.mainView.setAttribute("dji-cwu-update-topics","activate"):a.userData&&"create"===a.userData.action?(a.userData.activate||this.m_ui.mainView.setAttribute("dji-cwu-update-topics-hint","hint-too-many-active"),this.m_ui.mainView.setAttribute("dji-cwu-update-topics","create")):(a.userData.activate||this.m_ui.mainView.setAttribute("dji-cwu-update-topics-hint","hint-too-many-active"),this.m_ui.mainView.setAttribute("dji-cwu-update-topics",
"update"));this.m_ui.topicsUpdateInfoName.innerText=a.details.name;this.m_ui.topicsSearchResults.scrollTop=0;return c};
DjiCwuMainView.prototype.cancelResetToCreateTopic=function(a){this.m_ui.mainView.__updateTopic&&this.m_ui.topicsSearchBarInput.__search&&this.m_ui.topicsSearchBarInput.__search.extras&&(this.m_ui.mainView.removeAttribute("dji-cwu-update-topics"),this.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint"),this.m_ui.topicsUpdateInfoName.innerText="",this.m_ui.topicsSearchBarInput.enableInputEvents(),this.m_ui.mainView.__updateTopic=!1,this.__onTopicsSearchBack(),a&&a!==this.mode&&(a=this.m_ui.tabView.querySelector('dji-cwu-tab-view-toolbar-button[dji-cwu-link-to="'+
a+'"]'))&&this.__onTabViewToolbarButtonClick(a,!0))};
DjiCwuMainView.prototype.setSuggestions=function(a,b,c){if(a=this.__buildSuggestions(0,a,b,!1))this.m_data.suggestions=a.skipCache?[]:a.entries,c&&(this.m_ui.typePagePaneTranslations.setAttribute("dji-cwu-hidden",""),this.m_ui.typePagePaneTranslations.removeAllChildren("dji-cwu-suggestion")),this.m_ui.typePagePaneSuggestions.removeAllChildren(),this.m_ui.typePagePaneSuggestions.appendChild(a.fragment),0<this.m_data.suggestions.length?this.m_ui.typePagePaneSuggestions.removeAttribute("dji-cwu-hidden"):this.m_ui.typePagePaneSuggestions.setAttribute("dji-cwu-hidden",
""),c&&this.m_data.translation.source&&this.setTranslations(),this.__updateSuggestionsNumbering(),this.__updateAccessibilityManagerInTypePage(!c)};
DjiCwuMainView.prototype.setTranslations=function(a,b,c){if(a=this.__buildSuggestions(this.m_data.suggestions.length,a,b,!0))this.m_data.translations=a.skipCache?[]:a.entries,this.m_ui.typePagePaneTranslations.removeAllChildren("dji-cwu-suggestion"),c&&(this.m_ui.typePagePaneSuggestions.setAttribute("dji-cwu-hidden",""),this.m_ui.typePagePaneSuggestions.removeAllChildren()),this.m_ui.typePagePaneTranslations.appendChild(a.fragment),this.m_ui.typePagePaneTranslations.removeAttribute("dji-cwu-hidden"),
this.__updateAccessibilityManagerInTypePage(!c)};DjiCwuMainView.prototype.__updateSuggestionsNumbering=function(){9<=this.m_ui.typePagePaneSuggestions.querySelectorAll("dji-cwu-suggestion").length?this.m_ui.typePagePaneTranslations.setAttribute("dji-cwu-restart-numbering",""):this.m_ui.typePagePaneTranslations.removeAttribute("dji-cwu-restart-numbering")};
DjiCwuMainView.prototype.__updateSpeechRecognitionView=function(){if(this.m_data.translation.target){var a=this.m_data.translation.target,b=this.m_ui.speakPageToolbarButtons[0];b.__data={langCode:a.langCode||"",langShortName:a.langShortName||"",langFullName:a.langFullName||""};b.innerText=b.__data.langShortName;b.setAttribute("title",b.__data.langFullName)}if(this.m_data.translation.target&&this.m_data.translation.source){a=this.m_data.translation.source;b=this.m_ui.speakPageToolbarButtons[1];var c=
b.querySelector('[dji-cwu-role="source"]'),d=b.querySelector('[dji-cwu-role="target"]');c.innerText=this.m_data.translation.source.langShortName;d.innerText=this.m_data.translation.target.langShortName;b.__data={langCode:a.langCode||"",langShortName:a.langShortName||"",langFullName:a.langFullName||""};b.setAttribute("title",(this.m_messages.translateSpeech[this.m_data.locale]||"").replace("${source}",this.m_data.translation.source.langFullName).replace("${target}",this.m_data.translation.target.langFullName))}a=
this.m_ui.speakPageToolbarButtons[0];this.m_ui.speakPageToolbarButtons.removeAttribute("dji-cwu-active");this.m_data.translation.target&&this.m_data.translation.source?(this.m_ui.speakPagePaneSpeak.setAttribute("dji-cwu-options","multiple-languages"),a.setAttribute("dji-cwu-active","")):this.m_ui.speakPagePaneSpeak.removeAttribute("dji-cwu-options");this.m_ui.speakPageMicrophone.__data=a.__data};
DjiCwuMainView.prototype.pulseSpeechRecognition=function(a,b){"dictation"===b&&this.m_ui.speakPageMicrophone.__isActive&&(!0===a?(this.m_ui.speakPageMicrophone.setAttribute("dji-cwu-state","pulse"),this.m_ui.speakPageInfo.innerText="Listening..."):!1===a&&(this.m_ui.speakPageMicrophone.setAttribute("dji-cwu-state","active"),this.m_ui.speakPageInfo.innerText="Speak now..."))};
DjiCwuMainView.prototype.stopSpeechRecognition=function(a){"dictation"===a&&this.m_ui.speakPageMicrophone.__isActive?(this.m_ui.speakPageMicrophone.setAttribute("dji-cwu-state","idle"),this.m_ui.speakPageInfo.innerText="Click for speech to text",this.m_ui.speakPageMicrophone.__isActive=!1):"search_topics"===a&&this.m_ui.topicsSearchBox.__speechRecognitionActive&&this.__onTopicsSearchStopSpeechRecognition(!1,!0)};
DjiCwuMainView.prototype.showSpeechRecognitionError=function(a,b){"dictation"===b&&this.m_ui.speakPageMicrophone.__isActive?this.m_ui.tabViewPageSpeak&&(a?this.m_ui.tabViewPageSpeak.setAttribute("dji-cwu-error",""):this.m_ui.tabViewPageSpeak.removeAttribute("dji-cwu-error")):"search_topics"===b&&this.m_ui.topicsSearchBox.__speechRecognitionActive&&this.__onTopicsSearchStopSpeechRecognition(!1,!0)};DjiCwuMainView.prototype.__onStopPulseSpeechRecognition=function(a){this.pulseSpeechRecognition(!1,a)};
DjiCwuMainView.prototype.__buildSuggestions=function(a,b,c,d){if(this.m_templates.suggestion){if(a=!(!d||b&&!(0>=b.length)))b=[this.m_data.translation.source.langShortName+" > "+this.m_data.translation.target.langShortName],c=[(this.m_messages.translateWriting[this.m_data.locale]||"").replace("${source}",this.m_data.translation.source.langFullName).replace("${target}",this.m_data.translation.target.langFullName)];b=b||[];c=c||b;b.length!==c.length&&(c=b);d=document.createDocumentFragment();for(var e=
[],f=0;f<b.length;f++){var g=a?this.m_templates.suggestionTranslationPlaceholder.cloneNode(!0):this.m_templates.suggestion.cloneNode(!0);if(a){var k=g.querySelector('[dji-cwu-role="source"]'),h=g.querySelector('[dji-cwu-role="target"]');k.innerText=this.m_data.translation.source.langShortName;h.innerText=this.m_data.translation.target.langShortName}else g.innerText=b[f];g.__data={item:b[f],audio:c[f]};this.m_demoMode||(a||(g.addEventListener("click",this.m_eventHandlers.__onTypePageSuggestionClick),
g.addEventListener("x-enter",this.m_eventHandlers.__onTypePageSuggestionClick)),g.addEventListener("mouseover",this.m_eventHandlers.__onTypePageSuggestionMouseOver),g.addEventListener("x-focus",this.m_eventHandlers.__onTypePageSuggestionMouseOver),g.addEventListener("mouseout",this.m_eventHandlers.__onGenericMouseOut),g.addEventListener("x-blur",this.m_eventHandlers.__onGenericMouseOut));d.appendChild(g);e.push(g.__data)}return{fragment:d,entries:e,skipCache:a}}};
DjiCwuMainView.prototype.__clearGuesses=function(){this.m_ui.typePagePaneSuggestions.removeAllChildren();this.__updateSuggestionsNumbering()};DjiCwuMainView.prototype.__clearTranslations=function(){this.m_ui.typePagePaneTranslations.removeAllChildren("dji-cwu-suggestion");this.m_ui.typePagePaneTranslations.setAttribute("dji-cwu-hidden","")};
DjiCwuMainView.prototype.__buildTopics=function(a){if(this.m_templates.lookupTopic){a=a||[];for(var b=document.createDocumentFragment(),c=0;c<a.length;c++){var d=this.m_templates.topic.cloneNode(!0),e=d.querySelector("dji-cwu-label"),f=d.querySelector("dji-cwu-switch");e.innerText=a[c].name;f.turnOn(a[c].active);d.__data=e.__data=f.__data={item:a[c].name,active:a[c].active,topic:a[c]};this.m_demoMode||(f.addEventListener("click",this.m_eventHandlers.__onTopicsItemOnOff),e.addEventListener("mouseover",
this.m_eventHandlers.__onGenericMouseOver),e.addEventListener("mouseout",this.m_eventHandlers.__onGenericMouseOut),d.addEventListener("x-enter",this.m_eventHandlers.__onTopicsItemOnOff),d.addEventListener("x-focus",this.m_eventHandlers.__onGenericMouseOver),d.addEventListener("x-blur",this.m_eventHandlers.__onGenericMouseOut));b.appendChild(d)}return b}};
DjiCwuMainView.prototype.__buildTopicSearchResults=function(a,b){if(this.m_templates.lookupTopic){b=b||[];for(var c=document.createDocumentFragment(),d=[],e=0;e<b.length;e++){var f=this.m_templates.lookupTopic.cloneNode(!0);f.innerText=b[e].name;f.__data={item:b[e].name,url:b[e].url,local:a};this.m_demoMode||(f.addEventListener("click",this.m_eventHandlers.__onTopicsSearchItemClick),f.addEventListener("x-enter",this.m_eventHandlers.__onTopicsSearchItemClick),f.addEventListener("mouseover",this.m_eventHandlers.__onGenericMouseOver),
f.addEventListener("mouseout",this.m_eventHandlers.__onGenericMouseOut));c.appendChild(f);d.push(f.__data)}return{fragment:c,entries:d}}};
DjiCwuMainView.prototype.__prepareTranslationLanguages=function(a){this.m_data.translation.target=null;this.m_data.translation.source=null;a&&a.target&&a.target.langCode&&0<a.target.langCode.length&&(this.m_data.translation.target=a.target);a&&a.source&&a.source.langCode&&0<a.source.langCode.length&&(this.m_data.translation.source=a.source);return!(!this.m_data.translation.target||!this.m_data.translation.source)};
DjiCwuMainView.prototype.__detectElements=function(){this.m_ui.tabView=this.m_ui.mainView.querySelector("dji-cwu-tab-view");this.m_ui.tabViewToolbarButtons=this.m_ui.tabView.querySelectorAll("dji-cwu-tab-view-toolbar-button");this.m_ui.tabViewPages=this.m_ui.tabView.querySelectorAll("dji-cwu-tab-view-page");this.m_ui.tabViewPageType=this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="type"]');this.m_ui.tabViewPageTopics=this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="topics"]');
this.m_ui.tabViewPageSpeak=this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="speech-recognition"]');this.m_ui.typePageToolbarButtons=this.m_ui.tabViewPageType.querySelectorAll("dji-cwu-toolbar-button");this.m_ui.typePageToolbarButtonABC=this.m_ui.tabViewPageType.querySelector('dji-cwu-toolbar-button[dji-cwu-link-to="suggestions"]');this.m_ui.typePageToolbarButton123=this.m_ui.tabViewPageType.querySelector('dji-cwu-toolbar-button[dji-cwu-link-to="keyboard"]');this.m_ui.typePagePanes=
this.m_ui.tabViewPageType.querySelectorAll("dji-cwu-suggestions-pane, dji-cwu-keyboard-pane");this.m_ui.typePagePaneType=this.m_ui.tabViewPageType.querySelector("dji-cwu-suggestions-pane");this.m_ui.typePagePane123Keyboard=this.m_ui.tabViewPageType.querySelector("dji-cwu-keyboard-pane");this.m_ui.typePagePaneSuggestions=this.m_ui.typePagePaneType.querySelector("dji-cwu-guesses-pane");this.m_ui.typePagePaneTranslations=this.m_ui.typePagePaneType.querySelector("dji-cwu-translations-pane");this.m_ui.typePagePane123Keys=
this.m_ui.typePagePane123Keyboard.querySelectorAll("dji-cwu-keyboard-key");this.m_ui.speakPageToolbar=this.m_ui.tabViewPageSpeak.querySelector("dji-cwu-toolbar");this.m_ui.speakPageToolbarButtons=this.m_ui.speakPageToolbar.querySelectorAll("dji-cwu-toolbar-button");this.m_ui.speakPagePanes=this.m_ui.tabViewPageSpeak.querySelectorAll("dji-cwu-error-pane, dji-cwu-speech-recognition-pane");this.m_ui.speakPagePaneSpeak=this.m_ui.tabViewPageSpeak.querySelector("dji-cwu-speech-recognition-pane");this.m_ui.speakPagePaneError=
this.m_ui.tabViewPageSpeak.querySelector("dji-cwu-error-pane");this.m_ui.speakPageInfo=this.m_ui.speakPagePaneSpeak.querySelector("dji-cwu-info");this.m_ui.speakPageMicrophone=this.m_ui.speakPagePaneSpeak.querySelector('dji-cwu-icon[dji-cwu-role="microphone"]');this.m_ui.topicsSearchBox=this.m_ui.tabViewPageTopics.querySelector("dji-cwu-search-box");this.m_ui.topicsMainPane=this.m_ui.tabViewPageTopics.querySelector("dji-cwu-topics-pane");this.m_ui.topicsSearchBar=this.m_ui.topicsSearchBox.querySelector("dji-cwu-search-bar");
this.m_ui.topicsSearchBarInput=this.m_ui.topicsSearchBar.querySelector("input");this.m_ui.topicsSearchBarBack=this.m_ui.topicsSearchBar.querySelector('dji-cwu-icon[dji-cwu-role="back"]');this.m_ui.topicsSearchBarStartSpeak=this.m_ui.topicsSearchBar.querySelector('dji-cwu-icon[dji-cwu-role="start_speak"]');this.m_ui.topicsSearchBarStopSpeak=this.m_ui.topicsSearchBar.querySelector('dji-cwu-icon[dji-cwu-role="stop_speak"]');this.m_ui.topicsSearchBarClear=this.m_ui.topicsSearchBar.querySelector('dji-cwu-icon[dji-cwu-role="clear"]');
this.m_ui.topicsSearchResults=this.m_ui.topicsSearchBox.querySelector("dji-cwu-search-results");this.m_ui.topicsSearchResultsLocal=this.m_ui.topicsSearchResults.querySelector('dji-cwu-search-results-group[dji-cwu-role="dji-cwu-local"]');this.m_ui.topicsSearchResultsWeb=this.m_ui.topicsSearchResults.querySelector('dji-cwu-search-results-group[dji-cwu-role="dji-cwu-web"]');this.m_ui.topicsSearchInfo=this.m_ui.topicsSearchResults.querySelector('dji-cwu-info-pane[dji-cwu-role="info-no-results"]');this.m_ui.topicsSearchInfoPattern=
this.m_ui.topicsSearchInfo.querySelector('dji-cwu-div[dji-cwu-role="name"]');this.m_ui.topicsUpdateInfo=this.m_ui.topicsSearchResults.querySelector('dji-cwu-info-pane[dji-cwu-role="info-update-topics"]');this.m_ui.topicsUpdateInfoName=this.m_ui.topicsUpdateInfo.querySelector('dji-cwu-div[dji-cwu-role="name"]')};
DjiCwuMainView.prototype.__addEventListeners=function(){this.m_demoMode||(this.m_ui.tabViewToolbarButtons.addEventListener("click",this.m_eventHandlers.__onTabViewToolbarButtonClick),this.m_ui.tabViewToolbarButtons.addEventListener("x-enter",this.m_eventHandlers.__onTabViewToolbarButtonClick),this.m_ui.typePageToolbarButtons.addEventListener("click",this.m_eventHandlers.__onTypePageToolbarButtonClick),this.m_ui.typePageToolbarButtons.addEventListener("x-enter",this.m_eventHandlers.__onTypePageToolbarButtonClick),
this.m_ui.typePagePane123Keys.addEventListener("click",this.m_eventHandlers.__onTypePageKeyboardItemClick),this.m_ui.typePagePane123Keys.addEventListener("x-enter",this.m_eventHandlers.__onTypePageKeyboardItemClick),this.m_ui.typePagePane123Keys.addEventListener("mouseover",this.m_eventHandlers.__onTypePageKeyboardItemMouseOver),this.m_ui.typePagePane123Keys.addEventListener("mouseout",this.m_eventHandlers.__onGenericMouseOut),this.m_ui.speakPageToolbarButtons.addEventListener("click",this.m_eventHandlers.__onSpeakPageToolbarButtonClick),
this.m_ui.speakPageToolbarButtons.addEventListener("x-enter",this.m_eventHandlers.__onSpeakPageToolbarButtonClick),this.m_ui.speakPageMicrophone.addEventListener("click",this.m_eventHandlers.__onSpeakPageMicrophoneClick),this.m_ui.speakPageMicrophone.addEventListener("x-enter",this.m_eventHandlers.__onSpeakPageMicrophoneClick),this.m_ui.speakPageInfo.addEventListener("click",this.m_eventHandlers.__onSpeakPageInfoClick),this.m_ui.speakPageInfo.addEventListener("x-enter",this.m_eventHandlers.__onSpeakPageInfoClick),
this.m_ui.topicsSearchBarInput.addEventListener("x-enter",this.m_eventHandlers.__onTopicsSearchInputClick),this.m_ui.topicsSearchBarInput.addEventListener("focus",this.m_eventHandlers.__onTopicsSearchInputFocus),this.m_ui.topicsSearchBarInput.addEventListener("blur",this.m_eventHandlers.__onTopicsSearchInputBlur),this.m_ui.topicsSearchBarInput.addEventListener("input",this.m_eventHandlers.__onTopicsSearchInputChange),this.m_ui.topicsSearchBarBack.addEventListener("click",this.m_eventHandlers.__onTopicsSearchBack),
this.m_ui.topicsSearchBarBack.addEventListener("x-enter",this.m_eventHandlers.__onTopicsSearchBack),this.m_ui.topicsSearchBarStartSpeak.addEventListener("click",this.m_eventHandlers.__onTopicsSearchStartSpeechRecognition),this.m_ui.topicsSearchBarStartSpeak.addEventListener("x-enter",this.m_eventHandlers.__onTopicsSearchStartSpeechRecognition),this.m_ui.topicsSearchBarStopSpeak.addEventListener("click",this.m_eventHandlers.__onTopicsSearchStopSpeechRecognition),this.m_ui.topicsSearchBarStopSpeak.addEventListener("x-enter",
this.m_eventHandlers.__onTopicsSearchStopSpeechRecognition),this.m_ui.topicsSearchBarClear.addEventListener("click",this.m_eventHandlers.__onTopicsSearchClear),this.m_ui.topicsSearchBarClear.addEventListener("x-enter",this.m_eventHandlers.__onTopicsSearchClear))};
DjiCwuMainView.prototype.__createEventHandlers=function(){if(!this.m_demoMode){var a=this;this.m_eventHandlers.__onTabViewToolbarButtonClick=function(){a.__onTabViewToolbarButtonClick(this)};this.m_eventHandlers.__onTypePageToolbarButtonClick=function(){a.__onTypePageToolbarButtonClick(this)};this.m_eventHandlers.__onTypePageSuggestionMouseOver=function(){a.__onTypePageSuggestionMouseOver(this)};this.m_eventHandlers.__onTypePageSuggestionClick=function(){a.__onTypePageSuggestionClick(this)};this.m_eventHandlers.__onTypePageKeyboardItemMouseOver=
function(){a.__onTypePageKeyboardItemMouseOver(this)};this.m_eventHandlers.__onTypePageKeyboardItemClick=function(){a.__onTypePageKeyboardItemClick(this)};this.m_eventHandlers.__onSpeakPageToolbarButtonClick=function(){a.__onSpeakPageToolbarButtonClick(this)};this.m_eventHandlers.__onSpeakPageMicrophoneClick=function(){a.__onSpeakPageMicrophoneClick(this)};this.m_eventHandlers.__onSpeakPageInfoClick=function(){a.__onSpeakPageInfoClick(this)};this.m_eventHandlers.__onTopicsSearchInputClick=function(){a.m_ui.topicsSearchBarInput.focus()};
this.m_eventHandlers.__onTopicsSearchInputFocus=function(){a.__onTopicsSearchInputFocus()};this.m_eventHandlers.__onTopicsSearchInputBlur=function(){a.__onTopicsSearchInputBlur()};this.m_eventHandlers.__onTopicsSearchInputChange=function(b){a.__onTopicsSearchInputChange(this)};this.m_eventHandlers.__onTopicsSearchBack=function(){a.__onTopicsSearchBack()};this.m_eventHandlers.__onTopicsSearchStartSpeechRecognition=function(){a.__onTopicsSearchStartSpeechRecognition()};this.m_eventHandlers.__onTopicsSearchStopSpeechRecognition=
function(){a.__onTopicsSearchStopSpeechRecognition()};this.m_eventHandlers.__onTopicsSearchClear=function(){a.__onTopicsSearchClear()};this.m_eventHandlers.__onTopicsSearchItemClick=function(){a.__onTopicsSearchItemClick(this)};this.m_eventHandlers.__onTopicsItemOnOff=function(){var b="dji-cwu-switch"===this.tagName.toLowerCase()?this:this.querySelector("dji-cwu-switch");b&&a.__onTopicsItemOnOff(b)};this.m_eventHandlers.__onGenericMouseOver=function(){a.__onGenericMouseOver(this)};this.m_eventHandlers.__onGenericMouseOut=
function(){a.__onGenericMouseOut(this)}}};
DjiCwuMainView.prototype.__onTabViewToolbarButtonClick=function(a,b){var c=a.getAttribute("dji-cwu-link-to"),d=this.trueKeyMode;if(DjiCwuMainView.__isActive(a))this.m_ui.mainView.getAttribute("dji-cwu-mode")!==c&&(this.m_ui.mainView.setAttribute("dji-cwu-mode",c),this.__notifyTrueKeyModeDidChange(d));else{this.__notifyStopSpeechRecognition();var e=this.m_ui.tabView.querySelector("dji-cwu-tab-view-page[dji-cwu-active");e=e?e.getAttribute("dji-cwu-role"):null;var f=this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="'+
c+'"]');this.m_ui.tabViewPageSpeak.removeAttribute("dji-cwu-error");this.m_ui.tabViewToolbarButtons.removeAttribute("dji-cwu-active");this.m_ui.tabViewPages.removeAttribute("dji-cwu-active");a.setAttribute("dji-cwu-active","");f.setAttribute("dji-cwu-active","");this.m_ui.mainView.setAttribute("dji-cwu-mode",c);this.__resetAccessibilityManager();!b&&this.m_delegates.viewDidChangeDelegate&&this.m_delegates.viewDidChangeDelegate(c,e);this.__notifyTrueKeyModeDidChange(d)}};
DjiCwuMainView.prototype.__onTypePageToolbarButtonClick=function(a){if(!DjiCwuMainView.__isActive(a)){var b=this.trueKeyMode,c=a.getAttribute("dji-cwu-link-to");c=this.m_ui.tabViewPageType.querySelector('[dji-cwu-role="'+c+'"]');this.m_ui.typePageToolbarButtons.removeAttribute("dji-cwu-active");this.m_ui.typePagePanes.removeAttribute("dji-cwu-active");a.setAttribute("dji-cwu-active","");c.setAttribute("dji-cwu-active","");this.__resetAccessibilityManager();this.__notifyTrueKeyModeDidChange(b)}};
DjiCwuMainView.prototype.__onTypePageSuggestionMouseOver=function(a){this.__scheduleSpeakText(a.__data.audio)};DjiCwuMainView.prototype.__onTypePageSuggestionClick=function(a){this.m_delegates.suggestionClickDelegate&&this.m_delegates.suggestionClickDelegate(a.__data)};DjiCwuMainView.prototype.__onTypePageKeyboardItemMouseOver=function(a){a=a.getAttribute("dji-cwu-data");this.__scheduleSpeakText(a)};
DjiCwuMainView.prototype.__onTypePageKeyboardItemClick=function(a){a=parseInt(a.getAttribute("dji-cwu-data"));this.m_delegates.keyboardClickDelegate&&!isNaN(a)&&0<=a<=9&&this.m_delegates.keyboardClickDelegate({type:"click",code:"Digit"+a,key:""+a,keyCode:(""+a).charCodeAt(0),which:(""+a).charCodeAt(0)})};
DjiCwuMainView.prototype.__onSpeakPageToolbarButtonClick=function(a){DjiCwuMainView.__isActive(a)||(this.__notifyStopSpeechRecognition(),this.m_ui.speakPageToolbarButtons.removeAttribute("dji-cwu-active"),a.setAttribute("dji-cwu-active",""),this.m_ui.speakPageMicrophone.__data=a.__data)};
DjiCwuMainView.prototype.__onSpeakPageMicrophoneClick=function(a){var b=!a.__isActive;b&&(a.setAttribute("dji-cwu-state","active"),this.m_ui.speakPageInfo.innerText="Speak now...",a.__isActive=!0);this.m_delegates.speechRecognitionDelegate&&this.m_delegates.speechRecognitionDelegate({activate:b,langCode:a.__data.langCode,scope:"dictation"})};DjiCwuMainView.prototype.__onSpeakPageInfoClick=function(a){this.m_ui.speakPagePanes.setAttribute("dji-cwu-hidden","");this.m_ui.speakPagePaneError.removeAttribute("dji-cwu-hidden")};
DjiCwuMainView.prototype.__onTopicsSearchInputFocus=function(){this.m_ui.topicsSearchBarInput.__search={session:null,pattern:null};this.m_ui.topicsSearchBox.activate(!0);this.__pushTopicSearchStateToAccessibilityManager()};
DjiCwuMainView.prototype.__onTopicsSearchInputBlur=function(){this.m_ui.topicsSearchBox.__speechRecognitionActive||this.m_ui.mainView.__updateTopic||(this.m_ui.topicsSearchBarInput.value="",delete this.m_ui.topicsSearchBarInput.__search,this.__popTopicSearchStateFromAccessibilityManager(),this.m_ui.topicsSearchBox.activate(!1),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-no-results"),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-input"),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-speech-recognition"),
this.m_ui.mainView.__updateTopic||(this.m_ui.mainView.removeAttribute("dji-cwu-update-topics"),this.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint")))};
DjiCwuMainView.prototype.__onTopicsSearchBack=function(){this.m_ui.mainView.__updateTopic||(this.m_ui.topicsSearchBarInput.ownerDocument.activeElement===this.m_ui.topicsSearchBarInput?(this.m_ui.topicsSearchBarInput.blur(),document.hasFocus()||this.__onTopicsSearchInputBlur()):this.__onTopicsSearchInputBlur(),this.m_ui.mainView.removeAttribute("dji-cwu-update-topics"),this.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint"),this.m_ui.topicsSearchResultsLocal.removeAllChildren(),this.m_ui.topicsSearchResultsWeb.removeAllChildren())};
DjiCwuMainView.prototype.__onTopicsSearchStartSpeechRecognition=function(){if(this.m_delegates.speechRecognitionDelegate){var a=this;this.m_ui.topicsSearchBarInput.value="";this.m_ui.topicsSearchBox.setAttribute("dji-cwu-speech-recognition","");this.m_ui.topicsSearchBox.__speechRecognitionActive=!0;this.m_ui.topicsSearchBarInput.enableInputEvents(!1);this.m_ui.topicsSearchBarInput.focusAsync(function(){a.m_ui.topicsSearchResultsLocal.removeAllChildren();a.m_ui.topicsSearchResultsWeb.removeAllChildren();
a.m_delegates.speechRecognitionDelegate({activate:!0,langCode:null,scope:"search_topics"})})}};
DjiCwuMainView.prototype.__onTopicsSearchStopSpeechRecognition=function(a,b){this.m_ui.topicsSearchBox.__speechRecognitionActive&&(a||(this.m_ui.topicsSearchBarInput.value=""),this.m_ui.topicsSearchBox.removeAttribute("dji-cwu-speech-recognition"),this.m_ui.topicsSearchBox.__speechRecognitionActive=!1,this.m_ui.topicsSearchBarInput.enableInputEvents(),!a&&this.m_ui.topicsSearchBarInput.__search&&(this.m_ui.topicsSearchBarInput.__search.session=null,this.m_ui.topicsSearchBarInput.__search.pattern=
null),b||this.m_delegates.speechRecognitionDelegate({activate:!1,langCode:null,scope:"search_topics"}))};DjiCwuMainView.prototype.__onTopicsSearchClear=function(){this.m_ui.mainView.removeAttribute("dji-cwu-update-topics");this.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint");this.m_ui.topicsSearchBarInput.value="";this.__onTopicsSearchInputChange(this.m_ui.topicsSearchBarInput)};
DjiCwuMainView.prototype.__onTopicsSearchInputChange=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,l,k){for(;;)switch(d){case 0:if(!b.m_ui.topicsSearchBox.__speechRecognitionActive&&!b.m_ui.mainView.__updateTopic){d=1;break}d=-1;return{value:void 0,done:!0};case 1:if(a.__search){d=2;break}b.m_timers.searchTopics.stop();d=-1;return{value:void 0,done:!0};case 2:b.m_ui.mainView.removeAttribute("dji-cwu-update-topics");b.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint");
g=b;f=Date.now()+"-"+parseInt(1E3*Math.random());e=a.value.trim();if(a.__search.pattern!==e){d=3;break}d=-1;return{value:void 0,done:!0};case 3:b.m_timers.searchTopics.stop();a.__search.session=f;a.__search.pattern=e;if(!(0>=e.length)){d=4;break}g.m_ui.topicsSearchResultsLocal.removeAllChildren();g.m_ui.topicsSearchResultsWeb.removeAllChildren();g.m_ui.topicsSearchBox.removeAttribute("dji-cwu-no-results");g.m_ui.topicsSearchInfoPattern.innerText="";g.m_ui.topicsSearchBox.removeAttribute("dji-cwu-input",
"");d=-1;return{value:void 0,done:!0};case 4:b.m_timers.searchTopics.trigger(0,f,e),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,g,k={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())};
DjiCwuMainView.prototype.__onTopicsSearchItemClick=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,h,m){for(;;)switch(d){case 0:if(b.m_ui.topicsSearchBarInput.__search){d=1;break}d=-1;return{value:Logger.instance.error("Search metadata not found!"),done:!0};case 1:if(!b.m_ui.mainView.__updateTopic){d=2;break}d=-1;return{value:Logger.instance.error("Update topics is already in progress!"),done:!0};case 2:k=Date.now()+"-"+parseInt(1E3*Math.random());b.m_ui.mainView.__updateTopic=
!0;b.m_ui.topicsSearchBarInput.enableInputEvents(!1);b.m_ui.topicsSearchBarInput.__search={session:k,pattern:name};try{return f=b,d=5,{value:dji.topicHelper.updateTopicAsync({name:a.__data.item,url:a.__data.url,data:void 0,local:a.__data.local},function(a){f.m_ui.mainView.setAttribute("dji-cwu-update-topics",a.userData.action);a.userData.activate||f.m_ui.mainView.setAttribute("dji-cwu-update-topics-hint","hint-too-many-active");f.m_ui.topicsUpdateInfoName.innerText=a.name;f.m_ui.topicsSearchResults.scrollTop=
0}),done:!1}}catch(n){g=n;d=3;break}case 5:try{if(1!=c){d=6;break}d=-1;throw m;}catch(n){g=n;d=3;break}case 6:try{b.m_ui.topicsSearchBarInput.__search&&b.m_ui.topicsSearchBarInput.__search.session===k&&(b.m_ui.mainView.removeAttribute("dji-cwu-update-topics"),b.m_ui.mainView.removeAttribute("dji-cwu-update-topics-hint"),b.m_ui.topicsUpdateInfoName.innerText="",b.m_ui.topicsSearchBarInput.enableInputEvents(),b.m_ui.mainView.__updateTopic=!1,b.__onTopicsSearchBack());d=4;break}catch(n){g=n;d=3;break}case 3:e=
g,Logger.instance.error(e),b.m_ui.topicsSearchBarInput.__search&&b.m_ui.topicsSearchBarInput.__search.session===k&&"too_many_active_topics"===e.code&&(b.m_ui.mainView.setAttribute("dji-cwu-update-topics","too-many-active"),b.m_ui.topicsSearchBarInput.enableInputEvents(),b.m_ui.mainView.__updateTopic=!1);case 4:d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,g,k,h={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
DjiCwuMainView.prototype.__onTopicsItemOnOff=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,m,u){for(;;)switch(d){case 0:p=a.toggleOnOff();l=!1;window.dji.accessibility.manager.enable(!1,!0);try{return k=b,d=3,{value:dji.topicHelper.activateTopicAsync({name:a.__data.item,activate:p},function(a){k.m_ui.mainView.setAttribute("dji-cwu-update-topics","on-off")}),done:!1}}catch(q){h=q;d=1;break}case 3:try{if(1!=c){d=4;break}d=-1;throw u;}catch(q){h=q;d=1;break}case 4:try{f=
g=m;l=f.success;d=2;break}catch(q){h=q;d=1;break}case 1:e=h,Logger.instance.error(e);case 2:l||a.toggleOnOff(),b.m_ui.mainView.removeAttribute("dji-cwu-update-topics"),window.dji.accessibility.manager.enable(!0),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,f,g,k,h,l,p,m={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();m[Symbol.iterator]=function(){return this};return m}())};
DjiCwuMainView.prototype.__onSearchTopics=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function a(a,d,t){for(;;)switch(e){case 0:n=[];m=[];try{l=c.m_wikiReader?c.m_wikiReader.searchAsync(b,c.m_data.locale):void 0;n=c.__searchTopicsInLocal(b);if(!l){e=3;break}e=4;return{value:l,done:!1}}catch(r){p=r;e=1;break}case 4:try{if(1!=a){e=5;break}e=-1;throw t;}catch(r){p=r;e=1;break}case 5:try{m=h=d}catch(r){p=r;e=1;break}case 3:try{e=2;break}catch(r){p=r;e=1;break}case 1:k=p,Logger.instance.error(k);
case 2:c.m_ui.topicsSearchResultsLocal.removeAllChildren(),c.m_ui.topicsSearchResultsWeb.removeAllChildren(),g=c.__buildTopicSearchResults(!0,n),f=c.__buildTopicSearchResults(!1,m),0<g.entries.length&&c.m_ui.topicsSearchResultsLocal.appendChild(g.fragment),0<f.entries.length&&c.m_ui.topicsSearchResultsWeb.appendChild(f.fragment),0<g.entries.length||0<f.entries.length?(c.m_ui.topicsSearchBox.removeAttribute("dji-cwu-no-results"),c.m_ui.topicsSearchInfoPattern.innerText=""):(c.m_ui.topicsSearchInfoPattern.innerText=
b,c.m_ui.topicsSearchBox.setAttribute("dji-cwu-no-results","")),c.m_ui.topicsSearchBox.setAttribute("dji-cwu-input",""),c.__updateAccessibilityManagerInTopicsPage(!1,!0,!1),e=-1;default:return{value:void 0,done:!0}}}var e=0,f,g,k,h,l,p,m,n,t={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();t[Symbol.iterator]=function(){return this};return t}())};
DjiCwuMainView.prototype.__searchTopicsInLocal=function(a){a=a.toUpperCase();for(var b=[],c=0;c<this.m_data.topicsUpperCase.length;c++)0<=this.m_data.topicsUpperCase[c].indexOf(a)&&b.push({name:this.m_data.topics[c]});b.sort();return b};DjiCwuMainView.prototype.__onGenericMouseOver=function(a){a.__data.audio?this.__scheduleSpeakText(a.__data.audio):a.__data.item&&this.__scheduleSpeakText(a.__data.item)};DjiCwuMainView.prototype.__onGenericMouseOut=function(a){this.__cancelScheduleSpeakText()};
DjiCwuMainView.prototype.__scheduleSpeakText=function(a){this.m_timers.speak.stop();this.m_delegates.speakDelegate&&this.m_timers.speak.trigger(500,a)};DjiCwuMainView.prototype.__cancelScheduleSpeakText=function(){this.m_timers.speak.stop()};DjiCwuMainView.prototype.__onSpeakText=function(a){this.m_delegates.speakDelegate&&this.m_delegates.speakDelegate(a)};
DjiCwuMainView.prototype.__notifyStopSpeechRecognition=function(){this.m_ui.speakPageMicrophone.__isActive&&this.m_delegates.speechRecognitionDelegate&&this.m_delegates.speechRecognitionDelegate({activate:!1,langCode:null})};DjiCwuMainView.prototype.__notifyTrueKeyModeDidChange=function(a){if(this.m_delegates.trueKeyModeDidChangeDelegate){var b=this.trueKeyMode;a!==b&&this.m_delegates.trueKeyModeDidChangeDelegate(b,a)}};
DjiCwuMainView.prototype.__resetAccessibilityManager=function(){window.dji&&window.dji.accessibility&&window.dji.accessibility.manager&&(window.dji.accessibility.manager.reset(),window.dji.accessibility.manager.addBlockAndSetup("main",{name:"main",blocks:[{name:"type",dom:{element:this.m_ui.tabViewPageType,selectors:["[dji-accessible]"]}},{name:"topics",blocks:[{name:"search_bar",dom:{element:this.m_ui.tabViewPageTopics,selectors:["dji-cwu-search-box > dji-cwu-search-bar [dji-accessible]"]}},{name:"topic_items",
dom:{element:this.m_ui.tabViewPageTopics,selectors:["dji-cwu-topics-pane [dji-accessible]"]}}]},{name:"speak",dom:{element:this.m_ui.tabViewPageSpeak,selectors:["[dji-accessible]"]}},{name:"toolbar",dom:{element:this.m_ui.tabView,selectors:["dji-cwu-tab-view-toolbar-button[dji-accessible]"]}}]}),this.__updateAccessibilityManagerInTypePage(),this.__updateAccessibilityManagerInTopicsPage(!0,!0,!0),this.__updateAccessibilityManagerInSpeakPage())};
DjiCwuMainView.prototype.__pushTopicSearchStateToAccessibilityManager=function(){window.dji&&window.dji.accessibility&&window.dji.accessibility.manager&&window.dji.accessibility.manager.addBlockAndSetup("topics_search",{name:"topics_search",blocks:[{name:"search_bar",dom:{element:this.m_ui.tabViewPageTopics,selectors:["dji-cwu-search-box > dji-cwu-search-bar [dji-accessible]"]}},{name:"search_results",dom:{element:this.m_ui.tabViewPageTopics,selectors:["dji-cwu-search-box > dji-cwu-search-results [dji-accessible]"]}}]})};
DjiCwuMainView.prototype.__popTopicSearchStateFromAccessibilityManager=function(){window.dji&&window.dji.accessibility&&window.dji.accessibility.manager.removeBlock("topics_search")};DjiCwuMainView.prototype.__updateAccessibilityManagerInTypePage=function(a){window.dji&&window.dji.accessibility&&window.dji.accessibility.manager.reloadBlock("type",!!a)};
DjiCwuMainView.prototype.__updateAccessibilityManagerInTopicsPage=function(a,b,c,d){window.dji&&window.dji.accessibility&&(a&&window.dji.accessibility.manager.reloadBlock("topics search search_bar",d),b&&window.dji.accessibility.manager.reloadBlock("search_results",d),c&&window.dji.accessibility.manager.reloadBlock("topics topic_items",d))};
DjiCwuMainView.prototype.__updateAccessibilityManagerInSpeakPage=function(){window.dji&&window.dji.accessibility&&window.dji.accessibility.manager.reloadBlock("speak",!0)};DjiCwuMainView.__isActive=function(a){return!(!a||null===a.getAttribute("dji-cwu-active"))};DjiCwuMainView.__onBlockDefaultBehaviour=function(a){a.target&&a.target.nodeType===Node.ELEMENT_NODE&&"INPUT"===a.target.nodeName.toUpperCase()||(a.preventDefault(),a.stopPropagation())};
$jscomp.global.Object.defineProperties(DjiCwuMainView.prototype,{view:{configurable:!0,enumerable:!0,get:function(){return this.m_ui.mainView}},size:{configurable:!0,enumerable:!0,get:function(){var a={width:0,height:0};if(this.m_ui.mainView){var b=this.m_ui.mainView.getBoundingClientRect();a.width=Math.round(b.width);a.height=Math.round(b.height)}return a}},location:{configurable:!0,enumerable:!0,get:function(){var a={left:0,top:0,width:0,height:0};if(this.m_ui.mainView){var b=this.m_ui.mainView.getBoundingClientRect();
a.left=Math.round(b.left);a.top=Math.round(b.top);a.width=Math.round(b.width);a.height=Math.round(b.height)}return a}},mode:{configurable:!0,enumerable:!0,get:function(){var a=void 0;if(this.m_ui.mainView){var b=this.m_ui.tabView.querySelector("dji-cwu-tab-view-page[dji-cwu-active]");b&&(a=b.getAttribute("dji-cwu-role"))}return a}},viewDidChangeDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.viewDidChangeDelegate=a)}},trueKeyModeDidChangeDelegate:{configurable:!0,
enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.trueKeyModeDidChangeDelegate=a)}},suggestionClickDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.suggestionClickDelegate=a)}},keyboardClickDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.keyboardClickDelegate=a)}},speechRecognitionDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.speechRecognitionDelegate=
a)}},speakClickDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.speakDelegate=a)}},updateTopicDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.updateTopicDelegate=a)}},activateTopicDelegate:{configurable:!0,enumerable:!0,set:function(a){a instanceof Function&&(this.m_delegates.activateTopicDelegate=a)}},trueKeyMode:{configurable:!0,enumerable:!0,get:function(){return!!this.m_ui.tabView.querySelector('dji-cwu-tab-view-page[dji-cwu-role="type"][dji-cwu-active] dji-cwu-keyboard-pane[dji-cwu-active]')}},
windowOptions:{configurable:!0,enumerable:!0,set:function(a){a&&(this.scale=a.scale,this.fontFamily=a.fontFamily,this.textColor=a.textColor,this.backgroundColor=a.backgroundColor)}},fontFamily:{configurable:!0,enumerable:!0,set:function(a){a&&this.m_ui.mainView.style.setProperty("--dji-cwu-opt-text-font-family",a)}},textColor:{configurable:!0,enumerable:!0,set:function(a){(a=dji.color.parse(a))&&this.m_ui.mainView.style.setProperty("--dji-cwu-opt-text-color-rgb",a.red+", "+a.green+", "+a.blue)}},
backgroundColor:{configurable:!0,enumerable:!0,set:function(a){(a=dji.color.parse(a))&&this.m_ui.mainView.style.setProperty("--dji-cwu-opt-bkgnd-color-rgb",a.red+", "+a.green+", "+a.blue)}},suggestionsCount:{configurable:!0,enumerable:!0,set:function(a){isNaN(a)||this.m_ui.mainView.style.setProperty("--dji-cwu-opt-suggestion-elem-count",a)},get:function(){return this.m_ui.mainView?this.m_ui.mainView.__suggestionsCount:0}},translationsEnabled:{configurable:!0,enumerable:!0,set:function(a){a?(this.m_ui.typePagePaneType.setAttribute("dji-cwu-options",
"translations"),this.setTranslations()):(this.m_ui.typePagePaneType.removeAttribute("dji-cwu-options"),this.__clearTranslations());this.m_ui.mainView.__translationsEnabled=!!a},get:function(){return this.m_ui.mainView?this.m_ui.mainView.__translationsEnabled:!1}},scale:{configurable:!0,enumerable:!0,set:function(a){isNaN(a)||this.m_ui.mainView.style.setProperty("--dji-cwu-opt-transform-scale",a)}},searchTopicsPattern:{configurable:!0,enumerable:!0,set:function(a){this.m_ui.topicsSearchBox.__speechRecognitionActive&&
(this.m_ui.topicsSearchBarInput.value=a||"",this.__onTopicsSearchStopSpeechRecognition(!0),this.__onTopicsSearchInputChange(this.m_ui.topicsSearchBarInput))}},topics:{configurable:!0,enumerable:!0,set:function(a){this.m_data.topics=a?[].concat($jscomp.arrayFromIterable(a)):[];this.m_data.topicsUpperCase=this.m_data.topics.map(function(a){return a.toUpperCase()})}},displayTopics:{configurable:!0,enumerable:!0,set:function(a){var b=this.__buildTopics(a);this.m_ui.topicsMainPane.removeAllChildren();
this.m_ui.topicsMainPane.appendChild(b);this.m_data.displayTopics=a?[].concat($jscomp.arrayFromIterable(a)):[];this.__updateAccessibilityManagerInTopicsPage(!1,!1,!0)}}});
