var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,d){b!=Array.prototype&&b!=Object.prototype&&(b[h]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var h=0;return $jscomp.iteratorPrototype(function(){return h<b.length?{done:!1,value:b[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var h=b[Symbol.iterator];return h?h.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill=function(b,h,d,e){if(h){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];h=h(e);h!=e&&null!=h&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:h})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function h(){this.batch_=null}function d(a){return a instanceof f?a:new f(function(c,k){c(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;h.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};h.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;h.prototype.asyncExecuteFunction=function(a){e(a,
0)};h.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var k=a[c];delete a[c];try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};h.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(k){c.reject(k)}};f.prototype.createResolveAndReject_=
function(){function a(a){return function(b){k||(k=!0,a.call(c,b))}}var c=this,k=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var c=
void 0;try{c=a.then}catch(k){this.reject_(k);return}"function"==typeof c?this.settleSameAsThenable_(c,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,c=0;c<a.length;++c)a[c].call(),a[c]=null;this.onSettledCallbacks_=null}};var g=new h;f.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};f.prototype.settleSameAsThenable_=function(a,c){var k=this.createResolveAndReject_();try{a.call(c,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(a,c){function k(c,a){return"function"==typeof c?function(a){try{b(c(a))}catch(t){d(t)}}:a}var b,d,e=new f(function(c,
a){b=c;d=a});this.callWhenSettled_(k(a,b),k(c,d));return e};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,c){function b(){switch(l.state_){case 1:a(l.result_);break;case 2:c(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?g.asyncExecute(b):this.onSettledCallbacks_.push(function(){g.asyncExecute(b)})};f.resolve=d;f.reject=function(a){return new f(function(c,b){b(a)})};f.race=function(a){return new f(function(c,
b){for(var k=$jscomp.makeIterator(a),e=k.next();!e.done;e=k.next())d(e.value).callWhenSettled_(c,b)})};f.all=function(a){var c=$jscomp.makeIterator(a),b=c.next();return b.done?d([]):new f(function(a,k){function l(c){return function(b){e[c]=b;f--;0==f&&a(e)}}var e=[],f=0;do e.push(void 0),f++,d(b.value).callWhenSettled_(l(e.length-1),k),b=c.next();while(!b.done)})};return f},"es6","es3");
$jscomp.executeAsyncGenerator=function(b){function h(e){return b.next(e)}function d(e){return b.throw(e)}return new Promise(function(e,f){function g(a){a.done?e(a.value):Promise.resolve(a.value).then(h,d).then(g,f)}g(b.next())})};$jscomp.owns=function(b,h){return Object.prototype.hasOwnProperty.call(b,h)};
$jscomp.polyfill("WeakMap",function(b){function h(a){$jscomp.owns(a,e)||$jscomp.defineProperty(a,e,{value:{}})}function d(a){var c=Object[a];c&&(Object[a]=function(a){h(a);return c(a)})}if(function(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),c=Object.seal({}),k=new b([[a,2],[c,3]]);if(2!=k.get(a)||3!=k.get(c))return!1;k.delete(a);k.set(c,4);return!k.has(a)&&4==k.get(c)}catch(l){return!1}}())return b;var e="$jscomp_hidden_"+Math.random().toString().substring(2);d("freeze");d("preventExtensions");
d("seal");var f=0,g=function(a){this.id_=(f+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};g.prototype.set=function(a,c){h(a);if(!$jscomp.owns(a,e))throw Error("WeakMap key fail: "+a);a[e][this.id_]=c;return this};g.prototype.get=function(a){return $jscomp.owns(a,e)?a[e][this.id_]:void 0};g.prototype.has=function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)};g.prototype.delete=
function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)?delete a[e][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),a=new b($jscomp.makeIterator([[c,"s"]]));if("s"!=a.get(c)||1!=a.size||a.get({x:4})||a.set({x:4},"t")!=a||2!=a.size)return!1;var e=a.entries(),d=e.next();if(d.done||d.value[0]!=c||"s"!=d.value[1])return!1;d=e.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!e.next().done?!1:!0}catch(q){return!1}}())return b;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var h=new WeakMap,d=function(c){this.data_={};this.head_=g();this.size=0;if(c){c=$jscomp.makeIterator(c);for(var a;!(a=c.next()).done;)a=a.value,this.set(a[0],a[1])}};d.prototype.set=function(c,a){var b=e(this,c);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=a:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:c,value:a},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};d.prototype.delete=
function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};d.prototype.has=function(a){return!!e(this,a).entry};d.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};d.prototype.entries=function(){return f(this,function(a){return[a.key,
a.value]})};d.prototype.keys=function(){return f(this,function(a){return a.key})};d.prototype.values=function(){return f(this,function(a){return a.value})};d.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(c,b){var d=b&&typeof b;"object"==d||"function"==d?h.has(b)?d=h.get(b):(d=""+ ++a,h.set(b,d)):d="p_"+b;var e=c.data_[d];if(e&&$jscomp.owns(c.data_,d))for(c=0;c<e.length;c++){var f=
e[c];if(b!==b&&f.key!==f.key||b===f.key)return{id:d,list:e,index:c,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},f=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},g=function(){var a={};return a.previous=a.next=a.head=a},a=0;return d},"es6","es3");
$jscomp.iteratorFromArray=function(b,h){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var d=0,e={next:function(){if(d<b.length){var f=d++;return{value:h(f,b[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.values",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b,d){return d})}},"es6","es3");window.dji=window.dji||{};
window.dji.ui=window.dji.ui||{};
(function(b){var h=new Map;b.cache=function(b,e){return $jscomp.executeAsyncGenerator(function(){function d(d,f,p){for(;;)switch(g){case 0:try{return q=chrome&&chrome.extension&&chrome.extension.getURL?chrome.extension.getURL(b):b,g=3,{value:fetch(q),done:!1}}catch(m){n=m;g=1;break}case 3:try{if(1!=d){g=4;break}g=-1;throw p;}catch(m){n=m;g=1;break}case 4:try{return l=r=f,g=5,{value:l.text(),done:!1}}catch(m){n=m;g=1;break}case 5:try{if(1!=d){g=6;break}g=-1;throw p;}catch(m){n=m;g=1;break}case 6:try{return l=
k=f,(c=document.createRange().createContextualFragment(l))&&h.set(e,c),g=-1,{value:c,done:!0}}catch(m){n=m;g=1;break}case 1:a=n,Logger.instance.error(a);case 2:return g=-1,{value:void 0,done:!0};default:return{value:void 0,done:!0}}}var g=0,a,c,k,l,r,q,n,p={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();p[Symbol.iterator]=function(){return this};return p}())};b.source=function(b){return h.get(b)||
null};b.load=function(b,e){1===arguments.length&&(e=b,b=void 0);var d="dji-dom-module#"+e.toLowerCase(),g=void 0;if(b)(g=b.querySelector("dji-dom-module#"+e))&&(g=g.cloneNode(!0));else for(var a=h.values(),c=a.next();!c.done;c=a.next())if(g=c.value.querySelector(d)){g=g.cloneNode(!0);break}return g?(d=g.querySelector("style"),g=g.querySelector("template"),{style:d,content:g?g.content:null}):null}})(window.dji.ui.templatesRegistry=window.dji.ui.templatesRegistry||{});
