var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(b,g){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var c=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){c(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(q){g(q)}}:b}var d,g,h=new e(function(a,
b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return h};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=d;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
c){for(var g=$jscomp.makeIterator(a),e=g.next();!e.done;e=g.next())d(e.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new e(function(a,e){function g(b){return function(c){h[b]=c;f--;0==f&&a(h)}}var h=[],f=0;do h.push(void 0),f++,d(c.value).callWhenSettled_(g(h.length-1),e),c=b.next();while(!c.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(c,e){function f(a){a.done?c(a.value):Promise.resolve(a.value).then(b,d).then(f,e)}f(a.next())})};$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(b.call(d,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");
function CWEPredictionOptions(a,b,d,c){this.m_cweSettings=a;this.m_cwePredictionEngine=b;this.m_cweBackgroundManager=d;this.m_backgroundPage=c;this.m_mainDictionary=$("#dji-cwu-main-dictionary");this.m_mainDictionaryTemplate=null;this.m_momentaryTopic=$("#dji-cwu-momentary-topic");this.m_flexibleSpelling=$("#dji-cwu-flexible-spelling");this.m_locale=$("#dji-cwu-prediction-language");this.__fillLocaleInfo();this.m_translationLocale=$("#dji-cwu-translate-writing");this.m_topicsSearchContainer=$("#dji-cwu-search-container");
this.m_topicsSearch=$("#dji-cwu-search-topic-dictionary");this.m_topicsCancelSearch=$("#dji-cwu-cancel-search");this.m_topicsResetSearch=$("#dji-cwu-reset-search");this.m_localTopics=$("#dji-cwu-local-topic-list");this.m_wikiTopics=$("#dji-cwu-wiki-topic-list");this.m_activeTopics=$("#dji-cwu-active-topics-list");this.m_wikiReader=new CWEWikiReader(this.m_cwePredictionEngine.sensitiveWords());this.m_searchTimer=new DjiTimer(this,this.__searchTopics);this.m_wikiTopicsList=[];this.m_localTopicsList=
[];this.m_selectedWikiTopicIndex=-1;this.m_lastSearchText="";this.m_allLocalTopicsList=[];this.m_allLocalTopicsListLowerCase=[];this.m_activeTopicsList=[];this.m_displayTopicList=[];this.m_displayTopicsMap={};this.m_maxDisplayedTopics=6;this.__initialize();return this}CWEPredictionOptions.instance=null;
CWEPredictionOptions.prototype.__fillLocaleInfo=function(){var a=$("[dji-cwu-template-id=dji-cwu-prediction-language]").find("[dji-cwu-value='"+this.m_cweBackgroundManager.locale()+"']");a.attr("dji-check","");a=a.text();this.m_locale.find(".dji-cwu-option-item-value").text(a);this.m_localeLang=this.m_cweBackgroundManager.locale()};
CWEPredictionOptions.prototype.__initialize=function(){function a(a,b){}function b(a,b){a&&a.hasOwnProperty("text")&&(b=$("#dji-cwu-search-topic-dictionary"),b.val().trim()!==a.text&&(b.val(a.text),c.__scheduleTopicsSearch()))}function d(a,b){e()}var c=this;this.__fillLocaleInfo();this.__displayTopics();null!==this.m_cwePredictionEngine&&(this.m_cwePredictionEngine.addOptionsListener(this),this.m_cwePredictionEngine.getTopics(!0));this.m_locale.on("change",function(a){c.__changeLocale(a.value)});
this.m_translationLocale.on("change",function(a){a.value!==c.m_cweSettings.translationSource()&&c.__changeTranslationLocale(a.value,a.text)});this.m_mainDictionary.on("change",function(a){c.m_cweSettings.predictionMainDictionary(parseInt(a.value));c.m_mainDictionaryTemplate.find("[dji-check]").removeAttr("dji-check");c.m_mainDictionaryTemplate.find("[dji-cwu-value='"+a.value+"']").attr("dji-check","")});this.m_momentaryTopic.on("change",function(a){c.m_cweSettings.predictionMomentaryTopic(a.checked?
1:0)});this.m_flexibleSpelling.on("change",function(a){c.m_cweSettings.predictionFlexibleSpelling(a.checked?1:0)});this.m_activeTopics.on("change",".dji-cwu-switch-container",function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,h,p){for(;;)switch(d){case 0:if(!c.m_cweBackgroundManager.isBusy()){d=1;break}d=-1;return{value:void 0,done:!0};case 1:return n=$(a.currentTarget),f=a.checked,g=n.attr("dji-cwu-topic-dictionary-id"),e=c.m_displayTopicList[g],d=2,{value:c.m_cweBackgroundManager.activateTopicAsync(-1,
{name:e.name,activate:!!f}),done:!1};case 2:if(1!=b){d=3;break}d=-1;throw p;case 3:d=-1;default:return{value:void 0,done:!0}}}var d=0,e,g,f,n,m={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();m[Symbol.iterator]=function(){return this};return m}())});this.__load();var e=function(){var a=$("#dji-cwu-speech-to-text");a.hasClass("dji-cwu-speech-to-text-on")&&(a.find("i").text("mic"),a.removeClass("dji-cwu-speech-to-text-on"),
c.m_backgroundPage.dji.speechRecognition.stop())},f=function(){c.__scheduleTopicsSearch()};$("#dji-cwu-speech-to-text").on("click",function(e){$(e.currentTarget).hasClass("dji-cwu-speech-to-text-on")?($(e.currentTarget).find("i").text("mic"),$(e.currentTarget).removeClass("dji-cwu-speech-to-text-on"),$("#dji-cwu-search-topic-dictionary").focus(),c.m_backgroundPage.dji.speechRecognition.stop()):(navigator.webkitGetUserMedia({audio:!0},function(e){e.getTracks()[0].stop();c.m_backgroundPage.dji.speechRecognition.start(c.m_localeLang,
a,b,d,{})},function(a){Logger.instance.error(a)}),$(e.currentTarget).addClass("dji-cwu-speech-to-text-on"),$(e.currentTarget).find("i").text("mic_off"),$("#dji-cwu-search-topic-dictionary").focus())});this.m_topicsSearch.on("focus",function(){"dji-cwu-default"===c.m_topicsSearchContainer.attr("dji-cwu-view-mode")&&($("body").addClass("dji-cwu-search"),c.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus"))}).on("input",f).on("search",f);this.m_topicsCancelSearch.on("click",function(){e();
c.m_lastSearchText="";c.m_topicsSearch.val("");$("body").removeClass("dji-cwu-search");c.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-default").removeClass("dji-cwu-reset")});this.m_topicsResetSearch.on("click",function(){e();c.m_lastSearchText="";c.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus").removeClass("dji-cwu-reset");c.m_topicsSearch.focus().val("")});this.m_localTopics.on("click",".dji-cwu-topic-item",function(a){a=parseInt($(a.currentTarget).attr("dji-cwu-topic-index"));
c.__localTopicSelected(a);e()});this.m_wikiTopics.on("click",".dji-cwu-topic-item",function(a){a=parseInt($(a.currentTarget).attr("dji-cwu-topic-index"));c.__wikiTopicSelected(a);e()});$(document).on("keydown",function(a){27===a.keyCode&&"dji-cwu-default"!==c.m_topicsSearchContainer.attr("dji-cwu-view-mode")&&(c.__clearSearch(),c.m_topicsSearch.blur(),e())});$(window).on("blur",function(){e()})};
CWEPredictionOptions.prototype.__load=function(){if(this.m_cweSettings){this.__fillLocaleInfo();this.__fillAvailableTranslationLang();this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.m_cweSettings.predictionMomentaryTopic()&&this.m_momentaryTopic.addClass("dji-cwu-on");this.m_cweSettings.predictionFlexibleSpelling()&&this.m_flexibleSpelling.addClass("dji-cwu-on");var a=this.m_cweSettings.translationSource(),b=this.m_locale.find(".dji-cwu-option-item-value").text().trim(),
d="";if(a){var c=this.m_cweBackgroundManager.translationLanguageInfo(a);d=c?c.language_code:a;this.__isEnglish()||(toLang=b.substr(0,b.indexOf("(")));this.m_translationLocale.find(".dji-cwu-option-item-value").text(c?c.name:a);this.m_translationLocale.find(".dji-cwu-option-item-auxiliary").text(" > "+b)}a=this.m_translationLocale.find(".dji-cwu-option-item-label");$("[dji-cwu-template-id=dji-cwu-translate-writing]").find("[dji-cwu-value='"+d+"']").attr("dji-check","");a.text(a.text()+" "+b);this.__displayTopics();
(b=this.__isEnglish())||$(this.m_flexibleSpelling).prop("disabled",!0);this.m_mainDictionaryTemplate=b?$("[dji-cwu-template-id=dji-cwu-main-dictionary-en]"):$("[dji-cwu-template-id=dji-cwu-main-dictionary-no-en]");d=this.m_mainDictionaryTemplate.find("[dji-cwu-value='"+this.m_cweSettings.predictionMainDictionary()+"']");d.attr("dji-check","");d=d.text();this.m_mainDictionary.find(".dji-cwu-option-item-value").text(d);this.m_mainDictionary.attr("dji-cwu-dropdown-id",b?"dji-cwu-main-dictionary-en":
"dji-cwu-main-dictionary-no-en")}};
CWEPredictionOptions.prototype.__fillAvailableTranslationLang=function(){var a=this.m_cweBackgroundManager.localeLang(!1),b=this.m_cweBackgroundManager.translationLanguages(),d=$("[dji-cwu-template-id=dji-cwu-translate-language]"),c=$("[dji-cwu-template-id=dji-cwu-translate-writing]");c.children().slice(1).remove();var e={};b.forEach(function(a){var b=a.language_code.split("-")[0];a.lang=b;e[b]=e[b]?++e[b]:1});for(var f=0;f<b.length;f++){var g=b[f],h=g.lang,l=d.clone(!0),k=1<e[h]?g.name:g.name.split("-")[0];
$(l).attr("dji-cwu-value",g.language_code);$(l).find(".dji-cwu-menu-item-text").text(k);a===h&&$(l).attr("dji-cwu-not-available","");c.append(l)}};
CWEPredictionOptions.prototype.__changeTranslationLocale=function(a,b){var d=this;return $jscomp.executeAsyncGenerator(function(){function c(c,k,n){for(;;)switch(e){case 0:l=d.m_cweBackgroundManager.localeLang(!1);h=(a||"").split("-")[0];if(l!==h){e=1;break}e=-1;return{value:void 0,done:!0};case 1:return dji.ui.modalDlg.showMessageDlg("dji-cwu-changing-language-message"),e=2,{value:d.m_cweBackgroundManager.downloadHunspellResources(a),done:!1};case 2:if(1!=c){e=3;break}e=-1;throw n;case 3:(f=g=k)?
(d.m_cweSettings.translationSource(a&&0<a.length?a:null),d.m_cweBackgroundManager.changeSpellcheckerLocale(a),c=$("[dji-cwu-template-id=dji-cwu-translate-writing]"),c.find("[dji-check]").removeAttr("dji-check"),""===a?d.m_translationLocale.find(".dji-cwu-option-item-auxiliary").attr("dji-off",""):d.m_translationLocale.find(".dji-cwu-option-item-auxiliary").removeAttr("dji-off"),c.find("[dji-cwu-value='"+a+"']").attr("dji-check",""),dji.ui.modalDlg.hideDlg()):(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showModalDlg("dji-cwu-failed-download-hunspell",
{doneCallback:function(){dji.ui.modalDlg.hideDlg()}}),d.m_translationLocale.find(".dji-cwu-option-item-value").text(b)),e=-1;default:return{value:void 0,done:!0}}}var e=0,f,g,h,l,k={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())};
CWEPredictionOptions.prototype.__changeLocale=function(a){var b=this;this.m_backgroundPage.jsdapi.cow.updateLanguage(a,function(d){dji.ui.modalDlg.showMessageDlg("dji-cwu-download-resources-wait-message");b.m_cweBackgroundManager.downloadPredictionResources(a,function(c){c?b.m_backgroundPage.jsdapi.cow.updateLanguage(a,function(c){b.m_cweBackgroundManager.changeLocale(a)}):(dji.ui.modalDlg.hideDlg(),dji.ui.modalDlg.showModalDlg("dji-cwu-failed-download-language-resources",{doneCallback:function(){dji.ui.modalDlg.hideDlg();
b.__fillLocaleInfo()}}))})})};CWEPredictionOptions.prototype.__scheduleTopicsSearch=function(){this.m_searchTimer.trigger(10,this.m_topicsSearch.val().trim())};
CWEPredictionOptions.prototype.__searchTopics=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function d(d,k,n){for(;;)switch(c){case 0:a=a?a.trim():"";if(a!==b.m_lastSearchText){c=1;break}c=-1;return{value:void 0,done:!0};case 1:b.m_lastSearchText=a;if(!(0>=a.length)){c=2;break}b.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus").removeClass("dji-cwu-reset");b.m_localTopicsList=[];b.m_wikiTopicsList=[];c=-1;return{value:void 0,done:!0};case 2:l=void 0;try{l=
b.m_wikiReader.searchAsync(a,b.m_localeLang)}catch(m){Logger.instance.error(m)}b.__searchInLocalTopics(a);try{return c=5,{value:l,done:!1}}catch(m){h=m;c=3;break}case 5:try{if(1!=d){c=6;break}c=-1;throw n;}catch(m){h=m;c=3;break}case 6:try{f=g=k;f=f.reduce(function(a,b){a.push(b.name);return a},[]);a===b.m_lastSearchText&&b.__topicSearchFinished(f);c=4;break}catch(m){h=m;c=3;break}case 3:e=h,Logger.instance.error(e);case 4:c=-1;default:return{value:void 0,done:!0}}}var c=0,e,f,g,h,l,k={next:function(a){return d(0,
a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())};CWEPredictionOptions.prototype.__searchInLocalTopics=function(a){var b=[];a=a.toLowerCase();for(var d=0;d<this.m_allLocalTopicsListLowerCase.length;d++)-1!==this.m_allLocalTopicsListLowerCase[d].indexOf(a)&&b.push(this.m_allLocalTopicsList[d]);b.sort();this.__topicSearchFinished(b,!0)};
CWEPredictionOptions.prototype.topicsAvailable=function(a){this.m_allLocalTopicsList=a;this.m_allLocalTopicsListLowerCase=[];for(var b=0;b<a.length;b++)this.m_allLocalTopicsListLowerCase.push(a[b].toLowerCase())};CWEPredictionOptions.prototype.topicActivated=function(a){this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.__updateTopicUIState(a,!0)||this.__displayTopics();dji.ui.modalDlg.hideDlg()};
CWEPredictionOptions.prototype.topicDeactivated=function(a){this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[];this.__updateTopicUIState(a,!1)||this.__displayTopics();dji.ui.modalDlg.hideDlg()};CWEPredictionOptions.prototype.topicCreated=function(a,b){a&&0<a.length&&(this.m_cwePredictionEngine.getTopics(!0),this.m_activeTopicsList=this.m_cweSettings.topicsActive().slice()||[],this.__displayTopics());dji.ui.modalDlg.hideDlg()};
CWEPredictionOptions.prototype.__isEnglish=function(){return"US"===this.m_localeLang||"UK"===this.m_localeLang||"CAN"===this.m_localeLang||"BE"===this.m_localeLang};
CWEPredictionOptions.prototype.__topicSearchFinished=function(a,b){a&&0<a.length?(b?this.m_localTopics.show():this.m_wikiTopics.show(),this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-show-search-result").addClass("dji-cwu-reset")):b?this.m_localTopics.hide():this.m_wikiTopics.hide();b?(this.m_localTopics.empty(),this.m_localTopicsList=a||[]):(this.m_wikiTopics.empty(),this.m_wikiTopicsList=a||[]);if(a){0<this.m_localTopicsList.length?this.m_wikiTopics.addClass("dji-cwu-top-border"):
this.m_wikiTopics.removeClass("dji-cwu-top-border");b=b?this.m_localTopics:this.m_wikiTopics;for(var d=0;d<a.length;d++)b.append(jQuery("<div/>",{"class":"dji-cwu-topic-item",text:a[d],"dji-cwu-topic-index":d}))}else(0<this.m_wikiTopicsList.length||0<this.m_localTopicsList.length)&&this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-have-focus")};
CWEPredictionOptions.prototype.__localTopicSelected=function(a){this.__clearSearch();this.__topicIsActive(this.m_localTopicsList[a],!1)||(this.m_activeTopicsList.length<this.m_maxDisplayedTopics?(dji.ui.modalDlg.showMessageDlg("dji-cwu-activating-topic-message"),this.m_cwePredictionEngine.activateTopic(this.m_localTopicsList[a])):dji.ui.modalDlg.showModalDlg("dji-cwu-topic-active-limit"))};
CWEPredictionOptions.prototype.__wikiTopicSelected=function(a){this.__clearSearch();if(!this.m_cweBackgroundManager.isBusy()){this.m_selectedWikiTopicIndex=a;var b=this.__topicExists(this.m_wikiTopicsList[a]);if(this.m_maxDisplayedTopics<=this.m_activeTopicsList.length&&!this.__topicIsActive(this.m_wikiTopicsList[a],!0)){var d=this,c=function(c){c(!0);dji.ui.modalDlg.hideDlg();d.createTopic(d.m_wikiTopicsList[a],b,!1)};b?dji.ui.modalDlg.showModalDlg("dji-cwu-topic-update",{doneCallback:c}):dji.ui.modalDlg.showModalDlg("dji-cwu-topic-create",
{doneCallback:c})}else this.createTopic(this.m_wikiTopicsList[a],b,!0)}};
CWEPredictionOptions.prototype.createTopic=function(a,b,d){var c=this;return $jscomp.executeAsyncGenerator(function(){function e(e,g,k){for(;;)switch(f){case 0:c.m_cweBackgroundManager.updateTopicAsync(-1,{name:a,local:!1,userData:{action:b?"update":"create",activate:d,initiator:"options"}}),f=-1;default:return{value:void 0,done:!0}}}var f=0,g={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};CWEPredictionOptions.prototype.__buildDisplayTopicsList=function(){this.m_displayTopicList=this.m_cweBackgroundManager.displayTopics();this.m_displayTopicsMap={};for(var a=this.m_displayTopicList.length,b=0;b<a;b++){var d=this.m_displayTopicList[b];this.m_displayTopicsMap[d.name]=d}};
CWEPredictionOptions.prototype.__displayTopics=function(){this.__buildDisplayTopicsList();this.m_activeTopics.empty();for(var a=0;a<this.m_displayTopicList.length;a++){var b=this.m_displayTopicList[a],d=$(dji.templates.clone("dji-cwu-option-topic-dictionary"));d.find(".dji-cwu-option-item-label").text(b.name);d.find(".dji-cwu-switch-container").attr("dji-cwu-topic-dictionary-id",a);b.active&&d.find(".dji-cwu-switch-container").addClass("dji-cwu-on");d[0].topicIndex=a;this.m_activeTopics.append(d)}};
CWEPredictionOptions.prototype.__findUITopicIndex=function(a){for(var b=0;b<this.m_displayTopicList.length;b++)if(this.m_displayTopicList[b].name===a)return b;return-1};CWEPredictionOptions.prototype.__findUIElementWithTopicIndex=function(a){for(var b=this.m_activeTopics.children(),d=0;d<b.length;d++){var c=b[d];if(c.topicIndex===a)return c}return null};
CWEPredictionOptions.prototype.__updateTopicUIState=function(a,b){var d=this.__findUITopicIndex(a);if(-1===d)return!1;this.m_displayTopicList[d].active=b;this.m_displayTopicsMap[a].active=b;a=this.__findUIElementWithTopicIndex(d);if(null===a)return!1;b?$(a).find(".dji-cwu-switch-container").addClass("dji-cwu-on"):$(a).find(".dji-cwu-switch-container").removeClass("dji-cwu-on");return!0};
CWEPredictionOptions.prototype.__clearSearch=function(){this.m_lastSearchText="";this.m_topicsSearch.val("");$("body").removeClass("dji-cwu-search");this.m_topicsSearchContainer.attr("dji-cwu-view-mode","dji-cwu-default").removeClass("dji-cwu-reset")};CWEPredictionOptions.prototype.__topicExists=function(a){a=this.m_cwePredictionEngine.topicNameToDisplayName(a);for(var b=0;b<this.m_allLocalTopicsList.length;b++)if(this.m_allLocalTopicsList[b]===a)return!0;return!1};
CWEPredictionOptions.prototype.__topicIsActive=function(a,b){b&&(a=this.m_cwePredictionEngine.topicNameToDisplayName(a));return-1!==this.__activeTopicIndex(a)};CWEPredictionOptions.prototype.__activeTopicIndex=function(a){for(var b=0;b<this.m_activeTopicsList.length;b++)if(this.m_activeTopicsList[b]===a)return b;return-1};
