var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
function CWESpeechOptions(a,b,c){this.m_cweSettings=a;this.m_ttsEngine=b;this.m_cweBackgroundManager=c;this.m_voice=$("#dji-cwu-prediction-voice");this.m_rate=$("#dji-cwu-speak-rate");this.m_pitch=$("#dji-cwu-speak-pitch");this.m_volume=$("#dji-cwu-speak-volume");this.m_letters=$("#dji-cwu-speak-letters");this.m_words=$("#dji-cwu-speak-words");this.m_sentences=$("#dji-cwu-speak-sentences");this.m_demoMap={en:"Welcome to the CoWriter extension. You can change the pitch, rate, and volume of speech using the sliders below.",
es:"Bienvenido a la extensi\u00f3n Co Writer. Puede cambiar el tono, la frecuencia y el volumen del habla utilizando las diapositivas que aparecen a continuaci\u00f3n.",fr:"Bienvenue dans l'extension Co Writer. Vous pouvez modifier le pitch, le taux et le volume de la parole en utilisant les diapositives ci-dessous.",de:"Willkommen bei der Co-Writer-Erweiterung. Sie k\u00f6nnen die Tonh\u00f6he, die Rate und die Lautst\u00e4rke der Sprache mit den Folien unten \u00e4ndern."};this.__initialize();return this}
CWESpeechOptions.instance=null;
CWESpeechOptions.prototype.__initialize=function(){var a=this;this.m_voice.on("change",function(b){if(b.value!==a.m_cweSettings.speechVoice(b.value)){var c=$("[dji-cwu-template-id=dji-cwu-prediction-voice]");c.find("[dji-check]").removeAttr("dji-check");c.find("[dji-cwu-value='"+b.value+"']").attr("dji-check","");a.m_ttsEngine.stop();Logger.instance.log("change voice to:",b.value);b.noSave||a.m_cweSettings.speechVoice(b.value);a.__playDemo()}});this.m_rate.on("input change",function(b){a.m_ttsEngine.stop();
var c=Math.ceil(parseFloat(10*$(b.currentTarget).val()))-10;c=0===c?"default":0<c?"+"+c:""+c;$(b.currentTarget).closest(".dji-cwu-option-slider-item").find(".dji-cwu-slider-value").text(c);b.noSave||a.m_cweSettings.speechRate(parseFloat(a.m_rate.val()));b.hasOwnProperty("noSpeak")&&!1!==b.noSpeak||a.__playDemo()});this.m_pitch.on("input change",function(b){a.m_ttsEngine.stop();var c=Math.ceil(parseFloat(10*$(b.currentTarget).val()))-10;c=0===c?"default":0<c?"+"+c:""+c;$(b.currentTarget).closest(".dji-cwu-option-slider-item").find(".dji-cwu-slider-value").text(c);
b.noSave||a.m_cweSettings.speechPitch(parseFloat(a.m_pitch.val()));b.hasOwnProperty("noSpeak")&&!1!==b.noSpeak||a.__playDemo()});this.m_volume.on("input change",function(b){a.m_ttsEngine.stop();var c=parseFloat($(b.currentTarget).val());c=100*c+"%";$(b.currentTarget).closest(".dji-cwu-option-slider-item").find(".dji-cwu-slider-value").text(c);b.noSave||a.m_cweSettings.speechVolume(parseFloat(a.m_volume.val()));b.hasOwnProperty("noSpeak")&&!1!==b.noSpeak||a.__playDemo()});this.m_letters.on("change",
function(b){var c=b.checked;a.m_ttsEngine.stop();b.noSave||a.m_cweSettings.speechLetters(c?1:0)});this.m_words.on("change",function(b){var c=b.checked;a.m_ttsEngine.stop();b.noSave||a.m_cweSettings.speechWords(c?1:0)});this.m_sentences.on("change",function(b){var c=b.checked;a.m_ttsEngine.stop();b.noSave||a.m_cweSettings.speechSentences(c?1:0)});a.__load()};
CWESpeechOptions.prototype.__load=function(){if(this.m_cweSettings){var a=this.m_cweSettings.speechVoice();this.m_voice.innerHTML="";var b=!1,c=this.m_ttsEngine?this.m_ttsEngine.voicesForLanguage(this.m_cweBackgroundManager.localeLang()):[],e=this.m_ttsEngine.defaultVoiceForLanguage(this.m_cweBackgroundManager.localeLang(!0)),d=$("[dji-cwu-template-id=dji-cwu-prediction-voice]");d.empty();for(var f=$("[dji-cwu-template-id=dji-cwu-voice]"),g=0;g<c.length;g++){var h=CWEChromeUtilities.escapeHtml(c[g].name);
a===c[g].name&&(a=h,b=!0);var k=f.clone(!0);$(k).attr("dji-cwu-value",h);$(k).find(".dji-cwu-menu-item-text").text(h);d.append(k)}b||(a=e,this.m_cweSettings.speechVoice(e),this.m_ttsEngine.settings(this.m_cweSettings.speech()));this.m_voice.find(".dji-cwu-option-item-value").text(a);d.find("[dji-cwu-value='"+a+"']").attr("dji-check","");this.m_rate.val(this.m_cweSettings.speechRate()).trigger({type:"change",noSpeak:!0,noSave:!0});this.m_pitch.val(this.m_cweSettings.speechPitch()).trigger({type:"change",
noSpeak:!0,noSave:!0});this.m_volume.val(this.m_cweSettings.speechVolume()).trigger({type:"change",noSpeak:!0,noSave:!0});this.m_cweSettings.speechLetters()&&$(this.m_letters).addClass("dji-cwu-on");this.m_cweSettings.speechWords()&&$(this.m_words).addClass("dji-cwu-on");this.m_cweSettings.speechSentences()&&$(this.m_sentences).addClass("dji-cwu-on");Logger.instance.log(this.m_cweSettings)}};
CWESpeechOptions.prototype.__playDemo=function(){this.m_ttsEngine.settings(this.m_cweSettings.speech());this.m_ttsEngine.scheduleSpeak(this.m_demoMap[this.m_cweBackgroundManager.localeLang()],!0,200)};
