var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(m){c.reject(m)}};c.prototype.then=function(a,b){function e(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(u){f(u)}}:b}var d,f,g=new c(function(a,
b){d=a;f=b});this.callWhenSettled_(e(a,d),e(b,f));return g};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){g[b]=c;m--;0==m&&a(g)}}var g=[],m=0;do g.push(void 0),m++,d(e.value).callWhenSettled_(f(g.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(f,c)}f(a.next())})};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,d,e){$jscomp.initSymbolIterator();d=null!=d?d:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)b.push(d.call(e,f.value));else{f=a.length;for(var g=0;g<f;g++)b.push(d.call(e,a[g]))}return b}},"es6","es3");function CWEChromeUtilities(){return this}CWEChromeUtilities.addEventListener=function(a,b,d){a.hasOwnProperty(b)&&"function"==typeof d&&-1==a[b].indexOf(d)&&a[b].push(d)};
CWEChromeUtilities.removeEventListener=function(a,b,d){a.hasOwnProperty(b)&&"function"==typeof d&&(d=a[b].indexOf(d),-1!==d&&a[b].splice(d,1))};CWEChromeUtilities.callListeners=function(a,b){if(a&&a.hasOwnProperty(b)){var d=a[b];if(d&&0<d.length)for(var e=[].slice.call(arguments).splice(2),c=0;c<d.length;c++){var f=d[c];if(f)try{f.apply(this,e)}catch(g){Logger.instance.error(g)}}}};CWEChromeUtilities.callMethod=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}};
CWEChromeUtilities.checkInternetConnectionAvailable=function(a){var b=null,d=function(b){try{a(b)}catch(f){Logger.instance.error(f)}};if(navigator.onLine)try{var e=new XMLHttpRequest;e.open("HEAD","https://www.google.com/?random="+Math.random(),!0);e.onreadystatechange=function(){if(4===e.readyState&&0<e.status){var a=200<=e.status&&300>e.status||304===e.status;b&&clearTimeout(b);setTimeout(function(){d(a)},0)}};e.send();b=setTimeout(function(){e.abort();setTimeout(function(){d(!1)},0)},2E3)}catch(c){b&&
clearTimeout(b),d(!1)}else d(!1)};
CWEChromeUtilities.loadFile=function(a,b){return $jscomp.executeAsyncGenerator(function(){function d(d,p,t){for(;;)switch(e){case 0:try{return q=chrome.extension.getURL(a),e=3,{value:fetch(q),done:!1}}catch(h){k=h;e=1;break}case 3:try{if(1!=d){e=4;break}e=-1;throw t;}catch(h){k=h;e=1;break}case 4:try{m=r=p;l=void 0;if("text"!==b){e=5;break}e=7;return{value:m.text(),done:!1}}catch(h){k=h;e=1;break}case 7:try{if(1!=d){e=8;break}e=-1;throw t;}catch(h){k=h;e=1;break}case 8:try{l=n=p;e=6;break}catch(h){k=
h;e=1;break}case 5:try{if("json"!==b){e=9;break}e=11;return{value:m.json(),done:!1}}catch(h){k=h;e=1;break}case 11:try{if(1!=d){e=12;break}e=-1;throw t;}catch(h){k=h;e=1;break}case 12:try{l=g=p;e=10;break}catch(h){k=h;e=1;break}case 9:try{return e=13,{value:m.blob(),done:!1}}catch(h){k=h;e=1;break}case 13:try{if(1!=d){e=14;break}e=-1;throw t;}catch(h){k=h;e=1;break}case 14:try{l=f=p}catch(h){k=h;e=1;break}case 10:case 6:try{return e=-1,{value:l,done:!0}}catch(h){k=h;e=1;break}case 1:return c=k,Logger.instance.error(c),
e=-1,{value:void 0,done:!0};case 2:e=-1;default:return{value:void 0,done:!0}}}var e=0,c,f,g,n,l,m,r,q,k,p={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();p[Symbol.iterator]=function(){return this};return p}())};CWEChromeUtilities.isChromeOS=function(){return-1!=window.navigator.userAgent.indexOf("CrOS")};CWEChromeUtilities.isMacOS=function(){return-1!=window.navigator.userAgent.indexOf("Macintosh")};
CWEChromeUtilities.isWindowsOS=function(){return-1!=window.navigator.userAgent.indexOf("Windows")};CWEChromeUtilities.isLoginApp=function(){for(var a=[/.*login.*\.donjohnston\.net/,/.*login.*\.qadji\.com/,/.*login.*\.stagedji\.com/],b=window.location.hostname,d=0;d<a.length;d++)if(a[d].test(b))return!0;return!1};CWEChromeUtilities.isGoogleSearch=function(){var a=window.location.hostname.split(".");return 2!=a.length&&3!=a.length||"google"!==a[a.length-2]?!1:2==a.length||"www"===a[0]};
CWEChromeUtilities.isGoogleDocs=function(){return"docs.google.com"===window.location.hostname&&(window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i)||window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/edit/i))};CWEChromeUtilities.isGooglePresentation=function(){return"docs.google.com"===window.location.hostname&&(window.location.pathname.match(/^(\/a\/[^\/]+)?\/presentation\/d\//i)||window.location.pathname.match(/^(\/a\/[^\/]+)?\/presentation\/edit/i))};
CWEChromeUtilities.isGoogleMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.google.com")};CWEChromeUtilities.isYahooMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.yahoo.com")};CWEChromeUtilities.isMicrosoftMail=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"mail.live.com")};CWEChromeUtilities.isEvernote=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"evernote.com")};
CWEChromeUtilities.isFacebook=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"facebook.com")};CWEChromeUtilities.isTwitter=function(){return CWEChromeUtilities.stringEndsWith(window.location.hostname,"twitter.com")};CWEChromeUtilities.isIframeFree=function(){return CWEChromeUtilities.isGoogleMail()};CWEChromeUtilities.stringStartsWith=function(a,b){return 0===a.indexOf(b,0)};CWEChromeUtilities.stringEndsWith=function(a,b){return-1!==a.indexOf(b,a.length-b.length)};
CWEChromeUtilities.hostnameFromURL=function(a){return a.toString().replace(/^(.*\/\/[^\/?#]*).*$/,"$1")};
CWEChromeUtilities.jsonFromUrlQueryAndHash=function(a){if(!a)return null;try{var b=null,d=null;a=a.split("#");1==a.length?a=a[0]:2==a.length&&(d=a[1],a=a[0]);a=a.split("?");2==a.length&&(b=a[1]);if(b)for(key in b='{"'+b.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',b=JSON.parse(b),b)b.hasOwnProperty(key)&&(b[key]=decodeURIComponent(b[key]));if(d)for(key in d='{"'+d.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',d=JSON.parse(d),d)d.hasOwnProperty(key)&&(d[key]=decodeURIComponent(d[key]));return a=
{query:b,hash:d}}catch(e){Logger.instance.error(e)}return null};CWEChromeUtilities.htmlToAscii=function(a){return void 0===a||null===a||0==a.length?a:CWEChromeUtilities.htmlToAsciiTextArray(a).join("")};CWEChromeUtilities.latin1Table="AAAAAAACEEEEIIIIDNOOOOOXOUUUUYpbaaaaaaaceeeeiiiidnoooooxouuuuypy.......";
CWEChromeUtilities.wikiHtmlToAscii=function(a){if(!a)return"";a=CWEChromeUtilities.htmlToAsciiTextArray(a);for(var b=a.length,d=CWEChromeUtilities.latin1Table,e,c,f,g=0;g<b;g++)c=a[g],e=f=c.charCodeAt(0),"z"<e&&(c=".",192<e&&(c=d.charAt(e-192)),f=c.charCodeAt(0)),8203==f?c=" ":128<=f?c="=":"^"==c?c=" ":"\n"==c?c="\r":("?"==c||"["==c||"]"==c)&&g<b-1&&(e=a[g+1],"0"<=e&&"9">=e||"A"<=e&&"Z">=e||"a"<=e&&"z">=e)&&(c=" "),a[g]=c;return a=a.join("")};
CWEChromeUtilities.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};CWEChromeUtilities.escapeFileName=function(a){return a.replace(/\:/g,"_").replace(/\\/g,"_").replace(/\//g,"_").replace(/\&/g,"_").replace(/>/g,"_").replace(/</g,"_").replace(/"/g,"_").replace(/\|/g,"_").replace(/\*/g,"_").replace(/\?/g,"_")};
CWEChromeUtilities.indexOfElementInArray=function(a,b){if(a)for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1};CWEChromeUtilities.mapIsEmpty=function(a){if(a)for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};CWEChromeUtilities.findParagraph=function(a,b){return!a||b>a.length?null:CWEChromeUtilities.findToken(a,b,CWECharacterSet.paragraphSeparatorCharacterSet)};CWEChromeUtilities.findSentence=function(a,b){return!a||b>a.length?null:CWEChromeUtilities.findToken(a,b,CWECharacterSet.sentenceSeparatorCharacterSet)};
CWEChromeUtilities.findWord=function(a,b){return!a||b>a.length?null:CWEChromeUtilities.findToken(a,b,CWECharacterSet.wordSeparatorCharacterSet)};CWEChromeUtilities.findToken=function(a,b,d){if(b>a.length||null==d)return null;var e;for(e=b;0<=e;e--)if(d.characterIsMember(a.charAt(e))){e++;break}for(;b<a.length;b++)if(d.characterIsMember(a.charAt(b))){b--;break}0>e&&(e=0);d=null;e<=b&&(d=a.slice(e,b+1));return d};
CWEChromeUtilities.elementHasParent=function(a,b){for(;a&&a!==b;)a=a.parentElement;return a===b};CWEChromeUtilities.addClassToElement=function(a,b){a&&b&&(a=a.classList,a.contains(b)||a.add(b))};CWEChromeUtilities.removeClassFromElement=function(a,b){a&&b&&(a=a.classList,a.contains(b)&&a.remove(b))};CWEChromeUtilities.elementHasClass=function(a,b){return a&&b?a.classList.contains(b):!1};
CWEChromeUtilities.extractVisibleTextFromElement=function(a){if(!a)return"";if(3==a.nodeType)return a.textContent;var b="",d=null;for(a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(a){var c=a.id?a.id.toLowerCase():"";if(3==a.nodeType)return NodeFilter.FILTER_ACCEPT;if("SCRIPT"==a.tagName||"NOSCRIPT"==a.tagName||"IMG"==a.tagName||"SELECT"==a.tagName||"INPUT"==a.tagName&&(!a.type||"text"!=a.type.toLowerCase())||"dexcontrolscontainer"==c||"dexcontrolscontainermeasurement"==
c||"__dji_cwe_body_overlay"==c||"__dji_cwe_measurement_window_generic"==c||"__dji_cwe_chrome_google_docs_proxy"==c||"__dji_cwe_measurement_window"==c||"__dji_cwe_shortcuts"==c||"__dji_cwe_measurement_window_generic"==c||"none"==document.defaultView.getComputedStyle(a,null).getPropertyValue("display"))return NodeFilter.FILTER_REJECT;"SPAN"!=a.tagName&&(b+="\n");return NodeFilter.FILTER_ACCEPT},!0);d=a.nextNode();)3==d.nodeType?b+=" "+d.textContent:1==d.nodeType&&"TEXTAREA"==d.tagName&&(b+="\n"+d.value+
"\n");return b};CWEChromeUtilities.findValidDocumentElements=function(a,b){a=a.getElementsByTagName("iframe");for(var d=0;d<a.length;d++){var e=a[d];CWEChromeUtilities.validateIframe(e)&&null!==e.contentDocument&&(b.push(e.contentDocument),CWEChromeUtilities.findValidDocumentElements(e.contentDocument,b))}};
CWEChromeUtilities.findValidIframeElements=function(a,b,d){a=(a||document).getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var c=a[e];CWEChromeUtilities.validateIframe(c,d)&&null!==c.contentDocument&&(b.push(c),CWEChromeUtilities.findValidIframeElements(c.contentDocument,b,d))}};
CWEChromeUtilities.validateIframe=function(a,b){b=!0;try{if(void 0===a.src||null===a.src)return!1;var d=a.getAttribute("id");if("__dji_sru_templates"===d||!b&&d&&0<=d.indexOf("dji_sru"))return!1;b=null;var e=a.src.split("/")[2];if(void 0!==e&&null!==e&&-1===e.indexOf(document.domain))return!1;b=a.contentDocument;return null!==b&&void 0!==b}catch(c){}return!1};
CWEChromeUtilities.getScrollbarSize=function(){if(void 0===CWEChromeUtilities.getScrollbarSize.__scrollbarSize){var a=document.createElement("div");a.style.visibility="hidden";a.style.position="fixed";a.style.left="-5000px";a.style.width="-5000px";a.style.height="200px";a.style.height="200px";a.style.overflow="scroll";document.body.appendChild(a);var b={width:a.offsetWidth-a.clientWidth,height:a.offsetHeight-a.clientHeight};a.parentNode.removeChild(a);CWEChromeUtilities.getScrollbarSize.__scrollbarSize=
b}return CWEChromeUtilities.getScrollbarSize.__scrollbarSize};CWEChromeUtilities.generateUUID=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var d=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?d:d&7|8).toString(16)})};CWEChromeUtilities.blobToText=function(a,b){if(a){var d=new FileReader;d.onloadend=function(){b(d.result)};d.onerror=function(a){b(null)};d.readAsText(a)}else b(null)};
CWEChromeUtilities.convertFontPercentageToPixels=function(a){switch(a){case 0:return 13;case 20:return 16;case 40:return 20;case 60:return 24;case 80:return 32;case 100:return 48;default:return 16}};CWEChromeUtilities.convertFontPercentageToFontSize=function(a){switch(a){case 0:return 2;case 20:return 3;case 40:return 4;case 60:return 5;case 80:return 6;case 100:return 7;default:return 4}};CWEChromeUtilities.convertGuessPercentageToPixels=function(a){return parseInt(10+38*a/100)};
CWEChromeUtilities.convertMarginsPercentageToPixels=function(a){return parseInt(0+80*a/100)};
CWEChromeUtilities.htmlToAsciiTextArray=function(a){if(void 0===a||null===a)return null;if(0==a.length)return[];for(var b=a.length,d=Array(b),e=0;e<b;e++){var c=a.charAt(e),f=a.charCodeAt(e);switch(f){case 160:c=" ";break;case 216:case 248:case 510:case 511:c="0";break;case 451:c="!";break;case 192:case 193:case 194:case 195:case 196:case 197:case 198:case 256:case 258:case 260:case 461:case 478:case 480:case 482:case 506:case 508:case 512:case 514:case 550:c="A";break;case 224:case 225:case 226:case 227:case 228:case 229:case 230:case 257:case 259:case 261:case 462:case 479:case 481:case 483:case 507:case 509:case 513:case 515:case 551:c=
"a";break;case 199:case 262:case 264:case 266:case 268:c="C";break;case 231:case 263:case 265:case 267:case 269:c="c";break;case 208:case 270:case 272:c="D";break;case 271:case 273:c="d";break;case 200:case 201:case 202:case 203:case 274:case 276:case 278:case 280:case 282:case 516:case 518:case 552:c="E";break;case 232:case 233:case 234:case 235:case 275:case 277:case 279:case 281:case 283:case 517:case 519:case 553:c="e";break;case 284:case 286:case 288:case 290:case 484:case 486:case 500:c="G";
break;case 285:case 287:case 289:case 291:case 485:case 487:case 501:c="g";break;case 292:case 294:case 502:c="H";break;case 293:case 295:c="h";break;case 204:case 205:case 206:case 207:case 296:case 298:case 300:case 302:case 304:case 463:case 520:case 522:c="I";break;case 236:case 237:case 238:case 239:case 297:case 299:case 301:case 303:case 305:case 464:case 521:case 523:c="i";break;case 308:c="J";break;case 309:c="j";break;case 310:case 488:c="K";break;case 311:case 312:case 489:c="k";break;
case 313:case 315:case 317:case 319:case 321:c="L";break;case 314:case 316:case 318:case 320:case 322:c="l";break;case 209:case 323:case 325:case 327:case 330:case 504:c="N";break;case 240:case 241:case 324:case 326:case 328:case 329:case 331:case 505:c="n";break;case 210:case 211:case 212:case 213:case 214:case 332:case 334:case 336:case 465:case 490:case 492:case 524:case 526:case 554:case 556:case 558:case 560:c="O";break;case 242:case 243:case 244:case 245:case 246:case 333:case 335:case 337:case 466:case 491:case 493:case 525:case 527:case 555:case 557:case 559:case 561:c=
"o";break;case 340:case 342:case 344:case 528:case 530:c="R";break;case 341:case 343:case 345:case 529:case 531:c="r";break;case 346:case 348:case 350:case 352:case 536:c="S";break;case 347:case 349:case 351:case 353:case 537:case 223:c="s";break;case 354:case 356:case 358:case 538:c="T";break;case 355:case 357:case 359:case 539:c="t";break;case 217:case 218:case 219:case 220:case 360:case 362:case 364:case 366:case 368:case 370:case 467:case 469:case 471:case 473:case 475:case 532:case 534:c="U";
break;case 249:case 250:case 251:case 252:case 361:case 363:case 365:case 367:case 369:case 371:case 468:case 470:case 472:case 474:case 476:case 533:case 535:c="u";break;case 372:c="W";break;case 373:c="w";break;case 221:case 374:case 376:case 562:c="Y";break;case 253:case 254:case 255:case 375:case 563:c="y";break;case 377:case 379:case 381:case 548:c="Z";break;case 378:case 380:case 382:case 549:c="z";break;case 8211:c="-";break;case 8216:case 8217:c="'";break;case 8220:case 8221:c='"';break;case 8230:c=
".";break;default:if(10!=f&&13!=f&&0<=f&&31>=f||127<=f&&8203!=f)c=" "}d[e]=c}return d};
CWEChromeUtilities.htmlToUnicodeTextArray=function(a){if(void 0===a||null===a)return null;if(0==a.length)return[];for(var b=a.length,d=Array(b),e=0;e<b;e++){var c=a.charAt(e),f=a.charCodeAt(e);switch(f){case 160:case 8203:c=" ";break;case 216:case 248:case 510:case 511:c="0";break;case 451:c="!";break;case 8211:c="-";break;case 8216:case 8217:c="'";break;case 8220:case 8221:c='"';break;case 8230:c=".";break;default:10!=f&&13!=f&&0<=f&&31>=f?c=" ":32767<f&&(c=" ")}d[e]=c}return d};
CWEChromeUtilities.htmlToUnicode=function(a){return void 0===a||null===a||0==a.length?a:CWEChromeUtilities.htmlToUnicodeTextArray(a).join("")};CWEChromeUtilities.capsState=function(a){if(0<a.length&&a[0]===a[0].toUpperCase()){if(1===a.length)return"FIRSTCAPS";for(var b=1;b<a.length;b++)if(a[b]!==a[b].toUpperCase())return"FIRSTCAPS";return"ALLCAPS"}return"NOCAPS"};
CWEChromeUtilities.setCapsState=function(a,b){return"FIRSTCAPS"===b?a=a[0].toUpperCase()+a.slice(1).toLowerCase():"ALLCAPS"===b?a.toUpperCase():a.toLowerCase()};CWEChromeUtilities.titleFromPage=function(a){var b=document.title||"";if(0>=b.length){var d=document.querySelector('meta[name="DC.title"]');d||(d=document.querySelector('meta[name="dji-document-title"]'));d&&(b=d.getAttribute("content")||"")}a&&(b=CWEChromeUtilities.htmlToAscii(b));return b=b.trim()};
CWEChromeUtilities.titleForTopic=function(a){var b="",d=[],e=!!a.useAscii;if(a.usePageTitle){var c=CWEChromeUtilities.titleFromPage().replace(/\W/g," ");e&&(c=CWEChromeUtilities.htmlToAscii(c));c=c.trim();0<c.length&&(c=c.split(/\s/).filter(function(a){return!!(a&&0<a.length)}),0<c.length&&d.push.apply(d,[].concat($jscomp.arrayFromIterable(c))))}if(a.text&&0<a.text.length&&(a.combine||0>=d.length)){c=a.text.split(/[\r\n]/);for(var f=0;f<c.length;f++){var g=e?CWEChromeUtilities.htmlToAscii(c[f]).replace(/\W/g,
" ").trim():c[f].replace(/\W/g," ").trim();if(g&&0<g.length&&(g=g.split(/\s/).filter(function(a){return!!(a&&0<a.length)}),0<g.length)){0<d.length&&d.push("-");d.push.apply(d,[].concat($jscomp.arrayFromIterable(g)));break}}}if(0<d.length)for(a=isNaN(a.maxLength)||0>=a.maxLength?34:a.maxLength,e=0;e<d.length&&b.length<a;e++)if(c=d[e],f=0<b.length?1:0,b.length+f+c.length<=a)0<f&&(b+=" "),b+=c;else if(0>=b.length)b=c.substr(0,a);else break;return b};
CWEChromeUtilities.registerService=function(a,b,d){return $jscomp.executeAsyncGenerator(function(){function e(e,k,u){for(;;)switch(c){case 0:return c=1,{value:CWEChromeUtilities.sha256(a),done:!1};case 1:if(1!=e){c=2;break}c=-1;throw u;case 2:r=q=k,m=3E4,l=Date.now(),n=void 0,g=function(){var c=Date.now();m<c-l&&(clearInterval(n),window.removeEventListener("message",f,!0),d({success:!1}));(b?window.top:window.parent).postMessage({message:"com.donjohnston.cwu.service.available",timestamp:c,service:a,
checksum:r},"*")},f=function(b){b.data&&b.data.hasOwnProperty("message")&&"com.donjohnston.cwu.service.available.ack"===b.data.message&&b.data.checksum===r&&(clearInterval(n),window.removeEventListener("message",f,!0),d({success:!0,messageProxy:new MessageProxy("framePreloader::"+a,{wnd:b.source,port:b.ports[0]})}))},window.addEventListener("message",f,!0),n=setInterval(g,2E3),g(),c=-1;default:return{value:void 0,done:!0}}}var c=0,f,g,n,l,m,r,q,k={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())};
CWEChromeUtilities.sha256=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,l,q){for(;;)switch(d){case 0:return n=(new TextEncoder("utf-8")).encode(a),d=1,{value:crypto.subtle.digest("SHA-256",n),done:!1};case 1:if(1!=b){d=2;break}d=-1;throw q;case 2:return f=g=l,c=Array.from(new Uint8Array(f)),e=c.map(function(a){return("00"+a.toString(16)).slice(-2)}).join(""),d=-1,{value:e,done:!0};default:return{value:void 0,done:!0}}}var d=0,e,c,f,g,n,l={next:function(a){return b(0,a,void 0)},
throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();l[Symbol.iterator]=function(){return this};return l}())};CWEChromeUtilities.createLastErrorHandler=function(){if(Logger.instance===console){var a=Error().stack;return function(){chrome.runtime.lastError&&Logger.instance.error(chrome.runtime.lastError.message,"\nStack:",a)}}return CWEChromeUtilities.checkLastError};
CWEChromeUtilities.checkLastError=function(){chrome.runtime.lastError&&Logger.instance.error(chrome.runtime.lastError.message,"\nStack:",Error().stack)};
