var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,e){a!=Array.prototype&&a!=Object.prototype&&(a[c]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,c,e,g){if(c){e=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var d=a[g];d in e||(e[d]={});e=e[d]}a=a[a.length-1];g=e[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function e(b){return b instanceof d?b:new d(function(f,a){f(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};c.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var g=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){g(b,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var f=0;f<b.length;++f){var a=b[f];delete b[f];try{a()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};c.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(h){a.reject(h)}};d.prototype.createResolveAndReject_=
function(){function b(b){return function(f){h||(h=!0,b.call(a,f))}}var a=this,h=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(h){this.reject_(h);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,f=0;f<a.length;++f)a[f].call(),a[f]=null;this.onSettledCallbacks_=null}};var l=new c;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,d){var b=this.createResolveAndReject_();try{a.call(d,b.resolve,b.reject)}catch(k){b.reject(k)}};d.prototype.then=function(a,f){function b(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(m){e(m)}}:b}var c,e,g=new d(function(a,
b){c=a;e=b});this.callWhenSettled_(b(a,c),b(f,e));return g};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,d){function b(){switch(c.state_){case 1:a(c.result_);break;case 2:d(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?l.asyncExecute(b):this.onSettledCallbacks_.push(function(){l.asyncExecute(b)})};d.resolve=e;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
c){for(var d=$jscomp.makeIterator(a),f=d.next();!f.done;f=d.next())e(f.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?e([]):new d(function(a,d){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,e(c.value).callWhenSettled_(f(g.length-1),d),c=b.next();while(!c.done)})};return d},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function c(c){return a.next(c)}function e(c){return a.throw(c)}return new Promise(function(g,d){function l(a){a.done?g(a.value):Promise.resolve(a.value).then(c,e).then(l,d)}l(a.next())})};window.dji=window.dji||{};window.dji.cwe=window.dji.cwe||{};
(function(a){var c={};a.loadSvgData=function(a,g){return $jscomp.executeAsyncGenerator(function(){function d(d,k,l){for(;;)switch(e){case 0:h=null;if(f=c[a]){e=1;break}e=3;return{value:CWEChromeUtilities.loadFile(a,"text"),done:!1};case 3:if(1!=d){e=4;break}e=-1;throw l;case 4:if(h=b=k){e=5;break}e=-1;return{value:null,done:!0};case 5:f={"@":h};c[a]=f;e=2;break;case 1:h=f["@"];case 2:if(!f.hasOwnProperty(g)){e=6;break}h=f[g];e=-1;return{value:h,done:!0};case 6:return h=h.replace(/^<svg fill=\"[^\"]*\"/g,
'<svg fill="'+g+'"'),h="data:image/svg+xml;base64,"+btoa(h),f[g]=h,e=-1,{value:h,done:!0};default:return{value:void 0,done:!0}}}var e=0,b,f,h,k={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())};a.cacheSvgData=function(c){a.loadSvgData("Graphics/ic_mic_off_black_24px.svg",c);a.loadSvgData("Graphics/ic_mic_black_24px.svg",c)}})(window.dji.cwe.resourceProxy=
window.dji.cwe.resourceProxy||{});
