var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
var MessageProxy=function(b,a){var c=this;this.m_name=b||void 0;this.m_uuid=""+1E17*Math.random()+1E17*Math.random();this.m_service=a.service||void 0;this.m_wnd=a.wnd||void 0;this.m_port=a.port||void 0;this.m_enableWindowMessages=!!a.enableWindowMessages;this.m_messageId=0;this.m_postMessages={};this.m_messageDelegates={};this.m_messageHandler=function(a){c.__onMessage(this,a)};this.m_unloadHandler=function(a){c.__notifyDisconnect()};this.m_defaultMessageDelegate=a.defaultMessageDelegate||void 0;
window.addEventListener("unload",this.m_unloadHandler)};MessageProxy.prototype.enable=function(b){b?(this.m_enableWindowMessages&&this.m_wnd&&window.addEventListener("message",this.m_messageHandler,!0),this.m_port&&(this.m_port.addEventListener("message",this.m_messageHandler,!0),this.m_port.start())):(this.m_port&&this.m_port.removeEventListener("message",this.m_messageHandler,!0),this.m_enableWindowMessages&&this.m_wnd&&window.removeEventListener("message",this.m_messageHandler,!0))};
MessageProxy.prototype.disconnect=function(){this.__onDisconnect()};MessageProxy.prototype.on=function(b,a){if(b&&"function"===typeof a&&(!this.m_messageRegExp||this.m_messageRegExp.test(b))){var c=this.m_messageDelegates.hasOwnProperty(b)?this.m_messageDelegates[b]:void 0;c||(c=[],this.m_messageDelegates[b]=c);c.push(a)}};
MessageProxy.prototype.send=function(b,a){if(this.windowIsClosed||!this.m_port&&!this.m_enableWindowMessages)a&&a(Error(503));else{var c={message:b,messageId:this.m_uuid+"/"+ ++this.m_messageId,timestamp:Date.now()};2<arguments.length&&(c.arguments=[].slice.call(arguments).splice(2));this.m_port?this.m_port.postMessage(c):this.m_enableWindowMessages&&this.m_wnd.postMessage(c,"*");a&&"function"===typeof a&&(this.m_postMessages[c.messageId]={message:b,callback:a})}};
MessageProxy.prototype.respond=function(b,a,c){this.windowIsClosed||!this.m_port&&!this.m_enableWindowMessages||(b={message:b,messageId:this.m_uuid+"/"+ ++this.m_messageId,timestamp:Date.now(),responseFor:a,result:c},this.m_port?this.m_port.postMessage(b):this.m_enableWindowMessages&&this.m_wnd.postMessage(b,"*"))};MessageProxy.prototype.ping=function(){this.send(MessageProxy.MSG_SRV_PING)};
MessageProxy.prototype.__onMessage=function(b,a){if(!(!a.source&&!a.currentTarget||a.source&&a.source!==this.m_wnd||a.currentTarget&&a.currentTarget!==this.m_port)&&a.data&&a.data.hasOwnProperty("message")&&a.data.hasOwnProperty("messageId")&&(!this.m_messageRegExp||this.m_messageRegExp.test(a.data.message)))if(b=void 0,a.data.responseFor&&this.m_postMessages.hasOwnProperty(a.data.responseFor)&&(b=this.m_postMessages[a.data.responseFor],delete this.m_postMessages[a.data.messageId]),b)a.data.hasOwnProperty("result")?
b.callback.apply(this,[a.data.result]):b.callback.apply(this);else{if(a.data.message===MessageProxy.MSG_SRV_PING)return this.__onPing();if(a.data.message===MessageProxy.MSG_SRV_DISCONNECT)try{this.__onDisconnect()}catch(d){Logger.instance.error(d)}if(this.m_messageDelegates.hasOwnProperty(a.data.message)){b=this.m_messageDelegates[a.data.message];for(var c=0;c<b.length;c++)try{b[c].apply(this,[a.data.messageId].concat(a.data.arguments||[]))}catch(d){Logger.instance.error(d)}}else this.m_defaultMessageDelegate&&
this.m_defaultMessageDelegate(a)}};MessageProxy.prototype.__onPing=function(){this.send(MessageProxy.MSG_SRV_PONG)};MessageProxy.prototype.__onDisconnect=function(){this.enable(!1);this.m_port=this.m_wnd=void 0};MessageProxy.prototype.__notifyDisconnect=function(){window.removeEventListener("unload",this.m_unloadHandler);this.send(MessageProxy.MSG_SRV_DISCONNECT);this.enable(!1);this.m_port=this.m_wnd=void 0};
$jscomp.global.Object.defineProperties(MessageProxy.prototype,{service:{configurable:!0,enumerable:!0,get:function(){return this.m_service}},window:{configurable:!0,enumerable:!0,get:function(){return this.m_wnd}},windowIsClosed:{configurable:!0,enumerable:!0,get:function(){try{return this.m_wnd.closed}catch(b){}return!1}}});MessageProxy.MSG_SRV_AVAILABLE="com.donjohnston.cwu.service.available";MessageProxy.MSG_SRV_AVAILABLE_ACK="com.donjohnston.cwu.service.available.ack";
MessageProxy.MSG_SRV_DISCONNECT="com.donjohnston.cwu.service.disconnect";MessageProxy.MSG_SRV_PING="com.donjohnston.cwu.service.ping";MessageProxy.MSG_SRV_PONG="com.donjohnston.cwu.service.pong";
