window.dji=window.dji||{};
(function(c){function k(a){a.stopPropagation()}function n(a){a.preventDefault();a.stopPropagation()}var h=null,f=null;c.os=function(){h||(h={chrome:-1!=window.navigator.userAgent.indexOf("CrOS"),mac:-1!=window.navigator.userAgent.indexOf("Macintosh"),windows:-1!=window.navigator.userAgent.indexOf("Windows")},h.name=h.chrome?"chrome":h.mac?"mac":"windows");return h};c.browser=function(){if(!f){var a={},b=window.navigator.userAgent;/edge/i.test(b)?a.edge=!0:/trident/i.test(b)?a.ie=!0:/msie/i.test(b)?
a.ie=!0:/firefox/i.test(b)?a.firefox=!0:/chrome/i.test(b)?a.chrome=!0:/safari/i.test(b)&&(a.safari=!0);f=a}return f};c.loadFile=function(a,b){try{var d=new XMLHttpRequest,e=browserEngine.extension.getURL(a);d.open("GET",e,!!b);b&&(d.onreadystatechange=function(){d.readyState===XMLHttpRequest.DONE&&0<d.status&&b(d.responseText)});d.send();if(!b)return d.responseText}catch(l){Logger.instance.error(l)}};c.getMetadata=function(){try{var a={},b=document.querySelector("title"),d=document.querySelector("meta[name='DC.title'"),
e=d?d.getAttribute("content"):null;a.title=(b?b.innerText:e)||"";b=[];var c=document.querySelector("meta[name='author'");d="";if(c&&""!==c.getAttribute("content"))d=c.getAttribute("content");else{var g=document.querySelector("meta[name='DC.contributor'");g&&(d=g.getAttribute("content"))}if(""!=d){var f=d.split(" ");1<f.length?b.push({given:f.slice(0,f.length-1).join(" "),family:f[f.length-1]}):c?b.push({given:"",family:d}):b.push({given:d,family:""})}a.author=b;var m=document.querySelector("meta[name='date'")||
document.querySelector("meta[name='DC.created'"),h=m?m.getAttribute("content"):(new Date(Date.now())).getFullYear(),k=/[0-9]{4,4}/.exec(h);0<k.length&&(a.issued={},a.issued["date-parts"]=[[k]]);h=new Date(Date.now());var n=h.getMonth()+1,v=h.getDate();k=h.getFullYear();a.accessed={};a.accessed["date-parts"]=[[k,n,v]];var r=document.querySelector("meta[name='medium'");r&&(a.medium=r.getAttribute("content"));var t=window.location.pathname;a.URL=this.isSruPdf()?t.slice(1,t.length):window.location.href;
var u=a.URL.split("://")[1];if(u){var q=u.split("www.");a["container-title"]=1==q.length?q[0].split("/")[0]:q[1].split("/")[0]}return a}catch(w){Logger.instance.error(w)}return null};c.getSourcesFromXML=function(a){var b=[];a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("entry");for(var d=0;d<a.length;d++){for(var e={},c=0;c<a[d].childNodes.length;c++){var g=a[d].childNodes[c];switch(g.nodeName){case "title":e.title=g.textContent;break;case "content":e.citation={};e.citation.all=
g.textContent;g=(new DOMParser).parseFromString("<content>"+g.textContent+"</content>","text/xml").getElementsByTagName("p");for(var f=0;f<g.length;f++){var m=g[f].innerHTML;switch(g[f].getAttribute("class")){case "citation_style_APA":e.citation.APA=m;break;case "citation_style_MLA":e.citation.MLA=m;break;case "citation_style_CHICAGO":e.citation.CHICAGO=m;break;case "citation_style_HARVARD":e.citation.CHICAGO=m;break;case "citation_style_TURABIAN":e.citation.HARVARD=m}}break;case "author":e.authors=
g.childNodes[1].textContent;break;case "id":e.linkCatalog=g.textContent;break;case "oclcterms:recordIdentifier":e.recordId=g.textContent}}b.push(e)}return b};c.addEventListener=function(a,b,d){a.hasOwnProperty(b)&&"function"==typeof d&&-1==a[b].indexOf(d)&&a[b].push(d)};c.removeEventListener=function(a,b,d){a.hasOwnProperty(b)&&"function"==typeof d&&(d=a[b].indexOf(d),-1!==d&&a[b].splice(d,1))};c.callListeners=function(a,b){if(a&&a.hasOwnProperty(b)){var d=a[b];if(d&&0<d.length)for(var e=[].slice.call(arguments).splice(2),
c=0;c<d.length;c++){var g=d[c];if(g)try{g.apply(this,e)}catch(p){Logger.instance.error(p)}}}};c.callMethod=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}};c.checkInternetConnectionAvailable=function(a){var b=null,d=function(b){try{a(b)}catch(g){Logger.instance.error(g)}};if(navigator.onLine)try{var e=new XMLHttpRequest;e.open("HEAD","https://www.google.com/?random="+Math.random(),!0);e.onreadystatechange=function(){if(4===e.readyState&&0<e.status){var a=
200<=e.status&&300>e.status||304===e.status;b&&clearTimeout(b);setTimeout(function(){d(a)},0)}};e.send();b=setTimeout(function(){e.abort();setTimeout(function(){d(!1)},0)},2E3)}catch(l){b&&clearTimeout(b),d(!1)}else d(!1)};c.isChromeOS=function(){return-1!=window.navigator.userAgent.indexOf("CrOS")};c.isMacOS=function(){return-1!=window.navigator.userAgent.indexOf("Macintosh")};c.isWindowsOS=function(){return-1!=window.navigator.userAgent.indexOf("Windows")};c.isLoginApp=function(){for(var a=[/.*login.*\.donjohnston\.net/,
/.*login.*\.qadji\.com/,/.*login.*\.stagedji\.com/,/.*login.*\.codeiasi\.net/],b=window.location.hostname,d=0;d<a.length;d++)if(a[d].test(b))return!0;return!1};c.isGoogleSearch=function(){var a=window.location.hostname.split(".");return 2!=a.length&&3!=a.length||"google"!==a[a.length-2]?!1:2==a.length||"www"===a[0]};c.isGoogleDocs=function(){if("docs.google.com"!==window.location.hostname)return!1;var a=window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i);a||(a=window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/edit/i));
return null!==a&&void 0!==a&&0<a.length};c.isGoogleDocsEditor=function(a,b){if(!a||!b&&!c.isGoogleDocs())return!1;if("IFRAME"==a.tagName)return c.elementHasClass(a,"docs-texteventtarget-iframe");for(;a;){if(c.elementHasClass(a,"kix-appview-editor"))return!0;a=a.parentElement}return!1};c.isGoogleHangouts=function(){return"talkgadget.google.com"===window.location.hostname};c.isGoogleMail=function(){return c.stringEndsWith(window.location.hostname,"mail.google.com")};c.isYahooMail=function(){return c.stringEndsWith(window.location.hostname,
"mail.yahoo.com")};c.isMicrosoftMail=function(){return c.stringEndsWith(window.location.hostname,"mail.live.com")};c.isEvernote=function(){return c.stringEndsWith(window.location.hostname,"evernote.com")};c.isFacebook=function(){return c.stringEndsWith(window.location.hostname,"facebook.com")};c.isTwitter=function(){return c.stringEndsWith(window.location.hostname,"twitter.com")};c.isSru=function(){return c.stringStartsWith(window.location.href,"chrome-extension://"+browserEngine.runtime.id)};c.isSruPdf=
function(){return c.stringStartsWith(window.location.href,"chrome-extension://"+browserEngine.runtime.id)};c.isBookshareBook=function(){if("bookshare-reader.s3.amazonaws.com"!==window.location.hostname)return!1;var a=window.location.search.match(/[\?\&]book=/i);return null!==a&&void 0!==a&&0<a.length};c.isAmazonKindle=function(){return c.stringEndsWith(window.location.hostname,"read.amazon.com")};c.isIframeFree=function(){return c.isGoogleMail()};c.stringStartsWith=function(a,b){return 0===a.indexOf(b,
0)};c.stringEndsWith=function(a,b){return-1!==a.indexOf(b,a.length-b.length)};c.addLeadingZero=function(a,b){var d="0000000000"+a;return d.substr(d.length-Math.max(String(a).length,b||2))};c.hostnameFromURL=function(a){return a.toString().replace(/^(.*\/\/[^\/?#]*).*$/,"$1")};c.paramsFromUrlQueryAndHash=function(a){if(!a)return null;try{var b=null,d=null;a=a.split("#");1===a.length?a=a[0]:2===a.length&&(d=a[1],a=a[0]);a=a.split("?");2===a.length&&(b=a[1]);if(b){var e=b.split(/[=&]/);b=void 0;if(0===
e.length%2){b={};for(var c=0;c<e.length;c+=2)b[e[c]]=decodeURIComponent(e[c+1])}}if(d){var g=d.split(/[=&]/);d=void 0;if(0===g.length%2)for(d={},e=0;e<g.length;e+=2)d[g[e]]=decodeURIComponent(g[e+1])}return a={query:b,hash:d}}catch(p){Logger.instance.error(p)}return null};c.jsonFromUrlQueryAndHash=function(a){if(!a)return null;try{var b=null,d=null;a=a.split("#");1==a.length?a=a[0]:2==a.length&&(d=a[1],a=a[0]);a=a.split("?");2==a.length&&(b=a[1]);if(b)for(key in b='{"'+b.replace(/&/g,'", "').replace(/=/g,
'": "')+'"}',b=JSON.parse(b),b)b.hasOwnProperty(key)&&(b[key]=decodeURIComponent(b[key]));if(d)for(key in d='{"'+d.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',d=JSON.parse(d),d)d.hasOwnProperty(key)&&(d[key]=decodeURIComponent(d[key]));return a={query:b,hash:d}}catch(e){Logger.instance.error(e)}return null};c.htmlToAscii=function(a,b){return void 0===a||null===a||0==a.length?a:c.htmlToAsciiTextArray(a,b).join("")};c.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};c.escapeFileName=function(a){return a.replace(/\:/g,"_").replace(/\\/g,"_").replace(/\//g,"_").replace(/\&/g,"_").replace(/>/g,"_").replace(/</g,"_").replace(/"/g,"_").replace(/\|/g,"_").replace(/\*/g,"_").replace(/\?/g,"_")};c.objectsAreEqual=function(a,b){if(a===b)return!0;if(null===a||void 0===a||null===b||void 0===b||typeof a!==typeof b||"string"==typeof a||"number"==typeof a)return!1;if(a instanceof Array||b instanceof Array){if(!(a instanceof
Array&&b instanceof Array)||a.length!=b.length)return!1;for(var d=0;d<a.length;d++)if(!c.objectsAreEqual(a[d],b[d]))return!1;return!0}for(var e,l=0;2>l;l++){for(d in a)if(a.hasOwnProperty(d)&&(!b.hasOwnProperty(d)||!c.objectsAreEqual(a[d],b[d])))return!1;e=a;a=b;b=e}return!0};c.indexOfElementInArray=function(a,b){if(a)for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1};c.findParagraph=function(a,b){return!a||b>a.length?null:c.findToken(a,b,dji.charSet.paragraphSeparator)};c.findSentence=function(a,
b){return!a||b>a.length?null:c.findToken(a,b,dji.charSet.sentenceSeparator)};c.findWord=function(a,b){return!a||b>a.length?null:c.findToken(a,b,dji.charSet.wordSeparator)};c.findToken=function(a,b,d){if(b>a.length||null==d)return null;var e;for(e=b;0<=e;e--)if(d.characterIsMember(a.charAt(e))){e++;break}0>e&&(e=0);d=null;e<=b&&(d=a.slice(e,b+1));return d};c.colorToRgb=function(a){var b=/rgba?\((\d{1,3}), ?(\d{1,3}), ?(\d{1,3}),? ?(\d{1,3})?\)$/i.exec(a);if(b)return{r:parseInt(b[1]),g:parseInt(b[2]),
b:parseInt(b[3])};a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,c,g){return b+b+c+c+g+g});return(b=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(b[1],16),g:parseInt(b[2],16),b:parseInt(b[3],16)}:null};c.colorToHex=function(a){a&&(a=c.colorToRgb(a));return a?c.rgbToHex(a.r,a.g,a.b):null};c.rgbToHex=function(a,b,d){a=[a.toString(16),b.toString(16),d.toString(16)];for(b=0;b<a.length;b++)1==a[b].length&&(a[b]="0"+a[b]);return"#"+a.join("")};c.elementHasId=function(a,b){if(!a||
a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{var d=a.getAttribute("id");if(d&&0<d.length)return a=!1,a=b instanceof Array?-1!=b.indexOf(d):d===b}catch(e){}return!1};c.elementHasAttribute=function(a,b){if(!a||a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{if(b instanceof Array)for(var d=0;d<b.length;d++){if(a.hasAttribute(b))return!0}else return a.hasAttribute(b)}catch(e){}return!1};c.addClassToElement=function(a,b){if(a&&b)try{var d=(a.getAttribute("class")||"").split(/\s/,void 0,!0);-1==d.indexOf(b)&&
(d.push(b),a.setAttribute("class",d.join(" ")))}catch(e){}};c.removeClassFromElement=function(a,b){if(a&&b)try{var d=(a.getAttribute("class")||"").split(/\s/,void 0,!0),e=d.indexOf(b);-1!=e&&(d.splice(e,1),a.setAttribute("class",d.join(" ")))}catch(l){}};c.elementHasClass=function(a,b,d){if(!a||a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{var e=!1,c=(a.getAttribute("class")||"").split(/\s/,void 0,!0);if(b instanceof Array)for(a=0;a<b.length;a++)if(e=-1!=c.indexOf(b[a]),d){if(!e)return!0}else{if(e)return!0}else return e=
-1!=c.indexOf(b)}catch(g){}return!1};c.addClassToHtmlElements=function(a,b){b=c.findValidDocumentElements(b);for(var d=0;d<b.length;d++){var e=b[d];c.addClassToElement(e.documentElement,a);e.documentElement.setAttribute(a,"true")}};c.removeClassFromHtmlElements=function(a,b){b=c.findValidDocumentElements(b);for(var d=0;d<b.length;d++){var e=b[d];c.removeClassFromElement(e.documentElement,a);e.documentElement.removeAttribute(a)}};c.elementHasSpecialAttribute=function(a,b){return a.hasAttribute(b)&&
"true"==a.getAttribute(b)};c.elementIsVisible=function(a,b){if(!a)return!1;if(a.nodeType==Node.DOCUMENT_NODE)return!0;b=b||document;if(a.parentNode&&"HTML"==a.parentNode.tagName)return"BODY"===a.tagName;a.nodeType==Node.TEXT_NODE&&(a=a.parentElement);b=b.defaultView.getComputedStyle(a,null);return"fixed"===b.getPropertyValue("position")?"none"!==b.getPropertyValue("display"):a.offsetParent?!0:!1};c.closestParent=function(a,b){for(;a&&a.nodeType!=Node.ELEMENT_NODE;)a=a.parentElement;return a=a?a.closest(b):
null};c.elementIsInsideBody=function(a){for(;a;){if(a.tagName&&"BODY"==a.tagName.toUpperCase())return!0;a=a.parentNode}return!1};c.lastElementChild=function(a,b){if(a)try{if(b){b=null;for(var d=c.documentForElement(a);a&&(b=a.lastChild);){for(;b&&!c.elementIsVisible(b,d);)b=b.previousElementSibling;if(!b)break;a=b}}else for(;a&&a.lastChild&&a.nodeType!==Node.TEXT_NODE;)a=a.lastChild}catch(e){Logger.instance.error(e)}return a};c.isEditor=function(a,b){if(b)return(a=c.elementContext(a))?a.isEditor:
!1;if(void 0!==a.selectionStart)return!0;for(;a;){try{if("true"==a.getAttribute("contenteditable"))return!0}catch(d){}a=a.parentNode}return!1};c.editorContainer=function(a){if(a)try{if(void 0!==a.selectionStart)return a;if(a.isContentEditable){for(;a.parentElement&&a.parentElement.isContentEditable;)a=a.parentElement;return a}}catch(b){Logger.instance.error(b)}return null};c.elementContext=function(a){if(!a)return null;var b={document:c.documentForElement(a),element:a,editor:null,isEditor:!1,isPlainEditor:!1,
isContentEditable:!1,isGoogleDocs:c.isGoogleDocs(),isGoogleDocsEditor:!1,isGoogleHangouts:c.isGoogleHangouts(),isYahooMail:c.isYahooMail(),isAmazonKindle:!1};try{void 0!==a.selectionStart&&(b.isPlainEditor=!0)}catch(d){}try{a.isContentEditable&&(b.isContentEditable=!0)}catch(d){}b.isPlainEditor||b.isContentEditable?b.editor=a:c.isGoogleDocsEditor(a)?(b.isGoogleDocsEditor=!0,b.editor=document.querySelector(".kix-appview-editor")):c.isAmazonKindle()&&!dji.utils.elementHasClass(document.documentElement,
"dji-sru-screen-selection")&&(b.isAmazonKindle=!0);b.isEditor=b.isPlainEditor||b.isContentEditable||b.isGoogleDocsEditor;return b};c.activeElementInfo=function(a){var b=[],d=document,e=d.activeElement,l=!1,g=!1;if(c.isGoogleDocsEditor(e))"IFRAME"==e.tagName&&(a=(a=document.getElementById("kix-appview"))?a.getElementsByClassName("kix-appview-editor"):null)&&0<a.length&&(e=a[0]),l=!0;else if(c.isAmazonKindle()&&!dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection"))e=document.getElementById("KindleReaderIFrame").contentWindow.document,
e.getElementById("column_0_frame_0")&&"hidden"!=e.getElementById("column_0_frame_0").style.visibility?b.push(e.getElementById("column_0_frame_0")):e.getElementById("column_0_frame_1")&&b.push(e.getElementById("column_0_frame_1")),e.getElementById("column_1_frame_0")&&"hidden"!=e.getElementById("column_1_frame_0").style.visibility?b.push(e.getElementById("column_1_frame_0")):e.getElementById("column_1_frame_1")&&b.push(e.getElementById("column_1_frame_1")),d=document,g=!0;else{for(var f=!1;!f&&e&&
"IFRAME"==e.tagName;)try{f=!0,c.validateIframe(e,!0)&&null!==e.contentDocument&&(b.push(e),d=e.contentDocument,e=d.activeElement,f=!1)}catch(m){break}if(!e||a&&"IFRAME"==e.tagName)return null}return{iframes:b,document:d,element:e,isGoogleDocsEditor:l,isAmazonKindle:g}};c.extractVisibleTextFromElement=function(a){if(!a)return"";if(3==a.nodeType)return a.textContent;var b="",d=null;for(a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(a){if(3==a.nodeType)return NodeFilter.FILTER_ACCEPT;
if("SCRIPT"==a.tagName||"NOSCRIPT"==a.tagName||"IMG"==a.tagName||"SELECT"==a.tagName||"INPUT"==a.tagName&&(!a.type||"text"!=a.type.toLowerCase()))return NodeFilter.FILTER_REJECT;var d=(a.getAttribute("id")||"").toLowerCase();if("dexcontrolscontainer"==d||"dexcontrolscontainermeasurement"==d||"__dji_cwe_body_overlay"==d||"__dji_cwe_measurement_window_generic"==d||"__dji_cwe_chrome_google_docs_proxy"==d||"__dji_cwe_measurement_window"==d||"__dji_cwe_shortcuts"==d||"__dji_cwe_measurement_window_generic"==
d||"none"==document.defaultView.getComputedStyle(a,null).getPropertyValue("display"))return NodeFilter.FILTER_REJECT;"SPAN"!=a.tagName&&(b+="\n");return NodeFilter.FILTER_ACCEPT},!0);d=a.nextNode();)3==d.nodeType?b+=" "+d.textContent:1==d.nodeType&&"TEXTAREA"==d.tagName&&(b+="\n"+d.value+"\n");return b};c.addEventListenerToBodyElements=function(a,b,d,e){e=c.findValidDocumentElements(null,e);for(var f=0;f<e.length;f++)e[f].body&&e[f].body.addEventListener(a,b,d)};c.addEventListenerToDocumentElements=
function(a,b,d){for(var e=c.findValidDocumentElements(),f=0;f<e.length;f++)e[f].addEventListener(a,b,d)};c.removeEventListenerFromBodyElements=function(a,b,d,e){e=c.findValidDocumentElements(null,e);for(var f=0;f<e.length;f++)try{e[f].body&&e[f].body.removeEventListener(a,b,d)}catch(g){}};c.preventInputEventsOnBodyElements=function(a,b,d,e){var f=c.isGoogleDocs();e=c.findValidIframeAndDocumentElements(null,e);for(var g=0;g<e.length;g++){var h=e[g];h.doc.body&&(f?c.isGoogleDocsEditor(h.iframe)||c.preventInputEventsOnTree(h.doc.body,
a,b,d):c.preventInputEventsOnTree(h.doc.body,a,b,d))}};c.preventInputEventsOnTree=function(a,b,d,e){if(a&&3!=a.nodeType){var f=c.isGoogleDocs(),g=null;a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(a){if(3==a.nodeType||"SCRIPT"==a.tagName||"NOSCRIPT"==a.tagName||f&&c.isGoogleDocsEditor(a,!0))return NodeFilter.FILTER_REJECT;a=a.id?a.id.toLowerCase():"";return"dexcontrolscontainer"==a||"dexcontrolscontainermeasurement"==a||0==a.indexOf("__dji_cwe")||!d&&0==a.indexOf("dji-sru-")?
NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT},!0);var h=e||k;e=e||n;if(b)for(;g=a.nextNode();)g.addEventListener("click",e,!1),g.addEventListener("mousedown",h,!1),g.addEventListener("mouseup",e,!1),g.addEventListener("mousemove",e,!1),g.addEventListener("mouseout",e,!1),g.addEventListener("mouseover",e,!1),g.addEventListener("mousewheel",e,!1);else for(;g=a.nextNode();)try{g.removeEventListener("click",e,!1),g.removeEventListener("mousedown",h,!1),g.removeEventListener("mouseup",e,!1),g.removeEventListener("mousemove",
e,!1),g.removeEventListener("mouseout",e,!1),g.removeEventListener("mouseover",e,!1),g.removeEventListener("mousewheel",e,!1)}catch(m){}}};c.ignoreEvent=function(a){a.preventDefault();a.stopPropagation()};c.documentForElement=function(a){for(;a&&a.nodeType!=Node.DOCUMENT_NODE;)a=a.parentNode;return a};c.waitForDocumentToLoad=function(a,b){a=a||document;if("complete"===document.readyState)c.callMethod(b);else{var d=function(){"complete"===a.readyState&&(a.removeEventListener("load",d,!0),c.callMethod(b))};
a.addEventListener("load",d,!0)}};c.findValidDocumentElements=function(a,b){1==arguments.length&&"boolean"===typeof a&&(b=a,a=null);result=[];c.findValidDocumentElementsEx(a||document,result,b);return result};c.findValidDocumentElementsEx=function(a,b,d){b.push(a);a=a.getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var f=a[e];c.validateIframe(f,d)&&null!==f.contentDocument&&c.findValidDocumentElementsEx(f.contentDocument,b,d)}};c.findValidIframeElements=function(a,b){result=[];c.findValidIframeElementsEx(a||
document,result,b);return result};c.findValidIframeElementsEx=function(a,b,d){a=a.getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var f=a[e];c.validateIframe(f,d)&&null!==f.contentDocument&&(b.push(f),c.findValidIframeElementsEx(f.contentDocument,b,d))}};c.findValidIframeAndDocumentElements=function(a,b){result=[];c.findValidIframeAndDocumentElementsEx(a||document,result,b);return result};c.findValidIframeAndDocumentElementsEx=function(a,b,d){a=a.getElementsByTagName("iframe");for(var e=
0;e<a.length;e++){var f=a[e];c.validateIframe(f,d)&&null!==f.contentDocument&&(b.push({iframe:f,doc:f.contentDocument}),c.findValidIframeAndDocumentElementsEx(f.contentDocument,b,d))}};c.validateIframe=function(a,b){try{if(void 0===a.src||null===a.src)return!1;var d=a.getAttribute("id");if("__dji_sru_templates"==d||!b&&d&&0<=d.indexOf("dji_sru"))return!1;b=null;var c=a.src.split("/")[2];if(void 0!==c&&null!==c&&-1==c.indexOf(document.domain))return!1;b=a.contentDocument;return null!==b&&void 0!==
b}catch(l){}return!1};c.addCssToDocument=function(a,b,d){return c.addLinkToDocument(a,"stylesheet","text/css",b,d)};c.addStyleToDocument=function(a,b,d){c.loadFile(b,function(b){var c=a.createElement("style");c.type="text/css";b=b.replace(/dji-generic-extension:\/\/__extension_id__/g,browserEngine.extras.cssPrefix());if(0<=b.indexOf("dji-generic-extension"))throw Error("dji-generic-extension found");c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));a.head||(b=a.createElement("head"),
a.documentElement.appendChild(b));a.head.appendChild(c);d()&&d()})};c.addStylesToDocument=function(a,b,d){var e=0,f=function(){if(b.length<=e)return d();c.addStyleToDocument(a,b[e],function(){e+=1;f()})};f()};c.addJavascriptToDocument=function(a,b,d){return c.addLinkToDocument(a,null,"text/javascript",b,d)};c.addLinkToDocument=function(a,b,d,c,f){b='<link rel="'+b+'" type="'+d+'" href="'+(f?c:browserEngine.extension.getURL(c))+'" />';a.head.insertAdjacentHTML("beforeend",b)};c.generateUUID=function(){var a=
(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var d=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?d:d&7|8).toString(16)})};c.blobToText=function(a,b){if(a){var d=new FileReader;d.onloadend=function(){b(d.result)};d.onerror=function(a){b(null)};d.readAsText(a)}else b(null)};c.htmlToAsciiTextArray=function(a,b){if(void 0===a||null===a)return null;if(0==a.length)return[];for(var d=a.length,c=Array(d),f=0;f<d;f++){var g=a.charAt(f),h=a.charCodeAt(f);
switch(h){case 9:case 160:g=" ";break;case 216:case 248:case 510:case 511:g="0";break;case 451:g="!";break;case 192:case 193:case 194:case 195:case 196:case 197:case 198:case 256:case 258:case 260:case 461:case 478:case 480:case 482:case 506:case 508:case 512:case 514:case 550:g="A";break;case 224:case 225:case 226:case 227:case 228:case 229:case 230:case 257:case 259:case 261:case 462:case 479:case 481:case 483:case 507:case 509:case 513:case 515:case 551:g="a";break;case 199:case 262:case 264:case 266:case 268:g=
"C";break;case 231:case 263:case 265:case 267:case 269:g="c";break;case 208:case 270:case 272:g="D";break;case 271:case 273:g="d";break;case 200:case 201:case 202:case 203:case 274:case 276:case 278:case 280:case 282:case 516:case 518:case 552:g="E";break;case 232:case 233:case 234:case 235:case 275:case 277:case 279:case 281:case 283:case 517:case 519:case 553:g="e";break;case 284:case 286:case 288:case 290:case 484:case 486:case 500:g="G";break;case 285:case 287:case 289:case 291:case 485:case 487:case 501:g=
"g";break;case 292:case 294:case 502:g="H";break;case 293:case 295:g="h";break;case 204:case 205:case 206:case 207:case 296:case 298:case 300:case 302:case 304:case 463:case 520:case 522:g="I";break;case 236:case 237:case 238:case 239:case 297:case 299:case 301:case 303:case 305:case 464:case 521:case 523:g="i";break;case 308:g="J";break;case 309:g="j";break;case 310:case 488:g="K";break;case 311:case 312:case 489:g="k";break;case 313:case 315:case 317:case 319:case 321:g="L";break;case 314:case 316:case 318:case 320:case 322:g=
"l";break;case 209:case 323:case 325:case 327:case 330:case 504:g="N";break;case 240:case 241:case 324:case 326:case 328:case 329:case 331:case 505:g="n";break;case 210:case 211:case 212:case 213:case 214:case 332:case 334:case 336:case 465:case 490:case 492:case 524:case 526:case 554:case 556:case 558:case 560:g="O";break;case 242:case 243:case 244:case 245:case 246:case 333:case 335:case 337:case 466:case 491:case 493:case 525:case 527:case 555:case 557:case 559:case 561:g="o";break;case 340:case 342:case 344:case 528:case 530:g=
"R";break;case 341:case 343:case 345:case 529:case 531:g="r";break;case 346:case 348:case 350:case 352:case 536:g="S";break;case 347:case 349:case 351:case 353:case 537:g="s";break;case 354:case 356:case 358:case 538:g="T";break;case 355:case 357:case 359:case 539:g="t";break;case 217:case 218:case 219:case 220:case 360:case 362:case 364:case 366:case 368:case 370:case 467:case 469:case 471:case 473:case 475:case 532:case 534:g="U";break;case 249:case 250:case 251:case 252:case 361:case 363:case 365:case 367:case 369:case 371:case 468:case 470:case 472:case 474:case 476:case 533:case 535:g=
"u";break;case 372:g="W";break;case 373:g="w";break;case 221:case 374:case 376:case 562:g="Y";break;case 253:case 254:case 255:case 375:case 563:g="y";break;case 377:case 379:case 381:case 548:g="Z";break;case 378:case 380:case 382:case 549:g="z";break;case 8211:g="-";break;case 8216:case 8217:g="'";break;case 8220:case 8221:g='"';break;case 8203:b||(g="");break;default:if(10!=h&&13!=h&&0<=h&&31>=h||127<=h)g=" "}c[f]=g}return c};c.stringToArrayBuffer=function(a){if(null===a||void 0===a)return a;for(var b=
new ArrayBuffer(a.length),d=new Uint8Array(b),c=0;c<a.length;c++)d[c]=a.charCodeAt(c);return b};c.base64StringToArrayBuffer=function(a){return null===a||void 0===a?a:c.stringToArrayBuffer(atob(a))};c.splitInWords=function(a,b){a=a.split(/\W/i);if(b)return a;b=[];for(var d=0;d<a.length;d++){var c=a[d];c&&0<c.length&&b.push(c)}return b}})(window.dji.utils=window.dji.utils||{});
(function(c){function k(c,f){this.m_options=JSON.parse(JSON.stringify(c));this.m_listener=f;this.m_session=dji.utils.generateUUID();this.m_running=!1;this.m_timer=null;this.m_step=0;this.m_online=void 0;this.m_stateChanged=!1;this.m_onPerform=n.bind(this);this.m_options.frequency=this.m_options.frequency||12E4;this.m_options.useJsDapi=!!this.m_options.useJsDapi;this.m_options.timeout=this.m_options.timeout||2E3}function n(c){if(c==this.m_session){var f=this;f.m_step++;if(f.m_options.useJsDapi)jsdapi.http.sendRequest({method:"HEAD",
url:f.m_options.url||"https://www.google.com/?random="+Math.random(),timeout:f.m_options.timeout},function(a,d,e){c==f.m_session&&(a=200<=a&&300>a||304===a,d=void 0===f.m_online,f.m_stateChanged=a!==f.m_online,f.m_online=a,setTimeout(f.m_onPerform,f.m_options.frequency,f.m_session),!f.m_stateChanged||!f.m_listener||d&&f.m_online||f.m_listener(f.m_online))});else try{var a=new XMLHttpRequest;a.open("HEAD",f.m_options.url||"https://www.google.com/?random="+Math.random(),!0);a.timeout=f.m_options.timeout;
a.onreadystatechange=function(){if(c==f.m_session&&a.readyState===XMLHttpRequest.DONE&&0<a.status){var b=200<=a.status&&300>a.status||304===a.status,d=void 0===f.m_online;f.m_stateChanged=b!==f.m_online;f.m_online=b;setTimeout(f.m_onPerform,f.m_options.frequency,f.m_session);!f.m_stateChanged||!f.m_listener||d&&f.m_online||f.m_listener(f.m_online)}};a.ontimeout=a.onerror=a.onabort=function(){c==f.m_session&&(f.m_stateChanged=!1!==f.m_online,f.m_online=!1,setTimeout(f.m_onPerform,f.m_options.frequency,
f.m_session),f.m_stateChanged&&f.m_listener&&f.m_listener(f.m_online))};a.send()}catch(b){setTimeout(f.m_onPerform,f.m_options.frequency,f.m_session)}}}k.prototype.start=function(){this.m_running||(this.m_running=!0,this.m_onPerform(this.m_session))};k.prototype.stop=function(){this.m_timer&&(clearTimeout(this.m_timer),this.m_timer=null);this.m_session=dji.utils.generateUUID();this.m_running=!1;this.m_step=0;this.m_online=void 0;this.m_stateChanged=!1};k.prototype.reset=function(){this.m_online=void 0;
this.m_stateChanged=!1};c.createInternetConnectionMonitor=function(c,f){return new k(c,f)}})(window.dji.utils=window.dji.utils||{});
