var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(g){this.asyncThrow_(g)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(g){c.reject(g)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(v){f(v)}}:b}var d,f,k=new e(function(a,
b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return k};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())c(e.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,f){function e(b){return function(c){k[b]=c;g--;0==g&&a(k)}}var k=[],g=0;do k.push(void 0),g++,c(d.value).callWhenSettled_(e(k.length-1),f),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(g){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");
c("seal");var e=0,f=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=c;return this};f.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};f.prototype.has=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};f.prototype.delete=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),f=d.next();if(f.done||f.value[0]!=b||"s"!=f.value[1])return!1;f=d.next();return f.done||4!=f.value[0].x||"t"!=f.value[1]||!d.next().done?!1:!0}catch(u){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var b=new WeakMap,c=function(a){this.data_={};this.head_=f();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};c.prototype.delete=
function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).entry};c.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++h,b.set(c,d)):d="p_"+c;var f=a.data_[d];if(f&&$jscomp.owns(a.data_,d))for(a=0;a<f.length;a++){var e=
f[a];if(c!==c&&e.key!==e.key||c===e.key)return{id:d,list:f,index:a,entry:e}}return{id:d,list:f,index:-1,entry:void 0}},e=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.previous=a.next=a.head=a},h=0;return c},"es6","es3");
$jscomp.polyfill("Set",function(a){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a($jscomp.makeIterator([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};b.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};b.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=function(a){return this.map_.has(a)};b.prototype.entries=function(){return this.map_.entries()};
b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return b},"es6","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");function CWEBackgroundManagerInstance(){return CWEBackgroundManager.instance}
function CWEBackgroundManager(){this.m_tabs={};this.m_activeTabId=this.m_activeWindowId=-1;this.m_busy=this.m_on=this.m_turnOnInProgress=this.m_loaded=!1;this.m_contextMenu={CoWriter:null,startSpeak:null,stopSpeak:null,addPersonalWord:null,removePersonalWord:null};this.m_quickTopicActionInfo={action:"",topic:null,fromWiki:!1,tabId:-1};this.m_userDirectory=this.m_userName="";this.m_fileSystem=null;this.m_locale=this.findValidLanguage(localStorage.locale||"US");this.m_defaultLocale="US";this.m_localeRequiresReboot=
!1;this.m_translationLanguages=[];this.m_translationLanguagesMap={};this.m_appUrlPattern="chrome-extension://"+chrome.runtime.id+"/*";this.m_appOptionsUrlPattern="chrome-extension://"+chrome.runtime.id+"/Options/*";this.m_appOptions="/Options/options.html";this.m_token=null;this.m_restartReason=localStorage.__runtime_restart_reason||null;this.directories={common:"/common/dictionaries",mainDictionaries:"main",predefinedTopicDictionaries:"predefined_topics",hunspell:"/common/hunspell"};this.m_localeMap=
{US:"en-US",UK:"en-GB",BE:"en-GB",CAN:"en-US",FR:"fr-FR",SPA:"es-ES",GER:"de-DE"};this.m_defaultDisplayTopics={US:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),UK:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),BE:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),CAN:"Albert Einstein;Global Warming;William Shakespeare;Aquarium Visit;Compare and Contrast;Tsunamis & Tidal Waves".split(";"),
FR:"Tour de France;Le Vendee Globe;football;Victor Hugo;Musee d'Orsay;Samuel de Champlain".split(";"),GER:"Fusball;Albert Einstein;Ludwig van Beethoven;Schwarzwald;Jasmund;Bodensee".split(";"),SPA:"Futbol;Pablo Picasso;Antoni Gaudi;Frida Kahlo;Dia de Muertos;Astronomia".split(";")};this.m_wikiReader=new CWEWikiReader;localStorage.__runtime_restart_reason=null;return this}CWEBackgroundManager.instance=null;
CWEBackgroundManager.initialize=function(){if(null===CWEBackgroundManager.instance)try{CWEBackgroundManager.instance=new CWEBackgroundManager,CWEBackgroundManager.instance.__initialize()}catch(a){CWEBackgroundManager.instance=null,Logger.instance.error("Background Manager - cannot create instance!"),Logger.instance.error(a)}};CWEBackgroundManager.prototype.isLoaded=function(){return this.m_loaded};
CWEBackgroundManager.prototype.isBusy=function(){return!!(this.m_busy||this.m_turnOnInProgress||CWEPredictionEngine.instance&&CWEPredictionEngine.instance.state.action)};CWEBackgroundManager.prototype.__enterBusyState=function(){this.m_busy||(this.m_busy=!0,this.__sendNotification("busy_started"))};CWEBackgroundManager.prototype.__leaveBusyState=function(){this.m_busy&&(this.m_busy=!1,this.__sendNotification("busy_finished"))};CWEBackgroundManager.prototype.isTurnOnInProgress=function(){return this.m_turnOnInProgress};
CWEBackgroundManager.prototype.isLoggedIn=function(){return cwe.login.isLoggedIn()};CWEBackgroundManager.prototype.userInfo=function(){return cwe.login.userInfo()};CWEBackgroundManager.prototype.settings=function(){return CWESettings.instance};CWEBackgroundManager.prototype.locale=function(){return this.m_locale};CWEBackgroundManager.prototype.localeLang=function(a,b){b=this.m_localeMap[b||this.m_locale];!a&&b&&(b=b.split("-")[0]);return b};CWEBackgroundManager.prototype.translationLanguages=function(){return this.m_translationLanguages};
CWEBackgroundManager.prototype.translationLanguageInfo=function(a){return this.m_translationLanguagesMap[a]};CWEBackgroundManager.prototype.localeRequiresReboot=function(){return this.m_localeRequiresReboot};CWEBackgroundManager.prototype.restartReason=function(){return this.m_restartReason};CWEBackgroundManager.prototype.fileSystem=function(){return this.m_fileSystem};CWEBackgroundManager.prototype.requestFileSystem=function(a){a(this.m_fileSystem)};
CWEBackgroundManager.prototype.__initialize=function(){Logger.instance.log("Initializing Co:Writer Extension...");this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}});CWESettings.initialize(this);this.__startInitialization()};CWEBackgroundManager.prototype.__startInitialization=function(){this.__initializePersistentStorage()};
CWEBackgroundManager.prototype.__initializePersistentStorage=function(){var a=this;DjiHtml5FileSystem.initialize(function(b){return $jscomp.executeAsyncGenerator(function(){function c(c,e,k){for(;;)switch(d){case 0:a.m_fileSystem=b;try{return d=3,{value:CWEPredictionEngine.load(a),done:!1}}catch(l){d=1;break}case 3:try{if(1!=c){d=4;break}d=-1;throw k;}catch(l){d=1;break}case 4:try{CWEPredictionEngine.instance.addEventListener("crash",a.__predictionEngineCrashed.bind(a));a.__predictionEngineLoaded(!0);
d=2;break}catch(l){d=1;break}case 1:a.__predictionEngineLoaded(!1);case 2:d=-1;default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())})};
CWEBackgroundManager.prototype.__predictionEngineLoaded=function(a){if(a){var b=this;this.resetHunspellLanguages();setTimeout(function(){dji.tts.initialize(b)},10)}else Logger.instance.error("Failed to load Prediction Engine! Change status to UNAVAILABLE!")};CWEBackgroundManager.prototype.__predictionEngineInitialized=function(a){var b=this;setTimeout(function(){dji.tts.initialize(b)},10)};
CWEBackgroundManager.prototype.__ttsEngineInitialized=function(){var a=this;CWESettings.initialize(this);dji.speechRecognition.initialize();setTimeout(function(){a.loadConfig(function(){setTimeout(function(){a.__initializeDataManager()},10)})},0)};
CWEBackgroundManager.prototype.__initializeDataManager=function(){var a=this;CWEDataManager.initialize(function(){CWEDataManager.instance.setDataSyncManager(cwe.sync);cwe.sync.setDataManager(CWEDataManager.instance);cwe.sync.addUserSettingsUpdateListener(function(){a.__onUserSettingsSynced()});cwe.sync.addDictionariesUpdateListener(function(b,c){a.__onTopicsSynced(b,c)});Logger.instance.log("Initializing storage... DONE!");setTimeout(function(){a.__initializeDataMeasurements()},10)})};
CWEBackgroundManager.prototype.__initializeDataMeasurements=function(){var a=this;window.cwe.measure.initialize(function(){Logger.instance.log("Initializing measurements... DONE!");setTimeout(function(){a.__initializeSettings()},10)})};CWEBackgroundManager.prototype.__initializeSettings=function(){var a=this;CWESettings.initialize(this);CWESettings.instance.load(function(){Logger.instance.log("Initializing settings... DONE!");setTimeout(function(){a.__initializeTranslation()},0)})};
CWEBackgroundManager.prototype.__initializeTranslation=function(){var a=this;dji.translator.init({load:CWEDataManager.instance.loadTranslationCache.bind(CWEDataManager.instance),save:CWEDataManager.instance.saveTranslationCache.bind(CWEDataManager.instance)});setTimeout(function(){a.__initializeDefaultUser()},0)};
CWEBackgroundManager.prototype.__initializeDefaultUser=function(){var a=this;this.changeUser("DefaultUser",function(){Logger.instance.log("Initializing default user... DONE!");setTimeout(function(){a.__loadLastUserInfo()},0)})};
CWEBackgroundManager.prototype.__loadLastUserInfo=function(){var a=this,b=this.__changeToLastLoggedInUser.bind(this);this.__readUserInfo(function(c){cwe.login.silentAuth(function(d){d&&500!=d.code?0==d.code?c&&c.checksum!==d.user.checksum?a.__removeUserData(c,function(){a.__loadUserInfo(function(){setTimeout(b,10)})}):a.__saveUserInfo(function(){a.__loadUserInfo(function(){setTimeout(b,10)})}):a.__removeUserData(c,function(){a.__loadUserInfo(function(){setTimeout(b,10)})}):a.__loadUserInfo(function(){setTimeout(b,
10)})})})};CWEBackgroundManager.prototype.__changeToLastLoggedInUser=function(){var a=this;cwe.login.isLoggedIn()?a.changeUser(cwe.login.userInfo().checksum,function(){setTimeout(function(){a.__createContextMenus()},0)}):setTimeout(function(){a.__createContextMenus()},0)};
CWEBackgroundManager.prototype.__createContextMenus=function(){var a=this;chrome.contextMenus.removeAll();this.m_contextMenu.CoWriter=chrome.contextMenus.create({title:"Co:Writer",contexts:["all"]});this.m_contextMenu.startSpeak=chrome.contextMenus.create({title:"Speak",contexts:["selection"],parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onSpeakSelection(c.id,b.selectionText)}});this.m_contextMenu.stopSpeak=chrome.contextMenus.create({title:"Stop Speak",contexts:["all"],parentId:this.m_contextMenu.CoWriter,
enabled:!1,onclick:function(b,c){a.onStopSpeak()}});this.m_contextMenu.addPersonalWord=chrome.contextMenus.create({title:"Add Personal Word",contexts:["selection"],parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onAddPersonalWords(c.id,b.selectionText)}});this.m_contextMenu.removePersonalWord=chrome.contextMenus.create({title:"Remove Personal Word",contexts:["selection"],parentId:this.m_contextMenu.CoWriter,onclick:function(b,c){a.onRemovePersonalWords(c.id,b.selectionText)}});setTimeout(function(){a.__cacheTabs()},
0)};CWEBackgroundManager.prototype.__cacheTabs=function(){var a=this;chrome.tabs.query({},function(b){chrome.windows.getCurrent(null,function(c){if(c)for(a.m_activeWindowId=c.id,c=0;c<b.length;c++){var d=b[c];a.m_tabs[d.id]={tabId:d.id,windowId:d.windowId,port:null};d.active&&d.windowId==a.m_activeWindowId&&(a.m_activeTabId=d.id)}Logger.instance.log("CWEBackgroundManager.__cacheTabs");Logger.instance.log(a.m_tabs);setTimeout(function(){a.__finishInitialization()},0)})})};
CWEBackgroundManager.prototype.__finishInitialization=function(){var a=this;chrome.windows.onFocusChanged.addListener(function(b){a.__onWindowFocusChanged(b)});chrome.tabs.onCreated.addListener(function(b){a.__onTabCreated(b)});chrome.tabs.onActivated.addListener(function(b){a.__onTabActivated(b)});chrome.tabs.onRemoved.addListener(function(b,d){a.__onTabRemoved(b,d)});chrome.tabs.onHighlighted.addListener(function(b){a.__onTabHighlighted(b)});chrome.runtime.onMessage.addListener(function(b,d,e){a.__onRuntimeMessage(b,
d,e)});chrome.runtime.onConnect.addListener(function(b){a.__onPortConnect(b)});var b=function(){if(a.m_localeRequiresReboot)Logger.instance.log("Initializing Co:Writer Extension... DONE! Locales change requires restart!");else{a.m_loaded=!0;for(var b in a.m_tabs)try{a.m_tabs[b].port=null,chrome.tabs.sendMessage(a.m_tabs[b].tabId,{message:"com.donjohnston.cowriter.chrome.message.engineReady"})}catch(d){Logger.instance.log(d)}a.reloadAppTabs();Logger.instance.log("Initializing Co:Writer Extension... DONE!")}cwe.login.monitor({authRequired:a.__onAuthRequired.bind(a),
signoutRequired:a.__onSignoutRequired.bind(a)});dji.proxy.init({onNotification:a.__onExternalNotification.bind(a)});a.__sendNotification("load")};cwe.login.isLoggedIn()?this.__prepareUserLanguages(cwe.login.userInfo(),function(c){c&&(a.__validateTranslationSource(),cwe.sync.changeLanguage(a.m_locale),cwe.sync.start(),a.setIcon({path:a.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}));
b()}):(this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),b())};CWEBackgroundManager.prototype.__onRuntimeMessage=function(a,b,c){if(b.id===chrome.runtime.id){if("com.donjohnston.cowriter.chrome.message.options"===a.message)this.onOptions();c instanceof Function&&c()}};
CWEBackgroundManager.prototype.__onExternalNotification=function(a){if(a){var b=dji.config.loginUrlSignature();"auth"===a.category&&(!a.hasOwnProperty("version")||a.hasOwnProperty("version")&&2===a.version&&a.signature===b)&&("auth"===a.reason?this.__onAuthRequired():"signout"===a.reason&&this.__onSignoutRequired())}};
CWEBackgroundManager.prototype.__onAuthRequired=function(){var a=this;this.m_turnOnInProgress||(this.m_turnOnInProgress=!0,cwe.login.userInfo(),this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),cwe.login.silentAuth(function(b){b&&500!=b.code?0==b.code?a.__saveUserInfo(function(){a.__loadUserInfo(function(){if(cwe.login.isLoggedIn()){var b=cwe.login.userInfo();a.__saveUserInfo(function(){a.__prepareUserLanguages(b,function(c){c?a.changeUser(b.checksum,
function(){a.m_turnOnInProgress=!1;a.__validateTranslationSource();cwe.sync.start();a.setIcon({path:a.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})}):(a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1,dji.notifications.show({message:"Text prediction language has changed. Please reload the extension."}))})})}else dji.notifications.showByAuthCode(500),
a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1})}):(dji.notifications.showByAuthCode(b.code),a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=!1):(dji.notifications.showByAuthCode(b?b.code:null),a.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),a.m_turnOnInProgress=
!1)}))};CWEBackgroundManager.prototype.__onSignoutRequired=function(){this.signOut()};CWEBackgroundManager.prototype.__reloadRelatedWebsites=function(a){Logger.instance.log("Reload related websites:",a,dji.config.relatedUris());this.__notifyRelatedExtensionsAboutAuth(a);chrome.tabs.query({url:dji.config.relatedUris()},function(a){if(a)for(var b=0;b<a.length;b++){var d=a[b],e=new URL(d.url);chrome.tabs.update(d.id,{url:e.origin})}})};
CWEBackgroundManager.prototype.__notifyRelatedExtensionsAboutAuth=function(a){dji.proxy.broadcastNotification({category:"auth",version:2,reason:a?"auth":"signout",signature:dji.config.loginUrlSignature()})};CWEBackgroundManager.prototype.__sendNotification=function(a,b){chrome.runtime.sendMessage({message:"com.donjohnston.cowriter.notification",reason:a,details:b})};
CWEBackgroundManager.prototype.__onBrowserAction=function(a){if(this.m_loaded)if(this.m_turnOnInProgress)Logger.instance.log("Turn on is already in progress!");else{this.m_turnOnInProgress=!0;Logger.instance.log("------------- CWEBackgroundManager.__onBrowserAction");Logger.instance.log(this.m_activeTabId);this.onStopSpeak();dji.speechRecognition.stop();var b=this,c=function(c){var d=function(c){b.m_turnOnInProgress=!1;b.m_on=c;setTimeout(function(){b.setIcon({path:b.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",
38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})},0);a&&a();b.__sendNotification(b.m_on?"activated":"deactivated");b.__enableInActiveTab(b.m_on)};c?b.__initializePredictionEngine(function(a){d(a)},!0):d(!1)};if(b.m_on)return c(!1);cwe.login.isLoggedIn()?c(!b.m_on):cwe.login.login(function(a){a?b.__saveUserInfo(function(){b.__prepareUserLanguages(a,function(d){d?b.changeUser(a.checksum,function(){b.__validateTranslationSource();
cwe.sync.start();c(!0)}):b.m_turnOnInProgress=!1});b.__reloadRelatedWebsites(!0)}):b.m_turnOnInProgress=!1})}else this.m_localeRequiresReboot&&this.activateLocaleRequiresReboot()};
CWEBackgroundManager.prototype.__initializePredictionEngine=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,n,p){for(;;)switch(e){case 0:g=c;if(b||!c.m_turnOnInProgress){e=1;break}e=-1;return{value:CWEChromeUtilities.callMethod(a,!1,!1),done:!0};case 1:if(!CWEPredictionEngine.isInitialized()){e=2;break}e=-1;return{value:CWEChromeUtilities.callMethod(a,!0,!0),done:!0};case 2:return l=c.m_turnOnInProgress,c.m_turnOnInProgress=!0,g.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",
38:"/Graphics/CoWriterIcon-Loading_38.png"}}),c.__sendNotification("initialize_nacl_started"),Logger.instance.info("__initializePredictionEngine   #1"),e=3,{value:CWEPredictionEngine.instance.initializeAsync(c.m_locale,g.m_userDirectory),done:!1};case 3:if(1!=d){e=4;break}e=-1;throw p;case 4:h=k=n;if(!h){e=5;break}e=6;return{value:CWEPredictionEngine.instance.updateFromUserSettingsAsync(),done:!1};case 6:if(1!=d){e=7;break}e=-1;throw p;case 7:h=f=n;case 5:h||c.__predictionEngineCrashed(),g.setIcon({path:h?
g.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),g.m_turnOnInProgress=l,g.__sendNotification("initialize_nacl_finished"),CWEChromeUtilities.callMethod(a,h,!0),e=-1;default:return{value:void 0,done:!0}}}var e=0,f,h,k,l,g,n={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};
CWEBackgroundManager.prototype.__onWindowFocusChanged=function(a){if(!cwe.login.isPreparing()&&cwe.login.windowId()!==a){this.onStopSpeak();dji.speechRecognition.stop();var b=this;this.__notifyActiveTab("deactivate");this.m_on&&this.__enableInActiveTab(!1);this.m_activeWindowId=a;this.m_activeTabId=-1;0>a?chrome.windows.getCurrent({},function(a){a&&a.focused&&0<=a.id&&b.__onWindowFocusChanged(a.id)}):chrome.tabs.query({active:!0,windowId:a},function(a){var c=null;0<a.length&&(c=a[0].id);b.m_activeTabId!==
c&&(b.m_activeTabId=null===c?-1:c,b.__notifyActiveTab(),b.m_on&&b.m_loaded&&0<=b.m_activeTabId&&(CWEPredictionEngine.instance&&CWEPredictionEngine.instance.resetState(),b.__enableInActiveTab(!0)))})}};CWEBackgroundManager.prototype.__onTabCreated=function(a){cwe.login.isPreparing()||cwe.login.windowId()===a.windowId||(this.m_tabs[a.id]={tabId:a.id,windowId:a.windowId,port:null})};
CWEBackgroundManager.prototype.__onTabActivated=function(a){cwe.login.isPreparing()||cwe.login.windowId()===a.windowId||(this.m_tabs.hasOwnProperty(a.tabId)?this.m_tabs[a.tabId].windowId=a.windowId:this.m_tabs[a.tabId]={tabId:a.tabId,windowId:a.windowId,port:null},a.windowId===this.m_activeWindowId&&this.m_activeTabId!==a.tabId&&(this.onStopSpeak(),dji.speechRecognition.stop(),this.__notifyActiveTab("deactivate"),this.m_on&&this.__enableInActiveTab(!1),this.m_activeTabId=a.tabId,this.__notifyActiveTab(),
this.m_loaded&&this.m_on&&0<=this.m_activeTabId&&(CWEPredictionEngine.instance&&CWEPredictionEngine.instance.resetState(),this.__enableInActiveTab(!0))))};CWEBackgroundManager.prototype.__onTabHighlighted=function(a){Logger.instance.log("--------------- CWEBackgroundManager.__onHighlighted:");Logger.instance.log(a)};
CWEBackgroundManager.prototype.__onTabRemoved=function(a,b){Logger.instance.log("--------------- CWEBackgroundManager.__onTabRemoved:");Logger.instance.log(b);this.m_activeTabId==a&&(this.onStopSpeak(),dji.speechRecognition.stop());a in this.m_tabs?delete this.m_tabs[a]:Logger.instance.log("     - tab not cached");Logger.instance.log(this.m_tabs)};
CWEBackgroundManager.prototype.__onPortConnect=function(a){Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect");Logger.instance.log(a);if("__dji__cowriter_port"===a.name)if(a.sender&&a.sender.tab){var b=a.sender.tab.id;b in this.m_tabs||(Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect: unknow tabId "+b),this.m_tabs[b]={tabId:b,windowId:a.sender.tab.windowId,port:null});Logger.instance.log(" - active window: "+this.m_activeWindowId);Logger.instance.log(" - active tab: "+
this.m_activeTabId);Logger.instance.log(" - tabId: "+b);this.m_tabs[b].port=new CWEBackgroundPort(a,b,this)}else Logger.instance.log("------------- CWEBackgroundManager.__onPortConnect: no sender details")};CWEBackgroundManager.prototype.__onPortDisconnect=function(a,b){Logger.instance.log("------------- CWEBackgroundManager.__onPortDisconnect, tabId="+a);Logger.instance.log(b)};
CWEBackgroundManager.prototype.__enableInActiveTab=function(a){if(!a||-1!==this.m_activeTabId)try{a&&this.__applySettingsInActiveTab(!0,!0);var b=this,c=this.m_activeTabId,d={message:a?"com.donjohnston.cowriter.chrome.message.activate":"com.donjohnston.cowriter.chrome.message.deactivate",token:CWEChromeUtilities.generateUUID()};a&&(d.state=CWEPredictionEngine.instance.state);this.m_token=d.token;a&&this.__notifyActiveTab();if(a)try{chrome.tabs.sendMessage(c,d,function(c){CWEChromeUtilities.checkLastError();
a&&c&&c.active&&c.token===b.m_token&&b.requestMomentaryTopicContext()})}catch(f){Logger.instance.log(f)}else for(var e in this.m_tabs)if(this.m_tabs.hasOwnProperty(e))try{chrome.tabs.sendMessage(this.m_tabs[e].tabId,d,CWEChromeUtilities.createLastErrorHandler())}catch(f){Logger.instance.log(f)}}catch(f){Logger.instance.error(f)}};
CWEBackgroundManager.prototype.__notifyActiveTab=function(a,b){if(this.m_loaded&&0<=this.m_activeTabId)try{void 0===a&&void 0===b&&(b=CWEPredictionEngine.instance.state,b.action||(b=void 0),b&&(a="update_topic_started")),(a||b)&&chrome.tabs.sendMessage(this.m_activeTabId,{message:"com.donjohnston.cowriter.chrome.notification",reason:a||"generic",details:b},CWEChromeUtilities.createLastErrorHandler())}catch(c){}};
CWEBackgroundManager.prototype.__applySettingsInActiveTab=function(a){if(this.m_loaded&&this.m_on&&-1!==this.m_activeTabId)try{if(this.m_tabs[this.m_activeTabId].port){var b=this.prepareSpeechRecognitionInfo(CWESettings.instance.translationSource());dji.tts.settings(CWESettings.instance.speech());this.m_tabs[this.m_activeTabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.settings",settings:{locale:this.locale(),prediction:CWESettings.instance.prediction(),window:CWESettings.instance.window(),
text:CWESettings.instance.guessWindowForUI(),speech:{letters:CWESettings.instance.speechLetters(),words:CWESettings.instance.speechWords(),sentences:CWESettings.instance.speechSentences()},translation:{target:this.prepareSpeechRecognitionInfo(this.m_locale),source:b},isEnglish:CWEPredictionEngine.isEnglish()}});this.provideTopicsData(this.m_activeTabId);a||this.requestMomentaryTopicContext()}}catch(c){}};
CWEBackgroundManager.prototype.displayTopics=function(){var a=this.m_defaultDisplayTopics[this.locale()]||[],b=CWESettings.instance.topicsActive(),c=CWESettings.instance.topicsRecent(),d=new Set(b),e=b.map(function(a){return{name:a,active:!0}});c.forEach(function(a){d.has(a)||(e.push({name:a,active:!1}),d.add(a))});a.forEach(function(a){d.has(a)||(e.push({name:a,active:!1}),d.add(a))});return e.slice(0,6)};
CWEBackgroundManager.prototype.provideTopicsData=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,p,q){for(;;)switch(f){case 0:if(!d.m_loaded||-1===a){f=1;break}try{if(!d.m_tabs[a].port){f=4;break}if(!b){f=5;break}u=CWEPredictionEngine.instance.allTopics();f=6;break}catch(r){m=r;f=2;break}case 5:try{return f=7,{value:CWEPredictionEngine.instance.getTopicsAsync(),done:!1}}catch(r){m=r;f=2;break}case 7:try{if(1!=e){f=8;break}f=-1;throw q;}catch(r){m=r;f=2;break}case 8:try{u=
n=p}catch(r){m=r;f=2;break}case 6:try{g=u,l=d.displayTopics(),k={topics:g.topics,activeTopics:CWESettings.instance.topicsActive(),recentTopics:CWESettings.instance.topicsRecent(),displayTopics:l},c?chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.topics.data",data:k}):d.m_tabs[a].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.topics.data",data:k})}catch(r){m=r;f=2;break}case 4:try{f=3;break}catch(r){m=r;f=2;break}case 2:h=m,Logger.instance.error(h);
case 3:case 1:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,k,l,g,n,u,m,p={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();p[Symbol.iterator]=function(){return this};return p}())};CWEBackgroundManager.prototype.toggleOnOff=function(){this.__onBrowserAction(null)};
CWEBackgroundManager.prototype.requestMomentaryTopicContext=function(){this.m_loaded&&this.m_on&&CWESettings.instance.predictionMomentaryTopic()&&-1!=this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&this.m_tabs[this.m_activeTabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.getContextForMomentaryTopic"})};CWEBackgroundManager.prototype.tabNeedsSetup=function(a){chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.setup",data:{sensitiveWords:CWEPredictionEngine.instance.sensitiveWords()}})};
CWEBackgroundManager.prototype.documentReadyInTab=function(a){this.m_loaded&&this.m_on&&a===this.m_activeTabId&&this.__enableInActiveTab(!0)};CWEBackgroundManager.prototype.documentCapabilitiesUpdateInTab=function(a,b){this.m_loaded&&this.m_on&&this.m_activeTabId===a&&-1!==a&&"office365-word-document"===b.service&&this.requestMomentaryTopicContext()};CWEBackgroundManager.prototype.scheduleSpeakInTab=function(a,b,c){this.m_loaded&&this.m_on&&a===this.m_activeTabId&&dji.tts.scheduleSpeak(b,c)};
CWEBackgroundManager.prototype.speakInTab=function(a,b,c){this.m_loaded&&(this.m_on&&a===this.m_activeTabId||c)&&dji.tts.speak(b)};CWEBackgroundManager.prototype.stopSpeakInTab=function(a){this.onStopSpeak()};CWEBackgroundManager.prototype.onSpeakSelection=function(a,b){dji.tts.speak(b)};CWEBackgroundManager.prototype.onStopSpeak=function(){dji.tts.stop()};CWEBackgroundManager.prototype.speakStarted=function(){chrome.contextMenus.update(this.m_contextMenu.stopSpeak,{enabled:!0})};
CWEBackgroundManager.prototype.speakStopped=function(){chrome.contextMenus.update(this.m_contextMenu.stopSpeak,{enabled:!1})};CWEBackgroundManager.prototype.onAddPersonalWords=function(a,b){this.m_loaded&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.addPersonalWords(b)};CWEBackgroundManager.prototype.onRemovePersonalWords=function(a,b){this.m_loaded&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.removePersonalWords(b)};
CWEBackgroundManager.prototype.updateTopicAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,g){for(;;)switch(e){case 0:return f=c,e=-1,{value:new Promise(function(c){f.updateTopic(a,b,c)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};
return h}())};
CWEBackgroundManager.prototype.updateTopic=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,q,r){for(;;)switch(f){case 0:if(!d.m_busy){f=1;break}f=-1;return{value:c({status:"busy",name:b.name}),done:!0};case 1:p={details:{name:b.name},userData:b.userData};try{if(!b.local){f=4;break}f=-1;return{value:d.activateTopic(a,{name:b.name,activate:!0,provideTopicsData:!0},c),done:!0}}catch(t){m=t;f=2;break}case 4:try{if(b.local){f=5;break}u=CWEPredictionEngine.instance.canActivateTopic(b.name);d.__enterBusyState();
d.__sendNotification("update_topic_started",p);d.__notifyActiveTab("update_topic_started",p);if(n=b.data){f=6;break}f=7;return{value:d.m_wikiReader.loadAsync(b.name,d.locale()),done:!1}}catch(t){m=t;f=2;break}case 7:try{if(1!=e){f=8;break}f=-1;throw r;}catch(t){m=t;f=2;break}case 8:try{n=g=q}catch(t){m=t;f=2;break}case 6:try{if(n){f=9;break}d.__leaveBusyState();d.__sendNotification("update_topic_finished",p);d.__notifyActiveTab("update_topic_failed",p);f=-1;return{value:c({status:"failed",name:b.name}),
done:!0}}catch(t){m=t;f=2;break}case 9:try{return f=10,{value:CWEPredictionEngine.instance.createWikiTopicAsync(b.name,n,u,b.userData),done:!1}}catch(t){m=t;f=2;break}case 10:try{if(1!=e){f=11;break}f=-1;throw r;}catch(t){m=t;f=2;break}case 11:try{k=l=q;if(!k||!a){f=12;break}f=13;return{value:d.provideTopicsData(a),done:!1}}catch(t){m=t;f=2;break}case 13:try{if(1!=e){f=14;break}f=-1;throw r;}catch(t){m=t;f=2;break}case 14:case 12:try{d.__sendNotification("update_topic_finished",p);d.__leaveBusyState();
if(!k){f=15;break}d.__notifyActiveTab("update_topic_finished",p);f=-1;return{value:c({status:"ok",active:u,name:k.topic}),done:!0}}catch(t){m=t;f=2;break}case 15:try{return d.__notifyActiveTab("update_topic_failed",p),f=-1,{value:c({status:"failed",name:b.name}),done:!0}}catch(t){m=t;f=2;break}case 5:try{return f=-1,{value:c({status:"NOT IMPLEMENTED"}),done:!0}}catch(t){m=t;f=2;break}case 2:return h=m,Logger.instance.error(h),d.__leaveBusyState(),d.__notifyActiveTab("update_topic_failed",p),f=-1,
{value:c({status:"failed",name:b.name}),done:!0};case 3:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,k,l,g,n,u,m,p,x={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();x[Symbol.iterator]=function(){return this};return x}())};
CWEBackgroundManager.prototype.activateTopicAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,g){for(;;)switch(e){case 0:return f=c,e=-1,{value:new Promise(function(c){f.activateTopic(a,b,c)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};
return h}())};
CWEBackgroundManager.prototype.activateTopic=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,m,v){for(;;)switch(f){case 0:if(!d.m_busy){f=1;break}f=-1;return{value:c({status:"busy",name:b.name}),done:!0};case 1:if(!b.activate||CWEPredictionEngine.instance.canActivateTopic(b.name)){f=2;break}f=-1;return{value:c({status:"too_many_active_topics",name:b.name}),done:!0};case 2:u={status:null,active:!!b.activate,name:b.name};d.__enterBusyState();try{d.__sendNotification("activate_topic_started",b);
g=void 0;if(!b.activate){f=5;break}f=7;return{value:CWEPredictionEngine.instance.activateTopicAsync(b.name),done:!1}}catch(q){n=q;f=3;break}case 7:try{if(1!=e){f=8;break}f=-1;throw v;}catch(q){n=q;f=3;break}case 8:try{g=l=m;f=6;break}catch(q){n=q;f=3;break}case 5:try{return f=9,{value:CWEPredictionEngine.instance.deactivateTopicAsync(b.name),done:!1}}catch(q){n=q;f=3;break}case 9:try{if(1!=e){f=10;break}f=-1;throw v;}catch(q){n=q;f=3;break}case 10:try{g=k=m}catch(q){n=q;f=3;break}case 6:try{if(!(b.provideTopicsData&&
0<a)){f=11;break}f=12;return{value:d.provideTopicsData(a),done:!1}}catch(q){n=q;f=3;break}case 12:try{if(1!=e){f=13;break}f=-1;throw v;}catch(q){n=q;f=3;break}case 13:case 11:try{u.status="ok";u.name=g.topic;f=4;break}catch(q){n=q;f=3;break}case 3:h=n,Logger.instance.error(h),u.status="failed";case 4:d.__leaveBusyState(),d.__sendNotification("ok"===u.status?"activate_topic_finished":"activate_topic_failed",u),c(u),f=-1;default:return{value:void 0,done:!0}}}var f=0,h,k,l,g,n,u,m={next:function(a){return e(0,
a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();m[Symbol.iterator]=function(){return this};return m}())};
CWEBackgroundManager.prototype.contextAvailable=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,p,q){for(;;)switch(f){case 0:if(CWEPredictionEngine.instance){f=1;break}m=b.changed+":"+b.selection.start+":"+b.selection.length+":"+b.text;Logger.instance.log("CWEPrediction not intialized"+m);f=-1;return{value:void 0,done:!0};case 1:u={tabId:a,requestId:c};CWEPredictionEngine.instance.followTextChange(b.changed,b.selection.start,b.selection.length,b.text,u);try{g=
CWEChromeUtilities.findWord(b.text,b.selection.start-1);if(!(g&&0<g.length)){f=4;break}f=5;return{value:CWEPredictionEngine.instance.spellcheck(g,u),done:!1}}catch(r){n=r;f=2;break}case 5:try{if(1!=e){f=6;break}f=-1;throw q;}catch(r){n=r;f=2;break}case 6:try{if(k=l=p)k.userData=u,d.spellcheckDone(k)}catch(r){n=r;f=2;break}case 4:try{f=3;break}catch(r){n=r;f=2;break}case 2:h=n,Logger.instance.error(h);case 3:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,k,l,g,n,u,m,p={next:function(a){return e(0,
a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();p[Symbol.iterator]=function(){return this};return p}())};
CWEBackgroundManager.prototype.guessesAvailable=function(a){Logger.instance.log("------------- CWEBackgroundManager.guessesAvailable: "+a);Logger.instance.log(this.m_tabs);Logger.instance.log(this.m_activeTabId);a.userData.tabId===this.m_activeTabId&&-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port&&(a={message:"com.donjohnston.cowriter.chrome.message.guessesAvailable",guesses:a.guesses,replacements:a.replacements,requestId:a.userData.requestId},this.m_tabs[this.m_activeTabId].port.port().postMessage(a))};
CWEBackgroundManager.prototype.spellcheckDone=function(a){if(a.matchFound&&a.userData.tabId===this.m_activeTabId){var b=this;dji.translator.translateWord(CWESettings.instance.translationSource(),this.localeLang(),a.word,function(c){c&&0<c.length&&a.userData.tabId===b.m_activeTabId&&-1!==b.m_activeTabId&&b.m_tabs[b.m_activeTabId].port&&(c={message:"com.donjohnston.cowriter.chrome.message.translationsAvailable",translations:c,requestId:a.userData.requestId},b.m_tabs[b.m_activeTabId].port.port().postMessage(c))})}};
CWEBackgroundManager.prototype.replaceText=function(a,b,c){-1!==this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.replaceText",info:{selection:{start:a,end:b},text:c}})};CWEBackgroundManager.prototype.settingsChangedPredictionGuesses=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.setMaxPredictedGuesses(a)};
CWEBackgroundManager.prototype.settingsChangedPredictionMainDictionary=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.setMainDictionary(a)};CWEBackgroundManager.prototype.settingsChangedPredictionMomentaryTopic=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.enableMomentaryTopic(a)};CWEBackgroundManager.prototype.settingsChangedPredictionFlexibleSpelling=function(a){CWEPredictionEngine.instance&&CWEPredictionEngine.instance.enableFlexibleSpelling(a)};
CWEBackgroundManager.prototype.topicCreated=function(a){Logger.instance.log("------------------------- CWEBackgroundManager.topicCreated:");Logger.instance.log(a);try{"create"===this.m_quickTopicActionInfo.action&&(Logger.instance.log(this.m_tabs),Logger.instance.log(this.m_quickTopicActionInfo.tabId),-1!=this.m_quickTopicActionInfo.tabId&&this.m_tabs[this.m_quickTopicActionInfo.tabId].port&&this.m_tabs[this.m_quickTopicActionInfo.tabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.topicCreated",
success:!0}),this.m_quickTopicActionInfo.action="")}catch(b){Logger.instance.log(b)}CWEPredictionEngine.instance.removeOptionsListener(this);return!0};
CWEBackgroundManager.prototype.changeLocale=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,e,k){for(;;)switch(d){case 0:if(b.m_loaded&&a!==b.m_locale){d=1;break}d=-1;return{value:void 0,done:!0};case 1:return b.onStopSpeak(),dji.speechRecognition.stop(),cwe.sync.stop(),cwe.sync.changeLanguage(null),b.leaveTestingMode(),b.__enterBusyState(),b.m_on=!1,b.m_restartReason="--options-language-change",b.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),
b.__enableInActiveTab(!1),b.__sendNotification("deactivated"),CWEPredictionEngine.instance.reset(),b.m_locale=localStorage.locale=a,b.m_userDirectory=b.m_userName+"-"+b.m_locale,d=2,{value:b.__changeUserDirectoryAsync(),done:!1};case 2:if(1!=c){d=3;break}d=-1;throw k;case 3:cwe.sync.changeLanguage(b.m_locale),cwe.sync.start(),b.setIcon({path:b.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),
b.__leaveBusyState(),b.reloadAppTabs(),d=-1;default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};CWEBackgroundManager.prototype.changeSpellcheckerLocale=function(a){this.m_loaded&&CWEPredictionEngine.instance.changeSpellcheckerLocale(a)};
CWEBackgroundManager.prototype.downloadPredictionResources=function(a,b){var c=this.m_localeMap[a];if(!a||!c)return b(!1);if("en-US"===c)return b(!0);var d=this,e=this.directories.common;jsdapi.resources.downloadLanguageResources(c,jsdapi.resources.Type.Prediction,e,{main:this.directories.mainDictionaries,topics:this.directories.predefinedTopicDictionaries},d.m_fileSystem,function(a){if(!a.errorCode)return b(!0);d.m_fileSystem.removeDirectory(e,function(){b(!1)})})};
CWEBackgroundManager.prototype.downloadHunspellLanguages=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,k){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a){jsdapi.resources.listAvailableLanguages(jsdapi.resources.Type.Hunspell,function(b){b=!b.errorCode&&b.languages?b.languages:[];for(var c=[].concat($jscomp.arrayFromIterable(CWEPredictionEngine.instance.spellcheckerBundledLanguages())),f={},e=0;e<c.length;e++){var g=c[e];f[g.language_code]=
g}for(e=0;e<b.length;e++)g=b[e],f.hasOwnProperty(g.language_code)||(c.push(g),f[g.language_code]=g);c.sort(function(a,b){return a.name.localeCompare(b.name)});d.m_translationLanguages=c;d.m_translationLanguagesMap=f;a()})}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEBackgroundManager.prototype.downloadHunspellResources=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:if(!CWEPredictionEngine.instance.spellcheckerHasBundledResource(a)&&""!=a){d=1;break}d=-1;return{value:!0,done:!0};case 1:return e=b,d=-1,{value:new Promise(function(b){var c=e.directories.hunspell;jsdapi.resources.downloadLanguageResources(a,jsdapi.resources.Type.Hunspell,c,{},e.m_fileSystem,function(a){if(!a.errorCode)return b(!0);
e.m_fileSystem.removeDirectory(c,function(){b(!1)})})}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEBackgroundManager.prototype.resetHunspellLanguages=function(){for(var a=[].concat($jscomp.arrayFromIterable(CWEPredictionEngine.instance.spellcheckerBundledLanguages())),b={},c=0;c<a.length;c++){var d=a[c];b[d.language_code]=d}a.sort(function(a,b){return a.name.localeCompare(b.name)});this.m_translationLanguages=a;this.m_translationLanguagesMap=b};
CWEBackgroundManager.prototype.__predictionEngineLocaleChanged=function(a){a?(Logger.instance.debug("Successful switched to locale "+this.m_locale),localStorage.locale=this.m_locale,CWEPredictionEngine.instance.updateFromUserSettingsAsync(),cwe.login.isLoggedIn()?this.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}):this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}),this.m_loaded=
!0,this.changeUser(this.m_userName)):Logger.instance.error("Failed switching to locale "+this.m_locale)};CWEBackgroundManager.prototype.reloadAppTabs=function(a){chrome.tabs.query({url:this.m_appOptionsUrlPattern},function(b){var c=!1;try{for(var d=0;d<b.length;d++)chrome.tabs.reload(b[d].id),c=!0}catch(e){Logger.instance.error(e)}a&&a(c)})};
CWEBackgroundManager.prototype.__prepareUserLanguages=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,n,l){for(;;)switch(e){case 0:b=b||function(){};if(a){e=1;break}e=-1;return{value:b(!0),done:!0};case 1:return e=2,{value:c.downloadHunspellLanguages(),done:!1};case 2:if(1!=d){e=3;break}e=-1;throw l;case 3:k=CWESettings.instance.translationSource();if(!k){e=4;break}e=5;return{value:c.downloadHunspellResources(k),done:!1};case 5:if(1!=d){e=6;break}e=-1;throw l;
case 6:(f=h=n)&&CWEPredictionEngine.instance.changeSpellcheckerLocale(k);case 4:c.__checkUserLanguage(a,b),e=-1;default:return{value:void 0,done:!0}}}var e=0,f,h,k,l={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();l[Symbol.iterator]=function(){return this};return l}())};
CWEBackgroundManager.prototype.__checkUserLanguage=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,g){for(;;)switch(e){case 0:b=b||function(){};if(a){e=1;break}e=-1;return{value:b(!0),done:!0};case 1:f=c,jsdapi.cow.getLanguage(a.openID,function(a){return $jscomp.executeAsyncGenerator(function(){function c(c,k,l){for(;;)switch(d){case 0:Logger.instance.log("REMOTE LANGUAGE: "+a);Logger.instance.log("LOCALE LANGUAGE: "+f.m_locale);if("BE"!==a){d=1;break}a="UK";
try{return d=4,{value:jsdapi.cow.updateLanguageAsync(a),done:!1}}catch(w){h=w;d=2;break}case 4:try{if(1!=c){d=5;break}d=-1;throw l;}catch(w){h=w;d=2;break}case 5:try{d=3;break}catch(w){h=w;d=2;break}case 2:g=h,Logger.instance.error(g);case 3:case 1:e=f.findValidLanguage(a),f.downloadPredictionResources(e,function(c){return $jscomp.executeAsyncGenerator(function(){function d(d,h,k){for(;;)switch(g){case 0:if(!c||!a||a!==e||a!==f.m_locale){g=1;break}setTimeout(b,0,!0);g=2;break;case 1:if(!c||!a||a!==
e){g=3;break}f.m_locale=localStorage.locale=a;g=5;return{value:f.__changeUserDirectoryAsync(),done:!1};case 5:if(1!=d){g=6;break}g=-1;throw k;case 6:setTimeout(b,0,!0);g=4;break;case 3:a=f.m_defaultLocale,jsdapi.cow.updateLanguage(a,function(a){setTimeout(b,0,!0)});case 4:case 2:g=-1;default:return{value:void 0,done:!0}}}var g=0,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=
function(){return this};return h}())}),d=-1;default:return{value:void 0,done:!0}}}var d=0,e,g,h,k={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())}),e=-1;default:return{value:void 0,done:!0}}}var e=0,f,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
CWEBackgroundManager.prototype.__validateTranslationSource=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,l){for(;;)switch(c){case 0:e=a.localeLang(!1),d=(CWESettings.instance.translationSource()||"").split("-")[0],e===d&&CWESettings.instance.translationSource(null),c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
f[Symbol.iterator]=function(){return this};return f}())};
CWEBackgroundManager.prototype.changeUser=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,f,l){for(;;)switch(e){case 0:if(c.m_userName!==a){e=1;break}if(b)try{b()}catch(g){Logger.instance.error(g)}e=-1;return{value:void 0,done:!0};case 1:return c.m_loaded&&c.setIcon({path:{19:"/Graphics/CoWriterIcon-Loading_19.png",38:"/Graphics/CoWriterIcon-Loading_38.png"}}),cwe.sync.stop(),CWEPredictionEngine.instance.reset(),c.m_userName=a,e=2,{value:c.__changeUserDirectoryAsync(),
done:!1};case 2:if(1!=d){e=3;break}e=-1;throw l;case 3:c.m_loaded&&(cwe.login.isLoggedIn()?(c.m_on&&c.__enableInActiveTab(!0),c.setIcon({path:c.m_on?{19:"/Graphics/CoWriterIcon-Active_19.png",38:"/Graphics/CoWriterIcon-Active_38.png"}:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}})):c.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}}));cwe.sync.changeLanguage(c.m_locale);c.reloadAppTabs();if(b)try{b()}catch(g){Logger.instance.error(g)}e=
-1;default:return{value:void 0,done:!0}}}var e=0,f={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEBackgroundManager.prototype.__changeUserDirectoryAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,k){for(;;)switch(c){case 0:return d=a,a.m_userDirectory=a.m_userName+"-"+a.m_locale,c=-1,{value:new Promise(function(a){CWEDataManager.instance.changeUser(d.m_userDirectory,function(){CWESettings.instance.reload(d.m_userDirectory,function(){a()})})}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEBackgroundManager.prototype.signOut=function(a){var b=this;this.onStopSpeak();dji.speechRecognition.stop();this.leaveTestingMode();b.m_on&&(b.m_on=!1,b.setIcon({path:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),b.__enableInActiveTab(b.m_on));cwe.sync.stop();cwe.login.silentSignout(function(c){if(c)b.resetHunspellLanguages(),cwe.sync.changeLanguage(null),b.m_fileSystem.removeDirectory("/Users",function(){b.__saveUserInfo(function(){b.changeUser("DefaultUser",
function(){b.setIcon({path:{19:"/Graphics/CoWriterIcon-NotLoggedIn_19.png",38:"/Graphics/CoWriterIcon-NotLoggedIn_38.png"}})})});if(a)try{a(c)}catch(d){Logger.instance.error(d)}a&&b.__reloadRelatedWebsites(!1)});else if(cwe.sync.start(),a)try{a(c)}catch(d){Logger.instance.error(d)}})};
CWEBackgroundManager.prototype.__saveUserInfo=function(a){var b=cwe.login.userInfo();b=b?JSON.stringify(b):"";b=CryptoJS.AES.encrypt(b,"4$W%(WSFKS%W$W$@$%WMsdfsi042");this.m_fileSystem.writeFile("/info",b,function(){a&&a()})};CWEBackgroundManager.prototype.__loadUserInfo=function(a){cwe.login.userInfo()?a&&a():this.__readUserInfo(function(b){b&&cwe.login.userInfo(b);a&&a()})};
CWEBackgroundManager.prototype.__readUserInfo=function(a){this.m_fileSystem.readFileAsBinaryString("/info",function(b){var c=null;if(b&&0<b.length)try{(b=CryptoJS.AES.decrypt(b,"4$W%(WSFKS%W$W$@$%WMsdfsi042"))&&0<b.sigBytes&&(c=JSON.parse(CryptoJS.enc.Utf8.stringify(b)))}catch(d){Logger.instance.error(d)}a(c)})};
CWEBackgroundManager.prototype.__removeUserData=function(a,b){if(a){var c=this;this.m_fileSystem.removeDirectory("/Users",function(){c.m_userName="DefaultUser";c.m_userDirectory=c.m_userName+"-"+c.m_locale;CWEDataManager.instance.changeUser(c.m_userDirectory,function(){c.__removeUserInfo(function(){if(b)try{b()}catch(d){Logger.instance.error(d)}})})})}else b&&b()};CWEBackgroundManager.prototype.__removeUserInfo=function(a){this.m_fileSystem.removeFile("/info",function(){a&&a()})};
CWEBackgroundManager.prototype.tryEnterTestingMode=function(a){if(cwe.login.isLoggedIn()){var b=CWESettings.instance;if(a){if(!b.isInTestingMode(a))return!0}else b.isInTestingMode()&&b.leaveTestingMode()&&this.__onUserSettingsSynced()}return!1};CWEBackgroundManager.prototype.enterTestingMode=function(a){return cwe.login.isLoggedIn()&&CWESettings.instance.enterTestingMode(a)?!0:!1};
CWEBackgroundManager.prototype.leaveTestingMode=function(){return cwe.login.isLoggedIn()?CWESettings.instance.leaveTestingMode():!1};CWEBackgroundManager.prototype.isInTestingMode=function(){return cwe.login.isLoggedIn()?CWESettings.instance.isInTestingMode():!1};CWEBackgroundManager.prototype.allowChanges=function(){return cwe.login.isLoggedIn()?CWESettings.instance.allowChanges():["<none>"]};
CWEBackgroundManager.prototype.__onUserSettingsSynced=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,h,g){for(;;)switch(c){case 0:CWEPredictionEngine.instance&&(CWEPredictionEngine.instance.cacheTopics(),CWEPredictionEngine.instance.updateFromUserSettingsAsync());a.__applySettingsInActiveTab();a.reloadAppTabs();f=CWESettings.instance.translationSource();if(!f){c=1;break}c=2;return{value:a.downloadHunspellResources(f),done:!1};case 2:if(1!=b){c=3;break}c=-1;throw g;
case 3:(d=e=h)&&CWEPredictionEngine.instance&&CWEPredictionEngine.instance.changeSpellcheckerLocale(f);case 1:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e,f,h={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
CWEBackgroundManager.prototype.__onTopicsSynced=function(a,b){CWEPredictionEngine.instance&&(a||b?CWEPredictionEngine.instance.reloadDictionaries(a,b):CWEPredictionEngine.instance.rebuildTopicsCache())};
CWEBackgroundManager.prototype.onFilesChanged=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,f,l){for(;;)switch(c){case 0:e={};for(f=0;f<a.length;f++){var g=a[f];e.hasOwnProperty(g.type)?e[g.type].push(g):e[g.type]=[g]}if(!e.hasOwnProperty("dictionary/user")){c=1;break}c=2;return{value:CWEDataManager.instance.updateDictionaries(e["dictionary/user"]),done:!1};case 2:if(1!=b){c=3;break}c=-1;throw l;case 3:case 1:if(!e.hasOwnProperty("dictionary/user/personal")){c=4;break}d=
e["dictionary/user/personal"][0];c=5;return{value:CWEDataManager.instance.updatePersonalDictionary(d.filePath,d.name,d.type,d.language),done:!1};case 5:if(1!=b){c=6;break}c=-1;throw l;case 6:case 4:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEBackgroundManager.prototype.onTopicActivated=function(a){CWESettings.instance.data().addActiveTopic(a)&&CWESettings.instance.save()};CWEBackgroundManager.prototype.onTopicDeactivated=function(a){CWESettings.instance.data().removeActiveTopic(a)&&CWESettings.instance.save()};
CWEBackgroundManager.prototype.onTopicCreated=function(a,b){a&&0<a.length&&(b=CWESettings.instance.data().addOnlyMissingTopics(b),(b=CWESettings.instance.data().addRecentTopic(a)||b)&&CWESettings.instance.save());if(this.m_loaded&&this.m_on&&0<this.m_activeTabId&&this.m_tabs[this.m_activeTabId].port)try{this.m_tabs[this.m_activeTabId].port.port().postMessage({message:"com.donjohnston.cowriter.chrome.message.topics.update"})}catch(c){Logger.instance.error(c)}};
CWEBackgroundManager.prototype.activateLocaleRequiresReboot=function(){this.m_localeRequiresReboot=!0;this.m_loaded=!1;this.reloadAppTabs(function(a){a||chrome.tabs.create({url:"/Options/options.html",active:!0})})};CWEBackgroundManager.prototype.findValidLanguage=function(a){return"BE"===a||"CAN"===a||"UK"===a||"US"===a||"FR"===a||"SPA"===a||"GER"===a?a:"US"};
CWEBackgroundManager.prototype.prepareSpeechRecognitionInfo=function(a){if(!a)return null;a=this.m_localeMap.hasOwnProperty(a)?this.m_localeMap[a]:a;var b=a.split("-")[0],c=dji.languages.languageInfo(b);return{langCode:a,langShortName:b.toUpperCase(),langFullName:c?c.name:a}};CWEBackgroundManager.prototype.applyActivationCode=function(a,b){jsdapi.account.applyActivationCode({activationCode:a},b)};
CWEBackgroundManager.prototype.loadConfig=function(a){this.m_fileSystem.readFile("env.config",function(b){if(b)try{var c=JSON.parse(b),d=c.configName;for(b=0;b<c.configs.length;b++){var e=c.configs[b];e.name===d&&dji.config.update(e)}}catch(f){Logger.instance.error(f)}jsdapi.http.setup({headers:{"x-dji-app-product":"cowriter","x-dji-app-platform":"chrome-extension","x-dji-app-os":dji.utils.os().name,"x-dji-app-extension-id":chrome.runtime.id}});jsdapi.translator.setUrls({server:dji.config.translateUrl()});
jsdapi.cow.setUrls({dapi:dji.config.dapiUrl()});jsdapi.resources.setUrls({resources:dji.config.resourcesUrl(),dapi:dji.config.dapiUrl()});jsdapi.setServerUrl({login:dji.config.loginUrl(!0),dapi:dji.config.dapiUrl()});jsdapi.setRefreshTokenDelegate(cwe.login.silentRefreshToken);jsdapi.setClientId(dji.config.clientID());a()})};CWEBackgroundManager.prototype.imeActivationChanged=function(a){a?cwe.measure.startTimeTracker():cwe.measure.stopTimeTracker()};
CWEBackgroundManager.prototype.accumulateAndMeasureData=function(a){cwe.measure.accumulateAndMeasureData(a)};CWEBackgroundManager.prototype.measurementResults=function(a){return cwe.measure.measurementResults(a)};CWEBackgroundManager.prototype.resetMeasurement=function(){return cwe.measure.reset()};
CWEBackgroundManager.prototype.toggleSpeechRecognition=function(a,b,c,d,e){if(!b)return dji.speechRecognition.stop();var f=(b="dictation"===d)?this.localeLang():void 0,h=b?CWESettings.instance.translationSource():void 0,k=b&&c===h;this.onStopSpeak();c=c||this.locale();dji.speechRecognition.start(c,function(b,c){chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.speechRecognitionNotification",details:b,scope:b.scope,session:c.session})},function(b,c){k&&!b.error?dji.translator.translateText(h,
f,b.text,function(d){d&&0<d.length&&chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.speechRecognitionProgress",error:b.error,text:d,scope:b.scope,session:c.session})}):chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.speechRecognitionProgress",error:b.error,text:b.text,scope:b.scope,session:c.session})},function(b,c){chrome.tabs.sendMessage(a,{message:"com.donjohnston.cowriter.chrome.message.speechRecognitionEnd",error:b.error,scope:b.scope,session:c.session})},
{tabId:a,scope:d,session:e})};
CWEBackgroundManager.prototype.translateHtmlDocument=function(a){for(var b=$(a).find("[dji-i18n]"),c=0;c<b.length;c++){var d=$(b[c]),e=d.attr("dji-i18n");e&&""!==e&&(e=chrome.i18n.getMessage(e))&&""!==e&&d.text(e)}b=$(a).find("[dji-i18n-html]");for(c=0;c<b.length;c++)d=$(b[c]),(e=d.attr("dji-i18n-html"))&&""!==e&&(e=chrome.i18n.getMessage(e))&&""!==e&&d.html(e);b=$(a).find("[dji-i18n-placeholder]");for(c=0;c<b.length;c++)d=$(b[c]),(e=d.attr("dji-i18n-placeholder"))&&""!==e&&(e=chrome.i18n.getMessage(e))&&
""!==e&&d.attr("placeholder",e);b=$(a).find("[dji-i18n-title]");for(a=0;a<b.length;a++)c=$(b[a]),(d=c.attr("dji-i18n-title"))&&""!==d&&(d=chrome.i18n.getMessage(d))&&""!==d&&c.attr("title",d)};CWEBackgroundManager.prototype.onOptions=function(){var a=this.m_appOptions;chrome.tabs.query({url:this.m_appOptionsUrlPattern},function(b){if(b&&0<b.length){try{for(var c=0;c<b.length;c++)chrome.tabs.reload(b[c].id)}catch(d){}chrome.tabs.update(b[0].id,{active:!0})}else chrome.tabs.create({url:a,active:!0})})};
CWEBackgroundManager.prototype.onCreateTopicFromPage=function(){this.onCreateTopic(!1)};CWEBackgroundManager.prototype.onCreateTopicFromSelection=function(){this.onCreateTopic(!0)};
CWEBackgroundManager.prototype.onCreateTopic=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,n,l){for(;;)switch(d){case 0:if(b.m_loaded){d=1;break}d=-1;return{value:void 0,done:!0};case 1:return d=2,{value:b.__getCurrentTab(),done:!1};case 2:if(1!=c){d=3;break}d=-1;throw l;case 3:if(h=k=n){d=4;break}d=-1;return{value:void 0,done:!0};case 4:return d=5,{value:b.__ensurePredictionEngineInitialized(),done:!1};case 5:if(1!=c){d=6;break}d=-1;throw l;case 6:if(e=f=n){d=
7;break}Logger.instance.error("Failed to initialize the prediction engine!");d=-1;return{value:void 0,done:!0};case 7:try{chrome.tabs.sendMessage(h.id,{message:"com.donjohnston.cowriter.chrome.message.topics.create",params:{from:a?"selection":"page",locale:b.m_locale,isEnglish:CWEPredictionEngine.isEnglish(),topics:CWEPredictionEngine.instance.allTopics(),activeTopics:CWESettings.instance.topicsActive(),recentTopics:CWESettings.instance.topicsRecent(),displayTopics:b.displayTopics()}})}catch(m){Logger.instance.error(m)}d=
-1;default:return{value:void 0,done:!0}}}var d=0,e,f,h,k,l={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();l[Symbol.iterator]=function(){return this};return l}())};
CWEBackgroundManager.prototype.__ensurePredictionEngineInitialized=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,k){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a){var b=function(){d.__initializePredictionEngine(function(c,d){c?setTimeout(a,0,c):d?setTimeout(a,0,c):setTimeout(b,500)})};b()}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};CWEBackgroundManager.prototype.__predictionEngineCrashed=function(a){dji.notifications.show({message:"Co:Writer has encountered an error! Please reactivate it after a few moments!",noUuid:!1});this.m_on&&(this.m_on=!1,this.setIcon({path:{19:"/Graphics/CoWriterIcon-NotActive_19.png",38:"/Graphics/CoWriterIcon-NotActive_38.png"}}),this.__enableInActiveTab(!1));this.reloadAppTabs()};
CWEBackgroundManager.prototype.__getCurrentTab=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,g,m){for(;;)switch(c){case 0:l=null;try{return c=3,{value:a.__getCurrentWindow(),done:!1}}catch(p){k=p;c=1;break}case 3:try{if(1!=b){c=4;break}c=-1;throw m;}catch(p){k=p;c=1;break}case 4:try{return f=h=g,c=5,{value:a.__getCurrentTabFromWindowId(f.id),done:!1}}catch(p){k=p;c=1;break}case 5:try{if(1!=b){c=6;break}c=-1;throw m;}catch(p){k=p;c=1;break}case 6:try{l=e=g;c=2;
break}catch(p){k=p;c=1;break}case 1:d=k,Logger.instance.error(d);case 2:return c=-1,{value:l,done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e,f,h,k,l,g={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
CWEBackgroundManager.prototype.__getCurrentTabFromWindowId=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,d,h){for(;;)switch(c){case 0:return c=-1,{value:new Promise(function(b,c){chrome.tabs.getSelected(a,function(a){return $jscomp.executeAsyncGenerator(function(){function d(d,f,g){for(;;)switch(e){case 0:if(a&&a.id&&!(0>=a.id)){e=1;break}e=-1;return{value:c(),done:!0};case 1:b(a),e=-1;default:return{value:void 0,done:!0}}}var e=0,f={next:function(a){return d(0,a,void 0)},
throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())})}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();d[Symbol.iterator]=function(){return this};return d}())};
CWEBackgroundManager.prototype.__getCurrentWindow=function(){return $jscomp.executeAsyncGenerator(function(){function a(a,c,f){for(;;)switch(b){case 0:return b=-1,{value:new Promise(function(a,b){var c=function(d){chrome.windows.getAll({windowTypes:["normal","popup"],populate:!1},function(e){if(e)for(var f=0;f<e.length;f++){var g=e[f];if(g.focused)return a(g)}if(10<d)return b();setTimeout(c,10,d+1)})};c(1)}),done:!0};default:return{value:void 0,done:!0}}}var b=0,c={next:function(b){return a(0,b,void 0)},
throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();c[Symbol.iterator]=function(){return this};return c}())};
CWEBackgroundManager.prototype.setIcon=function(a){var b=CWEBackgroundManager.prototype.setIcon.session||(CWEBackgroundManager.prototype.setIcon.session={session:0,active:!1,queue:[]});b.session++;b.queue.push({session:b.session,details:a});if(!b.active){var c=function(){0>=b.queue.length?b.active=!1:chrome.browserAction.setIcon(b.queue.pop().details,c)};b.active=!0;c()}};
