(function(l){function K(a,b){if(navigator.onLine&&(!a.dapiFile||a.checksum!==a.dapiFile.checksum||b===d.Download)&&C(null,g.UserSettings,b)){var c=new DjiStorageFile(a.uuid,"Globar User Settings",n.settingsUser);c.creationDate=a.creationDate;c.lastModifiedDate=a.modifiedDate;c.lastModifiedUuid=a.modifiedUuid;c.checksum=a.checksum;c.revision=a.dapiFile?a.dapiFile.version:0;c.__custom={language:v};D({id:a.uuid,type:g.UserSettings,action:b,file:c,settings:a,body:null,checksum:c.checksum,session:null})}}
function I(a,b,c){navigator.onLine&&C(null,g.TestingSettings,c)&&((new DjiStorageFile(null,"Testing Settings",n.settingsTesting)).__custom={language:v},D({type:g.TestingSettings,action:c,state:a,test:b,session:null}))}function J(a,b){if(navigator.onLine&&C(a.uuid,g.Dictionary,b)){var c=new DjiStorageFile(a.uuid,a.title,n.userDictionaries);c.creationDate=a.creationDate;c.lastModifiedDate=a.modifiedDate;c.lastModifiedUuid=a.modifiedUuid;c.checksum=a.checksum;c.revision=a.dapiFile?a.dapiFile.version:
0;c.__custom={language:v,preview:a.preview};D({id:a.uuid,type:g.Dictionary,action:b,file:c,dictionary:a,checksum:c.checksum,session:null})}}function L(a,b){if(navigator.onLine&&C(a.uuid,g.Dictionary,b)){var c=new DjiStorageFile(a.uuid,a.title,n.userPersonalWords);c.creationDate=a.creationDate;c.lastModifiedDate=a.modifiedDate;c.lastModifiedUuid=a.modifiedUuid;c.checksum=a.checksum;c.revision=a.dapiFile?a.dapiFile.version:0;c.__custom={language:v,preview:a.preview};D({id:a.uuid,type:g.PersonalDictionary,
action:b,file:c,dictionary:a,checksum:c.checksum,session:null})}}function C(a,b,c){a:{for(var d=0;d<h.length;d++){var k=h[d];if((null===a||k.id===a)&&k.type===b&&k.action===c){a=d;break a}}a=-1}if(-1!==a){if(h[a].session)return!1;h.splice(a,1)}return!0}function D(a){if(a.action==d.Insert||a.action==d.Update||a.action==d.Delete){for(var b=0;b<h.length;b++){var c=h[b];if(c.action!=d.Insert&&c.action!=d.Update&&c.action!=d.Delete)break}h.splice(b,0,a)}else h.push(a);1!=h.length||u!=t.Idle||z||x()}function x(a){q&&
(y&&(clearTimeout(y),y=null),y=setTimeout(S,a||!z&&0<h.length?10:3E4))}function S(){u=t.Busy;y&&(clearTimeout(y),y=null);if(q){if(z||!navigator.onLine)u=t.Idle,x();var a=null;do a&&0<h.length&&h.splice(0,1),a=0<h.length?h[0]:null;while(a&&!0===F[a.type]);null===a?T():a.type===g.DataWordList?U(a):a.type===g.MeasuredData?V(a):a.type===g.PersonalDictionary?W(a):a.type===g.Dictionary?X(a):a.type===g.UserSettings?Y(a):a.type===g.TestingSettings?Z(a):(h.splice(h.indexOf(a),1),u=t.Idle,x())}else u=t.Idle}
function T(){var a=f,b=null,c=null,h=null,k=null,G=null,e=!1,w=null,l=!0===F[g.UserSettings]||CWEBackgroundManager.instance.isInTestingMode(),r=[{type:n.userPersonalWords,language:v},{type:n.userDictionaries,language:v},{type:n.testingMode},{type:n.userLanguage},{type:n.privacyMode}];l||r.unshift({type:n.settingsUser,language:v});r.unshift({type:n.dataWordList});var q=function(a){var b=!0;if(e){if(navigator.onLine&&(b=d.Download,C(null,g.DataWordList,b))){var f=new DjiStorageFile(null,null,n.dataWordList);
f.__custom={language:v};D({type:g.DataWordList,action:b,file:f,body:null,session:null})}b=!1}if(w){f=w.data;var r=w.uuid;if(navigator.onLine){var m=d.Update;C(null,g.MeasuredData,m)&&D({type:g.MeasuredData,action:m,body:f,uuid:r,session:null})}}h&&(h.filesToDownload&&0<h.filesToDownload.length?(L(h.filesToDownload[0],d.Download),b=!1):h.filesToUpload&&0<h.filesToUpload.length&&(f=h.filesToUpload[0],L(f,f.dapiFile?d.Update:d.Insert),b=!1));if(k){if(k.filesToDownload){for(r=0;r<k.filesToDownload.length;r++)f=
k.filesToDownload[r],J(f,d.Download);b=b&&0==k.filesToDownload.length}if(k.filesToUpload){for(r=0;r<k.filesToUpload.length;r++)f=k.filesToUpload[r],J(f,f.dapiFile?d.Update:d.Insert);b=b&&0==k.filesToUpload.length}if(k.filesToDelete){for(r=0;r<k.filesToDelete.length;r++)f=k.filesToDelete[r],J(f,d.Delete);b=b&&0==k.filesToDelete.length}}c&&(c.filesToDownload&&0<c.filesToDownload.length?(K(c.filesToDownload[0],d.Download),b=!1):c.filesToUpload&&0<c.filesToUpload.length&&(b=c.filesToUpload[0],K(b,b.dapiFile?
d.Update:d.Insert),b=!1));a&&CWEBackgroundManager.instance.tryEnterTestingMode(G)&&(I(null,G,d.Download),b=!1);A<=B?(A=Math.min(4,A+1),B=0):B++;a&&!b&&(B=A=0);u=t.Idle;x()},P=function(a){p.prepareMeasuredDataForSync(function(e,b){e&&b&&(w={data:e,uuid:b});q(a)})},y=function(e){for(var b=e.files[n.userDictionaries],c={},d=0;d<b.length;d++)c[b[d].id]=b[d].__custom;p.updateDictionariesFromDapiFileMap(c,function(b,c){a===f&&(k=c,c=e.files[n.testingMode],G=(c=1===c.length?c[0].__custom:null)&&c.comment&&
0<c.comment.length?c.comment:null,P(!0),b&&M())})},z=function(e){var b=e.files[n.userPersonalWords];p.updatePersonalDictionariesFromDapiFileMap(1===b.length?b[0].__custom:null,function(b,c){a===f&&(h=c,y(e))})},E=function(e){var b=e.files[n.settingsUser];p.updateUserSettingsFromDapiFileMap(1===b.length?b[0].__custom:null,function(b,d){a===f&&(c=d,z(e))})},H=function(a){var c=a.files[n.privacyMode];b=(c=c&&1===c.length?c[0].__custom:null)?"on"===c.comment:!1;p.enablePrivacyMode(b,function(){var b=
a.files[n.dataWordList];p.checkDataWordListNeedsDownload(1===b.length?b[0].__custom:null)&&(e=!0);l?z(a):E(a)})};A<=B?m.checkForUpdates(r,function(b){a===f&&(b&&0===b.errorCode&&b.files?H(b):q())}):P(!1)}function U(a){a.session=f;var b=function(){if(a.session===f){var b=h.indexOf(a);-1!=b&&h.splice(b,1);u=t.Idle;x()}};m.getDataWordList(a.language,function(a){!a||a.error?b():p.updateDataWordList(a,b)})}function V(a){a.session=f;var b=function(){if(a.session===f){var b=h.indexOf(a);-1!=b&&h.splice(b,
1);u=t.Idle;x()}};m.updateMeasurements(a.body,function(c){!c||c.error?p.measuredDataSyncDone(!1,a.uuid,b):p.measuredDataSyncDone(!0,a.uuid,b)})}function Y(a){a.session=f;var b=function(){if(a.session===f){var b=h.indexOf(a);-1!=b&&h.splice(b,1);u=t.Idle;x()}},c=function(e){a.session===f&&(e&&0===e.errorCode&&e.file&&e.file.__custom?(e=e.file.__custom,p.updateUserSettingsFromDapi(e,a.checksum!==e.checksum,null,function(a){b()})):b())},g=function(e,c){a.session===f&&e&&c?p.updateUserSettingsFromDapi(e,
!1,c,function(a){a&&Q();b()}):b(null)},k=function(e,w){a.session===f&&(a.action==d.Download?e&&w?g(e,w):b():(e&&(a.file.id=e.uuid,a.file.revision=e.version,a.action==d.Insert&&e&&(a.action=d.Update)),w=a.settings.createUploadData(w),a.file.checksum=w.checksum,a.body=w.data,a.action==d.Insert?m.insertFile(a.file,a.body,c):a.action==d.Update&&m.updateFile(a.file,a.body,c)))},G=function(b){m.getFiles(a.file.type,v,function(b){if(a.session===f)if(b&&0===b.errorCode&&b.files&&1===b.files.length){var e=
b.files[0];e.__responseType="json";m.downloadFile(e,function(a){k(e.__custom,a)})}else k(null,null)})};a.action==d.Insert||a.action==d.Update?G():a.action==d.Download?(a.file.__responseType="json",m.downloadFile(a.file,function(a,b){k(b?b.__custom:null,a)})):(Logger.instance.error("Sync Settings: unsupported action!!!!"),Logger.instance.error(a),b())}function Z(a){a.session=f;var b=E(a.state,a.test),c=E(a.state,null),d=E(null,a.test),k=E(null,null),g=[b];-1==g.indexOf(c)&&g.push(c);-1==g.indexOf(d)&&
g.push(d);-1==g.indexOf(k)&&g.push(k);b=[];for(c=0;c<g.length;c++)b.push({type:g[c],language:v});var e=function(b){b&&Q();b=h.indexOf(a);-1!=b&&h.splice(b,1);u=t.Idle;x()},w=function(b,c){a.session===f&&(c?CWEBackgroundManager.instance.enterTestingMode(a.test)?p.updateTestingSettingsFromDapi(b,c,function(b){a.session===f&&e(b)}):e():e())},l=function(a,b){a.__responseType="json";m.downloadFile(a,function(b){w(a.__custom,b)})};m.checkForUpdates(b,function(a){var b=null;if(a&&0===a.errorCode&&a.files)for(var c=
0;c<g.length;c++)if(a.files.hasOwnProperty(g[c])){b=(b=a.files[g[c]])&&1==b.length?b[0]:null;break}b?l(b):e()})}function W(a){a.session=f;var b=function(){if(a.session===f){var b=h.indexOf(a);-1!=b&&h.splice(b,1);u=t.Idle;x()}},c=function(e,c){a.session===f&&e&&c?p.updatePersonalDictionaryFromDapi(e,!1,c,function(){M(!0,!1);b()}):b(null)},g=function(c){a.session===f&&(c&&0===c.errorCode&&c.file&&c.file.__custom?(c=c.file.__custom,p.updatePersonalDictionaryFromDapi(c,a.checksum!==c.checksum,null,function(){b()})):
b())},k=function(c){c?a.action==d.Insert?m.insertFile(a.file,c,g):a.action==d.Update&&m.updateFile(a.file,c,g):b()},l=function(e){a.session===f&&(a.action==d.Delete?(a.file.revision=e.revision,m.deleteFile(a.file,!0,function(a){b()})):a.action==d.Download?m.downloadFile(a.file,function(a){c(e,a)}):(e&&(a.file.id=e.uuid,a.file.revision=e.version,a.action==d.Insert&&e&&(a.action=d.Update)),a.body?k(a.body):p.readUserPersonalDictionaryFile(k)))};a.action==d.Insert||a.action==d.Update?function(){m.getFiles(a.file.type,
v,function(b){a.session===f&&(b&&0===b.errorCode&&b.files&&1===b.files.length?l(b.files[0].__custom):l(null))})}():a.action==d.Download?m.downloadFile(a.file,function(a,b){c(b?b.__custom:null,a)}):b()}function X(a){a.session=f;var b=function(){if(a.session===f){var b=h.indexOf(a);-1!=b&&h.splice(b,1);u=t.Idle;x()}},c=function(c){a.session===f&&(c&&0===c.errorCode&&c.file&&c.file.__custom?(c=c.file.__custom,p.updateDictionaryFromDapi(c,a.checksum!==c.checksum,null,b)):b())},g=function(e){e?a.action==
d.Insert?m.insertFile(a.file,e,c):a.action==d.Update&&m.updateFile(a.file,e,c):b()},k=function(c,d){a.session===f&&c&&d?p.updateDictionaryFromDapi(c,!1,d,function(){M(!1,!0);b()}):b()},l=function(c){a.session===f&&(c&&0===c.errorCode&&c.file&&c.file.__custom?a.action==d.Delete?(a.file.revision=c.file.revision,m.deleteFile(a.file,!0,function(a){b()})):m.downloadFile(a.file,function(a){k(c.file.__custom,a)}):b())};a.action==d.Insert||a.action==d.Update?a.body?g(a.body):p.readUserDictionaryFile(a.dictionary.uuid,
g):a.action==d.Delete?m.getFile(a.file,l):a.action==d.Download&&m.downloadFile(a.file,function(a,b){k(b?b.__custom:null,a)})}function Q(){for(var a=0;a<H.length;a++)try{H[a]()}catch(b){Logger.instance.error(b)}}function M(a,b){for(var c=0;c<N.length;c++)try{N[c](a,b)}catch(R){Logger.instance.error(R)}}function O(){return f=CWEChromeUtilities.generateUUID()}function E(a,b){return n.settingsTesting.replace("[STATE]",a||"generic").replace("[TEST]",b||"generic")}var g={None:0,Writing:1,Image:2,PersonalDictionary:3,
Dictionary:4,UserSettings:5,TestingSettings:6,DataWordList:7,MeasuredData:8},d={None:0,Insert:1,Update:2,Delete:3,Download:4},t={Idle:0,Busy:1},v=null,f=O(),m=window.jsdapi.cow,p=null,H=[],N=[],h=[],y=null,B=0,A=0,u=t.Idle,q=!1,z=!1,F={},n={settingsUser:"settings/user",settingsTesting:"settings/testing/[STATE]/[TEST]",writings:"writing/*",userPersonalWords:"dictionary/user/personal",userDictionaries:"dictionary/user",images:"image/*",testingMode:"settings/testing/mode",userLanguage:"settings/user/language",
dataWordList:"data/word/list",privacyMode:"settings/privacy/mode"};l.ItemType=g;l.setDataManager=function(a){p=a};l.changeLanguage=function(a){a=a?a.toLowerCase():null;if(a!==v){var b=q;q&&l.stop();v=a;b&&l.start()}};l.start=function(){q||(O(),q=!0,z=!1,u=t.Idle,F={},A=B=0,x(!0))};l.stop=function(){q&&(O(),q=z=!1,u=t.Idle,h.splice(0,h.length),F={},A=B=0)};l.skipSync=function(a,b){F[a]=!0===b};l.addUserSettingsUpdateListener=function(a){H.push(a)};l.addDictionariesUpdateListener=function(a){N.push(a)};
l.enqueueUpdateUserSettings=function(a){q&&K(a,a.dapiFile?d.Update:d.Insert)};l.enqueueTestingSettingsPARCC=function(a){q&&I(a,"PARCC",d.Download)};l.enqueueTestingSettingsSmarterBalanced=function(a){q&&I(a,"SmarterBalanced",d.Download)};l.enqueueTestingSettings=function(a,b){q&&I(a,b,d.Download)};l.enqueueUpdateDictionary=function(a){q&&J(a,a.dapiFile?d.Update:d.Insert)};l.enqueueUpdatePersonalDictionary=function(a){q&&L(a,a.dapiFile?d.Update:d.Insert)}})(window.cwe.sync=window.cwe.sync||{});
