function CWEUserSettings(){this.version=1;this.hasText=!1;this.hasActiveTopics=!0;this.dapiData=this.dapiFile=this.downloadRequired=this.checksum=this.modifiedUuid=this.modifiedDate=this.creationDate=this.translation=this.topics=this.prediction=this.guessWindow=this.text=this.speech=this.uuid=null;this.reset()}
CWEUserSettings.prototype.reset=function(){this.os();this.uuid=CWEChromeUtilities.generateUUID();this.modifiedDate=0;this.speech={voice:dji.tts.defaultVoice(),rate:1,pitch:1,volume:1,letters:0,words:1,sentences:1};this.hasText&&(this.text={fontFamily:"Arial",fontSize:40,textColor:"#000000",backgroundColor:"#FFFFFF",marginSize:0});this.guessWindow={fontFamily:"Arial",fontSize:24,textColor:"#000000",backgroundColor:"#FFFFFF"};this.prediction={guesses:5,mainDictionary:0,momentaryTopic:1,flexibleSpelling:1,
grammar:1,ahead:1};this.topics={recent:[]};this.hasActiveTopics&&(this.topics.active=[]);this.translation={source:null};this.dapiData=this.dapiFile=this.checksum=null;this.fixVoice();this.fixTopics();this.fixPrediction();this.markAsModified()};
CWEUserSettings.prototype.fixVoice=function(){var a=CWEBackgroundManagerInstance().localeLang(!0);if(!dji.tts.hasVoiceForLanguage(CWEBackgroundManagerInstance().localeLang(),this.speech.voice)){a=dji.tts.defaultVoiceForLanguage(a);if(!a||0>=a.length)a=dji.tts.defaultVoice();this.speech.voice=a}};
CWEUserSettings.prototype.fixTopics=function(){var a=!1;this.topics&&(this.topics.recent&&CWEUserSettings.fixTopicList(this.topics.recent)&&(a=!0),this.hasActiveTopics&&this.app&&this.app.chromeExtension&&this.app.chromeExtension.topics&&this.app.chromeExtension.topics.active&&CWEUserSettings.fixTopicList(this.topics.active)&&(a=!0));return a};
CWEUserSettings.fixTopicList=function(a){var b=!1;if(a)for(var c=0;c<a.length;c++){var d=a[c];if("---MomentaryTopicDictionary---"===d||"---Momentary Topic Dictionary---"===d)a.splice(c,1),c--,b=!0}return b};CWEUserSettings.prototype.fixPrediction=function(){var a=!1;if(this.prediction){var b=parseInt(this.prediction.mainDictionary);0!==b&&4!==b&&5!==b&&(this.prediction.mainDictionary=0,a=!0)}return a};
CWEUserSettings.prototype.markAsModified=function(){var a=this.createUploadData(this.dapiData).checksum;this.checksum!==a&&(this.dapiFile&&this.dapiFile.checksum===a?this.updateFromLocalData(this.dapiFile):(null===this.creationDate&&(this.creationDate=Date.now()),this.modifiedDate=this.modifiedDate?Date.now():this.creationDate,this.modifiedUuid=CWEChromeUtilities.generateUUID(),this.checksum=a),this.downloadRequired=!1)};
CWEUserSettings.prototype.clone=function(){var a=new CWEUserSettings;a.version=this.version;a.hasText=this.hasText;a.hasActiveTopics=this.hasActiveTopics;a.uuid=this.uuid;a.speech=JSON.parse(JSON.stringify(this.speech));a.text=JSON.parse(JSON.stringify(this.text));a.guessWindow=JSON.parse(JSON.stringify(this.guessWindow));a.prediction=JSON.parse(JSON.stringify(this.prediction));a.topics=JSON.parse(JSON.stringify(this.topics));a.translation=JSON.parse(JSON.stringify(this.translation));a.creationDate=
this.creationDate;a.modifiedDate=this.modifiedDate;a.modifiedUuid=this.modifiedUuid;a.checksum=this.checksum;a.downloadRequired=this.downloadRequired;a.dapiFile=JSON.parse(JSON.stringify(this.dapiFile));a.dapiData=JSON.parse(JSON.stringify(this.dapiData));return a};
CWEUserSettings.prototype.updateFromLocalData=function(a){this.uuid=a?a.uuid:this.uuid;this.speech=a&&a.speech?a.speech:this.speech;this.prediction=a&&a.prediction?a.prediction:this.prediction;if(null===this.prediction.grammar||void 0===this.prediction.grammar)this.prediction.grammar=1;this.guessWindow=a&&a.guessWindow?a.guessWindow:this.guessWindow;this.hasText&&(this.text=a&&a.text?a.text:this.text);this.topics=a&&a.topics?a.topics:this.topics;this.translation=a&&a.translation?a.translation:this.translation;
this.creationDate=a&&a.creationDate?a.creationDate:this.creationDate;this.modifiedDate=a&&a.modifiedDate?a.modifiedDate:this.modifiedDate;this.modifiedUuid=a&&a.modifiedUuid?a.modifiedUuid:this.modifiedUuid;this.checksum=a&&a.checksum?a.checksum:this.checksum;this.downloadRequired=!(!a||!a.downloadRequired);this.dapiFile=a&&a.dapiFile?a.dapiFile:null;this.dapiData=a&&a.dapiData?a.dapiData:null;this.fixVoice();a=!1;this.fixTopics()&&(a=!0);this.fixPrediction()&&(a=!0);a&&this.markAsModified()};
CWEUserSettings.prototype.updateFromRemoteData=function(a,b,c){a&&(this.uuid=a.uuid,this.creationDate=a.creationDate,this.modifiedDate=a.modifiedDate,this.modifiedUuid=a.modifiedUuid,this.checksum=a.checksum,this.downloadRequired=!0,this.dapiFile=a);b&&(a=this.os(),a=(a=(b.platform&&b.platform.chrome?b.platform.chrome[a.name]:null)||null)?a.speech:null,b.common=b.common||{},a&&(this.speech.voice=a.voice||this.speech.voice,this.speech.rate=null===a.rate||void 0===a.rate?this.speech.rate:a.rate,this.speech.pitch=
null===a.pitch||void 0===a.pitch?this.speech.pitch:a.pitch,this.speech.volume=null===a.volume||void 0===a.volume?this.speech.volume:a.volume),b.common&&b.common.speech&&(this.speech.letters=null===b.common.speech.letters||void 0===b.common.speech.letters?this.speech.letters:b.common.speech.letters,this.speech.words=null===b.common.speech.words||void 0===b.common.speech.words?this.speech.words:b.common.speech.words,this.speech.sentences=null===b.common.speech.sentences||void 0===b.common.speech.sentences?
this.speech.sentences:b.common.speech.sentences),this.hasText&&b.common&&b.common.text&&(this.text={fontFamily:b.common.text.fontFamily||this.text.fontFamily,fontSize:null===b.common.text.fontSize||void 0===b.common.text.fontSize?this.text.fontSize:b.common.text.fontSize,textColor:b.common.text.textColor||this.text.textColor,backgroundColor:b.common.text.backgroundColor||this.text.backgroundColor,marginSize:null===b.common.text.marginSize||void 0===b.common.text.marginSize?this.text.marginSize:b.common.text.marginSize}),
b.common&&b.common.guessWindow&&(this.guessWindow={fontFamily:b.common.guessWindow.fontFamily||this.guessWindow.fontFamily,fontSize:null===b.common.guessWindow.fontSize||void 0===b.common.guessWindow.fontSize?this.guessWindow.fontSize:b.common.guessWindow.fontSize,textColor:b.common.guessWindow.textColor||this.guessWindow.textColor,backgroundColor:b.common.guessWindow.backgroundColor||this.guessWindow.backgroundColor}),b.common&&b.common.prediction&&(this.prediction={guesses:null===b.common.prediction.guesses||
void 0===b.common.prediction.guesses?this.prediction.guesses:b.common.prediction.guesses,mainDictionary:null===b.common.prediction.mainDictionary||void 0===b.common.prediction.mainDictionary?this.prediction.mainDictionary:b.common.prediction.mainDictionary,momentaryTopic:null===b.common.prediction.momentaryTopic||void 0===b.common.prediction.momentaryTopic?this.prediction.momentaryTopic:b.common.prediction.momentaryTopic,flexibleSpelling:null===b.common.prediction.flexibleSpelling||void 0===b.common.prediction.flexibleSpelling?
this.prediction.flexibleSpelling:b.common.prediction.flexibleSpelling,grammar:null===b.common.prediction.grammar||void 0===b.common.prediction.grammar?1:b.common.prediction.grammar},this.prediction.ahead=c?null===b.common.prediction.ahead||void 0===b.common.prediction.ahead?1:b.common.prediction.ahead:1),b.common&&b.common.topics&&(b.common.topics.recent&&(this.topics.recent=b.common.topics.recent),this.hasActiveTopics&&b.app&&b.app.chromeExtension&&b.app.chromeExtension.topics&&b.app.chromeExtension.topics.active&&
(this.topics.active=b.app.chromeExtension.topics.active)),this.dapiData=b,b.common&&b.common.translation&&(this.translation={source:b.common.translation.source||null}),this.fixVoice(),b=!1,this.fixTopics()&&(b=!0),this.fixPrediction()&&(b=!0),b&&this.markAsModified())};
CWEUserSettings.prototype.createUploadData=function(a){var b=this.os();a=a||{};a.version=1;a.common=a.common||{};a.common.speech=a.common.speech||{};a.common.speech.letters=this.speech.letters;a.common.speech.words=this.speech.words;a.common.speech.sentences=this.speech.sentences;this.hasText&&(a.common.text=a.common.text||{},a.common.text.fontFamily=this.text.fontFamily,a.common.text.fontSize=this.text.fontSize,a.common.text.textColor=this.text.textColor,a.common.text.backgroundColor=this.text.backgroundColor,
a.common.text.marginSize=this.text.marginSize);a.common.guessWindow=a.common.guessWindow||{};a.common.guessWindow.fontFamily=this.guessWindow.fontFamily;a.common.guessWindow.fontSize=this.guessWindow.fontSize;a.common.guessWindow.textColor=this.guessWindow.textColor;a.common.guessWindow.backgroundColor=this.guessWindow.backgroundColor;a.common.prediction=a.common.prediction||{};a.common.prediction.guesses=this.prediction.guesses;a.common.prediction.mainDictionary=this.prediction.mainDictionary;a.common.prediction.momentaryTopic=
this.prediction.momentaryTopic;a.common.prediction.flexibleSpelling=this.prediction.flexibleSpelling;a.common.prediction.grammar=this.prediction.grammar;a.common.topics=a.common.topics||{};a.common.topics.recent=this.topics.recent||[];a.common.translation=this.translation||{};a.platform=a.platform||{};a.platform.chrome=a.platform.chrome||{};a.platform.chrome[b.name]=a.platform.chrome[b.name]={};a.platform.chrome[b.name]=a.platform.chrome[b.name]||{};b=a.platform.chrome[b.name].speech=a.platform.chrome[b.name].speech||
{};b.voice=this.speech.voice;b.rate=this.speech.rate;b.pitch=this.speech.pitch;b.volume=this.speech.volume;this.hasActiveTopics&&(a.app=a.app||{},a.app.chromeExtension=a.app.chromeExtension||{},a.app.chromeExtension.topics=a.app.chromeExtension.topics||{},a.app.chromeExtension.topics.active=this.topics.active||[]);a=JSON.stringify(a);return{data:a,checksum:CryptoJS.MD5(a).toString()}};
CWEUserSettings.prototype.os=function(){var a={chrome:-1!=window.navigator.userAgent.indexOf("CrOS"),mac:-1!=window.navigator.userAgent.indexOf("Macintosh"),windows:-1!=window.navigator.userAgent.indexOf("Windows")};a.name=a.chrome?"chrome":a.mac?"mac":"windows";return a};CWEUserSettings.prototype.addActiveTopic=function(a){var b=!1;if(this.hasActiveTopics){b=this.topics.active;var c=this.__topicIndex(a,b);-1!=c&&b.splice(c,1);b.push(a);b.sort();b=!0}return this.addRecentTopic(a)||b};
CWEUserSettings.prototype.addOnlyMissingTopics=function(a){if(this.hasActiveTopics&&(a=this.__findMissingTopics(this.topics.active,a),0<a.length)){for(var b=this.topics.active,c=0;c<a.length;c++)b.push(a[c]),this.addRecentTopic(a[c]);b.sort();return a}return null};CWEUserSettings.prototype.removeActiveTopic=function(a){if(this.hasActiveTopics){var b=this.topics.active;if(b&&(index=this.__topicIndex(a,b),-1!=index))return b.splice(index,1),!0}return!1};
CWEUserSettings.prototype.addRecentTopic=function(a){var b=this.topics.recent;if(b){var c=this.__topicIndex(a,b);if(0!=c)return-1!=c&&b.splice(c,1),b.unshift(a),10<b.length&&b.splice(10,b.length-10),!0}return!1};CWEUserSettings.prototype.__topicIndex=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c]===a)return c;return-1};
CWEUserSettings.prototype.__findMissingTopics=function(a,b){a=a||[];b=b||[];for(var c={},d=0;d<a.length;d++)c[a[d]]=1;a=[];for(d=0;d<b.length;d++)c.hasOwnProperty(b[d])||a.push(b[d]);return a};
