var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,c,d,b){if(c){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};c.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var b=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){b(a,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new c;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(r){f(r)}}:b}var d,f,h=new e(function(a,
b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return h};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=d;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new e(function(a,e){function f(b){return function(c){h[b]=c;g--;0==g&&a(h)}}var h=[],g=0;do h.push(void 0),g++,d(c.value).callWhenSettled_(f(h.length-1),e),c=b.next();while(!c.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function c(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(b,e){function f(a){a.done?b(a.value):Promise.resolve(a.value).then(c,d).then(f,e)}f(a.next())})};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var c=[],b;for(b in a)$jscomp.owns(a,b)&&c.push(a[b]);return c}},"es8","es3");
function CWEDataManager(){this.user="DefaultUser";this.userDir="/Users/DefaultUser/";this.userTopicDir="/Users/DefaultUser/Topics/";this.userSettingsFile=this.userDir+"Preferences.txt";this.userDictionariesInfoFile=this.userDir+"UserDictionariesInfo.txt";this.userPersonalDictionaryInfoFile=this.userDir+"UserPersonalDictionaryInfo.txt";this.userMeasuredDataFile=this.userDir+"Measurements.txt";this.userDictionariesInfo={};this.m_syncUserSettingsTimer=this.m_dataSyncManager=this.userMeasurementsInfo=
this.userPersonalDictionaryInfo=null}CWEDataManager.instance=null;CWEDataManager.initialize=function(a){try{null===CWEDataManager.instance&&(CWEDataManager.instance=new CWEDataManager,CWEDataManager.instance.__initialize(a))}catch(c){Logger.instance.error(c)}};CWEDataManager.prototype.__initialize=function(a){var c=this;this.__loadPersonalDictionary(function(){c.__loadDictionaries(function(){c.__loadMeasurements(a)})})};
CWEDataManager.prototype.setDataSyncManager=function(a){this.m_dataSyncManager=a};
CWEDataManager.prototype.changeUser=function(a,c){var d=this;d.__cancelSyncUserSettingsTimer();(function(){cwe.measure.reset();d.user=a;d.userDir="/Users/"+a+"/";d.userTopicDir="/Users/"+a+"/Topics/";d.userTopicFile="/Users/"+a+"/topics.cache";d.userSettingsFile=d.userDir+"Preferences.txt";d.userDictionariesInfoFile=d.userDir+"UserDictionariesInfo.txt";d.userPersonalDictionaryInfoFile=d.userDir+"UserPersonalDictionaryInfo.txt";d.userMeasuredDataFile=d.userDir+"Measurements.txt";d.userDictionariesInfo=
{};d.userPersonalDictionaryInfo=null;d.userMeasurementsInfo=null;CWEBackgroundManager.instance.requestFileSystem(function(a){a.createDirectory(d.userTopicDir,function(){a.getFile(d.userTopicFile,!0,function(){d.__initialize(c)})})})})()};
CWEDataManager.prototype.updateDictionaries=function(a){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,q,u){for(;;)switch(b){case 0:if(a&&!(0>=a.length)){b=1;break}b=-1;return{value:void 0,done:!0};case 1:t=new DjiFileSystemDirectoryEntryProxy(CWEBackgroundManager.instance.fileSystem().m_fileSystem.root),p=[],n=0;case 2:if(!(n<a.length)){b=4;break}if((m=a[n])&&m.filePath&&m.name&&m.language){b=5;break}b=3;break;case 5:l="";k=m.filePath.split("/");0<k.length&&(l=k[k.length-
1]);g=null;for(var r in c.userDictionariesInfo)if(c.userDictionariesInfo.hasOwnProperty(r)){g=c.userDictionariesInfo[r];if(g.title===m.name&&g.preview===l)break;g=null}g?(g.modifiedDate=Date.now(),g.modifiedUuid=CWEChromeUtilities.generateUUID()):(g=CWEUserDictionaryInfo.createNew(m.filePath,m.name,m.type,m.language),c.userDictionariesInfo[g.uuid]=g);b=6;return{value:t.readAsBinaryStringAsync(m.filePath),done:!1};case 6:if(1!=d){b=7;break}b=-1;throw u;case 7:f=h=q,g.checksum=CryptoJS.MD5(JSON.stringify(f)).toString(),
p.push(g);case 3:n++;b=2;break;case 4:if(!(0>=p.length)){b=8;break}b=-1;return{value:void 0,done:!0};case 8:return e=c,b=-1,{value:new Promise(function(a){e.saveDictionariesInfo(function(){if(e.m_dataSyncManager)for(var b=0;b<p.length;b++)e.m_dataSyncManager.enqueueUpdateDictionary(p[b]);a()})}),done:!0};default:return{value:void 0,done:!0}}}var b=0,e,f,h,g,k,l,m,n,p,t,q={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q}())};
CWEDataManager.prototype.updateDictionariesFromDapiFileMap=function(a,c){var d=this,b={filesToDownload:[],filesToUpload:[],filesToDelete:[]},e=function(){for(var a in d.userDictionariesInfo){var c=d.userDictionariesInfo[a];c.dapiFile?c.deleted?b.filesToDelete.push(c):c.downloadRequired?b.filesToDownload.push(c):c.checksum!==c.dapiFile.checksum&&b.filesToUpload.push(c):b.filesToUpload.push(c)}return b};if(a){var f=[],h=[],g=[],k;for(k in this.userDictionariesInfo){var l=this.userDictionariesInfo[k];
l.dapiFile&&!a.hasOwnProperty(k)&&f.push(k)}for(k in a){var m=a[k];this.userDictionariesInfo.hasOwnProperty(k)?(l=this.userDictionariesInfo[k],!l.deleted&&l.dapiFile&&l.dapiFile.version<m.version&&h.push(k)):g.push(k)}if(0>=f.length&&0>=h.length&&0>=g.length)c&&(e(),c(!1,b));else{var n=function(){for(var a=[],b=0;b<f.length;b++){var c=f[b],e=d.userDictionariesInfo[c];delete d.userDictionariesInfo[c];a.push(d.userTopicDir+e.preview)}return a}();(function(){for(var b=0;b<h.length;b++){var c=h[b],e=
d.userDictionariesInfo[c];e.updateFromDapiFile(a[c]);e.downloadRequired=!0}})();(function(){for(var b=0;b<g.length;b++){var c=g[b],e=CWEUserDictionaryInfo.createNewFromDapiFile(a[c]);e.downloadRequired=!0;d.userDictionariesInfo[c]=e}})();e();CWEBackgroundManager.instance.requestFileSystem(function(a){a.writeFile(d.userDictionariesInfoFile,JSON.stringify(d.userDictionariesInfo),function(){a.removeFiles(n,function(){c&&c(!0,b)})})})}}else c&&(e(),c(!1,b))};
CWEDataManager.prototype.updateDictionaryFromDapi=function(a,c,d,b){if(a){var e=this.userDictionariesInfo[a.uuid];e?e.updateFromDapiFile(a):(e=CWEUserDictionaryInfo.createNewFromDapiFile(a),this.userDictionariesInfo[a.uuid]=e);e.downloadRequired=c;var f=this,h=this.userTopicDir+e.preview;CWEBackgroundManager.instance.requestFileSystem(function(a){a.writeFile(f.userDictionariesInfoFile,JSON.stringify(f.userDictionariesInfo),function(c){c?f.updateTopicsCache(e.preview,function(){d?a.writeFile(h,d,function(a){f.__callback(b)}):
f.__callback(b)}):f.__callback(b)})})}else this.__callback(b)};CWEDataManager.prototype.saveDictionaryInfo=function(a,c){this.saveDictionariesInfo(c)};CWEDataManager.prototype.saveDictionariesInfo=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.writeFile(c.userDictionariesInfoFile,JSON.stringify(c.userDictionariesInfo),a)})};
CWEDataManager.prototype.updatePersonalDictionary=function(a,c,d,b){var e=this;return $jscomp.executeAsyncGenerator(function(){function f(f,k,n){for(;;)switch(h){case 0:if(a&&c&&b){h=1;break}h=-1;return{value:void 0,done:!0};case 1:return e.userPersonalDictionaryInfo?(e.userPersonalDictionaryInfo.modifiedDate=Date.now(),e.userPersonalDictionaryInfo.modifiedUuid=CWEChromeUtilities.generateUUID()):e.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNew(a,c,d,b),g=e,h=-1,{value:new Promise(function(b){CWEBackgroundManager.instance.requestFileSystem(function(c){c.readFile(a,
function(a){a?(g.userPersonalDictionaryInfo.checksum=CryptoJS.MD5(a).toString(),g.savePersonalDictionaryInfo(function(){g.m_dataSyncManager&&g.m_dataSyncManager.enqueueUpdatePersonalDictionary(g.userPersonalDictionaryInfo);b()})):b()})})}),done:!0};default:return{value:void 0,done:!0}}}var h=0,g,k={next:function(a){return f(0,a,void 0)},throw:function(a){return f(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};
return k}())};
CWEDataManager.prototype.updatePersonalDictionaryFromDapi=function(a,c,d,b){if(a){this.userPersonalDictionaryInfo?this.userPersonalDictionaryInfo.updateFromDapiFile(a):this.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNewFromDapiFile(a);this.userPersonalDictionaryInfo.downloadRequired=c;var e=this,f=this.userDir+this.userPersonalDictionaryInfo.preview;CWEBackgroundManager.instance.requestFileSystem(function(a){a.writeFile(e.userPersonalDictionaryInfoFile,JSON.stringify(e.userPersonalDictionaryInfo),function(c){c?
d?a.writeFile(f,d,function(a){e.__callback(b)}):e.__callback(b):e.__callback(b)})})}else this.__callback(b)};
CWEDataManager.prototype.updatePersonalDictionariesFromDapiFileMap=function(a,c){var d={filesToDownload:[],filesToUpload:[]},b=this.userPersonalDictionaryInfo,e=!1;a?b&&b.dapiFile?b.downloadRequired||b.dapiFile.version<a.version?(b.updateFromDapiFile(a),b.downloadRequired=!0,d.filesToDownload.push(b),e=!0):b.modifiedDate>a.modifiedDate&&d.filesToUpload.push(b):(b?b.updateFromDapiFile(a):b=this.userPersonalDictionaryInfo=CWEUserDictionaryInfo.createNewFromDapiFile(a),b.downloadRequired=!0,d.filesToDownload.push(b),
e=!0):b&&d.filesToUpload.push(b);if(e){var f=this;this.savePersonalDictionaryInfo(function(){f.__callback(c,!0,d)})}else this.__callback(c,!1,d)};CWEDataManager.prototype.savePersonalDictionaryInfo=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.writeFile(c.userPersonalDictionaryInfoFile,JSON.stringify(c.userPersonalDictionaryInfo),a)})};
CWEDataManager.prototype.syncUserSettings=function(){this.__cancelSyncUserSettingsTimer();if(this.m_dataSyncManager&&!CWEBackgroundManager.instance.isInTestingMode()){var a=this,c=CWEBackgroundManager.instance.settings().data();if(!c.dapiFile||c.dapiFile.modifiedDate<c.modifiedDate)this.m_syncUserSettingsTimer=setTimeout(function(){a.m_dataSyncManager.enqueueUpdateUserSettings(c)},500)}};
CWEDataManager.prototype.saveUserSettings=function(a,c){var d=this;this.__cancelSyncUserSettingsTimer();CWEBackgroundManager.instance.isInTestingMode()||CWEBackgroundManager.instance.requestFileSystem(function(b){JSON.stringify(a);b.writeFile(d.userSettingsFile,JSON.stringify(a),function(){d.syncUserSettings();d.__callback(c)})})};
CWEDataManager.prototype.loadUserSettings=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.readFileAsText(c.userSettingsFile,function(b){var d=null;if(b)try{d=JSON.parse(b)}catch(f){Logger.instance.error(f)}c.__callback(a,d)})})};
CWEDataManager.prototype.updateUserSettingsFromDapiFileMap=function(a,c){var d=!1,b={filesToDownload:[],filesToUpload:[]},e=CWEBackgroundManager.instance.settings();if(!e.isInTestingMode()){var f=e.data();a?f.dapiFile?f.downloadRequired||f.dapiFile.version<a.version?(f.updateFromRemoteData(a,null),f.downloadRequired=!0,b.filesToDownload.push(f),d=!0):f.modifiedDate>a.modifiedDate&&b.filesToUpload.push(f):(f.updateFromRemoteData(a,null),f.downloadRequired=!0,b.filesToDownload.push(f),d=!0):b.filesToUpload.push(f)}if(d){var h=
this;this.saveUserSettings(f,function(){h.__callback(c,!0,b)})}else this.__callback(c,!1,b)};CWEDataManager.prototype.updateUserSettingsFromDapi=function(a,c,d,b){if(a){var e=CWEBackgroundManager.instance.settings();if(e.isInTestingMode())this.__callback(b,!1);else{e=e.data();e.updateFromRemoteData(a,d);e.downloadRequired=c;var f=this;f.saveUserSettings(e,function(){f.__callback(b,!0)})}}else this.__callback(b,!1)};
CWEDataManager.prototype.updateTestingSettingsFromDapi=function(a,c,d){if(a){var b=CWEBackgroundManager.instance.settings();b.isInTestingMode()?(b=b.data(),b.updateFromRemoteData(a,c,!0),b.downloadRequired=!1,this.__callback(d,!0)):this.__callback(d,!1)}else this.__callback(d,!1)};CWEDataManager.prototype.checkDataWordListNeedsDownload=function(a,c){return a?window.cwe.measure.version()<a.version:!0};
CWEDataManager.prototype.updateDataWordList=function(a,c){if(!a)return c();window.cwe.measure.update(a,c)};CWEDataManager.prototype.enablePrivacyMode=function(a,c){if(a!=this.userMeasurementsInfo.privacyMode){this.userMeasurementsInfo.privacyMode=a;cwe.measure.enablePrivacyMode(a);var d=this,b=JSON.stringify(this.userMeasurementsInfo);CWEBackgroundManager.instance.requestFileSystem(function(a){a.writeFile(d.userMeasuredDataFile,b,function(){d.__callback(c)})})}else this.__callback(c)};
CWEDataManager.prototype.prepareMeasuredDataForSync=function(a){if(this.userMeasurementsInfo.privacyMode)return this.__callback(a,null,null);var c=cwe.measure.measurementResults(!0),d=this.userMeasurementsInfo||{},b=d.current||{};b.words=b.words||{};b.totalWords=b.totalWords||0;b.totalTime=b.totalTime||0;var e=0,f;for(f in c.words)c.words.hasOwnProperty(f)&&(e=c.words[f],b.words[f]=(b.words[f]||0)+e);b.totalWords+=c.totalWords;b.totalTime+=c.totalTime;c=d.history||{};for(g in c){c=d.history[g].data;
for(f in c.words)c.words.hasOwnProperty(f)&&(e=c.words[f],b.words[f]=(b.words[f]||0)+e);b.totalWords+=c.totalWords;b.totalTime+=c.totalTime}d.history={};d.current=b;this.userMeasurementsInfo=d;if(0>=CWEChromeUtilities.mapIsEmpty(b.words)&&0>=b.totalWords&&0>=b.totalTime)this.__callback(a,null,null);else{var h=this;var g=CWEChromeUtilities.generateUUID();d.history=d.history||{};d.history[g]={timestamp:Date.now(),data:b};d.current={words:{},totalWords:0,totalTime:0};var k=JSON.stringify(d);CWEBackgroundManager.instance.requestFileSystem(function(c){c.writeFile(h.userMeasuredDataFile,
k,function(){b=d.history[g].data;h.__callback(a,b,g)})})}};
CWEDataManager.prototype.measuredDataSyncDone=function(a,c,d){var b=this.userMeasurementsInfo;if(!a){a=b.history[c].data;var e=b.current||{};e.words=e.words||{};e.totalWords=e.totalWords||0;e.totalTime=e.totalTime||0;var f=0,h;for(h in a.words)a.words.hasOwnProperty(h)&&(f=a.words[h],e.words[h]=(e.words[h]||0)+f);e.totalWords+=a.totalWords;e.totalTime+=a.totalTime;b.current=e}delete b.history[c];var g=JSON.stringify(b),k=this;CWEBackgroundManager.instance.requestFileSystem(function(a){a.writeFile(k.userMeasuredDataFile,g,
function(){k.__callback(d)})})};CWEDataManager.prototype.__loadPersonalDictionary=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.readFile(c.userPersonalDictionaryInfoFile,function(b){if(b)try{var d=JSON.parse(b);c.userPersonalDictionaryInfo=new CWEUserDictionaryInfo(d)}catch(f){Logger.instance.error(f)}c.__callback(a)})},function(){c.__callback(a)})};
CWEDataManager.prototype.__loadDictionaries=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.readFile(c.userDictionariesInfoFile,function(b){if(b)try{var d=JSON.parse(b),f;for(f in d)c.userDictionariesInfo[f]=new CWEUserDictionaryInfo(d[f])}catch(h){Logger.instance.error(h)}c.__callback(a)})},function(){c.__callback(a)})};
CWEDataManager.prototype.__loadMeasurements=function(a){var c=this;CWEBackgroundManager.instance.requestFileSystem(function(d){d.readFile(c.userMeasuredDataFile,function(b){if(b)try{c.userMeasurementsInfo=JSON.parse(b)}catch(e){Logger.instance.error(e)}c.userMeasurementsInfo||(c.userMeasurementsInfo={});c.userMeasurementsInfo.hasOwnProperty("privacyMode")||(c.userMeasurementsInfo.privacyMode=!1);cwe.measure.enablePrivacyMode(c.userMeasurementsInfo.privacyMode);c.__callback(a)})},function(){c.__callback(a)})};
CWEDataManager.prototype.__stopSync=function(){this.m_dataSyncManager&&this.m_dataSyncManager.stop()};CWEDataManager.prototype.__startSync=function(){this.m_dataSyncManager&&this.m_dataSyncManager.start()};CWEDataManager.prototype.__cancelSyncUserSettingsTimer=function(){this.m_syncUserSettingsTimer&&(clearTimeout(this.m_syncUserSettingsTimer),this.m_syncUserSettingsTimer=null)};
CWEDataManager.prototype.readUserDictionaryFile=function(a,c){if(this.userDictionariesInfo.hasOwnProperty(a)){var d=this,b=d.userTopicDir+this.userDictionariesInfo[a].preview;CWEBackgroundManager.instance.requestFileSystem(function(a){a.readFileAsArrayBuffer(b,function(a){d.__callback(c,a)})})}else this.__callback(c,null)};
CWEDataManager.prototype.readUserPersonalDictionaryFile=function(a){if(this.userPersonalDictionaryInfo){var c=this,d=this.userDir+this.userPersonalDictionaryInfo.preview;CWEBackgroundManager.instance.requestFileSystem(function(b){b.readFileAsArrayBuffer(d,function(b){c.__callback(a,b)})})}else this.__callback(a,null)};CWEDataManager.prototype.translationCacheFileName=function(a,c){if(a&&c)return this.userDir+"TranslationCache_"+a+"_"+c+".txt"};
CWEDataManager.prototype.saveTranslationCache=function(a,c,d,b){var e=this.translationCacheFileName(a,c);if(!e||CWEBackgroundManager.instance.isInTestingMode())return this.__callback(b,!1);var f=this;CWEBackgroundManager.instance.requestFileSystem(function(a){d=JSON.stringify(d);a.writeFile(e,d,function(){f.__callback(b,!0)})})};
CWEDataManager.prototype.loadTranslationCache=function(a,c,d){var b=this.translationCacheFileName(a,c);if(!b)return this.__callback(d,null);var e=this;CWEBackgroundManager.instance.requestFileSystem(function(a){a.readFileAsText(b,function(a){if(null!==a&&void 0!==a)try{a=JSON.parse(a)}catch(g){a=null,Logger.instance.error(g)}e.__callback(d,a)})})};
CWEDataManager.prototype.updateTopicsCache=function(a,c){var d=this;CWEBackgroundManager.instance.requestFileSystem(function(a){var b=Object.values(d.userDictionariesInfo).map(function(a){return"Topics/"+a.preview}).join("\n");a.writeFile(d.userTopicFile,b,c)})};CWEDataManager.prototype.__callback=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(c){Logger.instance.error(c)}};
