(function(){})(window.cwe=window.cwe||{});
(function(f){function t(a){d&&d.id==a&&(d=null,setTimeout(F,0))}function G(){chrome.windows.create({url:window.dji.config.loginUrl(),width:1E3,height:700,type:"popup"},function(a){d=a;chrome.windows.onRemoved.addListener(t)})}function u(a){k=a.url;chrome.windows.remove(d.id)}function v(a){if(a=CWEChromeUtilities.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a){if(a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}if(a.hasOwnProperty("expires_at"))try{a.expires_at=parseInt(a.expires_at)}catch(b){}}setTimeout(m,
0,a);return{redirectUrl:"javascript:"}}function w(a){400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(m,0,{code:a.statusCode})}function x(a){-1==a.tabId&&0<a.frameId&&(Logger.instance.error(a),setTimeout(m,0,null))}function y(a){if(a=CWEChromeUtilities.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a){if(a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}if(a.hasOwnProperty("expires_at"))try{a.expires_at=parseInt(a.expires_at)}catch(b){}}setTimeout(n,0,a);return{redirectUrl:"javascript:"}}
function z(a){400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(n,0,{code:a.statusCode})}function A(a){-1==a.tabId&&0<a.frameId&&(Logger.instance.error(a),setTimeout(n,0,null))}function B(a){if(a=CWEChromeUtilities.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a&&a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}setTimeout(p,0,a);return{redirectUrl:"javascript:"}}function C(a){400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(p,0,{code:a.statusCode})}function D(a){-1==a.tabId&&
0<a.frameId&&(Logger.instance.error(a),setTimeout(p,0,null))}var H="https://"+chrome.runtime.id+".chromiumapp.org",I="https://"+chrome.runtime.id+".chromiumapp.org/auth/callback",J="https://"+chrome.runtime.id+".chromiumapp.org/silent/auth/callback?*",K="https://"+chrome.runtime.id+".chromiumapp.org/silent/token/refresh/callback",L="https://"+chrome.runtime.id+".chromiumapp.org/silent/token/refresh/callback?*",M="https://"+chrome.runtime.id+".chromiumapp.org/silent/signout/callback?*",E=/[?&](auth|lauth|sauth|signout)_stamp=97eb647a233b(&|#|$)/i,
d=null,l=null,g=!1,k=null,e=null,h=CWEChromeUtilities.generateUUID,q=CWEChromeUtilities.generateUUID;f.monitor=function(a){a&&chrome.webRequest.onBeforeRequest.addListener(function(b){if(!(0>b.tabId)){var c=null;(0==b.url.indexOf("https://")||0==b.url.indexOf("http://"))&&0>b.url.indexOf(H)&&0<b.url.indexOf("_stamp=97eb647a233b")&&(c=new URL(b.url));if(c&&c.search&&(b=c.search.match(E)))if(b=b[1].toUpperCase(),"AUTH"==b||"LAUTH"==b)f.isLoggedIn()||a.authRequired();else if("SIGNOUT"==b&&(b=c.search.match(E))){c=
500;try{c=parseInt(b[1])}catch(r){Logger.instance.error(r)}500!=c&&a.signoutRequired()}}},{urls:["<all_urls>"]})};f.userInfo=function(a){if(a)e=a;else return e};f.isLoggedIn=function(){return!g&&null!=e&&void 0!=e};f.login=function(a){if(g)return d&&chrome.windows.update(d.id,{focused:!0}),!1;if(e)try{a(e)}catch(b){Logger.instance.error(b)}else return g=!0,l=a,k=null,chrome.webRequest.onBeforeRequest.addListener(u,{urls:[I]}),G(),!0};f.silentAuth=function(a){var b=document.getElementById(h);if(b)return a(null);
b=document.createElement("iframe");b.setAttribute("id",h);b.__calback=a;b.src=window.dji.config.silentAuthUrl();chrome.webRequest.onBeforeRequest.addListener(v,{urls:[J]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(w,{urls:[window.dji.config.silentAuthUrl()]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(x,{urls:[window.dji.config.silentAuthUrl()]});document.body.appendChild(b)};f.silentSignout=function(a){var b=document.getElementById(h);if(b)return a(null);b=document.createElement("iframe");
b.setAttribute("id",h);b.__calback=a;b.src=window.dji.config.silentSignoutUrl();chrome.webRequest.onBeforeRequest.addListener(B,{urls:[M]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(C,{urls:[window.dji.config.silentAuthUrl()]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(D,{urls:[window.dji.config.silentSignoutUrl()]});document.body.appendChild(b)};f.isPreparing=function(){return g&&!d};f.windowId=function(){return d?d.id:null};f.silentRefreshToken=function(a,b){var c=
document.getElementById(q);if(c)return b(null);a=a.login_url+"/silent/token/refresh?client_id="+encodeURIComponent(a.client_id)+"&refresh_token="+encodeURIComponent(a.refresh_token)+"&redirect_uri="+encodeURIComponent(K);c=document.createElement("iframe");c.setAttribute("id",q);c.__calback=b;c.src=a;chrome.webRequest.onBeforeRequest.addListener(y,{urls:[L]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(z,{urls:[a]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(A,{urls:[a]});
document.body.appendChild(c)};var F=function(){chrome.windows.onRemoved.removeListener(t);chrome.webRequest.onBeforeRequest.removeListener(u);d&&(chrome.windows.remove(d.id),d=null);var a=CWEChromeUtilities.jsonFromUrlQueryAndHash(k);if((a=a?a.hash:null)&&a.access_token&&a.expires_at)jsdapi.setAuth(a),jsdapi.account.me(function(a){if(a&&!a.error){e=a;try{l(e)}catch(c){Logger.instance.error(c)}l=k=null;g=!1}});else{try{l(e)}catch(b){Logger.instance.error(b)}l=k=null;g=!1}},m=function(a){chrome.webRequest.onBeforeRequest.removeListener(v);
chrome.webRequest.onHeadersReceived.removeListener(w);chrome.webRequest.onErrorOccurred.removeListener(x);var b=document.getElementById(h);if(!b)return dji.log.error("Invalid state for silent auth.");var c=b.__calback;document.body.removeChild(b);if(!a||500==a.code)return c(null);0==a.code?(jsdapi.setAuth(a),jsdapi.account.me(function(b){if(b)if(b.error)switch(b.error){case 401:a.code=800002}else e=b,a.user=b;c(a)})):c(a)},n=function(a){chrome.webRequest.onBeforeRequest.removeListener(y);chrome.webRequest.onHeadersReceived.removeListener(z);
chrome.webRequest.onErrorOccurred.removeListener(A);var b=document.getElementById(q);if(!b)return dji.log.error("Invalid state for silent refresh.");var c=b.__calback;document.body.removeChild(b);c(a)},p=function(a){chrome.webRequest.onBeforeRequest.removeListener(B);chrome.webRequest.onHeadersReceived.removeListener(C);chrome.webRequest.onErrorOccurred.removeListener(D);var b=document.getElementById(h);if(!b)return dji.log.error("Invalid state for silent signout.");var c=b.__calback;document.body.removeChild(b);
if(!a||500==a.code)return c(!1);e=null;try{c(!0)}catch(r){Logger.instance.error(r)}}})(window.cwe.login=window.cwe.login||{});
