var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,b){c!=Array.prototype&&c!=Object.prototype&&(c[d]=b.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var d=0;return $jscomp.iteratorPrototype(function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=c[Symbol.iterator];return d?d.call(c):$jscomp.arrayIterator(c)};
$jscomp.polyfill=function(c,d,b,a){if(d){b=$jscomp.global;c=c.split(".");for(a=0;a<c.length-1;a++){var e=c[a];e in b||(b[e]={});b=b[e]}c=c[c.length-1];a=b[c];d=d(a);d!=a&&null!=d&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:d})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function d(){this.batch_=null}function b(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;d.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};d.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var a=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){a(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};d.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(n){b.reject(n)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(n){this.reject_(n);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new d;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(m){c.reject(m)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(p){h(p)}}:b}var d,h,f=new e(function(a,
b){d=a;h=b});this.callWhenSettled_(c(a,d),c(b,h));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(function(){g.asyncExecute(c)})};e.resolve=b;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(c,
e){for(var d=$jscomp.makeIterator(a),h=d.next();!h.done;h=d.next())b(h.value).callWhenSettled_(c,e)})};e.all=function(a){var c=$jscomp.makeIterator(a),d=c.next();return d.done?b([]):new e(function(a,e){function h(b){return function(c){g[b]=c;f--;0==f&&a(g)}}var g=[],f=0;do g.push(void 0),f++,b(d.value).callWhenSettled_(h(g.length-1),e),d=c.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(c){function d(a){return c.next(a)}function b(a){return c.throw(a)}return new Promise(function(a,e){function g(c){c.done?a(c.value):Promise.resolve(c.value).then(d,b).then(g,e)}g(c.next())})};function CWEPredictionEngineInstance(){return CWEPredictionEngine.instance}
function CWEPredictionEngine(c,d){this.m_nacl="WebAssembly";this.m_spellcheckerWorker=new DjiSpellCheckerWorkerProxy({url:"cweSpellCheckerWorker.js",appDir:"/"+this.m_nacl});this.m_predictionWorker=new DjiPredictionWorkerProxy({url:"cwePredictionWorker.js",appDir:"/"+this.m_nacl});this.m_bundleResources={prediction:null,hunspell:null};this.m_spellcheckLanguage=null;this.m_spellcheckBundledLanguages=[];this.m_spellcheckBundledLanguagesMap={};this.m_sensitiveWordsMap={};this.m_listeners=[c];this.m_optionsListeners=
[];this.m_locale=null;this.m_allTopics=[];this.m_recentTopics=[];this.m_activeTopics=[];this.m_initialized=this.m_loaded=!1;this.m_state={action:null,details:{},userData:null};this.m_eventTarget=new EventTarget;Object.defineProperty(this,"state",{value:this.m_state,writable:!1});Object.defineProperty(this,"maxActiveTopics",{value:6,writable:!1});this.m_predictionWorker.onFollowTextChange(this.onFollowTextChange.bind(this));return this}CWEPredictionEngine.instance=null;
CWEPredictionEngine.load=function(c,d){return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:Logger.instance.log("Loading Prediction module! Please wait...");if(null!=CWEPredictionEngine.instance){a=1;break}try{return CWEPredictionEngine.instance=new CWEPredictionEngine(c,d),a=4,{value:CWEPredictionEngine.instance.__load("load",null),done:!1}}catch(k){g=k;a=2;break}case 4:try{if(1!=b){a=5;break}a=-1;throw m;}catch(k){g=k;a=2;break}case 5:try{a=3;break}catch(k){g=
k;a=2;break}case 2:e=g,CWEPredictionEngine.instance=null,Logger.instance.error("Prediction Engine - cannot create instance!"),Logger.instance.error(e);case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.isLoaded=function(){return CWEPredictionEngine.instance&&CWEPredictionEngine.instance.m_loaded};CWEPredictionEngine.isInitialized=function(){return CWEPredictionEngine.isLoaded()&&CWEPredictionEngine.instance.m_initialized};
CWEPredictionEngine.prototype.__load=function(c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function a(a,h,g){for(;;)switch(e){case 0:return b.m_loadReason=c,"locale"===c&&(b.m_locale=d),e=1,{value:b.__prepareBundleResources(),done:!1};case 1:if(1!=a){e=2;break}e=-1;throw g;case 2:return e=3,{value:b.__loadSpellcheckerLanguages(),done:!1};case 3:if(1!=a){e=4;break}e=-1;throw g;case 4:return e=5,{value:b.__loadSensitiveWords(),done:!1};case 5:if(1!=a){e=6;break}e=-1;throw g;case 6:b.m_loaded=
!0,e=-1;default:return{value:void 0,done:!0}}}var e=0,g={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
CWEPredictionEngine.prototype.__prepareBundleResources=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,q,r){for(;;)switch(b){case 0:try{return b=3,{value:CWEBackgroundManager.instance.fileSystem().removeDirectoryAsync("/bundle"),done:!1}}catch(p){k=p;b=1;break}case 3:try{if(1!=d){b=4;break}b=-1;throw r;}catch(p){k=p;b=1;break}case 4:try{b=2;break}catch(p){k=p;b=1;break}case 1:case 2:try{return b=7,{value:DjiFileSystemDirectoryEntryProxy.getPackageDirectoryEntryAsync(),
done:!1}}catch(p){k=p;b=5;break}case 7:try{if(1!=d){b=8;break}b=-1;throw r;}catch(p){k=p;b=5;break}case 8:try{return n=m=q,b=9,{value:n.fileAsync(c.m_nacl+"/resources/prediction.pvfs"),done:!1}}catch(p){k=p;b=5;break}case 9:try{if(1!=d){b=10;break}b=-1;throw r;}catch(p){k=p;b=5;break}case 10:try{return f=h=q,b=11,{value:n.fileAsync(c.m_nacl+"/resources/hunspell.pvfs"),done:!1}}catch(p){k=p;b=5;break}case 11:try{if(1!=d){b=12;break}b=-1;throw r;}catch(p){k=p;b=5;break}case 12:try{e=g=q;c.m_bundleResources.prediction=
f;c.m_bundleResources.hunspell=e;b=6;break}catch(p){k=p;b=5;break}case 5:throw a=k,Logger.instance.error(a),b=-1,a;case 6:b=-1;default:return{value:void 0,done:!0}}}var b=0,a,e,g,f,h,n,m,k,q={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q}())};
CWEPredictionEngine.prototype.__loadSpellcheckerLanguages=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,m,l){for(;;)switch(b){case 0:try{return b=3,{value:VfsContainer.fromContainerAsync(c.m_bundleResources.hunspell),done:!1}}catch(r){n=r;b=1;break}case 3:try{if(1!=d){b=4;break}b=-1;throw l;}catch(r){n=r;b=1;break}case 4:try{return f=h=m,b=5,{value:f.readFileAsJSONAsync("manifest.json.txt"),done:!1}}catch(r){n=r;b=1;break}case 5:try{if(1!=d){b=6;break}b=-1;throw l;
}catch(r){n=r;b=1;break}case 6:try{if((e=g=m)&&e.hasOwnProperty("languages")&&e.languages){c.m_spellcheckBundledLanguages=e.languages;for(var k=0;k<e.languages.length;k++)c.m_spellcheckBundledLanguagesMap[e.languages[k].language_code]=e.languages[k]}b=2;break}catch(r){n=r;b=1;break}case 1:a=n,Logger.instance.error(a);case 2:b=-1;default:return{value:void 0,done:!0}}}var b=0,a,e,g,f,h,n,m={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();m[Symbol.iterator]=function(){return this};return m}())};
CWEPredictionEngine.prototype.__loadSensitiveWords=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,p,u){for(;;)switch(b){case 0:try{return b=3,{value:VfsContainer.fromContainerAsync(c.m_bundleResources.prediction),done:!1}}catch(t){l=t;b=1;break}case 3:try{if(1!=d){b=4;break}b=-1;throw u;}catch(t){l=t;b=1;break}case 4:try{k=q=p,m=k.getDirectoryFiles("SensitiveWords"),n={},h=/\s+/,f=0}catch(t){l=t;b=1;break}case 5:try{if(!(f<m.length)){b=7;break}b=8;return{value:k.readFileAsTextAsync(m[f]),
done:!1}}catch(t){l=t;b=1;break}case 8:try{if(1!=d){b=9;break}b=-1;throw u;}catch(t){l=t;b=1;break}case 9:try{e=(g=p)||"",e.split(h).forEach(function(a){a=a.trim();0<a.length&&(n[a.toUpperCase()]=!0)})}catch(t){l=t;b=1;break}case 6:try{f++;b=5;break}catch(t){l=t;b=1;break}case 7:try{c.m_sensitiveWordsMap=n;b=2;break}catch(t){l=t;b=1;break}case 1:a=l,Logger.instance.error(a);case 2:b=-1;default:return{value:void 0,done:!0}}}var b=0,a,e,g,f,h,n,m,k,q,l,u={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();u[Symbol.iterator]=function(){return this};return u}())};CWEPredictionEngine.prototype.addEventListener=function(c,d){this.m_eventTarget.addEventListener(c,d)};CWEPredictionEngine.prototype.addListener=function(c){var d=this.m_listeners.indexOf(c);Logger.instance.log("-------------------------------- CWEPredictionEngine.addListener: "+d);-1===d&&this.m_listeners.push(c);Logger.instance.log(this.m_listeners)};
CWEPredictionEngine.prototype.removeListener=function(c){c=this.m_listeners.indexOf(c);Logger.instance.log("-------------------------------- CWEPredictionEngine.removeListener: "+c);-1!==c&&this.m_listeners.splice(c,1);Logger.instance.log(this.m_listeners)};CWEPredictionEngine.prototype.addOptionsListener=function(c){var d=this.m_optionsListeners.indexOf(c);Logger.instance.log("-------------------------------- CWEPredictionEngine.addOptionsListener: "+d);-1===d&&this.m_optionsListeners.push(c);Logger.instance.log(this.m_optionsListeners)};
CWEPredictionEngine.prototype.removeOptionsListener=function(c){c=this.m_optionsListeners.indexOf(c);Logger.instance.log("-------------------------------- CWEPredictionEngine.removeOptionsListener: "+c);-1!==c&&this.m_optionsListeners.splice(c,1);Logger.instance.log(this.m_optionsListeners)};CWEPredictionEngine.prototype.onCrash=function(){this.m_eventTarget.dispatchEvent(new CustomEvent("crash"))};
CWEPredictionEngine.prototype.initializeAsync=function(c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function a(a,n,q){for(;;)switch(e){case 0:if(b.m_initialized){e=1;break}try{return e=4,{value:b.__initializePredictionAsync(c,d),done:!1}}catch(l){h=l;e=2;break}case 4:try{if(1!=a){e=5;break}e=-1;throw q;}catch(l){h=l;e=2;break}case 5:try{if(!(b.m_spellcheckLanguage&&0<b.m_spellcheckLanguage.length)){e=6;break}}catch(l){h=l;e=2;break}try{return e=9,{value:b.__initializeSpellcheckerAsync(b.m_spellcheckLanguage),
done:!1}}catch(l){h=l;e=7;break}case 9:try{if(1!=a){e=10;break}e=-1;throw q;}catch(l){h=l;e=7;break}case 10:try{b.m_spellcheckLanguage=null;e=8;break}catch(l){h=l;e=7;break}case 7:try{f=h,Logger.instance.error(f)}catch(l){h=l;e=2;break}case 8:case 6:try{b.m_initialized=!0;e=3;break}catch(l){h=l;e=2;break}case 2:g=h,Logger.instance.error(g);case 3:case 1:return e=-1,{value:b.m_initialized,done:!0};default:return{value:void 0,done:!0}}}var e=0,g,f,h,n={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,
void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};
CWEPredictionEngine.prototype.__initializePredictionAsync=function(c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function a(a,n,q){for(;;)switch(e){case 0:try{f="";switch(c.toUpperCase()){case "BE":case "UK":case "FR":case "SPA":case "GER":f="/common/dictionaries"}e=3;return{value:b.m_predictionWorker.initAsync({locale:c,resourceDirectory:"/bundle/resources/prediction",commonDirectory:f,userDirectory:"/Users/"+d,resourceContainer:b.m_bundleResources.prediction},!0),done:!1}}catch(l){h=
l;e=1;break}case 3:try{if(1!=a){e=4;break}e=-1;throw q;}catch(l){h=l;e=1;break}case 4:try{b.rebuildTopicsCache(!0);e=2;break}catch(l){h=l;e=1;break}case 1:throw g=h,Logger.instance.error(g),b.m_predictionWorker.terminate(),e=-1,g;case 2:e=-1;default:return{value:void 0,done:!0}}}var e=0,g,f,h,n={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};
return n}())};
CWEPredictionEngine.prototype.__initializeSpellcheckerAsync=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,h,k){for(;;)switch(a){case 0:if(!(c&&0<c.length)){a=1;break}g=f="";e=null;d.spellcheckerHasBundledResource(c)?(e=d.m_bundleResources.hunspell,g="/bundle/resources/hunspell"):f="/common/hunspell";a=-1;return{value:d.m_spellcheckerWorker.initAsync({locale:c,commonDirectory:f,resourceDirectory:g,resourceContainer:e},!0),done:!0};case 1:a=-1;default:return{value:void 0,done:!0}}}
var a=0,e,g,f,h={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
CWEPredictionEngine.prototype.syncAsync=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(a,d,f){for(;;)switch(b){case 0:return b=-1,{value:c.m_predictionWorker.syncAsync(),done:!0};default:return{value:void 0,done:!0}}}var b=0,a={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();a[Symbol.iterator]=function(){return this};return a}())};
CWEPredictionEngine.prototype.reset=function(){this.m_predictionWorker.terminate();this.m_spellcheckerWorker.terminate();this.m_spellcheckLanguage=null;this.m_allTopics=[];this.m_recentTopics=[];this.m_activeTopics=[];this.m_initialized=!1};CWEPredictionEngine.prototype.supportsUnicode=function(){return!0};
CWEPredictionEngine.prototype.updateFromUserSettingsAsync=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}try{return a=4,{value:d.m_predictionWorker.setOptionsAsync({mainDictionary:CWESettings.instance.predictionMainDictionary(),enableMomentaryTopic:CWESettings.instance.predictionMomentaryTopic(),enableFlexibleSpelling:CWESettings.instance.predictionFlexibleSpelling(),enableGrammar:CWESettings.instance.predictionGrammar(),
enablePredictAhead:CWESettings.instance.predictionAhead(),maxPredictedGuesses:CWESettings.instance.predictionGuesses(),activeTopics:CWESettings.instance.topicsActive()}),done:!1}}catch(k){g=k;a=2;break}case 4:try{if(1!=b){a=5;break}a=-1;throw m;}catch(k){g=k;a=2;break}case 5:try{return a=6,{value:d.rebuildTopicsCache(),done:!1}}catch(k){g=k;a=2;break}case 6:try{if(1!=b){a=7;break}a=-1;throw m;}catch(k){g=k;a=2;break}case 7:try{a=3;break}catch(k){g=k;a=2;break}case 2:if(e=g,Logger.instance.error(e),
d.reset(),c)d.onCrash();case 3:case 1:return a=-1,{value:d.m_initialized,done:!0};default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.rebuildTopicsCache=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized&&!c){a=1;break}a=2;return{value:d.m_predictionWorker.getTopicsStateAsync(),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:e=g=f,d.handleGetTopicsStateResult(!0,!0,e,c);case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},
return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.cacheTopics=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(a,d,f){for(;;)switch(b){case 0:if(!c.m_initialized){b=1;break}b=2;return{value:c.m_predictionWorker.syncUserDirectoryAsync(),done:!1};case 2:if(1!=a){b=3;break}b=-1;throw f;case 3:case 1:b=-1;default:return{value:void 0,done:!0}}}var b=0,a={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
a[Symbol.iterator]=function(){return this};return a}())};
CWEPredictionEngine.prototype.reloadDictionaries=function(c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function a(a,g,n){for(;;)switch(e){case 0:if(!b.m_initialized||!c||d){e=1;break}e=2;return{value:b.m_predictionWorker.reloadDictionariesAsync(c,d),done:!1};case 2:if(1!=a){e=3;break}e=-1;throw n;case 3:CWEBackgroundManager.instance.requestMomentaryTopicContext();case 1:e=-1;default:return{value:void 0,done:!0}}}var e=0,g={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,
void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};CWEPredictionEngine.prototype.followTextChange=function(c,d,b,a,e){this.m_initialized&&this.m_predictionWorker.followTextChange(c,a,d,b,e)};CWEPredictionEngine.prototype.onFollowTextChange=function(c){this.m_initialized&&c.detail&&this.__notifyListeners("guessesAvailable",c.detail)};
CWEPredictionEngine.prototype.acceptGuess=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.acceptGuessAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:e=g=f,d.__notifyListeners("replaceText",e.rangeStart,e.rangeStart+e.rangeLength,e.replacement);case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.restartGuesses=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(a,d,f){for(;;)switch(b){case 0:if(!c.m_initialized){b=1;break}b=-1;return{value:c.m_predictionWorker.restartGuessesAsync(),done:!0};case 1:b=-1;default:return{value:void 0,done:!0}}}var b=0,a={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();a[Symbol.iterator]=
function(){return this};return a}())};
CWEPredictionEngine.prototype.resetState=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(a,d,f){for(;;)switch(b){case 0:if(!c.m_initialized){b=1;break}b=-1;return{value:c.m_predictionWorker.resetStateAsync(),done:!0};case 1:b=-1;default:return{value:void 0,done:!0}}}var b=0,a={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();a[Symbol.iterator]=function(){return this};
return a}())};
CWEPredictionEngine.prototype.setMainDictionary=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.setMainDictionaryAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};
$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.setMaxPredictedGuesses=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.setMaxPredictedGuessesAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.enableMomentaryTopic=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.enableMomentaryTopicAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.updateMomentaryTopic=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}c=c||"";c=c.replace(/(\n)+/g,"\r").replace(/(\r)+/g,"\r").replace(/( )+/g," ").replace(/( \r)+/g,"\r");g=Math.min(c.length,3E4);for(e=Math.min(c.length,g+20);g<e&&!dji.charSet.wordSeparator.characterIsMember(c.charAt(g));g++);g<c.length&&(c=c.substr(0,g));a=2;return{value:d.m_predictionWorker.updateMomentaryTopicAsync(c),
done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.getTopics=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(c||!d.m_initialized){a=1;break}a=3;return{value:d.m_predictionWorker.getTopicsAsync(),done:!1};case 3:if(1!=b){a=4;break}a=-1;throw m;case 4:e=g=f;d.m_allTopics=e.topics;d.__notifyOptionsListeners("topicsAvailable",d.m_allTopics.slice());a=2;break;case 1:d.__notifyOptionsListeners("topicsAvailable",d.m_allTopics.slice());case 2:a=-1;default:return{value:void 0,
done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.getTopicsAsync=function(){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,n){for(;;)switch(b){case 0:if(!c.m_initialized){b=1;break}b=2;return{value:c.m_predictionWorker.getTopicsAsync(),done:!1};case 2:if(1!=d){b=3;break}b=-1;throw n;case 3:return a=e=g,c.m_allTopics=a.topics,c.__notifyOptionsListeners("topicsAvailable",c.m_allTopics.slice()),b=-1,{value:{topics:a.topics},done:!0};case 1:b=-1;default:return{value:void 0,done:!0}}}var b=0,a,
e,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
CWEPredictionEngine.prototype.getActiveTopics=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(c||!d.m_initialized){a=1;break}a=3;return{value:d.m_predictionWorker.getActiveTopicsAsync(),done:!1};case 3:if(1!=b){a=4;break}a=-1;throw m;case 4:e=g=f;d.m_activeTopics=e.activeTopics;d.__notifyOptionsListeners("activeTopicsAvailable",d.m_activeTopics.slice());a=2;break;case 1:d.__notifyOptionsListeners("activeTopicsAvailable",d.m_activeTopics.slice());
case 2:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.activateTopic=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,k,n){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}h=null;try{return a=4,{value:d.m_predictionWorker.activateTopicAsync(c),done:!1}}catch(l){f=l;a=2;break}case 4:try{if(1!=b){a=5;break}a=-1;throw n;}catch(l){f=l;a=2;break}case 5:try{h=g=k;a=3;break}catch(l){f=l;a=2;break}case 2:throw e=f,Logger.instance.error(e),d.reset(),d.onCrash(),a=-1,e;case 3:d.handleGetTopicsStateResult(!1,
!1,h),CWEBackgroundManager.instance.onTopicActivated(c),d.__notifyOptionsListeners("topicActivated",c);case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f,h,n={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};
CWEPredictionEngine.prototype.activateTopicAsync=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,n,q){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}h=null;try{return a=4,{value:d.m_predictionWorker.activateTopicAsync(c),done:!1}}catch(l){f=l;a=2;break}case 4:try{if(1!=b){a=5;break}a=-1;throw q;}catch(l){f=l;a=2;break}case 5:try{h=g=n;a=3;break}catch(l){f=l;a=2;break}case 2:throw e=f,Logger.instance.error(e),d.reset(),d.onCrash(),a=-1,e;case 3:return d.handleGetTopicsStateResult(!1,
!1,h),CWEBackgroundManager.instance.onTopicActivated(c),d.__notifyOptionsListeners("topicActivated",c),a=-1,{value:{topic:c},done:!0};case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f,h,n={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};
CWEPredictionEngine.prototype.deactivateTopic=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.deactivateTopicAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:e=g=f,d.handleGetTopicsStateResult(!1,!1,e),CWEBackgroundManager.instance.onTopicDeactivated(c),d.__notifyOptionsListeners("topicDeactivated",c);case 1:a=-1;default:return{value:void 0,done:!0}}}
var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.deactivateTopicAsync=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.deactivateTopicAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:return e=g=f,d.handleGetTopicsStateResult(!1,!1,e),CWEBackgroundManager.instance.onTopicDeactivated(c),d.__notifyOptionsListeners("topicDeactivated",c),a=-1,{value:{topic:c},done:!0};case 1:a=
-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.createWikiTopicAsync=function(c,d,b,a){var e=this;return $jscomp.executeAsyncGenerator(function(){function g(g,q,r){for(;;)switch(f){case 0:if(!e.m_initialized){f=1;break}b&&(b=e.canActivateTopic(c));k=null;e.__changeState("create_topic",{name:c},a);try{return f=4,{value:e.m_predictionWorker.createWikiTopicAsync(c,d,b),done:!1}}catch(p){m=p;f=2;break}case 4:try{if(1!=g){f=5;break}f=-1;throw r;}catch(p){m=p;f=2;break}case 5:try{k=n=q;f=3;break}catch(p){m=p;f=2;break}case 2:throw h=
m,Logger.instance.error(h),e.reset(),e.onCrash(),f=-1,h;case 3:return e.handleGetTopicsStateResult(!0,!1,k.topicsState),e.__changeState(),e.handleFilesUpdateInfo(k.filesUpdateInfo),CWEBackgroundManager.instance.onTopicCreated(k.topic,e.m_activeTopics.slice()),e.__notifyOptionsListeners("topicCreated",k.topic,e.m_activeTopics.slice()),f=-1,{value:{topic:k.topic},done:!0};case 1:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,n,m,k,q={next:function(a){return g(0,a,void 0)},throw:function(a){return g(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q}())};
CWEPredictionEngine.prototype.addPersonalWords=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.addPersonalWordsAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:e=g=f,d.handleFilesUpdateInfo(e.filesUpdateInfo);case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},
return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.removePersonalWords=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,m){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.removePersonalWordsAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw m;case 3:e=g=f,d.handleFilesUpdateInfo(e.filesUpdateInfo);case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e,g,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,
a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
CWEPredictionEngine.prototype.enableFlexibleSpelling=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.enableFlexibleSpellingAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.enableGrammar=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.enableGrammarAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.enablePredictAhead=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}a=2;return{value:d.m_predictionWorker.enablePredictAheadAsync(c),done:!1};case 2:if(1!=b){a=3;break}a=-1;throw h;case 3:case 1:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};CWEPredictionEngine.prototype.recentTopics=function(){return this.m_recentTopics};CWEPredictionEngine.prototype.activeTopics=function(){return this.m_activeTopics};CWEPredictionEngine.prototype.allTopics=function(){return this.m_allTopics};
CWEPredictionEngine.prototype.topicNameToDisplayName=function(c){if(null===c||void 0===c)return null;c=c.replace("_"," ");CWEChromeUtilities.stringEndsWith(c," TD")&&(c=c.slice(0,c.length-3));for(var d="",b=0;b<c.length;b++){var a=c.charAt(b);d+=c.charAt(b);if(b<c.length-1){var e=c.charAt(b+1);a.toLowerCase()!=a.toUpperCase()&&e.toLowerCase()!=e.toUpperCase()&&a==a.toLowerCase()&&e==e.toUpperCase()&&(d+=" ")}}return d};CWEPredictionEngine.prototype.sensitiveWords=function(){return this.m_sensitiveWordsMap};
CWEPredictionEngine.prototype.spellcheckerBundledLanguages=function(){return this.m_spellcheckBundledLanguages};CWEPredictionEngine.prototype.spellcheckerHasBundledResource=function(c){return!(!c||!this.m_spellcheckBundledLanguagesMap.hasOwnProperty(c))};
CWEPredictionEngine.prototype.changeSpellcheckerLocale=function(c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(a){case 0:if(!d.m_initialized){a=1;break}d.m_spellcheckerWorker.terminate();d.m_spellcheckLanguage=null;a=-1;return{value:d.__initializeSpellcheckerAsync(c),done:!0};case 1:d.m_spellcheckLanguage=c;case 2:a=-1;default:return{value:void 0,done:!0}}}var a=0,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
CWEPredictionEngine.prototype.spellcheck=function(c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function a(a,e,g){for(;;)switch(d){case 0:return d=-1,{value:b.m_spellcheckerWorker.spellCheck(c),done:!0};default:return{value:void 0,done:!0}}}var d=0,g={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
CWEPredictionEngine.isEnglish=function(){return"FR"!==this.m_locale&&"GER"!==this.m_locale&&"SPA"!==this.m_locale};CWEPredictionEngine.prototype.topicIsActive=function(c){var d=this.m_activeTopics;c=this.topicNameToDisplayName(c);for(var b=0;b<d.length;b++)if(d[b]===c)return!0;return!1};CWEPredictionEngine.prototype.canActivateTopic=function(c){return this.m_activeTopics.length<this.maxActiveTopics||this.topicIsActive(c)};
CWEPredictionEngine.prototype.__topicIndex=function(c){for(var d=0;d<this.m_allTopics.length;d++)if(this.m_allTopics[d]===c)return d;return-1};CWEPredictionEngine.prototype.__activeTopicIndex=function(c){for(var d=0;d<this.m_activeTopics.length;d++)if(this.m_activeTopics[d]===c)return d;return-1};
CWEPredictionEngine.prototype.handleGetTopicsStateResult=function(c,d,b,a){(this.m_initialized||a)&&b&&(c&&(this.m_allTopics=b.allTopics),this.m_activeTopics=b.activeTopics,this.m_recentTopics=b.recentTopics,d&&(c&&this.__notifyOptionsListeners("topicsAvailable",this.m_allTopics.slice()),this.__notifyOptionsListeners("recentTopicsAvailable",this.m_recentTopics.slice()),this.__notifyOptionsListeners("activeTopicsAvailable",this.m_activeTopics.slice())))};
CWEPredictionEngine.prototype.handleFilesUpdateInfo=function(c){CWEBackgroundManager.instance.onFilesChanged(c.files)};CWEPredictionEngine.prototype.__notifyListeners=function(c){for(var d=[].slice.call(arguments).splice(1),b=this.m_listeners.length,a=0;a<b;a++)try{listener=this.m_listeners[a],c in listener&&listener[c].apply(listener,d)}catch(e){Logger.instance.log(e)}};
CWEPredictionEngine.prototype.__notifyOptionsListeners=function(c,d){d=[].slice.call(arguments).splice(1);for(var b=this.m_optionsListeners.length,a=0;a<b;a++)try{listener=this.m_optionsListeners[a],c in listener&&(listener[c].apply(listener,d),this.m_optionsListeners.length<b&&(a--,b--))}catch(e){this.m_optionsListeners.splice(a,1),a--,b--,Logger.instance.log(e)}};
CWEPredictionEngine.prototype.__changeState=function(c,d,b){this.m_state.action=c||null;this.m_state.details=this.m_state.action?d:null;this.m_state.userData=this.m_state.action?b:null};
