var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,f){c!=Array.prototype&&c!=Object.prototype&&(c[e]=f.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var e=0;return $jscomp.iteratorPrototype(function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=c[Symbol.iterator];return e?e.call(c):$jscomp.arrayIterator(c)};
$jscomp.polyfill=function(c,e,f,d){if(e){f=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var a=c[d];a in f||(f[a]={});f=f[a]}c=c[c.length-1];d=f[c];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function e(){this.batch_=null}function f(b){return b instanceof a?b:new a(function(g,a){g(b)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;e.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};e.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var d=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(b){d(b,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var g=0;g<b.length;++g){var a=b[g];delete b[g];try{a()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};e.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var a=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(k){a.reject(k)}};a.prototype.createResolveAndReject_=
function(){function b(b){return function(g){c||(c=!0,b.call(a,g))}}var a=this,c=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};a.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};a.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(k){this.reject_(k);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};a.prototype.reject_=function(b){this.settle_(2,b)};a.prototype.fulfill_=function(b){this.settle_(1,b)};a.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};a.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var h=new e;a.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};a.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(m){c.reject(m)}};a.prototype.then=function(b,c){function e(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(n){f(n)}}:b}var d,f,g=new a(function(b,
a){d=b;f=a});this.callWhenSettled_(e(b,d),e(c,f));return g};a.prototype.catch=function(b){return this.then(void 0,b)};a.prototype.callWhenSettled_=function(b,a){function c(){switch(d.state_){case 1:b(d.result_);break;case 2:a(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(function(){h.asyncExecute(c)})};a.resolve=f;a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(a,
c){for(var d=$jscomp.makeIterator(b),e=d.next();!e.done;e=d.next())f(e.value).callWhenSettled_(a,c)})};a.all=function(b){var c=$jscomp.makeIterator(b),d=c.next();return d.done?f([]):new a(function(a,b){function e(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,f(d.value).callWhenSettled_(e(g.length-1),b),d=c.next();while(!d.done)})};return a},"es6","es3");
$jscomp.executeAsyncGenerator=function(c){function e(d){return c.next(d)}function f(d){return c.throw(d)}return new Promise(function(d,a){function h(b){b.done?d(b.value):Promise.resolve(b.value).then(e,f).then(h,a)}h(c.next())})};
var Module={},WasmModuleWrapper=function(){var c=null,e=!1,f=!1,d=void 0;Module.locateFile=function(a){return c+"/"+a};Module.setStatus=function(a){};Module.monitorRunDependencies=function(a){};Module.onRuntimeInitialized=function(){e=!0;f=!1;try{d&&d(!0)}catch(a){console.error(a)}d=void 0};return{loadAndInitializeAsync:function(a){return $jscomp.executeAsyncGenerator(function(){function h(g,h,p){for(;;)switch(b){case 0:return b=-1,{value:new Promise(function(b,g){if(e||f)return g(Error("Loading in progress!"));
f=!0;d=b;c=a;importScripts(c+"/cowriter-spellchecker.js");importScripts("/Background/djiVFS.js");importScripts("/Background/djiSyncFSDriver.js")}),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return h(0,a,void 0)},throw:function(a){return h(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())},Module:Module}}();
(function(){function c(c,f){return $jscomp.executeAsyncGenerator(function(){function d(d,h,k){for(;;)switch(a){case 0:g=null;try{return a=3,{value:WasmModuleWrapper.loadAndInitializeAsync(c.appDir),done:!1}}catch(l){b=l;a=1;break}case 3:try{if(1!=d){a=4;break}a=-1;throw k;}catch(l){b=l;a=1;break}case 4:try{a=2;break}catch(l){b=l;a=1;break}case 1:g=e=b;case 2:self.postMessage({message:f,params:{error:g?g.message:null}}),a=-1;default:return{value:void 0,done:!0}}}var a=0,e,b,g,k={next:function(a){return d(0,
a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())}self.addEventListener("message",function(e){e=e.data;var f=e.message,d=e.params;e=(e.options||{}).callbackMessage;if("com.donjohnston.cowriter.worker.load"===f)c(d,e);else if("com.donjohnston.cowriter.worker.initialize"===f)if(d.locale)if(d.resourceDirectory||d.commonDirectory){f=d.locale;try{d.commonDirectory&&
0<d.commonDirectory.length&&FS.extensions.mapSyncFS(d.commonDirectory),d.resourceDirectory&&0<d.resourceDirectory.length&&FS.extensions.mapVfsContainer(d.resourceDirectory,d.resourceContainer),initialized=Module.initialize(f)}catch(g){console.error(g)}self.postMessage({message:e,params:{initialized:initialized,error:initialized?null:"Worker could not be initialized!"}})}else self.postMessage({message:e,params:{initialized:!1,error:"Missing resource directory parameter!"}});else self.postMessage({message:e,
params:{initialized:!1,error:"Missing locale parameter!"}});else if("com.donjohnston.cowriter.worker.spellcheck"===f){d=Module.spellcheck(d.word);f=d.word;for(var a=d.suggestions,h=[],b=0;b<a.size();b++)h.push(a.get(b));self.postMessage({message:e,params:{word:f,suggestions:h,matchWord:d.matchWord||"",matchFound:d.matchFound}})}});self.postMessage({message:"com.donjohnston.cowriter.worker.ready",params:{error:null}})})();
