var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,e,c,d){if(e){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var b=a[d];b in c||(c[b]={});c=c[b]}a=a[a.length-1];d=c[a];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}function c(f){return f instanceof b?f:new b(function(a,b){a(f)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;e.prototype.asyncExecute=function(f){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(f);return this};e.prototype.asyncExecuteBatch_=function(){var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})};var d=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(f){d(f,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var a=0;a<f.length;++a){var b=f[a];delete f[a];try{b()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};e.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var b=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{f(a.resolve,a.reject)}catch(l){a.reject(l)}};b.prototype.createResolveAndReject_=
function(){function f(f){return function(c){b||(b=!0,f.call(a,c))}}var a=this,b=!1;return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};b.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var a=null!=f;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(f):this.fulfill_(f)}};b.prototype.resolveToNonPromiseObj_=function(f){var a=
void 0;try{a=f.then}catch(l){this.reject_(l);return}"function"==typeof a?this.settleSameAsThenable_(a,f):this.fulfill_(f)};b.prototype.reject_=function(f){this.settle_(2,f)};b.prototype.fulfill_=function(f){this.settle_(1,f)};b.prototype.settle_=function(f,a){if(0!=this.state_)throw Error("Cannot settle("+f+", "+a|"): Promise already settled in state"+this.state_);this.state_=f;this.result_=a;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new e;b.prototype.settleSameAsPromise_=function(a){var f=this.createResolveAndReject_();a.callWhenSettled_(f.resolve,f.reject)};b.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(k){f.reject(k)}};b.prototype.then=function(a,c){function f(a,f){return"function"==typeof a?function(f){try{g(a(f))}catch(p){e(p)}}:f}var g,e,d=new b(function(a,
f){g=a;e=f});this.callWhenSettled_(f(a,g),f(c,e));return d};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function f(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?g.asyncExecute(f):this.onSettledCallbacks_.push(function(){g.asyncExecute(f)})};b.resolve=c;b.reject=function(a){return new b(function(f,b){b(a)})};b.race=function(a){return new b(function(f,
b){for(var g=$jscomp.makeIterator(a),e=g.next();!e.done;e=g.next())c(e.value).callWhenSettled_(f,b)})};b.all=function(a){var f=$jscomp.makeIterator(a),g=f.next();return g.done?c([]):new b(function(a,b){function e(f){return function(b){d[f]=b;m--;0==m&&a(d)}}var d=[],m=0;do d.push(void 0),m++,c(g.value).callWhenSettled_(e(d.length-1),b),g=f.next();while(!g.done)})};return b},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function e(c){return a.next(c)}function c(c){return a.throw(c)}return new Promise(function(d,b){function g(a){a.done?d(a.value):Promise.resolve(a.value).then(e,c).then(g,b)}g(a.next())})};$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var e=function(){};e.prototype=a;return new e};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},e={};try{return e.__proto__=a,e.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,e){a.__proto__=e;if(a.__proto__!==e)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,e){a.prototype=$jscomp.objectCreate(e.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,e)}else for(c in e)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(e,c);d&&Object.defineProperty(a,c,d)}else a[c]=e[c];a.superClass_=e.prototype};var DjiWasmWorkerProxy=function(a){this.m_options={url:a.url,appDir:a.appDir};this.m_worker=this.m_config=null;this.m_eventTarget=new EventTarget;this.__setup()};
DjiWasmWorkerProxy.prototype.initAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,g,d){for(;;)switch(b){case 0:return c.m_config=e?a:JSON.parse(JSON.stringify(a)),b=-1,{value:c.restartAsync(),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};
return g}())};
DjiWasmWorkerProxy.prototype.restartAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function e(b,f,e){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a,f){d.__restart(a,f)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,b={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=function(){return this};return b}())};
DjiWasmWorkerProxy.prototype.terminate=function(){this.m_worker&&(this.m_worker.removeEventListener("message",this.__onMessageProxy),this.m_worker.removeEventListener("error",this.__onMessageProxy),this.m_worker.terminate(),this.m_worker=null)};DjiWasmWorkerProxy.prototype.on=function(a,e){this.m_eventTarget.addEventListener(a,e)};DjiWasmWorkerProxy.prototype.__setup=function(){var a=this;this.__onMessageProxy=function(e){a.__onMessage(e)};this.__onErrorProxy=function(e){a.__onError(e)}};
DjiWasmWorkerProxy.prototype.__restart=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,q,p){for(;;)switch(b){case 0:r=c;try{return k=null,c.terminate(),c.m_worker=new Worker(c.m_options.url),c.m_worker.__pending=!0,b=3,{value:c.__waitForCallbackAsync(null,"com.donjohnston.cowriter.worker.ready"),done:!1}}catch(h){n=h;b=1;break}case 3:try{if(1!=d){b=4;break}b=-1;throw p;}catch(h){n=h;b=1;break}case 4:try{k=l=q;if(!k.error){b=5;break}b=-1;throw Error(k.error);}catch(h){n=
h;b=1;break}case 5:try{return b=6,{value:c.__executeCommandAsync(null,"com.donjohnston.cowriter.worker.load",{appDir:c.m_options.appDir}),done:!1}}catch(h){n=h;b=1;break}case 6:try{if(1!=d){b=7;break}b=-1;throw p;}catch(h){n=h;b=1;break}case 7:try{k=m=q;if(!k.error){b=8;break}b=-1;throw Error(k.error);}catch(h){n=h;b=1;break}case 8:try{if(!c.m_config){b=9;break}b=10;return{value:c.__executeCommandAsync(null,"com.donjohnston.cowriter.worker.initialize",c.m_config),done:!1}}catch(h){n=h;b=1;break}case 10:try{if(1!=
d){b=11;break}b=-1;throw p;}catch(h){n=h;b=1;break}case 11:try{k=f=q;if(!k.error){b=12;break}b=-1;throw Error(k.error);}catch(h){n=h;b=1;break}case 12:case 9:try{c.m_worker.addEventListener("message",r.__onMessageProxy);c.m_worker.addEventListener("error",r.__onMessageProxy);a("ready");b=2;break}catch(h){n=h;b=1;break}case 1:g=n,c.terminate(),e(g);case 2:b=-1;default:return{value:void 0,done:!0}}}var b=0,g,f,m,l,k,n,r,t={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},
return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();t[Symbol.iterator]=function(){return this};return t}())};DjiWasmWorkerProxy.prototype.__onMessage=function(a){};DjiWasmWorkerProxy.prototype.__onError=function(a){};DjiWasmWorkerProxy.prototype.__executeCommandAsync=function(a,e,c,d){var b=this;return new Promise(function(g,f){b.__executeCommand(a,e,c,d,g,f)})};
DjiWasmWorkerProxy.prototype.__executeCommand=function(a,e,c,d,b,g){if(b&&!(b instanceof Function))throw Error("Invalid arguments: successCallback is not a function!");a=a||this.m_worker;d=d||{};if(!a)return g(Error("Worker not running!"));var f=this.__executeCommand.session=(this.__executeCommand.session||0)+1;f=b?"com.donjohnston.cwu.wasm.session."+f:void 0;e={message:e,params:c,options:{wantDefaultCallbackMessage:d.wantDefaultCallbackMessage?!0:void 0,callbackMessage:f}};this.__watchForCallback(a,
f,b,g);a.postMessage(e)};DjiWasmWorkerProxy.prototype.__sendCommand=function(a,e,c,d){a=a||this.m_worker;d=d||{};if(!a)throw Error("Worker not running!");a.postMessage({message:e,params:c,options:{wantDefaultCallbackMessage:d.wantDefaultCallbackMessage?!0:void 0,callbackMessage:d.callbackMessage||void 0}})};
DjiWasmWorkerProxy.prototype.__waitForCallbackAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,k){for(;;)switch(b){case 0:return g=c,b=-1,{value:new Promise(function(f,b){g.__watchForCallback(a,e,f,b)}),done:!0};default:return{value:void 0,done:!0}}}var b=0,g,f={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};
return f}())};
DjiWasmWorkerProxy.prototype.__watchForCallback=function(a,e,c,d){if(c&&!(c instanceof Function))throw Error("Invalid arguments: successCallback is not a function!");var b=void 0,g=void 0;a=a||this.m_worker;c&&(b=function(f){var d=f.data;if(d&&d.message===e){f.preventDefault();f.stopPropagation();g&&(a.removeEventListener("error",g,!0),a.removeEventListener("crash",g,!0));a.removeEventListener("message",b,!0);try{c(d.params)}catch(l){Logger.instance.error(l)}}},a.addEventListener("message",b,!0));
d&&(g=function(f){a.removeEventListener("error",g,!0);a.removeEventListener("crash",g,!0);c&&a.removeEventListener("message",b,!0);try{d(f)}catch(m){Logger.instance.error(m)}},a.addEventListener("error",g,!0),a.addEventListener("crash",g,!0))};var DjiSpellCheckerWorkerProxy=function(a){DjiWasmWorkerProxy.call(this,a);this.m_messages={spellcheck:"com.donjohnston.cowriter.worker.spellcheck"}};$jscomp.inherits(DjiSpellCheckerWorkerProxy,DjiWasmWorkerProxy);
DjiSpellCheckerWorkerProxy.prototype.spellCheck=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.spellcheck,{word:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=function(){return this};
return b}())};
var DjiPredictionWorkerProxy=function(a){DjiWasmWorkerProxy.call(this,a);this.m_messages={sync:"com.donjohnston.cowriter.worker.sync",syncUserDirectory:"com.donjohnston.cowriter.worker.syncUserDirectory",options:"com.donjohnston.cowriter.worker.options",optionsMainDictionary:"com.donjohnston.cowriter.worker.options.mainDictionary",optionsMaxPredictedGuesses:"com.donjohnston.cowriter.worker.options.maxPredictedGuesses",optionsMomentaryTopic:"com.donjohnston.cowriter.worker.options.momentaryTopic",optionsFlexibleSpelling:"com.donjohnston.cowriter.worker.options.flexibleSpelling",
optionsGrammar:"com.donjohnston.cowriter.worker.options.grammar",optionsPredictAhead:"com.donjohnston.cowriter.worker.options.predictAhead",followTextChange:"com.donjohnston.cowriter.worker.followTextChange",acceptGuess:"com.donjohnston.cowriter.worker.acceptGuess",restartGuesses:"com.donjohnston.cowriter.worker.restartGuesses",resetState:"com.donjohnston.cowriter.worker.resetState",getTopicsState:"com.donjohnston.cowriter.worker.getTopicsState",getTopics:"com.donjohnston.cowriter.worker.getTopics",
getActiveTopics:"com.donjohnston.cowriter.worker.getActiveTopics",getRecentTopics:"com.donjohnston.cowriter.worker.getRecentTopics",activateTopic:"com.donjohnston.cowriter.worker.activateTopic",activateTopics:"com.donjohnston.cowriter.worker.activateTopics",setActiveTopics:"com.donjohnston.cowriter.worker.setActiveTopics",deactivateTopic:"com.donjohnston.cowriter.worker.deactivateTopic",deactivateTopics:"com.donjohnston.cowriter.worker.deactivateTopics",deactivateActiveTopics:"com.donjohnston.cowriter.worker.deactivateActiveTopics",
updateMomentaryTopic:"com.donjohnston.cowriter.worker.updateMomentaryTopic",createWikiTopic:"com.donjohnston.cowriter.worker.createWikiTopic",activatePersonalDictionary:"com.donjohnston.cowriter.worker.activatePersonalDictionary",addPersonalWords:"com.donjohnston.cowriter.worker.addPersonalWords",removePersonalWords:"com.donjohnston.cowriter.worker.removePersonalWords",reloadDictionaries:"com.donjohnston.cowriter.worker.reloadDictionaries"}};$jscomp.inherits(DjiPredictionWorkerProxy,DjiWasmWorkerProxy);
DjiPredictionWorkerProxy.prototype.__onMessage=function(a){(a=a.data)&&a.message===this.m_messages.followTextChange&&(a=new CustomEvent(this.m_messages.followTextChange,{detail:a.params}),this.m_eventTarget.dispatchEvent(a))};DjiPredictionWorkerProxy.prototype.onFollowTextChange=function(a){this.on(this.m_messages.followTextChange,a)};
DjiPredictionWorkerProxy.prototype.syncAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function e(b,e,f){for(;;)switch(c){case 0:return c=-1,{value:a.__executeCommandAsync(null,a.m_messages.sync,null,null),done:!0};default:return{value:void 0,done:!0}}}var c=0,d={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();d[Symbol.iterator]=function(){return this};return d}())};
DjiPredictionWorkerProxy.prototype.syncUserDirectoryAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function e(b,e,f){for(;;)switch(c){case 0:return c=-1,{value:a.__executeCommandAsync(null,a.m_messages.syncUserDirectory,null,null),done:!0};default:return{value:void 0,done:!0}}}var c=0,d={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();d[Symbol.iterator]=
function(){return this};return d}())};
DjiPredictionWorkerProxy.prototype.setOptionsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.options,{mainDictionary:a.mainDictionary,enableMomentaryTopic:a.enableMomentaryTopic,enableFlexibleSpelling:a.enableFlexibleSpelling,enableGrammar:a.enableGrammar,enablePredictAhead:a.enablePredictAhead,maxPredictedGuesses:a.maxPredictedGuesses,activeTopics:a.activeTopics,userData:e},
null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.setMainDictionaryAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsMainDictionary,{value:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.setMaxPredictedGuessesAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsMaxPredictedGuesses,{value:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.enableMomentaryTopicAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsMomentaryTopic,{flag:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.enableFlexibleSpellingAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsFlexibleSpelling,{flag:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.enableGrammarAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsGrammar,{flag:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.enablePredictAheadAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.optionsPredictAhead,{flag:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};DjiPredictionWorkerProxy.prototype.followTextChange=function(a,e,c,d,b){return this.__sendCommand(null,this.m_messages.followTextChange,{contextChanged:a,text:e,rangeStart:c,rangeLength:d,userData:b},{callbackMessage:this.m_messages.followTextChange})};
DjiPredictionWorkerProxy.prototype.acceptGuessAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.acceptGuess,{guess:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.restartGuessesAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.restartGuesses,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=
function(){return this};return b}())};
DjiPredictionWorkerProxy.prototype.resetStateAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.resetState,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=function(){return this};
return b}())};
DjiPredictionWorkerProxy.prototype.getTopicsStateAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.getTopicsState,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=function(){return this};
return b}())};
DjiPredictionWorkerProxy.prototype.getTopicsAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.getTopics,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=function(){return this};
return b}())};
DjiPredictionWorkerProxy.prototype.getActiveTopicsAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.getActiveTopics,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=
function(){return this};return b}())};
DjiPredictionWorkerProxy.prototype.getRecentTopicsAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,f,c){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.getRecentTopics,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();b[Symbol.iterator]=
function(){return this};return b}())};
DjiPredictionWorkerProxy.prototype.activateTopicAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.activateTopic,{topic:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.activateTopicsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.activateTopics,{topics:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.setActiveTopicsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(f,d,g){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.setActiveTopics,{topics:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.deactivateTopicAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.deactivateTopic,{topic:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.deactivateTopicsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.deactivateTopics,{topics:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.deactivateActiveTopicsAsync=function(a){var e=this;return $jscomp.executeAsyncGenerator(function(){function c(b,c,m){for(;;)switch(d){case 0:return d=-1,{value:e.__executeCommandAsync(null,e.m_messages.deactivateActiveTopics,{userData:a},null),done:!0};default:return{value:void 0,done:!0}}}var d=0,b={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
b[Symbol.iterator]=function(){return this};return b}())};
DjiPredictionWorkerProxy.prototype.updateMomentaryTopicAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.updateMomentaryTopic,{text:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.createWikiTopicAsync=function(a,e,c,d){var b=this;return $jscomp.executeAsyncGenerator(function(){function g(g,m,n){for(;;)switch(f){case 0:return f=-1,{value:b.__executeCommandAsync(null,b.m_messages.createWikiTopic,{name:a,text:e,activate:c,userData:d},null),done:!0};default:return{value:void 0,done:!0}}}var f=0,m={next:function(a){return g(0,a,void 0)},throw:function(a){return g(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
m[Symbol.iterator]=function(){return this};return m}())};
DjiPredictionWorkerProxy.prototype.activatePersonalDictionaryAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.activatePersonalDictionary,{activate:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.addPersonalWordsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.addPersonalWords,{text:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=
function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.removePersonalWordsAsync=function(a,e){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,l){for(;;)switch(b){case 0:return b=-1,{value:c.__executeCommandAsync(null,c.m_messages.removePersonalWords,{text:a,userData:e},null),done:!0};default:return{value:void 0,done:!0}}}var b=0,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiPredictionWorkerProxy.prototype.reloadDictionariesAsync=function(a,e,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,k){for(;;)switch(g){case 0:return g=-1,{value:d.__executeCommandAsync(null,d.m_messages.reloadDictionaries,{userDictionaries:a,topicsContent:e,userData:c},null),done:!0};default:return{value:void 0,done:!0}}}var g=0,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
