var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,f){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var h=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(m){f(m)}}:b}var e,f,g=new c(function(a,
b){e=a;f=b});this.callWhenSettled_(d(a,e),d(b,f));return g};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(function(){h.asyncExecute(c)})};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,
c){for(var e=$jscomp.makeIterator(a),h=e.next();!h.done;h=e.next())d(h.value).callWhenSettled_(b,c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function h(b){return function(c){f[b]=c;g--;0==g&&a(f)}}var f=[],g=0;do f.push(void 0),g++,d(e.value).callWhenSettled_(h(f.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function h(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(h,c)}h(a.next())})};
function CWEWikiReader(a,b){var d=this;this.m_listener=b;this.m_wikiSearchUrl={uk:"https://en.wikipedia.org/w/api.php?action=opensearch&search=",us:"https://en.wikipedia.org/w/api.php?action=opensearch&search=",be:"https://en.wikipedia.org/w/api.php?action=opensearch&search=",can:"https://en.wikipedia.org/w/api.php?action=opensearch&search=",fr:"https://fr.wikipedia.org/w/api.php?action=opensearch&search=",ger:"https://de.wikipedia.org/w/api.php?action=opensearch&search=",spa:"https://es.wikipedia.org/w/api.php?action=opensearch&search="};
this.m_wikiLoadUrl={uk:"https://en.wikipedia.org/w/index.php?printable=yes&title=",us:"https://en.wikipedia.org/w/index.php?printable=yes&title=",be:"https://en.wikipedia.org/w/index.php?printable=yes&title=",can:"https://en.wikipedia.org/w/index.php?printable=yes&title=",fr:"https://fr.wikipedia.org/w/index.php?printable=yes&title=",ger:"https://de.wikipedia.org/w/index.php?printable=yes&title=",spa:"https://es.wikipedia.org/w/index.php?printable=yes&title="};this.m_searchXHR=this.m_searchTimer=
null;this.m_sensitiveWordsMap=a||{};this.m_excludeWordsList="References;See also;External links;Notes;Rate this page;Notes and references;Footnotes;Bibliography;Further reading;Some references".split(";");this.__doSearchWrapper=function(a,b){d.__doSearch(a,b)}}CWEWikiReader.prototype.setOptions=function(a){a&&a.hasOwnProperty("sensitiveWords")&&(this.m_sensitiveWordsMap=a.sensitiveWords)};
CWEWikiReader.prototype.search=function(a,b){if(!this.m_listener)throw Error("Invalid parameters: callback is missing!");b=b.toLowerCase();null!==this.m_searchTimer&&clearTimeout(this.m_searchTimer);this.m_searchTimer=setTimeout(this.__doSearchWrapper,0,{text:a,locale:b,enhanced:!1})};
CWEWikiReader.prototype.searchAsync=function(a,b){b=b.toLowerCase();var d=this;null!==d.m_searchTimer&&clearTimeout(this.m_searchTimer);return new Promise(function(e){d.m_searchTimer=setTimeout(d.__doSearchWrapper,0,{text:a,locale:b,enhanced:!0},e)})};
CWEWikiReader.prototype.__doSearch=function(a,b){var d=this.__filter(a.text),e=a.locale;this.m_searchTimer=null;this.m_searchXHR&&(this.m_searchXHR.abort(),this.m_searchXHR=null);if(!navigator.onLine||void 0===d||null===d||0>=d.length)b instanceof Function?b([]):this.m_listener.wikiReaderSearchFinished([]);else{var c=this;this.m_searchXHR=$.ajax(this.m_wikiSearchUrl[e]+encodeURIComponent(d)).done(function(d){c.m_searchXHR=null;var e=d&&1<=d.length?d[1]:[],g=a.enhanced?[]:e;a.enhanced?(d=d&&3<=d.length?
d[3]:[],e.forEach(function(a){g.push({name:a})}),d.forEach(function(a,b){g[b].url=a}),g=g.filter(function(a){return c.__validate(a.name)})):g=g.filter(function(a){return c.__validate(a)});b instanceof Function?b(g):c.m_listener.wikiReaderSearchFinished(g)}).fail(function(){c.m_searchXHR=null;b instanceof Function?b([]):c.m_listener.wikiReaderSearchFinished([])})}};
CWEWikiReader.prototype.__filter=function(a){a=a.split(/\b/);for(var b=[],d=0;d<a.length;d++){var e=a[d].trim(),c=e.toUpperCase();0<c.length&&!this.m_sensitiveWordsMap.hasOwnProperty(c)&&b.push(e)}return b.join(" ")};CWEWikiReader.prototype.__validate=function(a){a=a.split(/\b/);for(var b=0;b<a.length;b++){var d=a[b].trim().toUpperCase();if(0<d.length&&this.m_sensitiveWordsMap.hasOwnProperty(d))return!1}return!0};CWEWikiReader.prototype.load=function(a,b){navigator.onLine?this.__load(a,b):this.m_listener.wikiReaderLoadFinished(null)};
CWEWikiReader.prototype.loadAsync=function(a,b){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,f,k){for(;;)switch(c){case 0:if(navigator.onLine){c=1;break}c=-1;return{value:null,done:!0};case 1:return h=d,c=-1,{value:new Promise(function(c){h.__load(a,b,c)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,h,f={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
f[Symbol.iterator]=function(){return this};return f}())};
CWEWikiReader.prototype.__load=function(a,b,d){var e=this;b=b?b.toLowerCase():"us";$.get(e.m_wikiLoadUrl[b]+encodeURIComponent(a)).done(function(a){a=a.replace(/<script>/g,"\x3c!-- ").replace(/<script /g,"\x3c!-- ").replace(/<\/script>/g,"< --!>").replace(/<noscript>/g,"\x3c!-- ").replace(/<\/noscript>/g,"< --!>").replace(/<link /g,"\x3c!-- ").replace(/<\/link>/g,"< --!>").replace(/<meta /g,"\x3c!-- ").replace(/<\/meta>/g,"< --!>").replace(/<style>/g,"\x3c!-- ").replace(/<style /g,"\x3c!-- ").replace(/<\/style>/g,
"< --!>").replace(/<img /g,"\x3c!-- ").replace(/<\/img>/g,"< --!>").replace(/<a /g,"\x3c!-- ").replace(/<\/a>/g,"< --!>").replace(/http/g,"xxx");a=document.createRange().createContextualFragment(a);var c=a.getElementById("content");c||(c=a.getElementById("bodyContent"));(a=c?c.textContent:null)&&(a=e.__processWikiContent(a,b));d?d(a||null):e.m_listener.wikiReaderLoadFinished(e.__processWikiContent(a||null,b))}).fail(function(){d?d(null):e.m_listener.wikiReaderLoadFinished(null,b)})};
CWEWikiReader.prototype.__processWikiContent=function(a,b){b=b.toLowerCase();a="fr"==b||"spa"==b||"ger"==b?CWEChromeUtilities.htmlToUnicode(a):CWEChromeUtilities.wikiHtmlToAscii(a);if(!a)return"";a=a.replace(/\r\r/g,"\r");b=a.length/4;for(var d=0;d<this.m_excludeWordsList.length;d++){var e=this.m_excludeWordsList[d];e="\r"+e+"\r";e=a.lastIndexOf(e);-1!=e&&e>b&&(a=a.slice(0,e))}return a};
