var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];delete a[b];try{d()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(c){d||(d=!0,a.call(b,c))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(k){d.reject(k)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(p){f(p)}}:b}var c,f,g=new e(function(a,
b){c=a;f=b});this.callWhenSettled_(d(a,c),d(b,f));return g};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?f.asyncExecute(d):this.onSettledCallbacks_.push(function(){f.asyncExecute(d)})};e.resolve=c;e.reject=function(a){return new e(function(b,d){d(a)})};e.race=function(a){return new e(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(d){g[b]=d;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<e;)if(b[c++]!=a[g++])return!1;return g>=f}},"es6","es3");function DjiHtml5FileSystem(){this.m_fileSystem=null;return this}DjiHtml5FileSystem.instance=null;
DjiHtml5FileSystem.initialize=function(a){if(null===DjiHtml5FileSystem.instance){DjiHtml5FileSystem.instance=new DjiHtml5FileSystem;try{DjiHtml5FileSystem.instance.__initialize(function(b){DjiHtml5FileSystem.instance=b;a&&a(b)})}catch(b){DjiHtml5FileSystem.instance=null,Logger.instance.error(b)}}};
DjiHtml5FileSystem.prototype.__initialize=function(a){var b=this;navigator.webkitPersistentStorage.requestQuota(524288E3,function(c){Logger.instance.log("Quota granted: ",c);window.webkitRequestFileSystem(window.PERSISTENT,c,function(d){b.m_fileSystem=d;Logger.instance.log("fileSystem: ",d);setTimeout(function(){b.__callback(a,b)},10)},function(d){Logger.instance.error(d);b.__callback(a,null)})},function(c){Logger.instance.error(c);b.__callback(a,null)})};
DjiHtml5FileSystem.prototype.getDirectory=function(a,b,c){var d=this;this.m_fileSystem.root.getDirectory(a,{create:b},function(a){d.__callback(c,a)},function(b){Logger.instance.groupCollapsed("getDirectory failed for file: "+a);Logger.instance.error(b);Logger.instance.groupEnd();d.__callback(c,null)})};DjiHtml5FileSystem.prototype.getDirectoryAsync=function(a,b){var c=this;return new Promise(function(d,e){c.m_fileSystem.root.getDirectory(a,{create:b},d,e)})};
DjiHtml5FileSystem.prototype.getFile=function(a,b,c){var d=this;this.m_fileSystem.root.getFile(a,{create:b},function(a){d.__callback(c,a)},function(b){Logger.instance.groupCollapsed("getFile failed for file: "+a);Logger.instance.error(b);Logger.instance.groupEnd();d.__callback(c,null)})};DjiHtml5FileSystem.prototype.directoryExists=function(a,b){this.m_fileSystem.root.getDirectory(a,{create:!1},function(){b(!0)},function(){b(!1)})};
DjiHtml5FileSystem.prototype.fileExists=function(a,b){this.m_fileSystem.root.getFile(a,{create:!1},function(){b(!0)},function(){b(!1)})};DjiHtml5FileSystem.prototype.createDirectory=function(a,b){var c=this,d=this.__splitPath(a);if(!d||0>=d.length)c.__callback(b,null);else{var e=this.m_fileSystem.root,f=-1,g=function(){f++;f<d.length?e.getDirectory(d[f],{create:!0},function(a){e=a;f+1<d.length?g():c.__callback(b,e)},function(a){Logger.instance.error(a);c.__callback(b,null)}):c.__callback(b,e)};g()}};
DjiHtml5FileSystem.prototype.createDirectories=function(a,b){var c=this;if(!a||0>=a.length)c.__callback(b,null);else{var d=-1,e=function(){d++;if(d<a.length){var f=a[d];c.directoryExists(f,function(g){g?(Logger.instance.log("directory already exists"),d+1<a.length?e():c.__callback(b)):c.createDirectory(f,function(){d+1<a.length?e():c.__callback(b)})})}else c.__callback(b)};e()}};
DjiHtml5FileSystem.prototype.writeFile=function(a,b,c){var d=this;this.m_fileSystem.root.getFile(a,{create:!0},function(a){a.createWriter(function(e){var f=function(){d.__callback(c,!0,a)},h=function(a){Logger.instance.error(a);d.__callback(c,!1,null)};e.onwriteend=function(){e.onwriteend=f;e.onerror=h;var a=b instanceof Blob?b:new Blob([b],{type:"application/octet-stream"});e.write(a)};e.onerror=function(a){Logger.instance.error(a);d.__callback(c,!1,null)};e.truncate(0)},function(a){Logger.instance.error(a);
d.__callback(c,!1,null)})},function(b){Logger.instance.error("error getting file:",a,"error:",b);d.__callback(c,!1,null)})};
DjiHtml5FileSystem.prototype.writeFileAsText=function(a,b,c){var d=this;this.m_fileSystem.root.getFile(a,{create:!0},function(a){a.createWriter(function(e){var f=function(){d.__callback(c,!0,a)},h=function(a){Logger.instance.error(a);d.__callback(c,!1,null)};e.onwriteend=function(){e.onwriteend=f;e.onerror=h;var a=b instanceof Blob?b:new Blob([b],{type:"text/plain;charset=UTF-8"});e.write(a)};e.onerror=function(a){Logger.instance.error(a);d.__callback(c,!1,null)};e.truncate(0)},function(a){Logger.instance.error(a);
d.__callback(c,!1,null)})},function(b){Logger.instance.error("error getting file:",a,"error:",b);d.__callback(c,!1,null)})};DjiHtml5FileSystem.prototype.writeFiles=function(a,b,c){var d=this;0!=a.length&&0!=b.length||d.__callback(c);var e=-1,f=function(){e++;e<a.length?d.writeFile(a[e],b[e],function(){f()}):d.__callback(c)};f()};
DjiHtml5FileSystem.prototype.readFile=function(a,b){var c=this;this.m_fileSystem.root.getFile(a,{},function(a){a.file(function(d){var e=new FileReader;e.onloadend=function(){c.__callback(b,this.result,a)};e.onerror=function(a){Logger.instance.error(a);c.__callback(b,null,null)};e.readAsBinaryString(d)},function(a){Logger.instance.error(a);c.__callback(b,null,null)})},function(d){"NotFoundError"!==d.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(d),Logger.instance.groupEnd());
c.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsBinaryString=function(a,b){var c=this;this.m_fileSystem.root.getFile(a,{},function(a){a.file(function(d){var e=new FileReader;e.onloadend=function(){c.__callback(b,this.result,a)};e.onerror=function(a){Logger.instance.error(a);c.__callback(b,null,null)};e.readAsBinaryString(d)},function(a){Logger.instance.error(a);c.__callback(b,null,null)})},function(d){"NotFoundError"!==d.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(d),
Logger.instance.groupEnd());c.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsArrayBuffer=function(a,b){var c=this;this.m_fileSystem.root.getFile(a,{},function(a){a.file(function(d){var e=new FileReader;e.onloadend=function(){c.__callback(b,this.result,a)};e.onerror=function(a){Logger.instance.error(a);c.__callback(b,null,null)};e.readAsArrayBuffer(d)},function(a){Logger.instance.error(a);c.__callback(b,null,null)})},function(d){"NotFoundError"!==d.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(d),
Logger.instance.groupEnd());c.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsText=function(a,b){var c=this;this.m_fileSystem.root.getFile(a,{},function(a){a.file(function(d){var e=new FileReader;e.onloadend=function(){c.__callback(b,this.result,a)};e.onerror=function(a){Logger.instance.error(a);c.__callback(b,null,null)};e.readAsText(d)},function(a){Logger.instance.error(a);c.__callback(b,null,null)})},function(d){"NotFoundError"!==d.name&&(Logger.instance.groupCollapsed("readFile failed for file: "+a),Logger.instance.error(d),Logger.instance.groupEnd());
c.__callback(b,null,null)})};
DjiHtml5FileSystem.prototype.readFileAsTextAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:return e=b,d=-1,{value:new Promise(function(b){e.m_fileSystem.root.getFile(a,{},function(a){a.file(function(a){var d=new FileReader;d.onloadend=function(){b(this.result)};d.onerror=function(a){Logger.instance.error(a);b(null)};d.readAsText(a)},function(a){Logger.instance.error(a);b(null)})},function(d){Logger.instance.groupCollapsed("readFile failed for file: "+a);
Logger.instance.error(d);Logger.instance.groupEnd();b(null)})}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
DjiHtml5FileSystem.prototype.removeDirectory=function(a,b){var c=this;this.m_fileSystem.root.getDirectory(a,{},function(a){a.removeRecursively(function(){c.__callback(b,!0)},function(a){Logger.instance.error(a);c.__callback(b,!1)})},function(a){"NotFoundError"!==a.name&&Logger.instance.error(a);c.__callback(b,"NotFoundError"===a.name)})};
DjiHtml5FileSystem.prototype.removeDirectoryAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:return e=b,d=-1,{value:new Promise(function(b){e.m_fileSystem.root.getDirectory(a,{},function(a){a.removeRecursively(function(){b(!0)},function(a){Logger.instance.error(a);b(!1)})},function(a){"NotFoundError"!==a.name&&Logger.instance.error(a);b("NotFoundError"===a.name)})}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,
a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};DjiHtml5FileSystem.prototype.removeDirectoryContents=function(a,b){var c=this;c.removeDirectory(a,function(){c.createDirectory(a,function(a){c.__callback(b)})})};
DjiHtml5FileSystem.prototype.removeFile=function(a,b){var c=this;this.m_fileSystem.root.getFile(a,{},function(a){a.remove(function(){c.__callback(b,!0)},function(a){Logger.instance.error(a);c.__callback(b,!1)})},function(a){"NotFoundError"!==a.name&&Logger.instance.error(a);c.__callback(b,"NotFoundError"===a.name)})};
DjiHtml5FileSystem.prototype.removeFiles=function(a,b){if(!a||0>=a.length)this.__callback(b);else{var c=this,d=-1,e=function(){d++;d<a.length?c.removeFile(a[d],function(){setTimeout(e,0)}):c.__callback(b)};e()}};DjiHtml5FileSystem.prototype.directoryExists=function(a,b){this.m_fileSystem.root.getDirectory(a,{create:!1},function(){b(!0)},function(){b(!1)})};DjiHtml5FileSystem.prototype.fileExists=function(a,b){this.m_fileSystem.root.getFile(a,{create:!1},function(){b(!0)},function(){b(!1)})};
DjiHtml5FileSystem.prototype.emptyDirectory=function(a,b){var c=this;this.m_fileSystem.root.getDirectory(a,{},function(a){a.createReader().readEntries(function(a){0<a.length?c.__callback(b,!1):c.__callback(b,!0)},function(a){Logger.instance.error("error getEntries:",a);c.__callback(b)})},function(a){Logger.instance.error("error getDirectory:",a)})};
DjiHtml5FileSystem.prototype.listDirectory=function(a,b){var c=this;this.m_fileSystem.root.getDirectory(a,{},function(a){var d=a.createReader(),f=[],g=function(){d.readEntries(function(a){0>=a.length?c.__callback(b,f):(f=f.concat(Array.prototype.slice.call(a,0)),g())},function(a){Logger.instance.error("error readEntries:",a);c.__callback(b,[])})};g()},function(a){"NotFoundError"!==a.name&&Logger.instance.error("error getDirectory:",a);c.__callback(b,[])})};
DjiHtml5FileSystem.prototype.listDirectoryAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:return e=b,d=-1,{value:new Promise(function(b){e.m_fileSystem.root.getDirectory(a,{},function(a){var d=a.createReader(),c=[],e=function(){d.readEntries(function(a){0>=a.length?b(c):(c=c.concat(Array.prototype.slice.call(a,0)),e())},function(a){Logger.instance.error("error readEntries:",a);b([])})};e()},function(a){"NotFoundError"!==a.name&&
Logger.instance.error("error getDirectory:",a);b([])})}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};DjiHtml5FileSystem.prototype.__splitPath=function(a){if(!a||0>=a.length)return null;a=a.split("/");for(var b=[],c=0;c<a.length;c++)0<a[c].length&&b.push(a[c]);return b};
DjiHtml5FileSystem.prototype.__callback=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}};
(function(){FileReader.prototype.readWithMethod=function(a,b,c,d){if(!(this[b]instanceof Function))throw Error(b+" is not a function of FileReader!");var e=this.onloadend,f=this.onerror;this.onloadend=function(){this.onloadend=e;this.onerror=f;c(this.result)};this.onerror=function(a){this.onloadend=e;this.onerror=f;d(a)};this[b](a)};FileReader.prototype.readAsTextEx=function(a,b,c){var d=this.onloadend,e=this.onerror;this.onloadend=function(){this.onloadend=d;this.onerror=e;b(this.result)};this.onerror=
function(a){this.onloadend=d;this.onerror=e;c(a)};this.readAsText(a)};FileReader.prototype.readAsTextAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:return e=b,d=-1,{value:new Promise(function(b,c){e.readAsTextEx(a,b,c)}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
f[Symbol.iterator]=function(){return this};return f}())};FileReader.prototype.readWithMethodAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,k){for(;;)switch(e){case 0:if(c[b]instanceof Function){e=1;break}e=-1;throw Error(b+" is not a function of FileReader!");case 1:return f=c,e=-1,{value:new Promise(function(c,d){f.readWithMethod(a,b,c,d)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())}})();var DjiFileSystemBaseEntryProxy=function(a){this.m_entry=a};
DjiFileSystemBaseEntryProxy.prototype.copyToAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,k){for(;;)switch(e){case 0:return f=c,e=-1,{value:new Promise(function(c,d){a instanceof DjiFileSystemBaseEntryProxy&&(a=a.entry);f.entry.copyTo(a,b,function(a){a.isDirectory?c(new DjiFileSystemDirectoryEntryProxy(a)):c(new DjiFileSystemFileEntryProxy(a))},d)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
$jscomp.global.Object.defineProperties(DjiFileSystemBaseEntryProxy.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return this.m_entry.name}},fullPath:{configurable:!0,enumerable:!0,get:function(){return this.m_entry.fullPath}},isDirectory:{configurable:!0,enumerable:!0,get:function(){return this.m_entry.isDirectory}},isFile:{configurable:!0,enumerable:!0,get:function(){return this.m_entry.isFile}},filesystem:{configurable:!0,enumerable:!0,get:function(){return this.m_entry.filesystem}},
entry:{configurable:!0,enumerable:!0,get:function(){return this.m_entry}}});var DjiFileSystemDirectoryEntryProxy=function(a){DjiFileSystemBaseEntryProxy.apply(this,arguments)};$jscomp.inherits(DjiFileSystemDirectoryEntryProxy,DjiFileSystemBaseEntryProxy);
DjiFileSystemDirectoryEntryProxy.getPackageDirectoryEntryAsync=function(){return $jscomp.executeAsyncGenerator(function(){function a(a,c,f){for(;;)switch(b){case 0:return b=-1,{value:new Promise(function(a){return chrome.runtime.getPackageDirectoryEntry(function(b){return a(new DjiFileSystemDirectoryEntryProxy(b))})}),done:!0};default:return{value:void 0,done:!0}}}var b=0,c={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();c[Symbol.iterator]=function(){return this};return c}())};
DjiFileSystemDirectoryEntryProxy.prototype.getDirectoryAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,f,l){for(;;)switch(d){case 0:return e=b,d=-1,{value:new Promise(function(b,c){(a.startsWith("/")?e.filesystem.root:e.entry).getDirectory(a,{create:!1},function(a){b(new DjiFileSystemDirectoryEntryProxy(a))},c)}),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};
DjiFileSystemDirectoryEntryProxy.prototype.getFileAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,k){for(;;)switch(e){case 0:return f=c,b=!!b,e=-1,{value:new Promise(function(c,d){(a.startsWith("/")?f.filesystem.root:f.entry).getFile(a,{create:b},function(a){c(new DjiFileSystemFileEntryProxy(a))},d)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
DjiFileSystemDirectoryEntryProxy.prototype.fileAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,g,k){for(;;)switch(d){case 0:return d=1,{value:b.getFileAsync(a),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw k;case 2:return e=f=g,d=-1,{value:e.fileAsync(),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};
DjiFileSystemDirectoryEntryProxy.prototype.readAsArrayBufferAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,g,k){for(;;)switch(d){case 0:return d=1,{value:b.getFileAsync(a),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw k;case 2:return e=f=g,d=-1,{value:e.readAsArrayBufferAsync(),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
DjiFileSystemDirectoryEntryProxy.prototype.readAsBinaryStringAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,g,k){for(;;)switch(d){case 0:return d=1,{value:b.getFileAsync(a),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw k;case 2:return e=f=g,d=-1,{value:e.readAsBinaryStringAsync(),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
DjiFileSystemDirectoryEntryProxy.prototype.readFileAsTextAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,g,k){for(;;)switch(d){case 0:return d=1,{value:b.getFileAsync(a),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw k;case 2:return e=f=g,d=-1,{value:e.readAsTextAsync(),done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,g={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
DjiFileSystemDirectoryEntryProxy.prototype.readFileAsJSONAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,l,m){for(;;)switch(d){case 0:return d=1,{value:b.getFileAsync(a),done:!1};case 1:if(1!=c){d=2;break}d=-1;throw m;case 2:return g=h=l,d=3,{value:g.readAsTextAsync(),done:!1};case 3:if(1!=c){d=4;break}d=-1;throw m;case 4:return e=f=l,null!==e&&void 0!==e&&(e=JSON.parse(e)),d=-1,{value:e,done:!0};default:return{value:void 0,done:!0}}}var d=0,e,f,g,h,l={next:function(a){return c(0,
a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();l[Symbol.iterator]=function(){return this};return l}())};
DjiFileSystemDirectoryEntryProxy.prototype.writeFileAsTextAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,n){for(;;)switch(e){case 0:return e=1,{value:c.getFileAsync(a,!0),done:!1};case 1:if(1!=d){e=2;break}e=-1;throw n;case 2:return f=g=h,e=-1,{value:f.writeAsTextAsync(b),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
DjiFileSystemDirectoryEntryProxy.prototype.listDirectoryAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,k){for(;;)switch(e){case 0:return f=c,a=!(!a&&void 0!==a),b=!(!b&&void 0!==b),e=-1,{value:new Promise(function(c,d){var e=f.entry.createReader(),g=[],h=function(){e.readEntries(function(d){if(0>=d.length)return c(g);if(a&&b)g.push.apply(g,[].concat($jscomp.arrayFromIterable(d)));else for(var e=0;e<d.length;e++)a&&d[e].isDirectory&&g.push(d[e]),b&&d[e].isFile&&
g.push(d[e]);h()},function(a){d(a)})};h()}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};var DjiFileSystemFileEntryProxy=function(a){DjiFileSystemBaseEntryProxy.apply(this,arguments)};$jscomp.inherits(DjiFileSystemFileEntryProxy,DjiFileSystemBaseEntryProxy);
DjiFileSystemFileEntryProxy.prototype.fileAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a,b){return d.entry.file(a,b)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};
return e}())};
DjiFileSystemFileEntryProxy.prototype.readAsArrayBufferAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a,b){d.entry.file(function(c){(new FileReader).readAsArrayBuffer(c,a,b)},b)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
e[Symbol.iterator]=function(){return this};return e}())};
DjiFileSystemFileEntryProxy.prototype.readAsBinaryStringAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a,b){d.entry.file(function(c){(new FileReader).readWithMethod(c,"readAsBinaryString",a,b)},b)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
DjiFileSystemFileEntryProxy.prototype.readAsTextAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,e,h){for(;;)switch(c){case 0:return d=a,c=-1,{value:new Promise(function(a,b){d.entry.file(function(c){(new FileReader).readAsTextEx(c,a,b)},b)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
e[Symbol.iterator]=function(){return this};return e}())};
DjiFileSystemFileEntryProxy.prototype.writeAsTextAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function c(c,e,h){for(;;)switch(d){case 0:return d=-1,{value:b.writeAsync(a,"text/plain;charset=UTF-8"),done:!0};default:return{value:void 0,done:!0}}}var d=0,e={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};
DjiFileSystemFileEntryProxy.prototype.writeAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,k){for(;;)switch(e){case 0:return f=c,e=-1,{value:new Promise(function(c,d){f.entry.createWriter(function(e){var f=a instanceof Blob?a:new Blob([a],{type:b||"application/octet-stream"});e.onwriteend=c;e.onerror=d;e.write(f)},d)}),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,
a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
