var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,n,d){l!=Array.prototype&&l!=Object.prototype&&(l[n]=d.value)};$jscomp.getGlobal=function(l){return"undefined"!=typeof window&&window===l?l:"undefined"!=typeof global&&null!=global?global:l};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(l,n,d,m){if(n){d=$jscomp.global;l=l.split(".");for(m=0;m<l.length-1;m++){var p=l[m];p in d||(d[p]={});d=d[p]}l=l[l.length-1];m=d[l];n=n(m);n!=m&&null!=n&&$jscomp.defineProperty(d,l,{configurable:!0,writable:!0,value:n})}};$jscomp.polyfill("Array.prototype.fill",function(l){return l?l:function(l,d,m){var n=this.length||0;0>d&&(d=Math.max(0,n+d));if(null==m||m>n)m=n;m=Number(m);0>m&&(m=Math.max(0,n+m));for(d=Number(d||0);d<m;d++)this[d]=l;return this}},"es6","es3");
var SyncFSDriver=function(){function l(a,b,c,e,h,f,g){if(FS.isBlkdev(c)||FS.isFIFO(c))throw new FS.ErrnoError(ERRNO_CODES.EPERM);k.ops_table||(k.ops_table={dir:{node:{getattr:n,setattr:d,lookup:m,mknod:p,rename:u,unlink:v,rmdir:w,readdir:x,symlink:y},stream:{llseek:r}},file:{node:{getattr:n,setattr:d},stream:{llseek:r,read:z,write:A,allocate:B}},link:{node:{getattr:n,setattr:d,readlink:C},stream:{}},chrdev:{node:{getattr:n,setattr:d},stream:FS.chrdev_stream_ops}});c=FS.createNode(a,b,c,e);c.timestamp=
f||Date.now();c.metadata=h;c.vfs=g;FS.isDir(c.mode)?(c.node_ops=k.ops_table.dir.node,c.stream_ops=k.ops_table.dir.stream,c.contents={}):FS.isFile(c.mode)?(c.metadata||(h={name:c.name,localPath:a.metadata.localPath+"/"+c.name,remotePath:a.metadata.remotePath+"/"+c.name,timestamp:c.timestamp,size:0},c.metadata=h),c.node_ops=k.ops_table.file.node,c.stream_ops=k.ops_table.file.stream,c.usedBytes=h.size,c.contents=null):FS.isLink(c.mode)?(c.node_ops=k.ops_table.link.node,c.stream_ops=k.ops_table.link.stream):
FS.isChrdev(c.mode)&&(c.node_ops=k.ops_table.chrdev.node,c.stream_ops=k.ops_table.chrdev.stream);a&&(a.contents[b]=c);return c}function n(a){var b={};b.dev=FS.isChrdev(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.usedBytes:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);
return b}function d(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&k.resizeFileStorage(a,b.size)}function m(a,b){throw FS.genericErrors[ERRNO_CODES.ENOENT];}function p(a,b,c,e){return k.createNode(a,b,c,e)}function u(a,b,c){if(FS.isDir(a.mode)){try{var e=FS.lookupNode(b,c)}catch(f){}if(e)for(var h in e.contents)throw new FS.ErrnoError(ERRNO_CODES.ENOTEMPTY);}delete a.parent.contents[a.name];a.name=c;b.contents[c]=a;a.parent=b}function v(a,b){delete a.contents[b]}
function w(a,b){var c=FS.lookupNode(a,b),e;for(e in c.contents)throw new FS.ErrnoError(ERRNO_CODES.ENOTEMPTY);delete a.contents[b]}function x(a){var b=[".",".."],c;for(c in a.contents)a.contents.hasOwnProperty(c)&&b.push(c);return b}function y(a,b,c){a=k.createNode(a,b,41471,0);a.link=c;return a}function C(a){if(!FS.isLink(a.mode))throw new FS.ErrnoError(ERRNO_CODES.EINVAL);return a.link}function z(a,b,c,e,h){if(isNaN(h)||a.node.contents&&a.node.contents.size<=h)return a.node.contents=null,0;if(!a.node.contents)try{if(a.node.vfs)a.node.contents=
a.node.vfs.readWithMetadata(a.node.metadata);else{var f=q.root.getFile(a.node.metadata.remotePath,{create:!1});a.node.contents=f.file()}}catch(t){return console.error(t),0}try{var g=a.node.contents.slice(h,h+e),l=F.readAsArrayBuffer(g);b.set(new Uint8Array(l),c);return g.size}catch(t){console.error(t)}return 0}function A(a,b,c,e,h,f){if(!e)return a.node.contents&&(b=q.root.getFile(a.node.metadata.remotePath,{create:!0}).createWriter(),c=a.node.contents.slice(0,a.node.usedBytes),c=new Blob([c],{type:"application/octet-stream"}),
b.truncate(0),b.write(c),a.node.contents=null),0;a=a.node;0===h&&(a.contents=null);k.expandFileStorage(a,h+e);if(0<e){if(b.subarray)a.contents.set(b.subarray(c,c+e),h);else for(f=0;f<e;f++)a.contents[h+f]=b[c+f];a.usedBytes=Math.max(a.usedBytes,h+e)}return e}function r(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.usedBytes);if(0>b)throw new FS.ErrnoError(ERRNO_CODES.EINVAL);return b}function B(a,b,c){k.expandFileStorage(a.node,b+c);a.node.usedBytes=Math.max(a.node.usedBytes,
b+c)}function D(a){for(var b=[a?q.root.getDirectory(a,{create:!1}):q.root],c=[],e={},h={},f=0;f<b.length;f++){var g=b[f],l=g.createReader(),d=[],m=g.getMetadata();d=g.fullPath.replace(a,"");0>=d.length&&(d="/");var n=null,k=null,p=[];n={id:g.fullPath,metadata:{name:g.name,localPath:d,remotePath:g.fullPath,timestamp:m.modificationTime.getTime(),size:m.size},files:p,node:null};c.push(n);e[n.id]=n;do for(d=l.readEntries(),g=0;g<d.length;g++)k=d[g],k.isDirectory&&b.push(k),k.isFile&&(m=k.getMetadata(),
k={id:k.fullPath,metadata:{name:k.name,localPath:k.fullPath.replace(a,""),remotePath:k.fullPath,timestamp:m.modificationTime.getTime(),size:m.size},parentId:n.id,node:null},p.push(k),h[k.id]=k);while(0<d.length)}c.sort(function(a,b){return a.localPath<b.localPath?-1:a.localPath>b.localPath?1:0});return{dirList:c,dirMap:e,fileMap:h}}var k=null,q=webkitRequestFileSystemSync(PERSISTENT,268435456),F=new FileReaderSync,E={};(function(){FS.extensions=FS.extensions||{};FS.extensions.mapSyncFS=function(a){FS.mkdirTree(a);
FS.mount(k,{syncFSPath:a},a)};FS.extensions.mapVfsContainer=function(a,b){FS.mkdirTree(a);FS.mount(k,{vfsContainer:b},a)};FS.extensions.syncAsyncFS=function(a){var b=D(a).fileMap;a=E[a];var c=a.fileMap,e={},h;for(h in b)b.hasOwnProperty(h)&&(e[h]={local:null,remote:b[h]});for(var f in c)c.hasOwnProperty(f)&&(e.hasOwnProperty(f)?e[f].local=c[f]:e[f]={local:c[f],remote:null});for(var g in e)e.hasOwnProperty(g)&&(b=e[g],!(b.local&&b.remote||b.local)&&b.remote&&(b=b.remote,h=a.dirMap[b.parentId]))&&(h.files.push(b),
a.fileMap[b.id]=b,b.node=l(h.node,b.metadata.name,33279,0,b.metadata,b.metadata.timestamp))}})();return k={ops_table:null,mount:function(a){if(a.opts.hasOwnProperty("syncFSPath")){var b=D(a.opts.syncFSPath),c=b.dirList,e={},h=l(null,"/",16895,0,c[0].metadata,c[0].metadata.timestamp);e["/"]=e[""]=h;for(var f=0;f<c.length;f++){var g=c[f];if("/"===g.metadata.localPath)g.node=h;else{var d=g.metadata.localPath.split("/");d=""+d.slice(0,d.length-1).join("/");g.node=l(e[d]||h,g.metadata.name,16895,0,g.metadata,
g.metadata.timestamp);e[g.metadata.localPath]=g.node}}for(e=0;e<c.length;e++)for(f=c[e],g=f.files,d=0;d<g.length;d++){var k=g[d];k.node=l(f.node,k.metadata.name,33279,0,k.metadata,k.metadata.timestamp)}E[a.opts.syncFSPath]=b;return h}if(a.opts.hasOwnProperty("vfsContainer")){a=new VfsContainer(a.opts.vfsContainer);c={};h=a.dirs;b=l(null,"/",16895,0,{},a.timestamp,a);c["/"]=c[""]=b;for(e=0;e<h.length;e++)f=h[e],""===f.path?f.node=b:(g=f.path.split("/"),g=""+g.slice(0,g.length-1).join("/"),f.node=l(c[g]||
b,f.name,16895,0,f.metadata,f.metadata.timestamp,a),c[f.path]=f.node);c=a.dirs;for(h=0;h<c.length;h++)for(e=c[h],f=e.files,g=0;g<f.length;g++)d=f[g],d.node=l(e.node,d.name,33279,0,d.metadata,d.metadata.timestamp,a);return b}return null},createNode:l,getFileDataAsRegularArray:function(a){if(a.contents&&a.contents.subarray){for(var b=[],c=0;c<a.usedBytes;++c)b.push(a.contents[c]);return b}return a.contents},getFileDataAsTypedArray:function(a){return a.contents?a.contents.subarray?a.contents.subarray(0,
a.usedBytes):new Uint8Array(a.contents):new Uint8Array},expandFileStorage:function(a,b){var c=a.contents?a.contents.length:0;b=4096*Math.ceil(b/4096);b<=c||(c=new Uint8Array(b),a.contents&&0<a.usedBytes&&c.set(a.contents,0),c.fill(0,a.usedBytes),a.contents=c,a.usedBytes=Math.min(a.usedBytes,b))},resizeFileStorage:function(a,b){if(b!==a.usedBytes){var c=a.contents?a.contents.length:0;newCapacity=4096*Math.ceil(b/4096);newCapacity!==c&&(c=new Uint8Array(newCapacity),a.contents&&0<a.usedBytes&&c.set(a.contents,
0),a.contents=c);a.contents&&a.contents.fill(0,b);a.usedBytes=b}},node_ops:{getattr:n,setattr:d,lookup:m,mknod:p,rename:u,unlink:v,rmdir:w,readdir:x,symlink:y,readlink:C},stream_ops:{read:z,write:A,llseek:r,allocate:B}}}();
