var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,f){c!=Array.prototype&&c!=Object.prototype&&(c[e]=f.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var e=0;return $jscomp.iteratorPrototype(function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=c[Symbol.iterator];return e?e.call(c):$jscomp.arrayIterator(c)};
$jscomp.polyfill=function(c,e,f,h){if(e){f=$jscomp.global;c=c.split(".");for(h=0;h<c.length-1;h++){var g=c[h];g in f||(f[g]={});f=f[g]}c=c[c.length-1];h=f[c];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function e(){this.batch_=null}function f(a){return a instanceof g?a:new g(function(b,d){b(a)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;e.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};e.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var h=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(a){h(a,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];delete a[b];try{d()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(d){b.reject(d)}};g.prototype.createResolveAndReject_=
function(){function a(a){return function(k){d||(d=!0,a.call(b,k))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(d){this.reject_(d);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var m=new e;g.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};g.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(k){d.reject(k)}};g.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{k(a(b))}catch(p){c(p)}}:b}var k,c,e=new g(function(a,
b){k=a;c=b});this.callWhenSettled_(d(a,k),d(b,c));return e};g.prototype.catch=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,b){function d(){switch(k.state_){case 1:a(k.result_);break;case 2:b(k.result_);break;default:throw Error("Unexpected state: "+k.state_);}}var k=this;null==this.onSettledCallbacks_?m.asyncExecute(d):this.onSettledCallbacks_.push(function(){m.asyncExecute(d)})};g.resolve=f;g.reject=function(a){return new g(function(b,d){d(a)})};g.race=function(a){return new g(function(b,
d){for(var k=$jscomp.makeIterator(a),c=k.next();!c.done;c=k.next())f(c.value).callWhenSettled_(b,d)})};g.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?f([]):new g(function(a,c){function k(b){return function(d){l[b]=d;e--;0==e&&a(l)}}var l=[],e=0;do l.push(void 0),e++,f(d.value).callWhenSettled_(k(l.length-1),c),d=b.next();while(!d.done)})};return g},"es6","es3");
$jscomp.executeAsyncGenerator=function(c){function e(e){return c.next(e)}function f(e){return c.throw(e)}return new Promise(function(h,g){function m(a){a.done?h(a.value):Promise.resolve(a.value).then(e,f).then(m,g)}m(c.next())})};$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(c){var e=function(){};e.prototype=c;return new e};$jscomp.underscoreProtoCanBeSet=function(){var c={a:!0},e={};try{return e.__proto__=c,e.a}catch(f){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(c,e){c.__proto__=e;if(c.__proto__!==e)throw new TypeError(c+" is not extensible");return c}:null;
$jscomp.inherits=function(c,e){c.prototype=$jscomp.objectCreate(e.prototype);c.prototype.constructor=c;if($jscomp.setPrototypeOf){var f=$jscomp.setPrototypeOf;f(c,e)}else for(f in e)if("prototype"!=f)if(Object.defineProperties){var h=Object.getOwnPropertyDescriptor(e,f);h&&Object.defineProperty(c,f,h)}else c[f]=e[f];c.superClass_=e.prototype};$jscomp.arrayFromIterator=function(c){for(var e,f=[];!(e=c.next()).done;)f.push(e.value);return f};
$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};$jscomp.owns=function(c,e){return Object.prototype.hasOwnProperty.call(c,e)};
$jscomp.polyfill("WeakMap",function(c){function e(a){$jscomp.owns(a,h)||$jscomp.defineProperty(a,h,{value:{}})}function f(a){var b=Object[a];b&&(Object[a]=function(a){e(a);return b(a)})}if(function(){if(!c||!Object.seal)return!1;try{var a=Object.seal({}),b=Object.seal({}),d=new c([[a,2],[b,3]]);if(2!=d.get(a)||3!=d.get(b))return!1;d.delete(a);d.set(b,4);return!d.has(a)&&4==d.get(b)}catch(k){return!1}}())return c;var h="$jscomp_hidden_"+Math.random().toString().substring(2);f("freeze");f("preventExtensions");
f("seal");var g=0,m=function(a){this.id_=(g+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};m.prototype.set=function(a,b){e(a);if(!$jscomp.owns(a,h))throw Error("WeakMap key fail: "+a);a[h][this.id_]=b;return this};m.prototype.get=function(a){return $jscomp.owns(a,h)?a[h][this.id_]:void 0};m.prototype.has=function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)};m.prototype.delete=
function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)?delete a[h][this.id_]:!1};return m},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(c){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),d=new c($jscomp.makeIterator([[a,"s"]]));if("s"!=d.get(a)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var k=d.entries(),l=k.next();if(l.done||l.value[0]!=a||"s"!=l.value[1])return!1;l=k.next();return l.done||4!=l.value[0].x||"t"!=l.value[1]||!k.next().done?!1:!0}catch(n){return!1}}())return c;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,f=function(a){this.data_={};this.head_=m();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,d){var b=h(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=d:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:d},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};f.prototype.delete=
function(a){a=h(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=m();this.size=0};f.prototype.has=function(a){return!!h(this,a).entry};f.prototype.get=function(a){return(a=h(this,a).entry)&&a.value};f.prototype.entries=function(){return g(this,function(a){return[a.key,
a.value]})};f.prototype.keys=function(){return g(this,function(a){return a.key})};f.prototype.values=function(){return g(this,function(a){return a.value})};f.prototype.forEach=function(a,d){for(var b=this.entries(),c;!(c=b.next()).done;)c=c.value,a.call(d,c[1],c[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var h=function(b,d){var c=d&&typeof d;"object"==c||"function"==c?e.has(d)?c=e.get(d):(c=""+ ++a,e.set(d,c)):c="p_"+d;var l=b.data_[c];if(l&&$jscomp.owns(b.data_,c))for(b=0;b<l.length;b++){var n=
l[b];if(d!==d&&n.key!==n.key||d===n.key)return{id:c,list:l,index:b,entry:n}}return{id:c,list:l,index:-1,entry:void 0}},g=function(a,d){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:d(b)};b=null}return{done:!0,value:void 0}})},m=function(){var a={};return a.previous=a.next=a.head=a},a=0;return f},"es6","es3");
var VfsContainer=function(){var c=120===(new Uint8Array((new Uint32Array([305419896])).buffer))[0];new Uint8Array((new Uint32Array([305419896])).buffer);var e="function"===typeof FileReaderSync,f=function(){this.m_fileReader=e?new FileReaderSync:new FileReader};f.prototype.readAsArrayBuffer=function(a){if(!e)throw Error("Sync FS is not available!");return this.m_fileReader.readAsArrayBuffer(a)};f.prototype.readAsText=function(a,b){if(!e)throw Error("Sync FS is not available!");return this.m_fileReader.readAsText(a,
b)};f.prototype.readAsArrayBufferAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function d(d,k,n){for(;;)switch(c){case 0:if(!e){c=1;break}c=-1;return{value:b.m_fileReader.readAsArrayBuffer(a),done:!0};case 1:return l=b,c=-1,{value:new Promise(function(b,d){return l.__readAsArrayBuffer(a,b,d)}),done:!0};default:return{value:void 0,done:!0}}}var c=0,l,n={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n}())};f.prototype.readAsTextAsync=function(a,b){var d=this;return $jscomp.executeAsyncGenerator(function(){function c(c,k,f){for(;;)switch(l){case 0:if(!e){l=1;break}l=-1;return{value:d.m_fileReader.readAsText(a,b),done:!0};case 1:return n=d,l=-1,{value:new Promise(function(d,c){return n.__readAsText(a,b,d,c)}),done:!0};default:return{value:void 0,done:!0}}}var l=0,n,f={next:function(a){return c(0,a,void 0)},throw:function(a){return c(1,
void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};f.prototype.__readAsArrayBuffer=function(a,b,d){var c=this.m_fileReader;c.onloadend=function(){this.onerror=this.onloadend=null;b(this.result)};c.onerror=function(a){this.onerror=this.onloadend=null;d(a)};c.readAsArrayBuffer(a)};f.prototype.__readAsText=function(a,b,d,c){var e=this.m_fileReader;e.onloadend=function(){this.onerror=this.onloadend=
null;d(this.result)};e.onerror=function(a){this.onerror=this.onloadend=null;c(a)};e.readAsText(a,b)};var h=function(a){this.m_fileReader=new f;this.m_container=a;this.m_timestamp=Date.now();this.m_content=this.m_header=this.m_priv=null};h.prototype.dir=function(a){a=a.split("/").slice(0,-1).join("/");return this.m_content.dirsMap.get(a)||null};h.prototype.getDirectoryFiles=function(a){return(a=this.m_content.dirsMap.get(a))?a.files.map(function(a){return a.path}):[]};h.prototype.__buildContent=function(){for(var a=
this.m_header.content.dirs,b=this.m_header.content.files,d=new Map,c=new Map,e=new Map,f=0;f<a.length;f++){var g=a[f];g.files=[];d.set(g.id,g);c.set(g.path,g)}for(a=0;a<b.length;a++)f=b[a],g=d.get(f.parentId),e.set(f.path,f),g&&g.files.push(f);this.m_content=Object.freeze({dirs:this.m_header.content.dirs,files:this.m_header.content.files,dirsMap:c,filesMap:e})};h.prototype.readWithMetadata=function(a,b,d){b=Math.max(0,void 0===b?0:b);d=void 0===d?a.size:d;d=Math.max(0,Math.min(d,a.size-b));b+=this.m_priv.cso+
a.offset;return this.m_container.slice(b,b+d)};h.prototype.readFile=function(a){return(a=this.m_content.filesMap.get(a))?this.readWithMetadata(a.metadata,0):null};$jscomp.global.Object.defineProperties(h.prototype,{timestamp:{configurable:!0,enumerable:!0,get:function(){return this.m_timestamp}},header:{configurable:!0,enumerable:!0,get:function(){return this.m_header}},dirs:{configurable:!0,enumerable:!0,get:function(){return this.m_content.dirs}},files:{configurable:!0,enumerable:!0,get:function(){return this.m_content.files}}});
var g=function(a){a=h.call(this,a)||this;a.__init();return a};$jscomp.inherits(g,h);g.fromContainer=function(a){return new g(a)};g.prototype.__init=function(){this.__readPriv();this.__readHeader();this.__buildContent()};g.prototype.__readPriv=function(){this.m_priv=Object.freeze({v:this.readUInt32LE(0),hso:this.readUInt32LE(4),hl:this.readUInt32LE(8),cso:this.readUInt32LE(12)})};g.prototype.__readHeader=function(){var a=this.readJSON(this.m_priv.hso,this.m_priv.hl);this.m_header=Object.freeze(a)};
g.prototype.readUInt32LE=function(a){a=this.m_fileReader.readAsArrayBuffer(this.m_container.slice(a,a+4));return c?(new Uint32Array(a))[0]:(new Uint32Array((new Uint8Array([].concat($jscomp.arrayFromIterable((new Uint8Array(a)).reverse())))).buffer))[0]};g.prototype.readText=function(a,b,d){return this.m_fileReader.readAsText(this.m_container.slice(a,a+b),d||"UTF-8")};g.prototype.readJSON=function(a,b,d){a=this.readText(a,b,d);return JSON.parse(a)};g.prototype.readFileAsText=function(a,b){return(a=
this.readFile(a))?this.m_fileReader.readAsText(a,b||"UTF-8"):null};g.prototype.readFileAsJSON=function(a,b){a=this.readFileAsText(a,b);return JSON.parse(a)};var m=function(a){return h.call(this,a)||this};$jscomp.inherits(m,h);m.fromContainerAsync=function(a){return $jscomp.executeAsyncGenerator(function(){function b(b,e,f){for(;;)switch(d){case 0:return c=new m(a),d=1,{value:c.__initAsync(),done:!1};case 1:if(1!=b){d=2;break}d=-1;throw f;case 2:return d=-1,{value:c,done:!0};default:return{value:void 0,
done:!0}}}var d=0,c,e={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e}())};m.prototype.__initAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,c,e){for(;;)switch(d){case 0:return d=1,{value:a.__readPrivAsync(),done:!1};case 1:if(1!=b){d=2;break}d=-1;throw e;case 2:return d=3,{value:a.__readHeaderAsync(),
done:!1};case 3:if(1!=b){d=4;break}d=-1;throw e;case 4:a.__buildContent(),d=-1;default:return{value:void 0,done:!0}}}var d=0,c={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();c[Symbol.iterator]=function(){return this};return c}())};m.prototype.__readPrivAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,l,k){for(;;)switch(d){case 0:return d=1,
{value:a.readUInt32LEAsync(0),done:!1};case 1:if(1!=b){d=2;break}d=-1;throw k;case 2:return p=r=l,d=3,{value:a.readUInt32LEAsync(4),done:!1};case 3:if(1!=b){d=4;break}d=-1;throw k;case 4:return h=m=l,d=5,{value:a.readUInt32LEAsync(8),done:!1};case 5:if(1!=b){d=6;break}d=-1;throw k;case 6:return f=g=l,d=7,{value:a.readUInt32LEAsync(12),done:!1};case 7:if(1!=b){d=8;break}d=-1;throw k;case 8:c=e=l,a.m_priv=Object.freeze({v:p,hso:h,hl:f,cso:c}),d=-1;default:return{value:void 0,done:!0}}}var d=0,c,e,f,
g,h,m,p,r,q={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q}())};m.prototype.__readHeaderAsync=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function b(b,f,g){for(;;)switch(d){case 0:return d=1,{value:a.readJSONAsync(a.m_priv.hso,a.m_priv.hl),done:!1};case 1:if(1!=b){d=2;break}d=-1;throw g;case 2:c=e=f,a.m_header=
Object.freeze(c),d=-1;default:return{value:void 0,done:!0}}}var d=0,c,e,f={next:function(a){return b(0,a,void 0)},throw:function(a){return b(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};m.prototype.readUInt32LEAsync=function(a){var b=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,l){for(;;)switch(e){case 0:return e=1,{value:b.m_fileReader.readAsArrayBufferAsync(b.m_container.slice(a,
a+4)),done:!1};case 1:if(1!=d){e=2;break}e=-1;throw l;case 2:return f=g=h,e=-1,{value:c?(new Uint32Array(f))[0]:(new Uint32Array((new Uint8Array([].concat($jscomp.arrayFromIterable((new Uint8Array(f)).reverse())))).buffer))[0],done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};
m.prototype.readTextAsync=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,g,h){for(;;)switch(f){case 0:return f=-1,{value:d.m_fileReader.readAsTextAsync(d.m_container.slice(a,a+b),c||"UTF-8"),done:!0};default:return{value:void 0,done:!0}}}var f=0,g={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};
m.prototype.readJSONAsync=function(a,b,c){var d=this;return $jscomp.executeAsyncGenerator(function(){function e(e,l,k){for(;;)switch(f){case 0:return f=1,{value:d.readTextAsync(a,b,c),done:!1};case 1:if(1!=e){f=2;break}f=-1;throw k;case 2:return g=h=l,f=-1,{value:JSON.parse(g),done:!0};default:return{value:void 0,done:!0}}}var f=0,g,h,k={next:function(a){return e(0,a,void 0)},throw:function(a){return e(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
k[Symbol.iterator]=function(){return this};return k}())};m.prototype.readFileAsTextAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,g,h){for(;;)switch(e){case 0:return f=c.readFile(a),e=-1,{value:f?c.m_fileReader.readAsTextAsync(f,b||"UTF-8"):null,done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
g[Symbol.iterator]=function(){return this};return g}())};m.prototype.readFileAsJSONAsync=function(a,b){var c=this;return $jscomp.executeAsyncGenerator(function(){function d(d,h,k){for(;;)switch(e){case 0:return e=1,{value:c.readFileAsTextAsync(a,b),done:!1};case 1:if(1!=d){e=2;break}e=-1;throw k;case 2:return f=g=h,e=-1,{value:JSON.parse(f),done:!0};default:return{value:void 0,done:!0}}}var e=0,f,g,h={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h}())};return e?g:m}();
