window.dji=window.dji||{};
(function(f){function R(a){var b=function(){var c=window.speechSynthesis.getVoices();if(c&&0<c.length)return a(c);setTimeout(b,100)};b()}function L(a,b){R(function(c){if(u.chrome&&(null===c||0>=c.length))setTimeout(function(){browserEngine.tts.speak("",{onEvent:function(e){"end"!==e.type&&"error"!==e.type||setTimeout(function(){L(a+1,b)},"end"===e.type?10:1E4)}},null)},10);else{for(var d="HEATHER RYAN GRAHAM LUCY SOLO FLITE ACAPELA".split(" "),e=[],g=0;g<c.length;g++){for(var D=c[g],l=!1,p=0;p<d.length;p++)if(0<=
D.name.toUpperCase().indexOf(d[p])){l=!0;break}l||browserEngine.os.isChrome&&0<=D.name.indexOf("Google")&&(l=!0);l||e.push(D)}k=M(e,!1);f.cacheOnlineVoices(function(){for(var a=0;a<k.length;a++){var e=k[a],c=e.extras,d=q[c.lang]=q[c.lang]||{};d=d[c.culture]=d[c.culture]||{};(d[c.gender]=d[c.gender]||[]).push(e)}S();setTimeout(function(){H&&H.__ttsEngineInitialized();A(b,!0)},0)})}})}function N(){m.voice=f.defaultVoice();m.translationVoice=null;m.rate=m.pitch=m.volume=1}function M(a,b){for(var c=[],
d=0;d<a.length;d++){var e=a[d],g=e={"default":!(b||!e.default),localService:!(b||!e.localService),remote:!(!b||!e.remote),lang:e.lang,name:b?e.voiceName:e.name,voiceURI:b?e.voiceIdentifier:e.voiceURI,voiceIdentifier:b?e.voiceIdentifier:e.voiceURI,adjustable:!(b&&!e.adjustable),rawVoice:e},D=b,l=(g.lang||"neutral").split("-"),p=(2<=l.length?l[1]:"").toUpperCase(),n=(g.gender||"neutral").toLowerCase();g.extras={langInfo:dji.languages.languageInfo(l[0]),lang:(l[0]||"").toLowerCase(),culture:p,gender:n,
isGoogle:f.isGoogleVoice(g.name),isMicrosoft:f.isMicrosoftVoice(g.name),isOnline:!!D};c.push(e)}return c}function S(){for(var a in q)if(q.hasOwnProperty(a)){var b=q[a],c=[],d;for(d in b)if(b.hasOwnProperty(d)){var e=b[d],g=[],f;for(f in e)e.hasOwnProperty(f)&&(g=g.concat(e[f]),c=c.concat(g));e["@"]=g}b["@"]=c}}function w(a){for(var b=0;b<k.length;b++)if(k[b].name===a)return k[b];return null}function I(a){a=w(a);return!!a}function O(a,b,c,d,e){for(var g=null,f=null,l=null,p=0;p<b.length;p++){var n=
b[p];n===a||!c&&n.extras.isOnline||!d&&!n.extras.isOnline||(c&&!g&&n.extras.isOnline&&(g=n),!d||f||n.extras.isOnline||n.extras.isGoogle||(f=n),e&&!l&&n.extras.isGoogle&&(l=n))}return f||l||g||null}function E(a,b,c,d,e){var g=b[a.extras.gender]||[];g=O(a,g,c,d,e);if(!g)for(var f in b)if(f!==a.extras.gender&&b.hasOwnProperty(f)&&(g=b[f]||[],g=O(a,g,c,d,e)))break;return g||null}function J(){null!==F&&(clearTimeout(F),F=null)}function P(a){if(void 0===a||null===a||1>a.length||0===a.trim().length)return!1;
for(var b=!1,c=0;c<a.length;c++){var d=a.charAt(c);if(!dji.charSet.wordSeparator.characterIsMember(d)){b=!0;break}}return b}function Q(a,b,c,d){d=w(m.voice);for(var e=w(m.translationVoice),g,f,l=[],p=f=0;p<a.length;p++){g=a[p].text;var n=!!a[p].isTranslated,k=[];var u=(u=a[p].isTranslated?e:d)?u.extras.isGoogle?200:2E4:-1;f=f||0;if(0>u)k.push({offset:f,text:g,isTranslated:n});else{var x=0;do{var B=g;var h=x,q=u;if(0>q||6*(B.length-h)<=q)var t=Math.max(0,B.length-1);else{for(var y=B.length,v=0,A=h;h<
y&&v<q;h++){t=B.charCodeAt(h);if(127>=t)var z=1;else if(2047>=t)z=2;else if(65535>=t)z=3;else for(z=4;t>>6*z;)z++;if(q<v+z)break;v+=z;A=h}t=A}t=z=t;if(t<g.length-1)for(t=z;x<=t&&(B=g.charAt(t),!dji.charSet.wordSeparator.characterIsMember(B));t--);t<=x&&(t=z);k.push({offset:f+x,text:g.substring(x,t+1),isTranslated:n});x=t+1}while(x<g.length)}0<k.length&&(f=k[k.length-1].offset+k[k.length-1].text.length);g=k;l=l.concat(g)}a={chunks:l,isSpoken:!1,cancel:!1,userData:b,listener:c,settings:JSON.parse(JSON.stringify(m))};
r.push(a);C&&1!==r.length||(a.isSpoken=K(a))}function K(a){var b=!C;C||(C=!0);if(0>=a.chunks.length||0>=a.settings.volume)return a.cancel=!0,setTimeout(G,0,a),!0;a.startTime=Date.now();var c=a.chunks[0],d=w(a.settings.voice);b&&(v(a.listener,"wait",a.userData),v(a.listener,"start",a.userData));if(!d||!P(c.text))return setTimeout(G,0,a),!0;Logger.instance.log("__doSpeak using voice:",d," (translated:",c.isTranslated,") / settings:",JSON.stringify(a.settings,!0,2));b=new SpeechSynthesisUtterance(c.text);
b.lang=d.lang;b.voice=d.rawVoice;b.volume=a.settings.volume;b.rate=a.settings.rate;b.pitch=a.settings.pitch;b.onboundary=function(b){var c=a,d=b.charIndex||0;c=c||b.utterance.__item;v(c.listener,"progress",d+c.chunks[0].offset,-1,c.userData)};b.onstart=function(b){var c=a,d=b.charIndex||0;c=c||b.utterance.__item;v(c.listener,"progress",d+c.chunks[0].offset,-1,c.userData)};b.onerror=function(b){var c=a;c=c||b.utterance.__item;c.cancel=!0;G(c)};b.onend=function(b){var c=a;c=c||b.utterance.__item;G(c)};
console.log(b);window.speechSynthesis.speak(b);return!0}function G(a){if(a&&!a.cancel&&1<a.chunks.length)return a.chunks.splice(0,1),K(a);C=!1;if(a&&-1!==r.indexOf(a)&&(r.splice(0,1),0===r.length)){var b=Date.now()-a.startTime;v(a.listener,"stop",a.userData,b)}for(;0<r.length&&(a=r[0],!a.isSpoken)&&(a.isSpoken=K(a),!a.isSpoken);)r.splice(0,1),v(a.listener,"stop",a.userData,0)}function A(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){Logger.instance.error(b)}}function v(a,b){if(a&&
a[b])try{a[b].apply(a,[].slice.call(arguments).splice(2))}catch(c){Logger.instance.error(c)}}var u=dji.utils.os(),T=dji.utils.browser(),m={voice:null,translationVoice:null,rate:1,pitch:1,volume:1},k=[],y=[],q={},F=null,C=!1,r=[],H=void 0;f.initialize=function(a,b){if(0<k.length)return A(b,!0);N();Logger.instance.log("Initialize TTS");H=a;L(1,b)};f.settings=function(a){if(void 0===a)return{voice:m.voice,translationVoice:m.translationVoice,rate:1*m.rate,pitch:1*m.pitch,volume:1*m.volume};if(null===
a)N();else if(!a.voice||I(a.voice))a.voice&&(m.voice=a.voice),a.translationVoice&&(m.translationVoice=a.translationVoice),void 0!==a.rate&&null!==a.rate&&(m.rate=a.rate/1),void 0!==a.pitch&&null!==a.pitch&&(m.pitch=a.pitch/1),void 0!==a.volume&&null!==a.volume&&(m.volume=a.volume/1)};f.voices=function(a){if(a)return k;for(var b=[],c=f.isOnlineVoiceAllowed(a),d=0;d<k.length;d++)a=k[d],!c&&a.extras.isOnline||b.push(a);return b};f.voicesMap=function(){return q};f.hasVoice=I;f.hasVoiceForLanguage=function(a,
b){a=f.voicesForLanguage(a)||[];for(var c=0;c<a.length;c++)if(a[c].name==b)return!0;return!1};f.defaultVoice=function(a){if(u.mac)return"Alex";if(!u.windows&&!a&&f.onlineServiceAllowed()){if(I("Michael (Online)"))return"Michael (Online)";if(0<y.length)return y[0].name}for(var b=null,c=null,d=null,e=null,g=null,m=null,l=null,p=null,n=null,q=null,r=null,x=null,v=0;v<k.length;v++){var h=k[v];if((!a||!h.extras.isOnline)&&h.name){var w=(h.lang||"").toUpperCase();"EN-US"===w?(b||(b=h.name),!l&&h.extras.isMicrosoft&&
u.windows&&(l=h.name)):"EN-GB"===w?(c||(c=h.name),!p&&h.extras.isMicrosoft&&u.windows&&(p=h.name)):"EN-CA"===w&&(d||(d=h.name),!n&&h.extras.isMicrosoft&&u.windows&&(n=h.name));0<=h.name.indexOf("English")&&(m||(m=h.name),!x&&h.extras.isMicrosoft&&u.windows&&(x=h.name),0<=h.name.indexOf("US")?(e||(e=h.name),!q&&h.extras.isMicrosoft&&u.windows&&(q=h.name)):0<=h.name.indexOf("UK")&&(g||(g=h.name),!r&&h.extras.isMicrosoft&&u.windows&&(r=h.name)))}}return u.windows?q?q:l?l:r?r:p?p:n?n:x||"native":e?e:
b?b:g?g:c?c:d?d:m||""};f.defaultVoiceForLanguage=function(a){var b=(a||"").split("-");a=b[0];b=(2<=b.length?b[1]:"").toUpperCase();var c=(dji.languages.languageCode_639_1(a)||"").toUpperCase();if(0>=c.length||"EN"===c)return f.defaultVoice();a=q[a]||{};var d=(a[b]||{})["@"]||[];c=a["@"]||[];for(b=0;b<d.length;b++)if(a=d[b],!a.extras.isOnline&&!a.extras.isGoogle)return a.name;var e=d=null;for(b=0;b<c.length;b++)a=c[b],d||(d=a.name),!e&&a.extras.isGoogle&&(e=a.name);return e?e:d||""};f.isGoogleVoice=
function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("GOOGLE")||0<=a.indexOf("CHROME")};f.isMicrosoftVoice=function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("MICROSOFT")};f.isOnlineVoice=function(a){a=w(a);return!(!a||!a.extras.isOnline)};f.onlineServiceAllowed=function(){return!1};f.hasOnlineVoices=function(){return f.onlineServiceAllowed()&&0<y.length};f.cacheOnlineVoices=function(a){0>=y.length&&f.onlineServiceAllowed()?window.dji.tts_service.loadVoices(function(b){0>=
y.length&&(b=b||[],0<b.length&&(y=M(b,!0),k=k.concat(y)));A(a,0<y.length)}):A(a,0<y.length)};f.isOnlineVoiceAllowed=function(a){return!1};f.voicesForLanguage=function(a,b){var c=[];b=f.voices(b);for(var d=0;d<b.length;d++){var e=b[d];e.lang&&0===e.lang.indexOf(a)&&c.push(e)}return c};f.localAlternativeForVoice=function(a){if((a=w(a))&&!a.extras.isOnline)return a.name;if(!a||"en"===a.extras.lang)return f.defaultVoice(!0);var b=a.extras,c=q[b.lang]||{},d=c[b.culture]||{};d=E(a,d,!1,!0,!0);if(!d)for(var e in c)if(e!==
b.culture&&c.hasOwnProperty(e)&&(d=c[e]||{},d=E(a,d,!1,!0,!0)))break;return d?d.name:f.defaultVoice(!0)};f.onlineAlternativeForVoice=function(a){var b=w(a);if(b&&b.extras.isOnline)return b.name;if(!b||"en"===b.extras.lang)return f.defaultVoice(!1);var c=b.extras,d=q[c.lang]||{},e=d[c.culture]||{};e=E(b,e,!0,!1,!1);if(!e)for(var g in d)if(g!==c.culture&&d.hasOwnProperty(g)&&(e=d[g]||{},e=E(b,e,!0,!1,!1)))break;return e?e.name:a};f.voiceSupportsSettings=function(a){a=w(a);return!(!a||a.extras.isOnline&&
!a.adjustable)};f.speak=function(a,b,c,d){(d=!!d)||f.stop();J();"string"===typeof a?a=[{text:a,isTranslated:!1}]:a instanceof Array||(a=null);a&&0<a.length&&Q(a,b,c,d)};f.scheduleSpeak=function(a,b,c,d,e){P(a)&&(b?f.stop():J(),F=setTimeout(function(){Q([{text:a,isTranslated:!1}],d,e)},c||200))};f.stop=function(){J();0<r.length&&(C?(r.splice(1,r.length-1),r[0].cancel=!0,T.edge?speechSynthesis.cancel():browserEngine.tts.stop()):r.splice(0,r.length))}})(window.dji.tts=window.dji.tts||{});
