var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,h){a!=Array.prototype&&a!=Object.prototype&&(a[e]=h.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,e,h,n){if(e){h=$jscomp.global;a=a.split(".");for(n=0;n<a.length-1;n++){var g=a[n];g in h||(h[g]={});h=h[g]}a=a[a.length-1];n=h[a];e=e(n);e!=n&&null!=e&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}function h(a){return a instanceof g?a:new g(function(l,f){l(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;e.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};e.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var n=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(a){n(a,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var m=0;m<a.length;++m){var f=a[m];delete a[m];try{f()}catch(b){this.asyncThrow_(b)}}}this.batch_=null};e.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var l=this.createResolveAndReject_();try{a(l.resolve,l.reject)}catch(f){l.reject(f)}};g.prototype.createResolveAndReject_=
function(){function a(b){return function(d){f||(f=!0,b.call(m,d))}}var m=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var l=null!=a;break a;case "function":l=!0;break a;default:l=!1}l?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var l=
void 0;try{l=a.then}catch(f){this.reject_(f);return}"function"==typeof l?this.settleSameAsThenable_(l,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,m){if(0!=this.state_)throw Error("Cannot settle("+a+", "+m|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=m;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,m=0;m<a.length;++m)a[m].call(),a[m]=null;this.onSettledCallbacks_=null}};var q=new e;g.prototype.settleSameAsPromise_=function(a){var l=this.createResolveAndReject_();a.callWhenSettled_(l.resolve,l.reject)};g.prototype.settleSameAsThenable_=function(a,e){var f=this.createResolveAndReject_();try{a.call(e,f.resolve,f.reject)}catch(b){f.reject(b)}};g.prototype.then=function(a,e){function f(a,k){return"function"==typeof a?function(c){try{b(a(c))}catch(r){d(r)}}:k}var b,d,k=new g(function(a,
k){b=a;d=k});this.callWhenSettled_(f(a,b),f(e,d));return k};g.prototype.catch=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,e){function f(){switch(b.state_){case 1:a(b.result_);break;case 2:e(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?q.asyncExecute(f):this.onSettledCallbacks_.push(function(){q.asyncExecute(f)})};g.resolve=h;g.reject=function(a){return new g(function(e,f){f(a)})};g.race=function(a){return new g(function(e,
f){for(var b=$jscomp.makeIterator(a),d=b.next();!d.done;d=b.next())h(d.value).callWhenSettled_(e,f)})};g.all=function(a){var e=$jscomp.makeIterator(a),f=e.next();return f.done?h([]):new g(function(b,a){function d(a){return function(d){p[a]=d;g--;0==g&&b(p)}}var p=[],g=0;do p.push(void 0),g++,h(f.value).callWhenSettled_(d(p.length-1),a),f=e.next();while(!f.done)})};return g},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function e(e){return a.next(e)}function h(e){return a.throw(e)}return new Promise(function(n,g){function q(a){a.done?n(a.value):Promise.resolve(a.value).then(e,h).then(q,g)}q(a.next())})};
function DjiStorageFile(a,e,h){this.id=a;this.title=e;this.type=h;this.description=null;this.isFolder=!1;this.revision=this.checksum=this.downloadUrl=this.thumbnailUrl=this.iconUrl=this.lastModifiedDate=this.creationDate=this.parent=null;this.trashed=!1;this.__custom=null}(function(a){})(window.jsdapi=window.jsdapi||{});
(function(a){function e(a){var b=jsdapi.url();b+="/cow";a&&(b+="/"+a);return b}function h(a){var b=e("files");a&&(b+="/"+a);return b}function n(a){var b=e("data");a&&(b+="/"+a);return b}function g(a){var b=e("measurements");a&&(b+="/"+a);return b}a.setUrls=function(a){};a.getLanguage=function(a,d){return $jscomp.executeAsyncGenerator(function(){function a(a,k,p){for(;;)switch(b){case 0:jsdapi.authorize(function(a){if(!a)return f(d,null);a={responseType:"json",method:"GET",url:e("language"),query:{access_token:a}};
jsdapi.http.sendRequest(a,function(a){f(d,a&&a.language?a.language:null)})}),b=-1;default:return{value:void 0,done:!0}}}var b=0,g={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();g[Symbol.iterator]=function(){return this};return g}())};a.updateLanguageAsync=function(b){return new Promise(function(d,k){a.updateLanguage(b,function(a){a?d(a):k()})})};a.updateLanguage=function(a,d){if(!a)return f(d,
null);jsdapi.authorize(function(b){if(!b)return f(d,null);b={responseType:"json",method:"GET",url:e("language/update"),query:{access_token:b,language:a}};jsdapi.http.sendRequest(b,function(a){f(d,a&&a.language?a.language:null)})})};a.getFiles=function(a,d,k){jsdapi.authorize(function(b){b?(a&&(a instanceof Array&&0<a.length&&(a=a[0]),"string"!==typeof a&&(a="")),b={responseType:"json",method:"GET",url:h("list"),query:{access_token:b,filters:JSON.stringify({type:a,language:d})}},jsdapi.http.sendRequest(b,
function(b){q(b,a,!1,k)})):f(k,{errorCode:1})})};a.checkForUpdates=function(a,d){!a||0>=a.length?f(d,{errorCode:400}):jsdapi.authorize(function(b){b?(b={responseType:"json",method:"GET",url:h("checkUpdates"),query:{access_token:b,filters:JSON.stringify({basic:!0,types:a})}},jsdapi.http.sendRequest(b,function(b){var k={errorCode:b&&0==b.error?0:2};if(0==k.errorCode&&(k.files={},b.files))for(var c=0;c<a.length;c++){var e=b.files[a[c].type],g=[];if(e)for(var p=0;p<e.length;p++)g.push(m(e[p]));k.files[a[c].type]=
g}f(d,k)})):f(d,{errorCode:401})})};a.getFile=function(a,d){jsdapi.authorize(function(b){null===b?f(d,{errorCode:401}):(b={responseType:"json",method:"GET",url:h("list"),query:{access_token:b,filters:JSON.stringify({type:a.type,uuid:a.id})}},jsdapi.http.sendRequest(b,function(b){q(b,a.type,!0,d)}))})};a.insertFile=function(a,d,e){jsdapi.authorize(function(b){if(null===b)f(e,{errorCode:401});else{var k={uuid:a.id,title:a.title,type:a.type,language:a.__custom&&a.__custom.language?a.__custom.language:
null,creationDate:a.creationDate,modifiedDate:a.lastModifiedDate,modifiedUuid:a.lastModifiedUuid,checksum:a.checksum,version:a.revision},c=new JsDapiUtf8Data;c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: info\r\n");c.appendString('Content-Disposition: inline; name="info";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");c.appendString(JSON.stringify(k));c.appendString("\r\n");
a.__custom&&a.__custom.metadata&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: metadata\r\n"),c.appendString('Content-Disposition: inline; name="metadata";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.metadata),c.appendString("\r\n"));a.__custom&&a.__custom.preview&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: preview\r\n"),
c.appendString('Content-Disposition: inline; name="preview";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.preview),c.appendString("\r\n"));c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: body\r\n");c.appendString('Content-Disposition: inline; name="body";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");
d instanceof ArrayBuffer||"[object ArrayBuffer]"==d.toString()?c.appendArrayBuffer(d):d instanceof Array?c.appendArray(d):c.appendString(d);c.appendString("\r\n");c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");b={responseType:"json",method:"POST",url:h("create"),query:{access_token:b},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',content:c.toUint8Array()};jsdapi.http.sendRequest(b,function(a){l(a,e)})}})};a.updateFile=function(a,d,e){jsdapi.authorize(function(b){if(null===
b)f(e,{errorCode:401});else{var k={uuid:a.id,title:a.title,type:a.type,language:a.__custom&&a.__custom.language?a.__custom.language:null,creationDate:a.creationDate,modifiedDate:a.lastModifiedDate,modifiedUuid:a.lastModifiedUuid,checksum:a.checksum,version:a.revision},c=new JsDapiUtf8Data;c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: info\r\n");c.appendString('Content-Disposition: inline; name="info";\r\n');c.appendString("Content-Type: application/octet-stream\r\n");
c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");c.appendString(JSON.stringify(k));c.appendString("\r\n");a.__custom&&a.__custom.metadata&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: metadata\r\n"),c.appendString('Content-Disposition: inline; name="metadata";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.metadata),c.appendString("\r\n"));
a.__custom&&a.__custom.preview&&(c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n"),c.appendString("Content-ID: preview\r\n"),c.appendString('Content-Disposition: inline; name="preview";\r\n'),c.appendString("Content-Type: application/octet-stream\r\n"),c.appendString("Content-Transfer-Encoding: binary\r\n\r\n"),c.appendString(a.__custom.preview),c.appendString("\r\n"));c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");c.appendString("Content-ID: body\r\n");c.appendString('Content-Disposition: inline; name="body";\r\n');
c.appendString("Content-Type: application/octet-stream\r\n");c.appendString("Content-Transfer-Encoding: binary\r\n\r\n");d instanceof ArrayBuffer||"[object ArrayBuffer]"==d.toString()?c.appendArrayBuffer(d):d instanceof Array?c.appendArray(d):c.appendString(d);c.appendString("\r\n");c.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");b={responseType:"json",method:"POST",url:h("update"),query:{access_token:b},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',
content:c.toUint8Array()};jsdapi.http.sendRequest(b,function(a){l(a,e)})}})};a.moveFile=function(a,d,e){f(e,{errorCode:-1})};a.deleteFile=function(a,d,e){jsdapi.authorize(function(b,k){null===b||null===k?f(e,{errorCode:1}):(b={responseType:"json",method:"GET",url:h("delete"),query:{access_token:b,dapiApprovalToken:'"'+k+'"',type:'"'+a.type+'"',uuid:'"'+a.id+'"',version:a.revision,purge:d}},jsdapi.http.sendRequest(b,function(a){f(e,a)}))})};a.downloadFile=function(a,d){jsdapi.authorize(function(b){null===
b?f(d,{errorCode:401}):(b={responseType:a.__responseType||"binary",method:"GET",url:h("content"),query:{access_token:b,type:'"'+a.type+'"',uuid:'"'+a.id+'"'}},jsdapi.http.sendRequest(b,function(a,b,c){b=null;if(c&&c.hasOwnProperty("dapi-file-info"))try{b=m(JSON.parse(c["dapi-file-info"]))}catch(r){Logger.instance.error(r)}f(d,a,b)}))})};a.resetFile=function(a,d){_storage.authorize(function(b){b?(b={responseType:"json",method:"GET",url:h("reset"),query:{access_token:b,type:a.type,language:a.language}},
dji.http.sendRequest(b,function(a){})):f(d,{errorCode:1})})};a.downloadImage=function(a,d){f(d,null)};a.downloadThumbnail=function(a,d){f(d,null)};a.downloadIcon=function(a,d){f(d,null)};a.getDataWordList=function(a,d){jsdapi.authorize(function(b){b?(b={responseType:"json",method:"GET",url:n("words/list"),query:{access_token:b,filters:JSON.stringify({language:a})}},jsdapi.http.sendRequest(b,function(a){f(d,a)})):f(d,{errorCode:401})})};a.updateMeasurements=function(a,d){jsdapi.authorize(function(b){b?
(b={responseType:"json",method:"POST",url:g("update"),query:{access_token:b},contentType:"application/json",content:JSON.stringify(a)},jsdapi.http.sendRequest(b,function(a){f(d,a)})):f(d,{errorCode:401})})};var q=function(a,d,e,g){d={errorCode:a&&0==a.error?0:2};if(0==d.errorCode){var b=[];if(a.files)for(var c=0;c<a.files.length;c++)b.push(m(a.files[c]));e&&1===b.length?d.file=b[0]:d.files=b}f(g,d)},l=function(a,d){var b={errorCode:a&&0==a.error?0:2};0==b.errorCode&&a.file&&(b.file=m(a.file));f(d,
b)},m=function(a){if(!a)return null;var b=new DjiStorageFile(a.uuid,a.title,a.type);b.creationDate=a.creationDate;b.lastModifiedDate=a.modifiedDate;b.checksum=a.checksum;b.revision=a.version;b.trashed=a.deleted;b.__custom=a;return b},f=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(d){Logger.instance.error(d)}}})(window.jsdapi.cow=window.jsdapi.cow||{});
