var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,f){a!=Array.prototype&&a!=Object.prototype&&(a[e]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,e,f,c){if(e){f=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in f||(f[d]={});f=f[d]}a=a[a.length-1];c=f[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function e(){this.batch_=null}function f(b){return b instanceof d?b:new d(function(a,c){a(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;e.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};e.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var c=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(b){c(b,
0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var c=b[a];delete b[a];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};e.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(h){a.reject(h)}};d.prototype.createResolveAndReject_=
function(){function b(b){return function(d){c||(c=!0,b.call(a,d))}}var a=this,c=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(h){this.reject_(h);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var g=new e;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(l){c.reject(l)}};d.prototype.then=function(b,a){function c(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(m){e(m)}}:b}var g,e,f=new d(function(b,
a){g=b;e=a});this.callWhenSettled_(c(b,g),c(a,e));return f};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(b,a){function c(){switch(d.state_){case 1:b(d.result_);break;case 2:a(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(function(){g.asyncExecute(c)})};d.resolve=f;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
c){for(var d=$jscomp.makeIterator(a),g=d.next();!g.done;g=d.next())f(g.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?f([]):new d(function(a,d){function g(b){return function(c){e[b]=c;h--;0==h&&a(e)}}var e=[],h=0;do e.push(void 0),h++,f(c.value).callWhenSettled_(g(e.length-1),d),c=b.next();while(!c.done)})};return d},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function e(c){return a.next(c)}function f(c){return a.throw(c)}return new Promise(function(c,d){function g(a){a.done?c(a.value):Promise.resolve(a.value).then(e,f).then(g,d)}g(a.next())})};window.jsdapi=window.jsdapi||{};
(function(a){var e="https://login.donjohnston.net",f="https://dapi.donjohnston.net",c={client_id:null,access_token:null,expires_at:null},d=null;a.setRefreshTokenDelegate=function(a){"function"===typeof a&&(d=a)};a.setServerUrl=function(c){a.clearAuth();e=c.login;f=c.dapi};a.setClientId=function(c){a.clearAuth();a.client_id=c};a.url=function(){return f};a.setAuth=function(a){a=a||{};c.access_token=a.access_token||null;c.expires_at=a.expires_at||null};a.clearAuth=function(){c.access_token=null;c.expires_at=
null};a.authorize=function(d){if(!c.access_token||!c.expires_at)return d(null);if(c.access_token&&Date.now()<=c.expires_at-6E5)return d(c.access_token);a.refreshToken(function(a){a?d(c.access_token):d(null)})};a.authorizeAsync=function(){return $jscomp.executeAsyncGenerator(function(){function d(d,f,g){for(;;)switch(b){case 0:try{if(c.access_token&&c.expires_at){b=3;break}b=-1;return{value:null,done:!0}}catch(k){b=1;break}case 3:try{if(!(c.access_token&&Date.now()<=c.expires_at-6E5)){b=4;break}b=
-1;return{value:c.access_token,done:!0}}catch(k){b=1;break}case 4:try{return b=5,{value:a.refreshTokenAsync(),done:!1}}catch(k){b=1;break}case 5:try{if(1!=d){b=6;break}b=-1;throw g;}catch(k){b=1;break}case 6:try{return e=f,b=-1,{value:e,done:!0}}catch(k){b=1;break}case 1:return b=-1,{value:null,done:!0};case 2:b=-1;default:return{value:void 0,done:!0}}}var b=0,e,f={next:function(a){return d(0,a,void 0)},throw:function(a){return d(1,void 0,a)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())};a.refreshToken=function(a){d?d({login_url:e,client_id:c.client_id,refresh_token:c.access_token},function(b){if(!(b&&b.hasOwnProperty("code")&&0===b.code&&b.hasOwnProperty("access_token")&&b.hasOwnProperty("expires_at")))return a(null);c.access_token=b.access_token;c.expires_at=b.expires_at;a(c)}):a(null)};a.refreshTokenAsync=function(){return $jscomp.executeAsyncGenerator(function(){function a(a,f,g){for(;;)switch(b){case 0:return b=
-1,{value:new Promise(function(a,b){d?d({login_url:e,client_id:c.client_id,refresh_token:c.access_token},function(d){if(!(d&&d.hasOwnProperty("code")&&0===d.code&&d.hasOwnProperty("access_token")&&d.hasOwnProperty("expires_at")))return b(null);c.access_token=d.access_token;c.expires_at=d.expires_at;a(c)}):b(null)}),done:!0};default:return{value:void 0,done:!0}}}var b=0,f={next:function(b){return a(0,b,void 0)},throw:function(b){return a(1,void 0,b)},return:function(a){throw Error("Not yet implemented");
}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f}())}})(window.jsdapi);
