function DexControl(a,b,c){this.extensionID=a;this.controlID=b;this.priority=c;this.domElement=null;return this}
function DexController(a){this.m_extensionID=chrome.i18n.getMessage("@@extension_id");this.m_isGoogleDocs="docs.google.com"===window.location.hostname&&window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i);this.m_cursorInfoDelegate=this.m_locationInfoDelegate=void 0;this.m_commonDiv={mainContainer:null,dragSurface:null,contentContainer:null,dragOverlayContainer:null};this.m_controls=null;this.m_drag={States:{Idle:0,Waiting:1,Active:2},state:0,start:{x:0,y:0},end:{x:0,y:0},offset:{x:0,
y:0},onMouseDown:null,onMouseUp:null,onMouseMove:null,onMouseOver:null,onMouseOut:null,ignoreWindowConstraints:!1};this.m_fixedPosition={active:!1,desired:{x:0,y:0},current:{x:0,y:0}};this.m_measurementTools={container:null,div:null,caret:null};this.m_eventListeners={"dexController-moveDone":{handler:null,listeners:[]}};var b=this;setTimeout(function(){b.__startInitializationProcedure(a)},0);return this}DexController.Event={MoveDone:"dexController-moveDone"};DexController.instance=null;
DexController.initialize=function(a){DexController.instance?a&&callback():DexController.instance=new DexController(a)};DexController.prototype.setLocationInfoDelegate=function(a){this.m_locationInfoDelegate=a};DexController.prototype.setCursorInfoDelegate=function(a){this.m_cursorInfoDelegate=a};
DexController.prototype.addExtensionControls=function(a,b){this.m_commonDiv.contentContainer.appendChild(a);a=new DexControl(this.m_extensionID,a.id,b);a=new CustomEvent("dexController-addExtensionControls",{detail:a});this.m_commonDiv.mainContainer.dispatchEvent(a)};
DexController.prototype.addEventListener=function(a,b){if(a in this.m_eventListeners){var c=this.m_eventListeners[a].listeners;-1==c.indexOf(b)&&(c.push(b),1===c.length&&this.m_commonDiv.mainContainer.addEventListener(a,this.m_eventListeners[a].handler,!1))}};
DexController.prototype.removeEventListener=function(a,b){if(a in this.m_eventListeners){var c=this.m_eventListeners[a].listeners;b=c.indexOf(b);-1!=b&&(c.splice(b,1),0===c.length&&this.m_commonDiv.mainContainer.removeEventListener(a,this.m_eventListeners[a].handler,!1))}};DexController.prototype.move=function(a,b,c){a=new CustomEvent("dexController-move",{detail:{controlID:a.id,x:b,y:c}});this.m_commonDiv.mainContainer.dispatchEvent(a)};
DexController.prototype.ensureVisibile=function(a){a=a.getBoundingClientRect();var b=window.innerWidth,c=window.innerHeight;if(0>=a.right||b<=a.x||0>=a.top||c<=a.y)b=parseInt((b-a.width)/2),a=parseInt((c-a.height)/2),this.m_commonDiv.mainContainer.style.left=b+"px",this.m_commonDiv.mainContainer.style.top=a+"px"};
DexController.prototype.__startInitializationProcedure=function(a){var b=this;"complete"===document.readyState?(this.__initialize(),a&&a()):window.addEventListener("load",function(){b.__initialize();a&&a()})};
DexController.prototype.__initialize=function(){var a=this;this.m_commonDiv.mainContainer=document.getElementById("dexControlsContainer");this.m_commonDiv.contentContainer=document.getElementById("dexControlsContainerBody");null===this.m_commonDiv.mainContainer&&(this.m_commonDiv.mainContainer=document.createElement("div"),this.m_commonDiv.mainContainer.id="dexControlsContainer",this.m_commonDiv.dragSurface=document.createElement("div"),this.m_commonDiv.dragSurface.id="dexControlsContainerDragSurface",
this.m_commonDiv.dragOverlayContainer=document.createElement("div"),this.m_commonDiv.dragOverlayContainer.id="dexControlsContainerOverlay",this.m_commonDiv.contentContainer=document.createElement("div"),this.m_commonDiv.contentContainer.id="dexControlsContainerBody",this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.dragSurface),this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.contentContainer),this.m_commonDiv.mainContainer.appendChild(this.m_commonDiv.dragOverlayContainer),document.documentElement.appendChild(this.m_commonDiv.mainContainer),
this.m_controls=[],this.m_drag.onMouseDown=function(b){a.__isDraggable(b.target)&&a.__onDragStart(b)&&(b.preventDefault(),b.stopPropagation(),document.addEventListener("mousemove",a.m_drag.onMouseMove,!0),document.addEventListener("mouseup",a.m_drag.onMouseUp,!0),document.addEventListener("mouseout",a.m_drag.onMouseOut,!0),document.addEventListener("mouseover",a.m_drag.onMouseOver,!0),a.__addClassToElement(a.m_commonDiv.mainContainer,"dexPrepareDragging"))},this.m_drag.onMouseMove=function(b){a.__onDrag(b)&&
(b.preventDefault(),b.stopPropagation())},this.m_drag.onMouseOver=function(a){a.preventDefault();a.stopPropagation()},this.m_drag.onMouseOut=function(b){if(null===b.toElement)a.m_drag.onMouseUp(b);else b.preventDefault(),b.stopPropagation()},this.m_drag.onMouseUp=function(b){a.__onDragEnd(b);b.preventDefault();b.stopPropagation();document.removeEventListener("mousemove",a.m_drag.onMouseMove,!0);document.removeEventListener("mouseup",a.m_drag.onMouseUp,!0);document.removeEventListener("mouseover",
a.m_drag.onMouseOver,!0);document.removeEventListener("mouseout",a.m_drag.onMouseOut,!0);a.__removeClassFromElement(a.m_commonDiv.mainContainer,"dexPrepareDragging")},this.m_commonDiv.mainContainer.addEventListener("mousedown",this.m_drag.onMouseDown,!0),this.m_commonDiv.mainContainer.addEventListener("dexController-addExtensionControls",function(b){a.__onAddExtensionControls(b);b.preventDefault();b.stopPropagation()},!0),this.m_commonDiv.mainContainer.addEventListener("dexController-move",function(b){a.__onMove(b);
b.preventDefault();b.stopPropagation()},!0),this.m_eventListeners[DexController.Event.MoveDone].handler=function(b){a.__onMoveDone(b)},this.m_measurementTools.container=document.createElement("div"),this.m_measurementTools.container.id="dexControlsContainerMeasurement",this.m_measurementTools.div=document.createElement("div"),this.m_measurementTools.div.id="dexControlsContainerMeasurementDiv",this.m_measurementTools.container.appendChild(this.m_measurementTools.div),document.documentElement.appendChild(this.m_measurementTools.container),
window.addEventListener("resize",function(b){setTimeout(function(){a.__onWindowResize(b)},0)}))};DexController.prototype.__onAddExtensionControls=function(a){a=a.detail;a.domElement=document.getElementById(a.controlID);this.m_controls.push(a);this.__sortControls()};
DexController.prototype.__sortControls=function(){this.m_controls.sort(function(a,c){return a.priority-c.priority});this.m_commonDiv.contentContainer.innerHTML="";for(var a=0;a<this.m_controls.length;a++)0<a&&this.m_commonDiv.contentContainer.appendChild(this.__createSeparator()),this.m_commonDiv.contentContainer.appendChild(this.m_controls[a].domElement)};DexController.prototype.__isDraggable=function(a){for(;a;){if(a.hasAttribute("dji-non-draggable"))return!1;a=a.parentElement}return!0};
DexController.prototype.__editorWillBeIgnored=function(a){for(;a;){if(a.hasAttribute("dji-dex-ignore-editor"))return!0;a=a.parentElement}return!1};DexController.prototype.__isEntireElementVisible=function(){var a=this.__getContentBoundingRect();return 0<=a.top&&a.bottom<window.innerHeight&&0<=a.left&&a.right<window.innerWidth};
DexController.prototype.__onMove=function(a){a=a.detail;this.m_fixedPosition.active||(this.m_commonDiv.mainContainer.style.left=parseFloat(a.x)+"px",this.m_commonDiv.mainContainer.style.top=parseFloat(a.y)+"px",a=new CustomEvent("dexController-moveDone",{detail:{extensionID:this.m_controls[0].extensionID,controlID:a.controlID,x:a.x,y:a.y}}),this.m_commonDiv.mainContainer.dispatchEvent(a))};
DexController.prototype.__onMoveDone=function(a){for(var b=this.m_eventListeners[DexController.Event.MoveDone].listeners,c=0;c<b.length;c++)try{b[c](a.detail)}catch(d){}};
DexController.prototype.__onDragStart=function(a){if(this.m_drag.state!==this.m_drag.States.Idle)return this.m_drag.onMouseUp(a),!1;if(1!==a.which)return!1;this.m_drag.state=this.m_drag.States.Waiting;this.m_drag.start.x=this.m_drag.end.x=a.x;this.m_drag.start.y=this.m_drag.end.y=a.y;this.m_drag.ignoreWindowConstraints=!this.__isEntireElementVisible();return!0};
DexController.prototype.__onDrag=function(a){if(this.m_drag.state==this.m_drag.States.Waiting||this.m_drag.state==this.m_drag.States.Active)if(this.m_drag.end.x=a.x,this.m_drag.end.y=a.y,this.m_drag.state==this.m_drag.States.Waiting){if(5<Math.sqrt((this.m_drag.end.x-this.m_drag.start.x)*(this.m_drag.end.x-this.m_drag.start.x)+(this.m_drag.end.y-this.m_drag.start.y)*(this.m_drag.end.y-this.m_drag.start.y))){var b=this.m_commonDiv.mainContainer.getBoundingClientRect(),c=this.__getContentBoundingRect();
this.m_drag.state=this.m_drag.States.Active;this.m_drag.start.x=this.m_drag.end.x=a.x;this.m_drag.start.y=this.m_drag.end.y=a.y;this.m_drag.offset.x=this.m_drag.start.x-b.left;this.m_drag.offset.y=this.m_drag.start.y-b.top;this.m_fixedPosition.active=!0;this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=this.m_drag.end.x-this.m_drag.offset.x;this.m_fixedPosition.desired.y=this.m_fixedPosition.current.y=this.m_drag.end.y-this.m_drag.offset.y;this.m_commonDiv.dragOverlayContainer.style.width=
c.width+"px";this.m_commonDiv.dragOverlayContainer.style.height=c.height+"px";this.__addClassToElement(this.m_commonDiv.mainContainer,"dexFixed");this.__addClassToElement(this.m_commonDiv.mainContainer,"dexDragging");this.m_commonDiv.mainContainer.style.left=b.left+"px";this.m_commonDiv.mainContainer.style.top=b.top+"px"}}else if(this.m_drag.state==this.m_drag.States.Active){a=this.m_drag.end.x-this.m_drag.offset.x;b=this.m_drag.end.y-this.m_drag.offset.y;c=window.innerWidth;var d=window.innerHeight,
f=parseInt(this.m_commonDiv.dragOverlayContainer.style.width),e=parseInt(this.m_commonDiv.dragOverlayContainer.style.height);if(this.m_drag.ignoreWindowConstraints||0<=a&&0<=b&&a+f<=c&&b+e<=d)this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=a,this.m_fixedPosition.desired.y=this.m_fixedPosition.current.y=b,this.m_commonDiv.mainContainer.style.left=this.m_fixedPosition.desired.x+"px",this.m_commonDiv.mainContainer.style.top=this.m_fixedPosition.desired.y+"px"}return this.m_drag.state==
this.m_drag.States.Active};
DexController.prototype.__onDragEnd=function(a){if(this.m_drag.state===this.m_drag.States.Waiting||this.m_drag.state===this.m_drag.States.Active){if(this.m_drag.state===this.m_drag.States.Active){var b=(a=this.m_locationInfoDelegate?this.m_locationInfoDelegate():null)?a.caret:this.__getCaretInfo();if(b){var c=this.__getDragOverlayBoundingRect();(c.left<=b.left&&b.left<=c.right||c.left<=b.right&&b.right<=c.right)&&(c.top<=b.top&&b.top<=c.bottom||c.top<=b.bottom&&b.bottom<=c.bottom)&&(this.m_fixedPosition.active=
!1,this.__removeClassFromElement(this.m_commonDiv.mainContainer,"dexFixed"),a?(this.m_commonDiv.mainContainer.style.left=a.left+"px",this.m_commonDiv.mainContainer.style.top=a.top+"px"):(this.m_commonDiv.mainContainer.style.left=b.left+window.pageXOffset+"px",this.m_commonDiv.mainContainer.style.top=b.bottom+window.pageYOffset+2+"px"))}this.__removeClassFromElement(this.m_commonDiv.mainContainer,"dexDragging")}this.m_drag.ignoreWindowConstraints=!1;this.m_drag.state=this.m_drag.States.Idle}};
DexController.prototype.__getDragOverlayBoundingRect=function(){var a=this.m_commonDiv.dragOverlayContainer.getBoundingClientRect(),b="fixed"===document.defaultView.getComputedStyle(this.m_commonDiv.mainContainer,null).position,c=b?window.pageXOffset:0;b=b?window.pageYOffset:0;return{left:Math.round(a.left+c),top:Math.round(a.top+b),right:Math.round(a.right+c),bottom:Math.round(a.bottom+b)}};
DexController.prototype.__getContentBoundingRect=function(){for(var a=this.m_commonDiv.contentContainer.getBoundingClientRect(),b={left:a.left,top:a.top,bottom:a.bottom,right:a.right,width:0,height:0},c=this.m_commonDiv.contentContainer.childNodes,d=0;d<c.length;d++)(a=c[d].style.display)||(a=document.defaultView.getComputedStyle(c[d],null).getPropertyValue("display")),"none"!==a&&(a=c[d].getBoundingClientRect(),a.left<b.left&&(b.left=a.left),a.top<b.top&&(b.top=a.top),b.right<a.right&&(b.right=a.right),
b.bottom<a.bottom&&(b.bottom=a.bottom));b.width=b.right-b.left;b.height=b.bottom-b.top;return b};DexController.prototype.__addClassToElement=function(a,b){a&&b&&a.classList.add(b)};DexController.prototype.__removeClassFromElement=function(a,b){a&&b&&a.classList.remove(b)};DexController.prototype.__createSeparator=function(){var a=document.createElement("div");a.setAttribute("class","dexSeparator");return a};
DexController.prototype.__getScrollOffset=function(){var a=document.documentElement;return{x:(window.pageXOffset||a.scrollLeft)-(a.clientLeft||0),y:(window.pageYOffset||a.scrollTop)-(a.clientTop||0)}};DexController.prototype.__getCaretInfo=function(){if(this.m_cursorInfoDelegate)try{return this.m_cursorInfoDelegate()}catch(b){}if(this.m_isGoogleDocs){var a=document.getElementsByClassName("kix-cursor-caret")[0];a=a.getBoundingClientRect();return a={left:a.left,top:a.top,right:a.right,bottom:a.bottom}}return this.__getCaretInfoFromGenericEditors()};
DexController.prototype.__getCaretInfoFromGenericEditors=function(){var a=this.__getActiveElementInfo();if(null===a||this.__editorWillBeIgnored(a.element))return null;var b={left:0,top:0,right:0,bottom:0};if(void 0!==a.element.selectionStart){var c=a.element.selectionStart,d=a.element.selectionEnd-a.element.selectionStart,f=a.element.value,e=this.__escapeHtml(f.slice(0,c+d));c=this.__escapeHtml(f.slice(c+d,f.length));d=document.defaultView.getComputedStyle(a.element,null);"INPUT"===a.element.tagName&&
0<e.length&&(e=e.replace(/ /g,"."));this.m_measurementTools.div.innerHTML="";this.m_measurementTools.div.style.cssText=d.cssText;this.m_measurementTools.div.innerHTML=e+"<span id='dexControlsContainerMeasurementDivCaret'></span>"+c;this.m_measurementTools.caret=document.getElementById("dexControlsContainerMeasurementDivCaret");e=a.element.getBoundingClientRect();c=this.m_measurementTools.div.getBoundingClientRect();d=this.m_measurementTools.caret.getBoundingClientRect();b.left=-a.element.scrollLeft+
e.left+d.left-c.left;b.top=-a.element.scrollTop+e.top+d.top-c.top;b.right=d.right-d.left;b.bottom=d.bottom-d.top}else if(void 0!==a.element.contentEditable&&"true"===a.element.contentEditable){e=a.document.getSelection();c=e.focusNode;d=e.focusOffset;try{f=0<e.rangeCount?e.getRangeAt(0).cloneRange():null;!f&&c&&(f=document.createRange(),f.setStart(c,d),f.setEnd(c,d));var g=f.getClientRects();0>=g.length&&0<d&&d<=c.childNodes.length&&(f.detach(),f.selectNode(c.childNodes[d-1]),g=f.getClientRects());
f.detach();if(0<g.length){var h=g[g.length-1];b.left=h.right;b.top=h.top;b.right=0;b.bottom=h.bottom-h.top}else if(c){var k=document.defaultView.getComputedStyle(c,null),l=c.getBoundingClientRect(),m=parseFloat(k.getPropertyValue("padding-left")),n=parseFloat(k.getPropertyValue("padding-top")),p=parseFloat(k.getPropertyValue("font-size"));b.left=m+l.left;b.top=n+l.top;b.right=0;b.bottom=p+2}}catch(q){Logger.instance.error(q,c,d,e)}}if(0<a.iframes.length)for(e=0;e<a.iframes.length;e++)c=a.iframes[e].getBoundingClientRect(),
b.left+=c.left,b.top+=c.top;b.right=b.left+b.right;b.bottom=b.top+b.bottom;return b};
DexController.prototype.__getActiveElementInfo=function(){var a={element:document.activeElement,document:document,iframes:[]};if(a.element)for(;;)if(a.element.shadowRoot&&a.element.shadowRoot.activeElement)a.element=a.element.shadowRoot.activeElement;else if("IFRAME"===a.element.tagName)try{if(!this.__validateIframe(a.element))break;var b=a.element;a.element=b.contentDocument.activeElement;a.document=b.contentDocument;a.iframes=[b].concat(a.iframes)}catch(c){break}else break;return a};
DexController.prototype.__validateIframe=function(a){if(void 0===a.src||null===a.src)return!1;a=a.src.split("/")[2];return void 0===a||null===a?!0:0<=a.indexOf(document.domain)};DexController.prototype.__escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};
DexController.prototype.__onWindowResize=function(a){if(this.m_fixedPosition.active){this.m_commonDiv.mainContainer.getBoundingClientRect();a=this.__getContentBoundingRect();var b=window.innerWidth,c=window.innerHeight,d=a.top;c<a.bottom&&(d=c-a.height);0>d&&(d=0);c=a.left;b<a.right&&(c=b-a.width);0>c&&(c=0);c!=a.left&&(this.m_fixedPosition.desired.x=this.m_fixedPosition.current.x=c,this.m_commonDiv.mainContainer.style.left=this.m_fixedPosition.desired.x+"px");d!=a.left&&(this.m_fixedPosition.desired.y=
this.m_fixedPosition.current.y=d,this.m_commonDiv.mainContainer.style.top=this.m_fixedPosition.desired.y+"px")}};
